### ISSUE TITLE
Problems with valgrind

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudat#107]
In order to test the memory usage of my Tudat app, I installed valgrind following this guide: https://prateekvjoshi.com/2013/02/27/how-to-install-valgrind-on-mac-os-x/

I couldn't make it work because I get this error when I try to analyse my app:
```
valgrind: mmap-FIXED(0x0, 253952) failed in UME (load_segment1) with error 12 (Cannot allocate memory).
```

After installing valgrind I got a folder with many files. In the Qt Creator preferences I changed the Valgrind executable in Preferences > Analyzer > Valgrind to one of the files in that folder. I chose `vg-in-place` but I don't know if that is the right one. Apparently Qt does find valgrind now, although for some reason I am getting this error.

But what is even worse, now when I run my app as usual (in Default configuration) the propagation is about 10x slower than it used to be. Before yesterday it was propagating about 20 days in one second and now it is just about 1.8 days in one second, although I haven't changed my code (the only thing I've done is installing valgrind and trying to use it).

**Comment by aleixpinardell** [comment]
I tried removing the Valgrind executable in Preferences > Analyzer > Valgrind. After that I get the same error that I was getting before installing valgrind when I try to analyse my app:
```
Error: no Valgrind executable set.
```

However, the propagation is still 10x slower than it was before installing valgrind when I just run it with the Default condiguration. Quite weird.

**Comment by aleixpinardell** [comment]
Cleaning and building again solved the "10x slower" problem.

**Comment by DominicDirkx** [comment]
Great to hear! Still not sure what the root cause was, though...
