### ISSUE TITLE
Program stuck when using "ParameterizedThrustMagnitudeSettings"

### ISSUE THREAD

**Issue by jesperspillenaar** [Tudat/tudat#110]
My program gets stuck (probably in some infinate loop) when changing from "ConstantThrustEngineSettings" to "ParameterizedThrustMagnitudeSettings". 

I already included altitude termintation conditions at 1 km and 120 km, to make sure the space plane cannot go below the earth surface. I also included extra colums and rows in the thrust and Specific Impulse tables to make sure the dependent variables to interpolate cannot be outside the domain of the tables. Both don't solve the problem

Below my compile output and application file:

[compile_output.txt](https://github.com/Tudat/tudat/files/661812/compile_output.txt)
[spacePlaneAscent.txt](https://github.com/Tudat/tudat/files/661809/spacePlaneAscent.txt)

**Comment by DominicDirkx** [comment]
Hi Jesper,

It seems that you have stumbled upon a very interesting set of initial conditions: the altitude stays between 1 and 120 km for all times. My theory as to why this is happening is the following:

- As your altitude goes up, your thrust goes down (as it seems to be decreasing with dynamic pressure and therefore with altitude). 
- At a certain altitude, the upwards components of the lift and the thrust are no longer able to counteract gravity, and the vehicle starts descending. Now you are at a lower altitude, and your density goes up and so does your thrust.
- Thrust is now large enough to overcome gravity, and the loop begins anew.

There's a very easy fix for this. Now you are using the following as stopping conditions:

    ```
std::vector< boost::shared_ptr< PropagationTerminationSettings > >  propagationTerminationSettingsList;
    propagationTerminationSettingsList.push_back( boost::make_shared< PropagationDependentVariableTerminationSettings >(
                                                 boost::make_shared< SingleDependentVariableSaveSettings >(
                                                     altitude_dependent_variable, "SpacePlane", "Earth" ), 120.0E3, false ) );
    propagationTerminationSettingsList.push_back( boost::make_shared< PropagationDependentVariableTerminationSettings >(
                                                 boost::make_shared< SingleDependentVariableSaveSettings >(
                                                     altitude_dependent_variable, "SpacePlane", "Earth" ), 1.0E3, true ) );
```

Change this to:

   ```
 std::vector< boost::shared_ptr< PropagationTerminationSettings > >  propagationTerminationSettingsList;
    propagationTerminationSettingsList.push_back( boost::make_shared< PropagationDependentVariableTerminationSettings >(
                                                 boost::make_shared< SingleDependentVariableSaveSettings >(
                                                     altitude_dependent_variable, "SpacePlane", "Earth" ), 120.0E3, false ) );
    propagationTerminationSettingsList.push_back( boost::make_shared< PropagationDependentVariableTerminationSettings >(
                                                 boost::make_shared< SingleDependentVariableSaveSettings >(
                                                     altitude_dependent_variable, "SpacePlane", "Earth" ), 1.0E3, true ) );
    propagationTerminationSettingsList.push_back( boost::make_shared< PropagationTimeTerminationSettings >( testTimeEnd ) );
```

where testTimeEnd is a double that you set to some (pretty large) value, to let the simulation 'try' to leave the 1 to 120 km bounds.

Hope this clears it up,

Dominic
