### ISSUE TITLE
Fixed step sizes in rungeKutta87DormandPrince Runtime error

### ISSUE THREAD

**Issue by mvandenbroeck** [Tudat/tudat#111]
Hi,

When trying to set the minimum step size equal to the maximum step size when using the rungeKutta87DormandPrince coefficients in the numerical integrator, the program gives the following runtime error:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator<double, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> >::MinimumStepSizeExceededError> >'
  what():  Minimum step size exceeded.

I thought it had to do with the fact that the number of steps is not an integer. But even for step sizes for which the number of steps is an integer, the code gives the run time error.

Is there an easy fix for this, so that it allows me to take fixed step sizes in a variable step size numerical integrator.

Thanks,

Michael

**Comment by DominicDirkx** [comment]
Hi Michael,

The cause of this error is what is shown at the end of the message:

what(): Minimum step size exceeded.

Which means that the step size that the integrator requires is smaller than the minimum step that is provided by you. The Dormand-Prince is much more susceptible to this behaviour than the RKF integrators (it seems to be much more stringent in certain situations).

I would propose that you either make the mimum step size small, make the tolerances looser, or choose a different integrator,

Best,

Dominic

**Comment by mvandenbroeck** [comment]
Thanks! Loosening the tolerances indeed solves the problem.

So it is the combination of the large minimumStepSize and the stringent tolerances that cause the problem because for the numerical integrator, meeting the user-defined tolerances is more important than meeting the user-defined minimumStepSize.

**Comment by DominicDirkx** [comment]
I wouldn't say that one is more 'important' than the other. Both specofy properties of the integrator that are to be met. In the algorithm, a new step size is computed (if needed) using the tolerances. Subsequently it is checked whether the new time step meets with the requirement set by the minimum step size. If it does not meet this requirements, it indicates that it is not possible to perform the integration with the required settings, and the integration terminated.

**Comment by mvandenbroeck** [comment]
Ok, I understand.
Thanks!
