### ISSUE TITLE
Root finder in Encke propagator not converging for high eccentricity orbits

### ISSUE THREAD

**Issue by thomasvdj** [Tudat/tudat#112]
When using the Encke propagator for an orbit of high eccentricity, for example e = 0.8, the root finder used by the Encke propagator does not converge in some cases. The attached file is a slightly changed version of singleSatellitePropagator.cpp that replicates the issue.

[singleSatellitePropagator.zip](https://github.com/Tudat/tudat/files/733343/singleSatellitePropagator.zip)

**Comment by DominicDirkx** [comment]
Thanks for catching this, the mistake has been patched in https://github.com/Tudat/tudat/commit/6f6dcbc04ae47c671f83345a3967a61e1bbbcdb7
