### ISSUE TITLE
getAerodynamicCoefficientIndependentVariables( ) always return currentAngleOfAttack = 0

### ISSUE THREAD

**Issue by jesperspillenaar** [Tudat/tudat#114]
In my aerodynamic guidance system I am trying to update the aerodynamic coefficients to match with the current flight conditions. The independent variables are 'Mach' and 'angle of attack'. I update with:

aerodynamicCoefficientInterface_->updateCurrentCoefficients( vehicleFlightConditions_->getAerodynamicCoefficientIndependentVariables(  ) );

All works well except that 'getAerodynamicCoefficientIndependentVariables(  )' always returns: angle of attack = 0. How can this be solved?

**Comment by DominicDirkx** [comment]
HI Jesper,

Does the getAerodynamicCoefficientIndependentVariables function return 0 at every time step of the numerical propagation? If so, what values do you set the angle to in your code? Do you have a link to the code you are using?

Dominic

**Comment by DominicDirkx** [comment]
The wiki has now been updated to explicitly explain this fact:

http://tudat.tudelft.nl/projects/tudat/wiki/Aerodynamic_Guidance
