### ISSUE TITLE
Guidance interpolator angle of attack only uses first two input values 

### ISSUE THREAD

**Issue by eroorda** [Tudat/tudat#115]
For the guidance I am following a predefined angle of attack profile.  To update the guidance I use the LinearInterpolatorDouble to interpolate the angle of attack value for the current altitude; 

            currentAngleOfAttack_ = (angleOfAttackInterpolator->interpolate (
                        vehicleFlightConditions_->getCurrentAltitude( ) ) ) * mathematical_constants::PI / 180.0;

Where   angleOfAttackInterpolator = boost::make_shared<interpolators::LinearInterpolatorDouble>
                   ( altitudeInKm, angleOfAttackInDeg);

The angle of attack values that result from this interpolator only follow the interpolation between the first two given values (of the vectors altitudeInKm and angleOfAttackInDeg). Thus the resulting angle of attacks are all on one linear line (wrt altitude). What is going wrong that the interpolation only takes place for the first two input values?

**Comment by DominicDirkx** [comment]
Could you attach your full application code, including any data files you may be using (or send by e-mail if you don't want it visible), and indicate where the problem is occuring?

**Comment by DominicDirkx** [comment]
Issue has been resolved, the problem was due to the independent variable data being passed to the interpolator in descending, not ascending order
