### ISSUE TITLE
Writing dependent variables to text file column order bug 

### ISSUE THREAD

**Issue by eroorda** [Tudat/tudat#119]
When I print the aerodynamic moment coefficients and control surface deflection as dependent variables (in that order), in the actual output text file (computed by writeDataMapToTextFile) their column orders are reversed. 

Thus the application output window says ;

Dependent variables being saved, output vectors contain: 
Vector entry, Vector contents
0, Mach number of Aurora
1, Altitude of Aurora w.r.t. Earth
2, Aerodynamic moment coefficients of Aurora
3, Control Surface Deflectionof Aurora w.r.t. WingFlap

Whereas in the text file it actually is; 

Dependent variables being saved, output vectors contain: 
Vector entry, Vector contents
0, Mach number of Aurora
1, Altitude of Aurora w.r.t. Earth
2, Control Surface Deflectionof Aurora w.r.t. WingFlap
3, Aerodynamic moment coefficients of Aurora

**Comment by DominicDirkx** [comment]
Thanks for opening this issue, I've uploaded a modification to the Github branch. For now, I would recommend not updating the branch directly, we're making a few modifications that may break your code if you do (nothing major, main change is that basic_mathematics::Vector6d will become Eigen::Vector6d). If you have a look at the changes of this commit:

https://github.com/DominicDirkx/tudat/commit/5c7a291d1b5b63ff63f2216727e3aed08a114ec1

you'll see that only propagationOutput.h is modified. Copy and paste these changes to this file on your machine, and the terminal output should match the file contents.
