### ISSUE TITLE
Solution explosion when using NRLMSISE-00

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudat#128]
I've noticed that using the NRLMSISE-00 atmosphere model can lead to a solution explosion in which suddenly the X,Y,Z start changing very quickly. For instance, a "normal" LEO at 200 km altitude:

![leonrlmsise](https://cloud.githubusercontent.com/assets/10518548/22889006/fb6ad1d6-f207-11e6-85c7-3276f0ad52b3.png)

When propagating the same orbit with the exponential model instead of NRLMSISE-00, there is no singularity:

![leoexp](https://cloud.githubusercontent.com/assets/10518548/22889045/1ab84d02-f208-11e6-85ae-c9dc5e0f23a0.png)

So I am guessing that some discontinuity in the data provided by the NRLMSISE model is causing the equations of motions to change very quickly and the RK4 cannot respond properly to this discontinuity.
Using a variable step-size integrator for this orbit yields:
`
terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<tudat::numerical_integrators::RungeKuttaVariableStepSizeIntegrator<double, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> >::MinimumStepSizeExceededError> >: Minimum step size exceeded.
`
even when setting the minimum step size to something very low, such as 1E-12. At least here you get an error; if you are using RK4 you only realise something went wrong when you get to analyse the data.

I can provide more info about the initial conditions, environment, settings etc. needed to reproduce this problem.

**Comment by DominicDirkx** [comment]
Hi Aleix,

That's very peculiar, your idea on the origin of the problem sounds very likely. Could you provide the file you use to run the application (either as an attachment or a link to your github account)? I'll have a more detailed look to figure out what's going on here.

**Comment by aleixpinardell** [comment]
I am running a Tudat app that can be compiled from the source code in [this repo](https://github.com/aleixpinardell/tesp). This app takes a (path to a) text-file with extension ".tespin" as argument. To reproduce the problem, the following text-file can be provided:
```
GEOPOTENTIAL_DEGREE  7

BODY_MASS  3000.0  % kg
BODY_CROSS_SECTIONAL_AREA  15.0  % m^2
BODY_DRAG_COEFFICIENT  2.2

INITIAL_EPOCH  '1998-01-01 12:00'
END_EPOCH  '1998-01-03 12:00'

INITIAL_PERIGEE_ALTITUDE  200.0  % km
INITIAL_APOGEE_ALTITUDE  200.0  % km
INITIAL_INCLINATION  10.0  % deg
INITIAL_LONGITUDE_ASCENDING_NODE  196.0  % deg

OUTPUT_BODY_KEPLERIAN_STATE  NO
OUTPUT_BODY_CARTESIAN_STATE  YES
OUTPUT_SUN_POSITION  YES

SKIP_PROPAGATION_IF_RESULTS_FOUND  NO

```

**Comment by DominicDirkx** [comment]
Hi Aleix,

I've run the program, and i think I know what is happening. For this simulation, the termination on final altitude seems to be turned off. The vehicle, however, is dipping very deeply into the atmosphere. When running the RK4 simulation (step size 60s), the acceleration comes to about 40000 m/s2. At 60 s step size, this will (quite unrealistically) scatter the spacecraft away from the Earth. In the variable step size integrator, the spacecraft propagates to an altitude < 0 km. The propagation happily continues here, until the density/acceleration reches ridiculous values and the step size control can no longer keep up. In short, it seems as though the vehicle is crashing, but the simulation is not catching this. Consider setting an altitude>0 termination for all cases.

My guess is that the exponential atmosphere produces a density that is too low at high altitudes, and the spacecraft is not captured as it is for the NRLMSISE model.

Let me know what you think,

Dominic

**Comment by aleixpinardell** [comment]
Yes, the problem was indeed that the object was re-entering very quickly.
