### ISSUE TITLE
Unit Tests in  Windows 10 allowed to be named as '...Setup' or '...Updater'

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#129]
Failed unit tests, windows 10 Education.
I made .txt file from LastTest.log since that filetype wasnt allowed to attach. 
[LastTest.txt](https://github.com/Tudat/tudat/files/777522/LastTest.txt)

**Comment by DominicDirkx** [comment]
Hi Frank,

I recall this issue having occured in the past as a result of an overzealous virus scanner/Windows defender. In your Windows explorer .../tudat/bin/unit_tests/, does there happen to be a 'defender' icon on these three executables?

**Comment by FrankHogervorst** [comment]
Yes there is

**Comment by DominicDirkx** [comment]
Duplicate report: #130

**Comment by DominicDirkx** [comment]
A fix is proposed in pull request #132.

This afternoon, we can test it to make sure it works on your systems, then commit it

**Comment by DominicDirkx** [comment]
To everyone afflicted by this issue: we have made the necessary modifications and have updated the code on Github. If you follow the guide here (step 5.2):

http://tudat.tudelft.nl/projects/tudat/wiki/Setup_Tudat_Bundle_Smartgit_Developer#52-EVERY-TIME-Update-to-the-latest-Tudat

You can retrieve the latest version of the code. Remember to _first_ recompile Tudat before rerunning all the tests. 

If the problem persists, please let us know.

**Comment by Rimsky** [comment]
Is it possible to just recompile the changed parts instead of whole tudat?

**Comment by magnific0** [comment]
@Rimsky this should be be the default behaviour, unless you delete your build folder. Only changed code will be actually rebuild. Of course it will run through all the tudat libraries and make sure they're there and up-to-date, but this should take significantly less time.
Did you experience a complete rebuild after pulling in the new Tudat version from the upstream?

**Comment by Rimsky** [comment]
@magnific0 I rebuild it partly I think (in few minutes, for me first compile took more than 3 hours). 
Got the following message:
The following tests FAILED:
	 77 - test_EnvironmentModelUpdater (BAD_COMMAND)
	136 - test_EnvironmentSetup (BAD_COMMAND)
	137 - test_AccelerationModelSetup (BAD_COMMAND)
Errors while running CTest
makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
18:08:40: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
The kit Desktop has configuration issues which might be the root cause for this problem.
When executing step "Make".

Maybe I did something wrong with pulling the new code or building the code.

**Comment by DominicDirkx** [comment]
It looks like the code did not get updated correctly (the names of the unit tests should be different). If you bring your laptop on Thursday, we can have a look.

**Comment by magnific0** [comment]
@rimsky one more quick test: try deleting the old applications from the tudat/bin folder.

**Comment by DominicDirkx** [comment]
Also, did you remove the 'test' command in the project tab _before_ recompiling the code?

**Comment by TommyKranen** [comment]
I pulled the code from github and deleted all previously created .exe's in the tudat/bin folder. Recompiled Tudat and afterwards added the 'test' command in the project tab, compiling again gave the following error:

```
98% tests passed, 3 tests failed out of 137

Total Test time (real) =  87.76 sec

The following tests FAILED:
	 77 - test_EnvironmentModelUpdater (BAD_COMMAND)
	136 - test_EnvironmentSetup (BAD_COMMAND)
	137 - test_AccelerationModelSetup (BAD_COMMAND)
Errors while running CTest
makefile:70: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
11:05:09: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "Make"
11:05:09: Elapsed time: 01:28.
```

**Comment by magnific0** [comment]
Hi @TommyKranen, thanks for reporting your findings and trying to remove the old .exes. Can you confirm the new renamed executables are build? If this is the case the build doesn't seem to want to forget old test executables.

**Comment by TommyKranen** [comment]
@magnific0, I'm not sure as to what the new names should be. See below for the full extract of all executables in the `\tudatBundle\tudat\bin\unit_tests` directory.

`test_AccelerationModel.exe
test_AccelerationModelSetup.exe
test_AccelerationPartials.exe
test_AerodynamicAngleCalculator.exe
test_AerodynamicCoefficientGenerator.exe
test_AerodynamicCoefficientReader.exe
test_AerodynamicCoefficientsFromFile.exe
test_AerodynamicMomentAndAerodynamicForce.exe
test_AerodynamicsNamespace.exe
test_AngularPositionModel.exe
test_ApparentAccelerationModel.exe
test_ApproximatePlanetPositions.exe
test_AstrodynamicsFunctions.exe
test_BasicInputOutput.exe
test_BasicStatistics.exe
test_BodyMassPropagation.exe
test_BodyShapeModels.exe
test_BoostDistributions.exe
test_CannonBallRadiationPressureAccelerationAndForce.exe
test_CartesianStateExtractor.exe
test_CelestialBodyConstants.exe
test_CentralAndZonalGravityModel.exe
test_CentralBodyData.exe
test_ClohessyWiltshirePropagator.exe
test_CompositeEphemeris.exe
test_ControlSurfaceIncrements.exe
test_CoordinateConversions.exe
test_CowellStateDerivative.exe
test_CubicSplineInterpolator.exe
test_CustomStatePropagation.exe
test_DependentVariableOutput.exe
test_DictionaryInputSystem.exe
test_EnckeStateDerivative.exe
test_EnvironmentModelUpdater.exe
test_EnvironmentSetup.exe
test_EscapeAndCapture.exe
test_EulerIntegrator.exe
test_ExponentialAtmosphere.exe
test_Extractor.exe
test_FieldValue.exe
test_FixedWidthParser.exe
test_FrameManager.exe
test_GeodeticCoordinateConversions.exe
test_GravitationalForce.exe
test_GravityAssist.exe
test_GravityFieldVariations.exe
test_GroundStationState.exe
test_HeatTransfer.exe
test_HermiteCubicSplineInterpolator.exe
test_JacobiEnergy.exe
test_KeplerEphemeris.exe
test_KeplerPropagator.exe
test_KeplerStateExtractor.exe
test_KernelDensityDistribution.exe
test_LagrangeInterpolator.exe
test_LambertRoutines.exe
test_LambertTargeter.exe
test_LambertTargeterGooding.exe
test_LambertTargeterIzzo.exe
test_LawgsSurfaceGeometry.exe
test_LegendrePolynomials.exe
test_LibrationPoints.exe
test_LightTime.exe
test_LinearAlgebra.exe
test_LinearFieldTransform.exe
test_LinearInterpolator.exe
test_LorentzStaticMagneticAccelerationAndForce.exe
test_MathematicalConstants.exe
test_MathematicalShapeFunctions.exe
test_MatrixTextFileReader.exe
test_MeanToEccentricAnomalyConversion.exe
test_MeanToHyperbolicEccentricAnomalyConversion.exe
test_MissileDatcomData.exe
test_MissileDatcomReader.exe
test_MissionGeometry.exe
test_ModifiedEquinoctialElementConversions.exe
test_MultiArrayReader.exe
test_MultiLinearInterpolator.exe
test_MultiRevolutionLambertTargeterIzzo.exe
test_MultiTypeStatePropagation.exe
test_MultiVariateProbabilityDistributions.exe
test_MutualSphericalHarmonicsGravityModel.exe
test_NearestNeighbourSearch.exe
test_NRLMSISE00Atmosphere.exe
test_NumericalDerivative.exe
test_NumericalIntegrator.exe
test_OneWayRangeModel.exe
test_OrbitalElementConversions.exe
test_ParsedDataVectorUtilities.exe
test_PhysicalConstants.exe
test_PositionObservationModel.exe
test_RadiationPressureInterface.exe
test_RandomSampling.exe
test_ReferenceFrameTransformations.exe
test_RootFinders.exe
test_RotationAboutArbitraryAxis.exe
test_RotationalEphemeris.exe
test_RotationMatrixPartials.exe
test_RungeKutta4Integrator.exe
test_RungeKutta87DormandPrinceIntegrator.exe
test_RungeKuttaCoefficients.exe
test_RungeKuttaFehlberg45Integrator.exe
test_RungeKuttaFehlberg56Integrator.exe
test_RungeKuttaFehlberg78Integrator.exe
test_RungeKuttaVariableStepSizeIntegrator.exe
test_SeparatedParser.exe
test_SequentialVariationEquationIntegration.exe
test_ShapiroTimeDelay.exe
test_SimpleLinearRegression.exe
test_SimpleRotationalEphemeris.exe
test_SolarActivityData.exe
test_SphericalHarmonicPartials.exe
test_SphericalHarmonics.exe
test_SphericalHarmonicsGravityField.exe
test_SphericalHarmonicsGravityModel.exe
test_SphericalOrbitalStateConversions.exe
test_SpiceInterface.exe
test_StateDerivativeRestrictedThreeBodyProblem.exe
test_StateElementConversions.exe
test_StoppingConditions.exe
test_StreamFilters.exe
test_TabulatedAerodynamicCoefficients.exe
test_TabulatedAtmosphere.exe
test_TabulatedEphemeris.exe
test_TextParser.exe
test_ThirdBodyPerturbation.exe
test_ThrustAcceleration.exe
test_TimeConversions.exe
test_TimeTypes.exe
test_TrapezoidalIntegrator.exe
test_TriAxialEllipsoidGravity.exe
test_TwoLineElementsTextFileReader.exe
test_UnifiedStateModelElementConversions.exe
test_UnitConversions.exe
test_UnitConversionsCircularRestrictedThreeBodyProblem.exe
test_VariationalEquations.exe
test_ZeroRevolutionLambertTargeterIzzo.exe
`

**Comment by magnific0** [comment]
Thanks for the quick reply. The new names are:

```
test_EnvironmentModelComputations
test_EnvironmentCreation
test_AccelerationModelCreation
```

So they don't seem to be present, confirming @DominicDirkx suspicion that the new code is not pulled in correctly (possibly lack in guide). Let's look at this Thursday, in the mean time don't be hesitant to continue working on the assignment.
