### ISSUE TITLE
Unit Tests in  Windows 10 allowed to be named as '...Setup' or '...Updater' - Bug Fix

### ISSUE THREAD

**Issue by DominicDirkx** [Tudat/tudat#131]
As has been noted in issues #129 and #130 (many thanks for bringing this to our attention), three of the unit tests refuse to run from Qt when using Windows. The issue seems to be related with Windows Defender(?) not allowing Qt to run them.

It seems that the issue is simply the _name_ of the executables:

test_EnvironmentModelUpdater
test_EnvironmentSetup
test_AccelerationModelSetup

Changing them to 

test_EnvironmentModelComputations
test_EnvironmentCreation
test_AccelerationModelCreation

seems to fix the problem (see attachment) 
![windowsexecutabletudat](https://cloud.githubusercontent.com/assets/5039068/22995971/4c5cf512-f3cd-11e6-85e8-e016983488cc.png)

Let's test this tomorrow to see if the solution is robust

**Comment by FrankHogervorst** [comment]
It fixed one of the failures, two left. LastTest.log is attached.
[LastTest.txt](https://github.com/Tudat/tudat/files/780266/LastTest.txt)

**Comment by DominicDirkx** [comment]
Closing this issue, a pull request has been added #132. After testing on an additional machine on Monday, we will post a guide on how to retrieve the corrected code.
