### ISSUE TITLE
add_executable cannot create target "application_HelloWorld"

### ISSUE THREAD

**Issue by BeatrizMOliveira** [Tudat/tudat#137]
I got these issues when trying to open the tudatBundle
![screenshot 2017-02-17 16 34 48](https://cloud.githubusercontent.com/assets/25655772/23071398/849687ce-f52e-11e6-8351-9b31c983c6cf.png)

**Comment by DominicDirkx** [comment]
Could you add the full compile output in a text file?

Thanks,

Dominic

**Comment by DominicDirkx** [comment]
If I'm right, this error occured at the end of the

http://tudat.tudelft.nl/projects/tudat/wiki/Setup_New_Applications

step. 

The guide was not quite clear on the steps to take for the space project, and which to take for a 'regular' application, I'm afraid. You seem to have added:

add_subdirectory( "${PROJECTROOT}/tudatApplications/myApplication/MyApplication")

to your top-level CMakeLists.txt (in tudatBundle). If you change this to:

add_subdirectory( "${PROJECTROOT}/tudatApplications/myApplication/spaceProjectAssignment1")

it will hopefully work. Make sure to check whether the name of the directory (including capital letters) is correct for you.

**Comment by BeatrizMOliveira** [comment]
I think that solved it, but now I get another one.
![screenshot 2017-02-17 18 39 16](https://cloud.githubusercontent.com/assets/25655772/23076182/a683a04a-f53f-11e6-982c-54cb0e0a9188.png)

Should I comment out the code as for the remaining solutions?

**Comment by DominicDirkx** [comment]
Also comment (using #) the application_LroPropagation_Sol1, that should fix it.

**Comment by BeatrizMOliveira** [comment]
Thank you. It's fixed.

**Comment by DominicDirkx** [comment]
Great!
