### ISSUE TITLE
Unit_test failures

### ISSUE THREAD

**Issue by ifodde** [Tudat/tudat#138]
when doing the unit test, some failures occcured, just to be sure I wanted to ask if this is okay. Here is the error message and the log file:

98% tests passed, 3 tests failed out of 137

Total Test time (real) = 203.81 sec

The following tests FAILED:
	 77 - test_EnvironmentModelUpdater (BAD_COMMAND)
	136 - test_EnvironmentSetup (BAD_COMMAND)
	137 - test_AccelerationModelSetup (BAD_COMMAND)
Errors while running CTest
makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
21:02:28: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "Make"
21:02:28: Elapsed time: 03:24.

[error_qt.txt](https://github.com/Tudat/tudat/files/784202/error_qt.txt)

**Comment by Rimsky** [comment]
exact same problem here!

**Comment by DominicDirkx** [comment]
This issue seems to occur for most Windows users. We're tracking it in issue #129, and are working on a solution on #131.

Its not a problem, you can start on the assignments if you like. We'll post a solution guide early next week
