### ISSUE TITLE
Using debugger

### ISSUE THREAD

**Issue by BeatrizMOliveira** [Tudat/tudat#139]
I got this error when trying to run my version of the LROPropagation application:
'The vectors used in the lagrange interpolator initialization are empty'
I've been trying to set breakpoints with the debugger but it seems to run the entire code instead. How can  I make use of the debugger?

**Comment by DominicDirkx** [comment]
I think this was a small error on our side: the final time of the simulation was smaller than the initial time, leading to this error. I have sent a blackboard announcement on how to correct this. If you want to now the details of _why_ this is occuring, let me know and I'll be hapy to explain. Apologies for the inconvenience.

Do note that the code as provided will not yet run, you need to make a couple of modifications for it to produce output
