### ISSUE TITLE
"symbol(s) not found for architecture x86_x64" "linker command failed"

### ISSUE THREAD

**Issue by melelakel** [Tudat/tudat#144]
Hi !

When trying to build the libraries on Qt creator, I have the following two error messages.
![screen shot 2017-02-22 at 10 43 01](https://cloud.githubusercontent.com/assets/25686946/23205892/d99ad994-f8eb-11e6-856e-0ff33937f8bd.png)

Last time, during the "open hours", Dominic tried to fix it and it seems that my computer was using two different compilers:
![screen shot 2017-02-22 at 10 43 30](https://cloud.githubusercontent.com/assets/25686946/23205958/30238fb8-f8ec-11e6-9952-63252a9d0f19.png)
He advised me to deinstall it and install again but even after that, it keeps giving me the same error.

**Comment by magnific0** [comment]
Hi @melelakel, unfortunate that this didn't solve your problem. Can you post your clang version here and a screenshet of your kit?

To get your clang version see:
http://tudat.tudelft.nl/projects/tudat/wiki/Troubleshooting#12-Check-Compiler

Next to gcc -v, do clang -v. Please report both. Thanks!

Jacco

**Comment by magnific0** [comment]
Recap open-office hours: so far we have determined that an older version of "Command Utilities for XCode" was installed (7.3). Dowloading and installing a newer version did not fix the problem as the old one was still used.

@melelakel could you please run the following command in iTerm? Please copy the output here.
    xcode-select -p

(1) After this go ahead and uninstall XCode from your system. Follow the instructions under "How to uninstall Xcode manually" here (all the way to the bottom of the guide):
https://macpaw.com/how-to/uninstall-xcode-on-macos

(3) Redownload and install the latest stable version, here
http://adcdownload.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.11_for_Xcode_8.2/Command_Line_Tools_macOS_10.11_for_Xcode_8.2.dmg

Let me know how this works out!

**Comment by DominicDirkx** [comment]
@melelakel Do you have an update on the status of this issue? 

If it still doesn't work, we can try to help you again tomorrow at the open office hours. Do make sure to go through the above steps before then.

**Comment by melelakel** [comment]
@magnific0, I did all the steps above and still get an error when building
![screen shot 2017-02-26 at 14 59 17](https://cloud.githubusercontent.com/assets/25686946/23340303/33d45a98-fc34-11e6-896d-273be7e8ab18.png)
Do I have to re-install Xcode as well?

**Comment by magnific0** [comment]
@melelakel, indeed, better to also try to install XCode 8.2. I don't think the contents of XCode are actually necessary, but it might reconfigure your system properly again. Please drop by the office hours if this does not work for you.
Thanks!

**Comment by melelakel** [comment]
@magnific0 I tried to download it on another computer but I got this error
![capture d ecran 2017-02-27 a 12 12 04 pm](https://cloud.githubusercontent.com/assets/25686946/23359342/1f27c3e8-fce6-11e6-8228-5a8e895c6596.png)
Is there a quick way to solve it (by adding a code line in the CmakeList.txt ?) 

I won't be able to come at the open hour today, however, can I drop by your office  tomorrow ?

**Comment by DominicDirkx** [comment]
@melelakel This looks like a simpler problem than your previous one. Could you attach a screenshot of your options->build&run->kits window?

It should look something (but not exactly!) like the following

![image](https://cloud.githubusercontent.com/assets/5039068/23361221/e03a327e-fcef-11e6-887f-617f6b451ef5.png)

**Comment by melelakel** [comment]
I have the following:
![capture d ecran 2017-02-27 a 1 25 13 pm](https://cloud.githubusercontent.com/assets/25686946/23361297/471a5ea6-fcf0-11e6-85b6-fa8df99686b1.png)

**Comment by DominicDirkx** [comment]
This issue was also encountered by a few others. Its resolution is shown here:

https://blackboard.tudelft.nl/webapps/discussionboard/do/message?action=list_messages&forum_id=_211258_1&nav=discussion_board_entry&conf_id=_255596_1&course_id=_57860_1&message_id=_441152_1#msg__441152_1Id

In the CMakeConfiguration 'Change' popup window change the CMAKE_C_COMPILE:string.

**Comment by melelakel** [comment]
@DominicDirkx I changed the CMAKE_C_COMPILE:string to CMAKE_C_COMPILER:STRING=/usr/bin/clang as specified in the forum but still get the same error.
![capture d ecran 2017-03-01 a 8 23 35 am](https://cloud.githubusercontent.com/assets/25686946/23449849/6baa5da2-fe58-11e6-9d80-229871c40dc1.png)
![capture d ecran 2017-03-01 a 8 23 28 am](https://cloud.githubusercontent.com/assets/25686946/23449850/6bca7664-fe58-11e6-89f2-0899e35c463f.png)
What should I do?

**Comment by DominicDirkx** [comment]
Could you post your full cmake output (it should be either under 'Compile Output' or 'General Messages' in the bottom tabs.

Try deleting your CMakeLists.txt.user file and run again. If that doesn't work, try deleting the build folder and rerun.

**Comment by melelakel** [comment]
It works, thanks ! 

I got however one error when running the test 
![capture d ecran 2017-03-01 a 10 34 00 am](https://cloud.githubusercontent.com/assets/25686946/23453963/c627bb14-fe6a-11e6-93c9-a3c05be2ab04.png)
![capture d ecran 2017-03-01 a 10 33 49 am](https://cloud.githubusercontent.com/assets/25686946/23453965/c66d68e4-fe6a-11e6-8ceb-8847bd35f173.png)

**Comment by magnific0** [comment]
@melelakel Good to hear Tudat is now building for you! This issue #136 is know and you can safely ignore it for now.
