### ISSUE TITLE
Test failures: AccelerationPartials, LegendrePolynomials & AccelerationModelCreation

### ISSUE THREAD

**Issue by bernalmencia** [Tudat/tudat#145]
After building tudat, I ran the tests and I got the following errors, about which I could not find any information in the forum:
        69 - test_AccelerationPartials (Failed)
	109 - test_LegendrePolynomials (Failed)
	137 - test_AccelerationModelCreation (Failed)

I got the following output on the Compile Output:

98% tests passed, 3 tests failed out of 137

Total Test time (real) = 129.78 sec

The following tests FAILED:
	 69 - test_AccelerationPartials (Failed)
	109 - test_LegendrePolynomials (Failed)
	137 - test_AccelerationModelCreation (Failed)
Errors while running CTest
makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
15:03:18: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "Make"

**Comment by DominicDirkx** [comment]
Thanks for letting us know! Could you also post the test output file (see end of 'Configure and Build' guide on tudat website)

**Comment by DominicDirkx** [comment]
@bernalmencia  Could you please post your test log file? Without it, we cannot diagnose the situation.

**Comment by bernalmencia** [comment]
Sorry for the delay, it was hard for me to find the file. I uploaded the .log file as a .txt file because the page does not accept .log attachments.

[LastTest_log.txt](https://github.com/Tudat/tudat/files/804007/LastTest_log.txt)

**Comment by DominicDirkx** [comment]
No worries. I've had a look and all errors appear to be a result of rounding (last 1 or 2 significant digits coming out differently than on most other systems). We'll patch the code shortly to make sure the tests pass on systems like yours as well. I'll post a message here when the situation has been fixed.

**Comment by DominicDirkx** [comment]
Sorry for taking so long to get to this. The Tudat master has been updated (3e16a0c1eaca0900c186f9aab890042cb0c1e0c5) with some modifications that I hope will mitigate the errors you are getting in the tests
