### ISSUE TITLE
Runtime error: "'std::bad_alloc' what(): std::bad_alloc"

### ISSUE THREAD

**Issue by BeatrizMOliveira** [Tudat/tudat#146]
When trying to run my code for part 2 I get the following exit code and message:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
C:\3_Space_Project_TUDat\tudatBundle\tudatApplications\Assign_1\bin\applications\application_LroPropagation_Sol3.exe exited with code 3

**Comment by magnific0** [comment]
Hi @BeatrizMOliveira, there could be a number of causes. The best way to solve this is run a debugger, such that the offending code can be identified. The following documents should help you run the debugger on your system.

Setup the debugger for QtCreator:
http://doc.qt.io/qtcreator/creator-debugger-engines.html

QtCreator debugging documentation:
http://doc.qt.io/qtcreator/creator-debugger-operating-modes.html

If you can't get the debugger to run. You can also populate your code with ```ai++; std::cout << "Still no crash " << ai << std::endl;``` messages, and just increment the number for each statement. Define ```int ai = 0;``` at the top of your program.

Good luck!

**Comment by DominicDirkx** [comment]
Hi @BeatrizMOliveira, if you push your code to your own _**private**_ repository and link to it here, we can have a look.

**Comment by BeatrizMOliveira** [comment]
The code file shows up as Ignored in Smartgit. I'm not being able to push it...

**Comment by DominicDirkx** [comment]
Ok, if you send it by email Ill have a quick look. Otherwise, drop by on Monday,

Have a nice weekend,

Dominic

**Comment by DominicDirkx** [comment]
This problem was caused by excessive memory (RAM) usage when running the simulation with RK4 integrator and 0.1 time step. An announcement has been placed on blackboard explaining the situation and its mitigation.
