### ISSUE TITLE
CowelstateDerivative & RKF56 Unit Test Failure on Mac

### ISSUE THREAD

**Issue by shfmartens** [Tudat/tudat#151]
[unit_test_failure.txt](https://github.com/Tudat/tudat/files/803793/unit_test_failure.txt)

**Comment by DominicDirkx** [comment]
Thanks for uploading this. 

You have two distinct failures, which are tracking through issues #136 and #141 .

The failure of the RKF56 is completely irrelevant for the assignments, as it is not used anywhere. The Cowell unit test failure is highly unlikely to be an issue, but we are actively looking into the cause of it. Fixes will be communicated through the two issues when ready.
