### ISSUE TITLE
Implement Catch unit test framework

### ISSUE THREAD

**Issue by kartikkumar** [Tudat/tudat#16]
I've been using the `Catch` unit test framework for a while now (https://github.com/philsquared/Catch) and it works like a charm. It's a lightweight dependency (1 header file) and can be used for TDD and BDD. 

Also also for the dependency on the Boost unit test framework to be eliminated, hopefully allowing Boost to be removed as a core dependency of the library down the line.

**Comment by DominicDirkx** [comment]
I'm closing this issue. I don't see us putting in the time to fully remove the boost dependency of the code, which is the main, if not the only, reason for pursuing this.
