### ISSUE TITLE
boost libraries not found: "Library not loaded" "Image not found"

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#161]
After moving/reinstalling Tudat in a new folder, I keep getting errors about loading libraries. For instance, while running Hello World application, I get:
`dyld: Library not loaded: libboost_unit_test_framework-mt.dylib`
`Referenced from: /Users/Michele/GitHub/tudatBundle/tudatExampleApplications/templateApplication/bin/applications/application_HelloWorld`
`Reason: image not found`
`The program has unexpectedly finished.`

**Comment by magnific0** [comment]
@mfacchinelli after looking at your system yesterday I have the idea that it links the boost libraries correctly, but then forgets where to find them. 

To confirm, can you please post the output of

     otools -L tudatBundle/tudat/bin/unit_tests/test_NumericalDerivative

and 

     otool -l tudatBundle/tudat/bin/unit_tests/test_NumericalDerivative | grep LC_RPATH -A2

This post on SO seems to talk about the exact same issue:
http://stackoverflow.com/questions/32460262/mac-os-dynamically-linked-library-not-found-despite-correct-rpath

**Comment by magnific0** [comment]
Can you also post the output of the CMake here. Just the part where it lists the libraries that we added yesterday is fine. Thanks!

**Comment by mfacchinelli** [comment]
I ran the commands you gave me in the terminal. These are the outputs:
```
tudatBundle/tudat/bin/unit_tests/test_NumericalDerivative:
	libboost_unit_test_framework-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
and
```
          cmd LC_RPATH
      cmdsize 72
         path /Users/Michele/GitHub/tudatBundle/cspice/include/../lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 64
         path /Users/Michele/GitHub/tudatBundle/nrlmsise-00/lib (offset 12)
```
I am not sure what you mean with the output of the CMake. What do you mean?

**Comment by magnific0** [comment]
Thanks for the providing the outputs. It seems that it tries to use dynamic libraries of boost instead of static ones. Dynamic libraries are linked at runtime. This explains why all executables build, but can't find the libraries. Still I would expect it to use the full path (like /usr/lib/libc++.1.dylib).

Can you try rebuilding Tudat, but forcing boost to use the static libraries? Place the following line

    set(Boost_USE_STATIC_LIBS   ON)

just before add_boost in [tudatBundle/CMakeLists.txt](https://github.com/Tudat/tudatBundle/blob/master/CMakeLists.txt#L57) and before any find_packge(boost) in the [subproject's CMakeLists.txt](https://github.com/Tudat/tudat/blob/master/Tudat/CMakeLists.txt#L100). Last part shouldn't be necessary, but let's not take any chances.

The output of CMake that is generated when you configure the project, see #152 for reference, I'm looking for these outputs in specific:

    -- FILESYSTEM: ON - /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/boost/stage/lib/libboost_filesystem-mt.a
    [...]
    -- UNIT_TEST_FRAMEWORK: ON - /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/boost/stage/lib/libboost_unit_test_framework-mt.a

**Comment by mfacchinelli** [comment]
Ok, I added the `set(...)` command in both CMakeList.txt. I then ran the HelloWorld application and it worked! I also ran the assignment questions, and they seem to work fine. Thank you so much!

Just in case, this is the output of CMake:
```
-- FILESYSTEM: ON - /Users/Michele/GitHub/tudatBundle/boost/stage/lib/libboost_filesystem-mt.a
-- SYSTEM: ON - /Users/Michele/GitHub/tudatBundle/boost/stage/lib/libboost_system-mt.a
-- THREAD: ON - /Users/Michele/GitHub/tudatBundle/boost/stage/lib/libboost_thread-mt.a
-- REGEX: ON - /Users/Michele/GitHub/tudatBundle/boost/stage/lib/libboost_regex-mt.a
-- DATE_TIME: ON - /Users/Michele/GitHub/tudatBundle/boost/stage/lib/libboost_date_time-mt.a
-- UNIT_TEST_FRAMEWORK: ON - /Users/Michele/GitHub/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a
```

**Comment by DominicDirkx** [comment]
Great! Many thanks to magnific0 for fixing this.

Should we set the command to force static linking in the master?

**Comment by magnific0** [comment]
@mfacchinelli great news, thanks for trying ! @DominicDirkx yes, this is probably a good idea. I'd like to propose adding in to tudatBundle/CMakeLists.txt (or add_boost.cmake) only, as the option should trickle down. Also in theory we support dynamic libraries, but it shouldn't be default.
