### ISSUE TITLE
Writing to file

### ISSUE THREAD

**Issue by BeatrizMOliveira** [Tudat/tudat#162]
I'm getting this error in the code I'm using:

'error_angle_1' was not declared in this scope

The code I used is below:

```
if( assignmentQuestion > 1 ){
            std::ofstream errorFile_1 ("STSErrors_"+ boost::lexical_cast< std::string >(
                                           questionName.at( assignmentQuestion ) ) + "_1.dat");
            for( unsigned int ii = 0; ii < numberOfRuns; ii++ ){
                errorFile_1 << ii << "\t" << error_angle_1.at( ii ) << std::endl
            }
            errorFile_1.close();

            std::ofstream errorFile_2;
            errorFile_2.open ("STSErrors_"+ boost::lexical_cast< std::string >( questionName.at( assignmentQuestion ) ) + "_2.dat");
            for( unsigned int ii = 0; ii < numberOfRuns; ii++ ){
                errorFile_2 << ii << "\t" << error_angle_2.at( ii ) << std::endl;
            }
            errorFile_2.close();
        }
```

Also, would this strategy create a matrix as the ones created with writeDataMapToTextFile?
I tried looking for the code of this function, but wasn't able to find it.

**Comment by DominicDirkx** [comment]
It seems that the code cannot find the variable: error_angle_1. In assuming that this is a vector of doubles (?). Is this variable in scope here? You have something like:

```
{
    std::vector< double > error_angle_1;
}

{
    //Your code to save data
}
```

If you want to have a look at the writeDataMapToTextFile, it is in the InputOutput/basicInputOutput.h file

**Comment by BeatrizMOliveira** [comment]
I got the problem. Sorry, it seems I was misreading the error message. I interpreted it as errorFile_1 not being declared.
