### ISSUE TITLE
The program has unexpectedly finished

### ISSUE THREAD

**Issue by BeatrizMOliveira** [Tudat/tudat#163]
I've previously finished question 2.5, but due to memory issues I needed to separate it from the rest of the questions. But now, I get that error. I've used some std::cout statements to figure out where it happens, and it appears to propagate everything and fails in writting the file.

**Comment by BeatrizMOliveira** [comment]
I now get a segmentation fault before the propagation (despite not having changed anything)...

**Comment by DominicDirkx** [comment]
You just missed the office hours this afternoon. If you push your code to a private repository, I can try to find time to have a look.

**Comment by DominicDirkx** [comment]
Problem was due to exceeding the maximum entry of a VectorXd
