### ISSUE TITLE
FromFunctionThrustEngineSettings does not accept a function for the bodyFixedThrustDirection

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#164]
The 'FromFunctionThrustEngineSettings' derived class from `ThrustEngineSettings` has input type  `Eigen::Vector3d ` for input `bodyFixedThrustDirection`.  It would be convenient to input functions for thrust vector steering.

**Comment by DominicDirkx** [comment]
Modification has (finally) been made in commit 4de7a7445c380f3d4914bdc1aa0f9584c63578b6
