### ISSUE TITLE
GroundStation in Doppler observation model

### ISSUE THREAD

**Issue by oscar93gonmar** [Tudat/tudat#169]
Hi,
I am trying to run the one way doppler observation model in which the receiver is an Earth ground station. Now, what I have for the receiver is:
linkEnds[ receiver ] = std::make_pair( "Earth" , ""  );
I was thinking of using the compositeEphemeris.h to create the state of the ground station but I don't really know how to do it, and whether it will be possible to input this data to compute the doppler shift afterwards.
Thank you!
Oscar

**Comment by DominicDirkx** [comment]
Hi Oscar,

You can just say:

linkEnds[ receiver ] = std::make_pair( "Earth" , "StationName" );

But then you have to define a ground station with the name "StationName". Have a look at the unitTestGroundStationState.cpp (Astrodynamics/GroundStations) for how to create a station. it has examples for definitions of the state in Cartesian, spherical and geodetic coordinates,

Dominic
