### ISSUE TITLE
Refactor file/folder structure

### ISSUE THREAD

**Issue by kartikkumar** [Tudat/tudat#17]
I've come to realise that it makes sense to use the `standard` cpp library architecture for manageability and interoperability with other libraries. I've been fine-tuning a standard template for a cpp project for a while now: it's pretty consolidate at the moment. You can find it here: https://github.com/kartikkumar/cpp-project

I think Tudat would benefit from adopting these standard practices. Would make the library easier to parse for someone used to the standard architecture of cpp projects and also has maintainability advantages.

**Comment by DominicDirkx** [comment]
Considering the various other developments that are in the pipeline, and no specific indications that users are looking for this feature, I'm closing the issue.
