### ISSUE TITLE
Verify execution order in FromFunctionThrustEngineSettings

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#170]
Verify whether the update function is called before the other functions in FromFunctionThrustEngineSettings.

**Comment by DominicDirkx** [comment]
What exactly was this issue about again? I remember I asked you to open it to remind to have a look at it, but now I forgot the details of it....

**Comment by FrankHogervorst** [comment]
Hmm, this is a while ago. This issue could be the result of a question I had about my guidance class. This class contains one function which updates the attributes (`thrustMagnitude `and `bodyFixedThrustDirection`) and has get functions to obtain these specific parameters.  

At the time I was wondering how I could call the update function only once per integration step and use the get functions for the `ThrustMagnitudeFunction_ ` and `bodyFixedThrustDirection_` inside `FromFunctionThrustEngineSettings`. Now I call `updateGuidance() ` in the `getBodyFixedThrustDirection() `method before the return statement.

**Comment by DominicDirkx** [comment]
Which classes are you referring to exactly?

**Comment by FrankHogervorst** [comment]
The updatefunction in the guidance class is located in [thrustParameterisation](https://github.com/FrankHogervorst/thesis/blob/f18676952e27cc6323bdec1bf17bbd239c6beee9/test/thrustParameterisation.cpp#L129-L188).

The get functions for [bodyFixedThrustDirection](https://github.com/FrankHogervorst/thesis/blob/f18676952e27cc6323bdec1bf17bbd239c6beee9/test/thrustParameterisation.h#L47) and [thrustMagnitude](https://github.com/FrankHogervorst/thesis/blob/f18676952e27cc6323bdec1bf17bbd239c6beee9/test/thrustParameterisation.cpp#L190).

If I remember correctly you said it wasnt required to place the updateguidance() function inside the [getBodyFixedThrustDirection](https://github.com/FrankHogervorst/thesis/blob/f18676952e27cc6323bdec1bf17bbd239c6beee9/test/thrustParameterisation.h#L47) due to the execution order in FromFunctionThrustEngineSettings. But you had to verify that.

An example of its usage can be found [here](https://github.com/FrankHogervorst/thesis/blob/f18676952e27cc6323bdec1bf17bbd239c6beee9/test/orbitSimulator.cpp#L177-L194).

**Comment by DominicDirkx** [comment]
Hi Frank,

I didn't realise that all referenced your own code. As this is specific to what you have written, I'm closing this issue. To be able to properly understand your question, you should walk me through your code some time. If you want, you can reopen this issue on your own Github Tudat, which is the correct place for it, I think.

Dominic
