### ISSUE TITLE
Unit test failures on Mac

### ISSUE THREAD

**Issue by ramanathang5** [Tudat/tudat#171]
I have three unit test failures 
6:test_TabulatedAerodynamicCoefficients
72:test_CowellStateDerivative
79:test_DependentVariableOutput
I use Mac OS X 10.12.2 
Can I continue or will this have effect on the assignments ?

Thanks
[LastTest.txt](https://github.com/Tudat/tudat/files/870753/LastTest.txt)

**Comment by DominicDirkx** [comment]
The test_CowellStateDerivative failure has been reported by various Mac users: #136.

The other two failures are related to an Earth atmosphere model. Is your download of the tudat bundle recent or are you using an older one? Do you see a folder 'nrlmsise-00' in your file tree in Qt creator? 
![image](https://cloud.githubusercontent.com/assets/5039068/24331923/021abbda-123e-11e7-8af6-71bb3ddeacde.png)

**Comment by ramanathang5** [comment]
Before I started the complete installation with new tudat bundle, I deleted the old tudat bundle which I had last year. I do not see that folder in the file tree.
![1](https://cloud.githubusercontent.com/assets/22065899/24332074/715416a2-1240-11e7-86ec-d8338ddba39d.png)

**Comment by DominicDirkx** [comment]
Could you attach you top-level CMakeLists.txt file, as well as your CMakeCache.txt file. The last one should be in your build folder (probably called qt-creator .... -build-..... or something like that, at the same level as the tudatBundle folder.

**Comment by ramanathang5** [comment]
Here they are. However, I noticed now that 'nrlmsise-00' folder is in tudatBundle folder, but did not appear in the file tree.
![screen shot 2017-03-26 at 16 53 02](https://cloud.githubusercontent.com/assets/22065899/24332312/ca9a89fe-1244-11e7-96a7-b74c79b4009a.png)



[CMakeLists.txt](https://github.com/Tudat/tudat/files/870825/CMakeLists.txt)
[CMakeCache.txt](https://github.com/Tudat/tudat/files/870826/CMakeCache.txt)

**Comment by DominicDirkx** [comment]
Strange... In line 409 of your CMakeCache.txt, you see the following line:

USE_NRLMSISE00:BOOL=OFF

Close Qt and change it to

USE_NRLMSISE00:BOOL=ON

Now reopen Qt, recompile all tests, run the tests and let us know what happens.

**Comment by ramanathang5** [comment]
The test failures I mentioned was probably due to not clearing the "build-tudatBundle" folder I had from last year. Clearing that and running, I had the failure "dyld: Library not loaded: libboost_unit_test_framework-mt.dylib" during the Hello world application run. It was rectified by adding "set(Boost_USE_STATIC_LIBS   ON)" in the CMakeLists.txt. Only test failure now is "test_CowellStateDerivative".
Thanks
