### ISSUE TITLE
Modified Equinoctical elements definition changes at 90 deg inclination for conversion from cartesian

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#174]
The Modified Equinoctical elements definition changes at 90 deg inclination for conversion from keplerian elements. This could pose a problem for polar orbit using the result of this conversion.

**Comment by magnific0** [comment]
Hi @FrankHogervorst, can you elaborate a bit? I think the current implementation takes all scenarios properly into account. The singularity for Keplerian elements is at an inclination of 0 and 180 degrees. The definition of the MEEs is different for posigrade and retrograde orbits, but does not strictly "change" at 90 degrees. You will of course have to use the retrograde definition if your inclination is close to 180 deg.

**Comment by FrankHogervorst** [comment]
I discussed this issue with @DominicDirkx. He warned me that the conversion function automatically switches to the retrograde definition if the inclination is larger than 90 degrees and back to the posigrade definition for inclinations smaller than 90 degrees.

**Comment by magnific0** [comment]
Which conversion function are you referring to? [This one](https://github.com/Tudat/tudat/blob/9b162ac74ff6c6a1f1d3c36f3703a1cb8c748cec/Tudat/Astrodynamics/BasicAstrodynamics/modifiedEquinoctialElementConversions.cpp#L53) takes a boolean flag that needs to be set manually.

**Comment by FrankHogervorst** [comment]
I'm sorry, I meant the conversion from cartesian to Modified Equinoctial Elements, which calls the one you refer to but automatically fills in the boolean flag.

**Comment by magnific0** [comment]
There is indeed the [function that tries to guess](https://github.com/Tudat/tudat/blob/9b162ac74ff6c6a1f1d3c36f3703a1cb8c748cec/Tudat/Astrodynamics/BasicAstrodynamics/modifiedEquinoctialElementConversions.cpp#L251) the most suitable MEE formulation (posi- or retrograde), which would indeed not be advisable for a polar orbit. However, there is still the [same function, but with a manual flag](https://github.com/Tudat/tudat/blob/9b162ac74ff6c6a1f1d3c36f3703a1cb8c748cec/Tudat/Astrodynamics/BasicAstrodynamics/modifiedEquinoctialElementConversions.cpp#L271).

So what exactly is the use case that's causing issues? Is this related to #165?

In general don't use the automatic code, it probably shouldn't exist (different discussion). Also be aware that your MEE state consists of 7 (not 6) variables, you need the flag to define your orbit. If you properly keep track of the value of the flag even with automatic switching you should never run into issue.

**Comment by FrankHogervorst** [comment]
@DominicDirkx asked me to create this issue when we were talking about using modified equinoctial elements. It could indeed be related to #165. Maybe Dominic can clear things up on this point? 

For me it is clear now how I can avoid potential problems for polar orbits by using the manual flag.

**Comment by DominicDirkx** [comment]
To finalize this issue: I've added a note in the Doxygen for these function functions to make it explicit that the 7th element is selected automatically.
