### ISSUE TITLE
Pagmo example problem executables not able to find boost libraries.

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#179]
The created executable for any pagmo example does not run correctly. It is unable to locate the boost libraries. The problem is now temporarily fixed by copying all relevant library files to the same folder as the executable.

Is there a more elegant solution which correctly links the executable to the correct libraries in different folders on Windows 10?

OS: Windows 10 Education
Version: 10.0.14393 Build 14393

**Comment by magnific0** [comment]
Hi @FrankHogervorst this sounds like a problem with using the dynamic libraries. If you compile your programs to use the dynamic libraries they should indeed be either in the same path as the executable or in your system path. If this is unwanted you can choose to force using static libraries, see #161 for more information.

**Comment by magnific0** [comment]
Also can you please report your MinGW version? It seems very arbitrary when CMake chooses to link to dynamic libraries instead of the static ones. This problem is relatively new and first occured for (some) Macs. In the future we should probably add the fix to the bundle's CMakeLists.txt.

**Comment by magnific0** [comment]
Update, I wrote applied to fix to ```add_boost.cmake``` and created a pull request. Perhaps @FrankHogervorst you can try whether this fixes the need to copy the libs into your bin folder? You don't need to checkout my branch as it is only one line in ```add_boost.cmake``` which you can just copy in. You will have to delete your entire build folder and of course remove the libraries that you manually copied into your bin folder.
@DominicDirkx if this is found to resolve the issue, can you accept the pull?

**Comment by FrankHogervorst** [comment]
Thanks @magnific0 this fixed the problem.

For your information: I use MinGW 5.3.0 32bit

**Comment by magnific0** [comment]
Thanks @FrankHogervorst for the information and testing the fix.

**Comment by DominicDirkx** [comment]
One comment on this (Frank: please correct me if I'm wrong), in the CMakeLists.txt for the application that was being built, the following:

if(NOT Boost_USE_STATIC_LIBS)
  set(Boost_USE_STATIC_LIBS ON)
endif()
if(NOT Boost_USE_MULTITHREADED)
  set(Boost_USE_MULTITHREADED ON)
endif()
if(NOT Boost_USE_STATIC_RUNTIME)
  set(Boost_USE_STATIC_RUNTIME ON)
endif()

had to be commented out for the executable to even compile. With these statements on, the Boost_LIBRARIES variable is the static libraries, without it, the dynamic libraries. Perhaps the issue was that it needed to be put in the top-level CMakeLists (as in https://github.com/Tudat/tudatBundle/pull/15). I'll try to reproduce the problem on a Windows machine, and see if this fixes it.

**Comment by FrankHogervorst** [comment]
@DominicDirkx  This is true indeed, forgot to mention that change.

**Comment by magnific0** [comment]
I would expect that only one of the above flags (probably Boost_USE_MULTITHREADED) caused the compilation issues. In this case it doesn't really matter whether Boost_USE_STATIC_LIBS was set top level or in the application.

**Comment by DominicDirkx** [comment]
That sounds like it makes sense. Nevertheless, I distinctly remember having to comment out 

if(NOT Boost_USE_STATIC_LIBS)
  set(Boost_USE_STATIC_LIBS ON)
endif()

to make it work....

**Comment by magnific0** [comment]
Strange, I guess it is necessary to have it set the same across the board. So perhaps PaGMO used dynamic boost libs, the application used static. Commenting out made the application also use dynamic libs, which made the code compile, but not find the libraries at runtime.

**Comment by DominicDirkx** [comment]
That's my guess as well
