### ISSUE TITLE
Numerical integration of CRTBP

### ISSUE THREAD

**Issue by lucianliu1990** [Tudat/tudat#181]
CRTBP (Circular Restricted Three Body Problem) model is commonly used in the preliminary design of space missions. Generally, it involves three bodies, the primary, the secondary and the spacecraft. The eccentricity of the secondary is set to be zero.

**Comment by DominicDirkx** [comment]
Hi Yuxin,

The code has been put in the form of a unit test, works like a charm! Code added to repository:

https://github.com/Tudat/tudat/commit/866957cfcc0a1e40ef4301d64e3dce5bf0831025
