### ISSUE TITLE
Fails in unit tests

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#183]
Hi all,

I have recently downloaded the new version of the tudat and have encountered some fails when running the unit tests. The fails occurred everytime data were loaded from spice.  In windows it seems that the command lines order is very important to make it work.  The correct order of the command lines is the followiing:

spice_interface::loadSpiceKernelInTudat( input_output::getSpiceKernelPath( ) + "pck00009.tpc" );
    spice_interface::loadSpiceKernelInTudat( input_output::getSpiceKernelPath( ) + "de-403-masses.tpc" );
    spice_interface::loadSpiceKernelInTudat( input_output::getSpiceKernelPath( ) + "de421.bsp" );

Moreover, in the unitTestLightTimeCorrectionPartials the test fails because the desired tolerance is not reached. In particular the error occurs at the following line at the second iteration (i = 1):

 BOOST_CHECK_CLOSE_FRACTION( currentParameterPartial, numericalPartialsWrtDoubleParameters[ i ].x( ), 1.0E-4 );

**Comment by DominicDirkx** [comment]
Hi Giovanni,

If I remember correctly, we fixed these issues, right? Could you open a pull request with the changes we made to get it to work?
