### ISSUE TITLE
Failed unit test - windows 10

### ISSUE THREAD

**Issue by AMPronk** [Tudat/tudat#196]
Hi, 

Running the unit tests gives me an error:

Errors while running CTest
makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
11:38:02: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "Make"
11:38:02: Elapsed time: 00:30.

Testing document attached:
[LastTest.txt](https://github.com/Tudat/tudat/files/1013749/LastTest.txt)

**Comment by DominicDirkx** [comment]
Hi,

Many of these look like errors with the Spice kernel order, which were also reported here: #183 . We implemented some fixes for them, but I don't think they've been added to the repository. 

Which operating system are you using?

Dominic

**Comment by AMPronk** [comment]
Hi Dominic,

Thank you!
My operating system is windows 10.

**Comment by DominicDirkx** [comment]
Hi Anne,

Which version of the code are you on? If you update the tudat code to the latest revision of the master branch, recompile and then rerun the tests, does this also occur?

To update the code in SmartGit, you can right-click the tudat repository and there should be option to open a 'Git shell'. A terminal environment will open after which you can use the following commands:

git checkout master
git fetch upstream 
git merge upstream/master

to get the latest version of the code.

Let me know if this works. If you get stuck with the git stuff, just let me know,

Dominic

**Comment by DominicDirkx** [comment]
Hi,

Just a quick extra note: from the names of your test executables, I'm pretty sure you're working with a relatively old version of the code (mid-February at the latest). Let me know if these errors persist if you update the master branch. If updating the branch does not go smoothly, post the problems here and we'll sort it out

Cheers,

Dominic

**Comment by AMPronk** [comment]
Hi Dominic,

Silly me. Updating solved the issue! (And a few other things I didn't quite understand)
Thanks a lot!

Anne

**Comment by DominicDirkx** [comment]
Great! Do let us know if there are any other questions/problems.
