### ISSUE TITLE
Memory issue when compiling some tests on Windows (4 Gb RAM)

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#198]
Hi all,

I have a Windows operating system and a laptop with 4 Gb RAM. I am working in the FullDevelopmentBranch and I have encountered some memory issues when compiling the following tests:

test_EstimationFromPositionDoubleLongDouble
test_EstimationFromPositionTimeDouble
test_EstimationFromPositionTimeLongDouble
test_MultiArcStateEstimation

Kind regards,
Giovanni

**Comment by DominicDirkx** [comment]
I've added a compiler flag that, when turned OFF, prevents compilation of these tests. Default is ON and if it is ON, a warning is given by CMake that it may lead to excessive compilation RAM usage with mingw/gcc. Commits have been made to development branch, so I'm closing this issue.
