### ISSUE TITLE
Sofa test failure

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#199]
Hi all,

I am working in the FullDevelopmentBranch and I have windows. When performing the several tests, the "test_SofaFundamentalArguments " fails because of the tolerance. Since the tolerance is already quite loose there might be some other problems in the code to check.

Best regards,
Giovanni

**Comment by DominicDirkx** [comment]
I've looked into this, and the tolerances that are achieved are most likely due to slightly different conventions that are being used. The tolerance that is achieved is still well below what is practically needed.
