### ISSUE TITLE
New functionality needed (EP violation parameter equation implementation)

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#202]
Hello Dominic,

As discussed together, for the simulation purposes of my thesis project I would need a new parameter to be added to the list of estimated parameters in the least squares algorithms of the Tudat, FullDevelopmentBranch. It is the Equivalence Principle violation parameter.  As agreed, I will provide you with the equation to be implemented as soon as I develop it during my thesis work.

Thank you for your support,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

I've implemented a first iteration of the estimation of the equivalence principle violation parameter in the latest version of the development branch. I'm not sure if the formulation is exactly correct, but the interfaces, which are the main challenge, are now set up to allow properties of the proper time rate component of the Doppler observable to be estimated.

Before properly documenting the modifications, I'd like to discuss them with you, and get your point-of-view on especially the interfaces. Would you be available for a quick (max. 30 minutes) meeting tomorrow (Tuesday) or Wednesday at 17:00?

Cheers,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

Thank you very much for working on the implementation. Would be great to discuss these modifications together. I'm afraid tomorrow I might have some problems so if it's fine for you I would prefer to meet on Wednesday at 17:00.

Thank you and best regards,
Giovanni

**Comment by DominicDirkx** [comment]
Implemented and closed.
