### ISSUE TITLE
New functionality implementation (empirical accelerations)

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#204]
Hi Dominic,

As discussed together, would it be possible to add empirical accelerations to the list of parameters that can be estimated with the least squares approach?

Thanks and best regards,
Giovanni

**Comment by DominicDirkx** [comment]
The empirical acceleration code, as well as the associated partial derivatives have been implemented and tested. They have been pushed to the development branch

https://github.com/Tudat/tudat/tree/development
