### ISSUE TITLE
Update documentation to new layout in Qt Creator tree

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#212]
Hi Dominic,

I am working on Linux and when I configure and build the tudat project I have a strange layout of the files. In particular I am not able to see most of the header files; there are actually only a few of them and are collected in a different folder called Headers.

I have Qt Creator 4.3.1 and when I open the 'about Qt' window it says that is Based on Qt 5.9.1 (GCC 5.3.1 20160406 (Red Hat 5.3.1-6), 64 bit)

Can this be fixed in some way? Although everything works well and the code runs properly it would be very comfortable to get back to the "usual" layout.

Thanks,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Could you post a (couple of) screenshot(s) of the tree as it looks for you?

By the way, did all unit tests pass successfully?

**Comment by ggranato92** [comment]
In this screenshot you should get an idea of how it looks like. If you need other screenshots let me know
![screenshot_qt_layout](https://user-images.githubusercontent.com/28297936/27914669-3243c006-6264-11e7-89a6-3f234b5009c3.png)

All the tests passed correctly, I just replied you on the other issue

**Comment by DominicDirkx** [comment]
I've been able to recreate this layout when reinstalling (on Windows). You are actually still able to access all the files, but they are hidden a but more deeply. In the above screenshot, if you click the 'tudat_aerodynamics' line, you'll be able to access the .h/.cpp files in Tudat/Astrodynamics/Aerodynamics.

**Comment by DominicDirkx** [comment]
I'm afraid that this simply appears to be the new Qt layout...

@FrankHogervorst Do you know if the Qt project tree is discusse anywhere explicitly? If not, it should be. If it is, it should be updated.

No need for you to write it, as you still have an installation with the original layout. Let me know where it is/will be, and I'll write the corresponding text/add screenshot.

**Comment by FrankHogervorst** [comment]
No there is no discussion of the Qt project tree in the documentation. 

This should be located in the Developer Guide section under Qt Basics. As is it similar to Github Basics. Then refer to it from the installation guide.

**Comment by DominicDirkx** [comment]
Good, thank you.

**Comment by FrankHogervorst** [comment]
I've created a first version of the Qt Basics page, with the Linux Qt project tree. https://github.com/Tudat/tudat/blob/source/developerGuide/qtBasics/qtBasics.rst
