### ISSUE TITLE
Failed unit test(s) macOS Sierra 10.12.5

### ISSUE THREAD

**Issue by TimDeurvorst** [Tudat/tudat#216]
I cannot add .log files, so I copied the LastTest.log content to a word document.

[LastTest.docx](https://github.com/Tudat/tudat/files/1142745/LastTest.docx)

**Comment by DominicDirkx** [comment]
Hi Tim,

We haven't encountered these errors before. Which compiler are you using? 

It looks likely that the error originates in only one or two places. Could you verify that the applications in the example applications run properly?

In particular: could you compile and run the single satellite propagator, and the perturbed single satellite propagator?

I'm copying the relevant parts of the log file here for reference:

51/139 Testing: test_GravityFieldVariations
51/139 Test: test_GravityFieldVariations
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_GravityFieldVariations"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/Astrodynamics/Gravitation
"test_GravityFieldVariations" start time: Jul 12 18:24 CEST
Output:
----------------------------------------------------------
Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 365.
Running 1 test case...
unknown location:0: fatal error in "testGravityFieldVariations": signal: SIGABRT (application abort requested)

*** 1 failure detected in test suite "Master Test Suite"
<end of output>
Test time =   0.11 sec
----------------------------------------------------------
Test Failed.
"test_GravityFieldVariations" end time: Jul 12 18:24 CEST
"test_GravityFieldVariations" time elapsed: 00:00:00
---------------------------------------------------------

69/139 Testing: test_AccelerationPartials
69/139 Test: test_AccelerationPartials
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_AccelerationPartials"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials
"test_AccelerationPartials" start time: Jul 12 18:24 CEST
Output:
----------------------------------------------------------
Assertion failed: ((!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."), function resize, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/PlainObjectBase.h, line 285.
Running 3 test cases...
unknown location:0: fatal error in "testThirdBodyGravityPartials": signal: SIGABRT (application abort requested)
/Users/Tim/tudatBundle/tudat/Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials/UnitTests/unitTestAccelerationPartials.cpp:279: last checkpoint

*** 1 failure detected in test suite "Master Test Suite"
<end of output>
Test time =   0.06 sec
----------------------------------------------------------
Test Failed.
"test_AccelerationPartials" end time: Jul 12 18:24 CEST
"test_AccelerationPartials" time elapsed: 00:00:00
----------------------------------------------------------

77/139 Testing: test_EnvironmentModelComputations
77/139 Test: test_EnvironmentModelComputations
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_EnvironmentModelComputations"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/Astrodynamics/Propagators
"test_EnvironmentModelComputations" start time: Jul 12 18:37 CEST
Output:
----------------------------------------------------------
Running 2 test cases...
Warning, position of Mars taken as barycenter of that body's planetary system.
Assertion failed: (startRow >= 0 && blockRows >= 0 && startRow <= xpr.rows() - blockRows && startCol >= 0 && blockCols >= 0 && startCol <= xpr.cols() - blockCols), function Block, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/Block.h, line 147.
unknown location:0: fatal error in "test_centralGravityEnvironmentUpdate": signal: SIGABRT (application abort requested)
/Users/Tim/tudatBundle/tudat/Tudat/Astrodynamics/Propagators/UnitTests/unitTestEnvironmentUpdater.cpp:253: last checkpoint

*** 1 failure detected in test suite "Master Test Suite"
<end of output>
Test time =   1.30 sec
----------------------------------------------------------
Test Failed.
"test_EnvironmentModelComputations" end time: Jul 12 18:37 CEST
"test_EnvironmentModelComputations" time elapsed: 00:00:01
----------------------------------------------------------

85/139 Testing: test_ThrustAcceleration
85/139 Test: test_ThrustAcceleration
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_ThrustAcceleration"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/Astrodynamics/Propulsion
"test_ThrustAcceleration" start time: Jul 12 18:38 CEST
Output:
----------------------------------------------------------
Assertion failed: (m_row<m_xpr.rows() && "Too many rows passed to comma initializer (operator<<)"), function operator,, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/CommaInitializer.h, line 69.
Running 8 test cases...
unknown location:0: fatal error in "testConstantThrustForce": signal: SIGABRT (application abort requested)
Assertion failed: (m_row<m_xpr.rows() && "Too many rows passed to comma initializer (operator<<)"), function operator,, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/CommaInitializer.h, line 69.
unknown location:0: fatal error in "testFromEngineThrustAcceleration": signal: SIGABRT (application abort requested)
Dependent variables being saved, output vectors contain: 
Vector entry, Vector contents

******** EDIT BY DOMINIC: REST OF TEST RUNS FINE, REMOVING OUTPUT ****************************

*** 2 failures detected in test suite "Master Test Suite"
<end of output>
Test time =  29.04 sec
----------------------------------------------------------
Test Failed.
"test_ThrustAcceleration" end time: Jul 12 18:39 CEST
"test_ThrustAcceleration" time elapsed: 00:00:29
----------------------------------------------------------

139/139 Testing: test_AccelerationModelCreation
139/139 Test: test_AccelerationModelCreation
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_AccelerationModelCreation"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/SimulationSetup
"test_AccelerationModelCreation" start time: Jul 12 18:39 CEST
Output:
----------------------------------------------------------
Assertion failed: (((m_row+m_currentBlockRows) == m_xpr.rows() || m_xpr.cols() == 0) && m_col == m_xpr.cols() && "Too few coefficients passed to comma initializer (operator<<)"), function finished, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/CommaInitializer.h, line 120.
Running 5 test cases...
unknown location:0: fatal error in "test_shGravityModelSetup": signal: SIGABRT (application abort requested)
/Users/Tim/tudatBundle/tudat/Tudat/SimulationSetup/UnitTests/unitTestAccelerationModelSetup.cpp:181: last checkpoint
Warning, overriding existing angle of attack function in AerodynamicAngleCalculator
Warning, overriding existing angle of sideslip function in AerodynamicAngleCalculator
Warning, overriding existing bank angle function in AerodynamicAngleCalculator
Warning, overriding existing angle of attack function in AerodynamicAngleCalculator
Warning, overriding existing angle of sideslip function in AerodynamicAngleCalculator
Warning, overriding existing bank angle function in AerodynamicAngleCalculator
Warning, overriding existing angle of attack function in AerodynamicAngleCalculator
Warning, overriding existing angle of sideslip function in AerodynamicAngleCalculator
Warning, overriding existing bank angle function in AerodynamicAngleCalculator
Warning, overriding existing angle of attack function in AerodynamicAngleCalculator
Warning, overriding existing angle of sideslip function in AerodynamicAngleCalculator
Warning, overriding existing bank angle function in AerodynamicAngleCalculator

*** 1 failure detected in test suite "Master Test Suite"
<end of output>
Test time =   1.51 sec
----------------------------------------------------------
Test Failed.
"test_AccelerationModelCreation" end time: Jul 12 18:39 CEST
"test_AccelerationModelCreation" time elapsed: 00:00:01
----------------------------------------------------------

**Comment by TimDeurvorst** [comment]
Hi Dominic,

I have downloaded all applications according to the manual (CMake, QT creator, git, XCode, Smartgit). As I am new to the Tudat environment, I'm not sure which one is the compiler?


The example applications for the single satellite propagator and the perturbed single satellite propagator seem to run properly.


(I had two errors during the installation of qt creator earlier which I fixed with the help of a forum. If it is not clear what the problem is, I can elaborate on the fixes I used.)


Kind regards,

Tim


T.R. Deurvorst
M +31 (0)6 51890808

________________________________
Van: DominicDirkx <notifications@github.com>
Verzonden: woensdag 12 juli 2017 22:05:30
Aan: Tudat/tudat
CC: TimDeurvorst; Author
Onderwerp: Re: [Tudat/tudat] Failed unit test(s) macOS Sierra 10.12.5 (#216)


Hi Tim,

We haven't encountered these errors before. Which compiler are you using?

It looks likely that the error originates in only one or two places. Could you verify that the applications in the example applications run properly?

In particular: could you compile and run the single satellite propagator, and the perturbed single satellite propagator?

I'm copying the relevant parts of the log file here for reference:

51/139 Testing: test_GravityFieldVariations
51/139 Test: test_GravityFieldVariations
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_GravityFieldVariations"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/Astrodynamics/Gravitation
"test_GravityFieldVariations" start time: Jul 12 18:24 CEST
Output:

Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 365.
Running 1 test case...
unknown location:0: fatal error in "testGravityFieldVariations": signal: SIGABRT (application abort requested)

*** 1 failure detected in test suite "Master Test Suite"

Test time = 0.11 sec
Test Failed.
"test_GravityFieldVariations" end time: Jul 12 18:24 CEST
"test_GravityFieldVariations" time elapsed: 00:00:00
69/139 Testing: test_AccelerationPartials
69/139 Test: test_AccelerationPartials
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_AccelerationPartials"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials
"test_AccelerationPartials" start time: Jul 12 18:24 CEST
Output:

Assertion failed: ((!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."), function resize, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/PlainObjectBase.h, line 285.
Running 3 test cases...
unknown location:0: fatal error in "testThirdBodyGravityPartials": signal: SIGABRT (application abort requested)
/Users/Tim/tudatBundle/tudat/Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials/UnitTests/unitTestAccelerationPartials.cpp:279: last checkpoint

*** 1 failure detected in test suite "Master Test Suite"

Test time = 0.06 sec
Test Failed.
"test_AccelerationPartials" end time: Jul 12 18:24 CEST
"test_AccelerationPartials" time elapsed: 00:00:00
77/139 Testing: test_EnvironmentModelComputations
77/139 Test: test_EnvironmentModelComputations
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_EnvironmentModelComputations"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/Astrodynamics/Propagators
"test_EnvironmentModelComputations" start time: Jul 12 18:37 CEST
Output:

Running 2 test cases...
Warning, position of Mars taken as barycenter of that body's planetary system.
Assertion failed: (startRow >= 0 && blockRows >= 0 && startRow <= xpr.rows() - blockRows && startCol >= 0 && blockCols >= 0 && startCol <= xpr.cols() - blockCols), function Block, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/Block.h, line 147.
unknown location:0: fatal error in "test_centralGravityEnvironmentUpdate": signal: SIGABRT (application abort requested)
/Users/Tim/tudatBundle/tudat/Tudat/Astrodynamics/Propagators/UnitTests/unitTestEnvironmentUpdater.cpp:253: last checkpoint

*** 1 failure detected in test suite "Master Test Suite"

Test time = 1.30 sec
Test Failed.
"test_EnvironmentModelComputations" end time: Jul 12 18:37 CEST
"test_EnvironmentModelComputations" time elapsed: 00:00:01
85/139 Testing: test_ThrustAcceleration
85/139 Test: test_ThrustAcceleration
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_ThrustAcceleration"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/Astrodynamics/Propulsion
"test_ThrustAcceleration" start time: Jul 12 18:38 CEST
Output:

Assertion failed: (m_row<m_xpr.rows() && "Too many rows passed to comma initializer (operator<<)"), function operator,, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/CommaInitializer.h, line 69.
Running 8 test cases...
unknown location:0: fatal error in "testConstantThrustForce": signal: SIGABRT (application abort requested)
Assertion failed: (m_row<m_xpr.rows() && "Too many rows passed to comma initializer (operator<<)"), function operator,, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/CommaInitializer.h, line 69.
unknown location:0: fatal error in "testFromEngineThrustAcceleration": signal: SIGABRT (application abort requested)
Dependent variables being saved, output vectors contain:
Vector entry, Vector contents

******** EDIT BY DOMINIC: REST OF TEST RUNS FINE, REMOVING OUTPUT ****************************

*** 2 failures detected in test suite "Master Test Suite"

Test time = 29.04 sec
Test Failed.
"test_ThrustAcceleration" end time: Jul 12 18:39 CEST
"test_ThrustAcceleration" time elapsed: 00:00:29
139/139 Testing: test_AccelerationModelCreation
139/139 Test: test_AccelerationModelCreation
Command: "/Users/Tim/tudatBundle/tudat/bin/unit_tests/test_AccelerationModelCreation"
Directory: /Users/Tim/build-tudatBundle-Desktop-Debug/tudat/Tudat/SimulationSetup
"test_AccelerationModelCreation" start time: Jul 12 18:39 CEST
Output:

Assertion failed: (((m_row+m_currentBlockRows) == m_xpr.rows() || m_xpr.cols() == 0) && m_col == m_xpr.cols() && "Too few coefficients passed to comma initializer (operator<<)"), function finished, file /Users/Tim/tudatBundle/eigen/Eigen/src/Core/CommaInitializer.h, line 120.
Running 5 test cases...
unknown location:0: fatal error in "test_shGravityModelSetup": signal: SIGABRT (application abort requested)
/Users/Tim/tudatBundle/tudat/Tudat/SimulationSetup/UnitTests/unitTestAccelerationModelSetup.cpp:181: last checkpoint
Warning, overriding existing angle of attack function in AerodynamicAngleCalculator
Warning, overriding existing angle of sideslip function in AerodynamicAngleCalculator
Warning, overriding existing bank angle function in AerodynamicAngleCalculator
Warning, overriding existing angle of attack function in AerodynamicAngleCalculator
Warning, overriding existing angle of sideslip function in AerodynamicAngleCalculator
Warning, overriding existing bank angle function in AerodynamicAngleCalculator
Warning, overriding existing angle of attack function in AerodynamicAngleCalculator
Warning, overriding existing angle of sideslip function in AerodynamicAngleCalculator
Warning, overriding existing bank angle function in AerodynamicAngleCalculator
Warning, overriding existing angle of attack function in AerodynamicAngleCalculator
Warning, overriding existing angle of sideslip function in AerodynamicAngleCalculator
Warning, overriding existing bank angle function in AerodynamicAngleCalculator

*** 1 failure detected in test suite "Master Test Suite"

Test time = 1.51 sec
Test Failed.
"test_AccelerationModelCreation" end time: Jul 12 18:39 CEST
"test_AccelerationModelCreation" time elapsed: 00:00:01

**Comment by DominicDirkx** [comment]
Hi Tim,

Ok, good to hear that the examples run properly. Go ahead with the assignments. Probably, you won' t be affected by the issues. Nevertheless, we should fix them as soon as possible.

You can find your compiler settings in Tools -> Options and by then going to the build and run window (see below)

![image](https://user-images.githubusercontent.com/5039068/28163720-a14c9af0-67cc-11e7-9d63-7f683fe05a2b.png)


Could you elaborate on the qt errors that you got, and how you fixed them?

Dominic

**Comment by TimDeurvorst** [comment]
Hi Dominic,

I'm using the GCC compiler. (see below)

[cid:9e09ad7c-ee66-485f-b5bb-74a7baec38e3]


The first error I got was in Smartgit, I got the following error at the step:

(On Mac OS X this file is hidden, you can right-click tudatBundle in the repository tree in SmartGit and select Open in Terminal).


[cid:e7452185-05e7-491d-a670-25c4a447d525]

I fixed it by editing the 'Open in Terminal' tool to the form below:

[cid:2c53d3c2-02f8-47e8-b69b-9c7e037e113a]


The second error was in qt creator. I got the following error when trying to run the application 'Hello World':


Starting /Users/Tim/tudatBundle/tudatExampleApplications/templateApplication/bin/applications/application_HelloWorld...

dyld: Library not loaded: libboost_unit_test_framework-mt.dylib

Referenced from: /Users/Tim/tudatBundle/tudatExampleApplications/templateApplication/bin/applications/application_HelloWorld

Reason: image not found

The program has unexpectedly finished.

/Users/Tim/tudatBundle/tudatExampleApplications/templateApplication/bin/applications/application_HelloWorld crashed.


I fixed it by adding the following line (fix from a forum):


[cid:c1838cc5-29c0-4ca7-8ef1-f6919a028f88]

I've just deleted the line again and it seems to work without it as well (strange..). Apparently something else was wrong but now fixed.


Regards,

Tim



T.R. Deurvorst
M +31 (0)6 51890808

________________________________
Van: DominicDirkx <notifications@github.com>
Verzonden: donderdag 13 juli 2017 13:10:57
Aan: Tudat/tudat
CC: TimDeurvorst; Author
Onderwerp: Re: [Tudat/tudat] Failed unit test(s) macOS Sierra 10.12.5 (#216)


Hi Tim,

Ok, good to hear that the examples run properly. Go ahead with the assignments. Probably, you won' t be affected by the issues. Nevertheless, we should fix them as soon as possible.

You can find your compiler settings in Tools -> Options and by then going to the build and run window (see below)

[image]<https://user-images.githubusercontent.com/5039068/28163720-a14c9af0-67cc-11e7-9d63-7f683fe05a2b.png>

Could you elaborate on the qt errors that you got, and how you fixed them?

Dominic

**Comment by DominicDirkx** [comment]
Hi Tim,

Your figures do not show correctly on my computer, could you attach them?

Dominic

**Comment by TimDeurvorst** [comment]
Hi Dominic, see attached.


T.R. Deurvorst
M +31 (0)6 51890808

________________________________
Van: DominicDirkx <notifications@github.com>
Verzonden: donderdag 13 juli 2017 14:03:50
Aan: Tudat/tudat
CC: TimDeurvorst; Author
Onderwerp: Re: [Tudat/tudat] Failed unit test(s) macOS Sierra 10.12.5 (#216)


Hi Tim,

Your figures do not show correctly on my computer, could you attach them?

Dominic

**Comment by DominicDirkx** [comment]
Hi Tim,

It seems Github doesn't like the file (format). You can send the figure by e-mail,

Dominic

**Comment by DominicDirkx** [comment]
Hi Tim,

I've merged some fixes to the problems with your unit tests into the master branch:

https://github.com/Tudat/tudat/commit/ace46371170c8174e4e4ff5ff62a19202ec19891

Update your master branch, recompile and rerun the tests (make sure to remove the ' test' compile argument when recompiling), and let me know if all tests pass now. If now, please add the error output file again,

Dominic

**Comment by TimDeurvorst** [comment]
Hi Dominic,

Thanks. As I mentioned, I am still figuring out the whole environment. How do I update my master branch?



T.R. Deurvorst
M +31 (0)6 51890808

________________________________
Van: DominicDirkx <notifications@github.com>
Verzonden: vrijdag 14 juli 2017 10:48:58
Aan: Tudat/tudat
CC: TimDeurvorst; Author
Onderwerp: Re: [Tudat/tudat] Failed unit test(s) macOS Sierra 10.12.5 (#216)


Hi Tim,

I've merged some fixes to the problems with your unit tests into the master branch:

ace4637<https://github.com/Tudat/tudat/commit/ace46371170c8174e4e4ff5ff62a19202ec19891>

Update your master branch, recompile and rerun the tests (make sure to remove the ' test' compile argument when recompiling), and let me know if all tests pass now. If now, please add the error output file again,

Dominic

**Comment by DominicDirkx** [comment]
In SmartGit, there should be a button 'pull'. Make sure that your current project is 'tudat' and pull the latest code. Here:

http://tudat.tudelft.nl/developerGuide/githubBasics.html#push-pull

we have a short explanation of some git features.

**Comment by TimDeurvorst** [comment]
Thanks. I've tried to update the master branch by pressing 'pull' and 'merge' on the 'upstream' branch within the 'tudat' project. This however doesn't seem to work. I cannot find the corrections you've made when looking directly at the .cpp files on my computer so the pull is not performed correctly. Any idea about what I'm doing wrong?


Sorry for the hassle. I'm trying to understand the system as quick as possible.




T.R. Deurvorst
M +31 (0)6 51890808

________________________________
Van: DominicDirkx <notifications@github.com>
Verzonden: vrijdag 14 juli 2017 13:27:19
Aan: Tudat/tudat
CC: TimDeurvorst; Author
Onderwerp: Re: [Tudat/tudat] Failed unit test(s) macOS Sierra 10.12.5 (#216)


In SmartGit, there should be a button 'pull'. Make sure that your current project is 'tudat' and pull the latest code. Here:

http://tudat.tudelft.nl/developerGuide/githubBasics.html#push-pull

we have a short explanation of some git features.

**Comment by DominicDirkx** [comment]
Another student contacted me by mail with the same problem. I've sent both of you an e-mail to drop by so I can help you fix this, since the wiki description is not yet up.

**Comment by DominicDirkx** [comment]
Code has been updated, compiles, and all tests pass. Closing issue.
