### ISSUE TITLE
Git repository was detected but Git is not configured

### ISSUE THREAD

**Issue by WillemRoos** [Tudat/tudat#218]
Despite being able to run all the tests without errors, the following error keeps appearing: 

Cannot run "git rev-parse --git-dir C:\Users\Willem Roos\Desktop\Studie\Tudat" in "C:\Users\Willem Roos\Desktop\Studie\Tudat": 

The reason QT Creator gives is: "Git repository was detected but Git is not configured"

I checked with the installation guide "Step 6. Configure QT Creator", but everything seemed to be as it should be. The only thing I was hesitant about was the following check: The primary generator is MinGW and secondary generator is CodeBlocks. I couldn't find the primary generator in the Build & Run tab.

The screenshot below shows the specifications of the Build & Run tab and the error can be seen in the top right corner.

Any help at all is very welcome, as you might have noticed I'm new to Github and still very inexperienced. Thanks in advance!

![image](https://user-images.githubusercontent.com/28866000/28212967-384ad822-68a4-11e7-9b2a-2d6fca32d0ef.png)

**Comment by DominicDirkx** [comment]
If all the tests compile and run fine, this is nothing to worry about. We don't really use any Git functionality directly from Qt. You can click the 'Do not show again'.
