### ISSUE TITLE
Undocumented code

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudat#219]
As suggested, I will update this list with parts of undocumented code that I come across.

### master branch
- [x]  `determineBodyCreationOrder` @ [SimulationSetup/EnvironmentSetup/createBodies.h::68](../blob/master/Tudat/SimulationSetup/EnvironmentSetup/createBodies.h#L68)
- [x]  `determineBodyCreationOrder` @ [SimulationSetup/EnvironmentSetup/createBodies.cpp::30](../blob/master/Tudat/SimulationSetup/EnvironmentSetup/createBodies.cpp#L30)

### development branch
- [x] `getMakeMultiArcEphemeris` @ [SimulationSetup/EnvironmentSetup/createEphemeris.h::102](../blob/development/Tudat/SimulationSetup/EnvironmentSetup/createEphemeris.h#L102)
- [x] `resetMakeMultiArcEphemeris` @ [SimulationSetup/EnvironmentSetup/createEphemeris.h::121](../blob/development/Tudat/SimulationSetup/EnvironmentSetup/createEphemeris.h#L121)
- [x] `makeMultiArcEphemeris_` @ [SimulationSetup/EnvironmentSetup/createEphemeris.h::137](../blob/development/Tudat/SimulationSetup/EnvironmentSetup/createEphemeris.h#L137)

**Comment by DominicDirkx** [comment]
I fixed these missing comments, and pushed the code to the development branch. Also, it turns out that the body creation order is not (yet/anymore) relevant, so I removed the order creation functionality. I've kept the function, so that the interface exists when models are implemented that do require some specific creation order.

I'll close this issue now, you can reopen it, if/when you find more undocumented code.

**Comment by agonzalezpuerta** [comment]
I just found that the SingleArcDynamicsSimulator 's constructor default options for the optional arguments do not match with the Doxygen documentation:

//! Constructor of simulator.

    /*!

     *  Constructor of simulator, constructs integrator and object for calculating each time step of integration.

     *  \param bodyMap Map of bodies (with names) of all bodies in integration.

     *  \param integratorSettings Settings for numerical integrator.

     *  \param propagatorSettings Settings for propagator.

     *  \param areEquationsOfMotionToBeIntegrated Boolean to denote whether equations of motion should be integrated

     *  immediately at the end of the contructor or not (default true).

     *  \param clearNumericalSolutions Boolean to determine whether to clear the raw numerical solution member variables

     *  after propagation and resetting ephemerides (default true).

     *  \param setIntegratedResult Boolean to determine whether to automatically use the integrated results to set

     *  ephemerides (default true).

     */

    SingleArcDynamicsSimulator(

            const simulation_setup::NamedBodyMap& bodyMap,

            const boost::shared_ptr< numerical_integrators::IntegratorSettings< TimeType > > integratorSettings,

            const boost::shared_ptr< PropagatorSettings< StateScalarType > > propagatorSettings,

            const bool areEquationsOfMotionToBeIntegrated = true,

            const bool clearNumericalSolutions = false,

            const bool setIntegratedResult = false ):

        DynamicsSimulator< StateScalarType, TimeType >(

            bodyMap, integratorSettings, propagatorSettings, clearNumericalSolutions, setIntegratedResult )

**Comment by DominicDirkx** [comment]
@agonzalezpuerta Thanks for spotting this, the code has been updated.
