### ISSUE TITLE
Function 'WriteMatrixToFile' does not accept a file output path as input argument

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#220]
Hi Dominic,

In the EarthOrbiterStateEstimation application the output is saved through the function ‘WriteMatrixToFile’ which belongs to the input_output library of the Tudat. However, the path of the output file cannot be specified among the function arguments and, moreover, it is not clear where the output files are actually saved. 

Could this problem be fixed by adding the possibility to choose the files output path when using the function?

Thank you,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

I've updated the function as requested:

https://github.com/DominicDirkx/tudat/tree/SelectFilePathWhenWritingMatrixToFile

and have taken the liberty of merging it into the development branch

https://github.com/Tudat/tudat/tree/development

In addition, I've updated the example applications with this code, have a look here:

https://github.com/Tudat/tudatExampleApplications/blob/development/satellitePropagatorExamples/SatellitePropagatorExamples/earthOrbiterStateEstimation.cpp

I'm closing this issue, as the code has been added, but don't hesitate to ask if something isn't clear.
