### ISSUE TITLE
PodInputDataType explanation

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#221]
Hi Dominic,

In the orbit determination files the observation input data for the precise orbit determination simulations is defined as an object of type ‘PodInputDataType’. This type of object, which is the return type of the function ‘simulateObservations’, is a map containing another map with a couple of std::pair objects as well. Since it is quite a complex structure built on several levels and there are not many comments in the header file, could you please add some more explanation in the code? For instance, in which way are the observations data stored in that object? They do not always have the same size.

Thank you and best regards, 
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni, 

The first two map entries are relatively straightforward: ObservableType and LinkEnds denote the type of observable and set of link ends for which a particular set of observations/times are provided. Where it gets a bit tricky is in the inner entry of the map, which is of the following type (in case you are using double as TimeType and StateScalarType_:

std::pair< Eigen::VectorXd, std::pair< std::vector< double >, observation_models::LinkEndType > >

The Eigen::VectorXd contains the observations, the  std::vector< double > contains the times of the observations and the LinkEndType the type of link end at which the given time is valid. For instance: when specifying a range observation of 1E6 m at t=1000 s with link end type transmitter, this represents the range observation, as obtained for a laser ranging measurement for which the pulse was transmitted at t=1000 s.

For observables that have size 1, the link between the Eigen::VectorXd of observations and std::vector< double > of times is straightforward: entry j of one corresponds to entry j of the other. However, if the size of the observable is N (for instance for the position observation, in which case N=3), the position observables are concatenated into the observation Eigen::VectorXd. So, for observation j, the associated time is simply at entry j of the time std::vector. The associated entries of the observable (x,y and z component) are at entry j*3, j*3+1 and j*3 + 2, respectively.

**Comment by ggranato92** [comment]
Thank you very much for the explanation and the example. It is now clear how to use the PodInputDataType

Kind regards,
Giovanni

**Comment by DominicDirkx** [comment]
Great!
