### ISSUE TITLE
Error using function readMatrixFromFile

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#222]
Hi Dominic,

I am having problems reading a file with the function ‘readMatrixFromFile’. The error is the following:

 terminate called after throwing an instance of 'std::runtime_error'
what(): Data file could not be opened: C:/home/giovanni/Downloads/MikhailFile.txt
The program has unexpectedly finished.

Could you please help me?

Thanks,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Does the file 'C:/home/giovanni/Downloads/MikhailFile.txt' exist? If you're working on Linux, I'm assuming that it won't, since 'C:/' doesn't exist. What is the full path of the file you are trying to open?

**Comment by ggranato92** [comment]
Thank you for your immediate reply. I have written the path without C:/, putting just "/home/giovanni/etc..." but it then gives another error:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> >'
  what():  bad lexical cast: source type value could not be interpreted as target
The program has unexpectedly finished.

I found the path through the terminal by the command readlink -f

**Comment by DominicDirkx** [comment]
Hi Giovanni,

This seems like there is an issue when reading the file, the lexical cast is used ti convert the string that is read to numerical data. If the string is not a number, this error occurs. Could you

a) Post the command you use to read the file
b) Send the exact file you're reading to me by e-mail (I'm not sure if Mikhail wants it posted publicly)

**Comment by ggranato92** [comment]
I have just sent you the email. These are the few code lines that I have written:
Eigen::MatrixXd MikhailDataRA = readMatrixFromFile( "/home/giovanni/Downloads/MikhailFile.txt", " ", "%" );


    std::cout<< MikhailDataRA.rows()<<std::endl;
    std::cout<< MikhailDataRA.cols()<<std::endl;

**Comment by DominicDirkx** [comment]
Solved. It was indeed a matter of incompatible file contents
