### ISSUE TITLE
Time conversions help

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#223]
Hi Dominic,

After carefully checking the time conversions files of the tudat I have some doubts. In many functions which accept the calendar date as input you say in the description that year, month, day, hour, minutes and seconds are the ones used in everyday life. Do you mean that they are they expressed in TT?

I have not found any function to directly convert UTC to TT, which is the time adopted for  (almost)all the tudat applications. How can I deal with times expressed in UTC then? Also in the unit test sofa this conversion is not performed.
In the Tudat there is a function which converts  TT to TAI and viceversa. I thought of using this one considering that TAI and UTC differ from a certain amount of leap seconds that I could find out, is it correct?

Thanks,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

There is a convertTTtoUTC and convertUTCtoTT in the sofaTimeConversions.h function

**Comment by ggranato92** [comment]
Thank you very much. I was looking for those files in the basic astrodynamics folder and didnt actually check the External folder. What I was actually seeing were the timeconversions files and not  the sofa ones, sorry.
