### ISSUE TITLE
Variable M_PI not declared in unitTestObservationViabilityCalculator

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#225]
Hi Dominic,

In the cpp file unitTestObservationViabilityCalculator the variable M_PI is not declared. Therefore the build process stops being this an issue. The variable should be declared as mathematical_constants::PI to make it work.

Giovanni

**Comment by DominicDirkx** [comment]
Thanks for posting this, I've made the necessary corrections here:

https://github.com/Tudat/tudat/commit/edf048d65e888a2317aa2b5a3c45bf793f27cc41
