### ISSUE TITLE
Print interval of propagator not working when set equal to integrator's step-size

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudat#228]
Nothing is printed when the print interval of the propagator is set to be equal to the integrator's (fixed) step-size. If it's set to be at least 1 s longer than the step-size, then it does work as expected.

**Comment by DominicDirkx** [comment]
Thanks for picking this up. In Astrodynamics/Propagators/integrateEquations.h, there is the line:

if( ( static_cast<int>( std::fabs( static_cast< double >( currentTime - initialTime ) ) ) %
                      static_cast< int >( printInterval ) ) <
                        ( static_cast< int >( std::fabs( static_cast< double >( previousTime - initialTime ) ) ) %
                          static_cast<int>( printInterval ) )  )

If you change the < to <=, does it print correctly? 

Cheers,

Dominic

**Comment by aleixpinardell** [comment]
Yes, changing that solves the problem

**Comment by DominicDirkx** [comment]
Thanks, corrected in commit 27f9881da7cf96367bee05cf6f1d680f3b9f0850
