### ISSUE TITLE
Implementation of NRLMSISE

### ISSUE THREAD

**Issue by Reneh107** [Tudat/tudat#23]
I notice that with the current implementation of NRLMSISE, the libraries need to be linked in a certain order. Otherwise an error occurs: undefined reference to gtd7

tudat_aerodynamics -> nrlmsise00

Maybe it is an idea to merge nrlmsise00 and tudat_aerodynamic libraries if NRLMSISE is used. 

@magnific0 pointed out that ranlib can be used to merge static libraries.

**Comment by DominicDirkx** [comment]
This has now been incorporated into the code, with many thanks to Reneh107
