### ISSUE TITLE
Wrong operator for member function calls of interpolator examples in the documentation

### ISSUE THREAD

**Issue by magnific0** [Tudat/tudat#230]
The examples in the docs cast the interpolator in a boost::shared_ptr, and call it by ```interpolator.interpolate(0.0)``` which should read ```interpolator->interpolate(0.0)``` in this context.

See:
http://tudat.tudelft.nl/tutorials/tudatFeatures/mathTools/interpolators.html#interpolators 

It is unnecessary to use shared pointers here, so I propose changing changing type of ```interpolator``` rather than the call. I can change this, but I'd like to hear your input on the matter first!

**Comment by DominicDirkx** [comment]
Thanks for spotting this! The issue is that createOneDimensionalInterpolator returns a pointer to an interpolator, so it's kind of necessary to keep the pointer interface.

**Comment by DominicDirkx** [comment]
@FrankHogervorst could you add fixing this issue to your to do list?

**Comment by FrankHogervorst** [comment]
Yes, its on the list.

**Comment by FrankHogervorst** [comment]
This is fixed with pull request https://github.com/Tudat/tudat/pull/260
