### ISSUE TITLE
Failed unit tests: test_SpiceInterface and test_PropagationTerminationReason

### ISSUE THREAD

**Issue by JimF007** [Tudat/tudat#231]
[LastTest.txt](https://github.com/Tudat/tudat/files/1247828/LastTest.txt)

**Comment by magnific0** [comment]
Hi @JimF007 Thanks for reporting the failed unit tests. Can you run these two individually and report their full output. Perhaps we can further pin it down to certain test cases.

**Comment by JimF007** [comment]
Hi,
When I compile test_SpiceInterface
11:27:00: Running steps for project TudatBundle...
11:27:00: Starting: "C:\Program Files (x86)\CMake\bin\cmake.exe" --build . --target test_SpiceInterface
Built target tudat_spice_interface
Built target tudat_ephemerides
Built target tudat_basic_astrodynamics
Built target tudat_basic_mathematics
Scanning dependencies of target test_SpiceInterface
Linking CXX executable C:\TUDAT\tudat\bin\unit_tests\test_SpiceInterface.exe
Built target test_SpiceInterface
11:27:05: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited normally.
11:27:05: Elapsed time: 00:05.

When I compile test_PropagationTerminationReason
11:27:54: Running steps for project TudatBundle...
11:27:54: Starting: "C:\Program Files (x86)\CMake\bin\cmake.exe" --build . --target test_PropagationTerminationReason
[  1%] Built target tudat_simulation_setup
[ 91%] Built target cspice
[ 91%] Built target nrlmsise00
[ 91%] Built target tudat_gravitation
[ 92%] Built target tudat_electro_magnetism
[ 92%] Built target tudat_ephemerides
[ 92%] Built target tudat_relativity
[ 93%] Built target tudat_system_models
[ 93%] Built target tudat_propulsion
[ 93%] Built target tudat_propagators
[ 93%] Built target tudat_basic_astrodynamics
[ 94%] Built target tudat_aerodynamics
[ 95%] Built target tudat_reference_frames
[ 96%] Built target tudat_mission_segments
[ 96%] Built target tudat_basics
[ 97%] Built target tudat_input_output
[ 97%] Built target tudat_basic_mathematics
[ 98%] Built target tudat_geometric_shapes
[ 98%] Built target tudat_numerical_integrators
[ 98%] Built target tudat_spice_interface
[100%] Built target test_PropagationTerminationReason
11:28:07: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited normally.
11:28:07: Elapsed time: 00:14.

There seems to be no error shown. I am not sure what happened.

**Comment by DominicDirkx** [comment]
HI @JimF007, this seems to be only the compilation output. Could you run the program as well and see what it prodiuces? Thanks!

**Comment by DominicDirkx** [comment]
For completeness, these have also been reported in #226

**Comment by DominicDirkx** [comment]
Closing this, as it is redundant to #226
