### ISSUE TITLE
Leap seconds in SPICE and SOFA

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#233]
Hi Dominic,

could you please check if the leap seconds in SPICE and SOFA are up to date?

Thank you very much,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Thanks for reminding me, I've checked and the Sofa code is up to date. The spice code was not, and I have updated the repository. Note the I've removed the naif0009.tls file, so any references to it in your code should be replaced by naif0012.tls,

Cheers,

DOminic
