### ISSUE TITLE
Add GroundStationSettings, and map of GroundStationSettings to BodySettings

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudat#234]
Add `GroundStationSettings` so that settings for creating ground stations can be provided to a `std::map< std::string, boost::shared_ptr< GroundStationSettings > >`, which would be used during creation of the `Body` object by calling the `createGroundStation` function for each `GroundStationSettings` in the map.

**Comment by DominicDirkx** [comment]
I've added the feature here:

https://github.com/DominicDirkx/tudat/tree/GroundStationSettings

Code is not yet commented, but should be self-explanatory (will add comments before committing to master). I decided to use a std::vector< boost::shared_ptr< GroundStationSettings > > and add the station name as a member of  GroundStationSettings.
