### ISSUE TITLE
missing separator error in makefile, gh-pages branch, while building documentation

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#238]
I've created a makefile (as described in [how to write the wiki step 5](http://tudat.tudelft.nl/developerGuide/howToWriteTheWiki.html))  and set the SOURCEDIR and BUILDDIR parameters. 

When I execute:  make html it gives the following error:
`makefile:13  *** missing separator.  Stop.`
which is this line:
`@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)`
I have not created a make.bat file since @DominicDirkx told me it was only neccesary for windows users. 

Any idea what is meant by this missing separator?

**Comment by DominicDirkx** [comment]
[Makefile.txt](https://github.com/Tudat/tudat/files/1292100/Makefile.txt)
I vaguely recall having had to mess with the Makefile. Attached is the one I am using (remove the .txt extension first, github doesn't let me attach without it....). Does it work for you?

**Comment by FrankHogervorst** [comment]
That works, it looks like a: tab != three spaces problem.

**Comment by DominicDirkx** [comment]
Ok, good. Make sure to update the wiki to prevent others from encountering this.
