### ISSUE TITLE
AerodynamicCoefficientSettings default values and documentation

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudat#244]
The aerodynamic frame is wrongly documented as `(lift, drag, side force)` in several places.

Additionally, for `ConstantAerodynamicCoefficientSettings`, `areCoefficientsInAerodynamicFrame` is `false` by default in several places, while it is `true` by default when the `AerodynamicCoefficientInterface` is created manually without using the settings object.

**Comment by DominicDirkx** [comment]
Thanks for spotting this, code has been corrected in 3666bac72a5aa4ddaa12ac9dee09016bbc9dd5e6
