### ISSUE TITLE
New Functionality needed: arcwise solar radiation pressure coefficient estimation

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#252]
Hi Dominic,

Concerning the Tudat orbit determination tools, in particular the multi-arc estimation tool, the solar radiation pressure coefficient cannot be estimated for each arc. Would it be possible to implement this new functionality?

Thank you very much,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

I've written the code and pushed in to:

https://github.com/DominicDirkx/tudat/tree/ArcWiseRadiationPressure

There is no unit test/comments yet, but I've sort of tested it by including the estimation of arc-wise radiation pressure in the basic earth orbiter estimation parameters as:

    parameterNames.push_back( boost::make_shared< ArcWiseRadiationPressureCoefficientEstimatableParameterSettings >(
                                  "Vehicle", boost::assign::list_of( initialEphemerisTime )( initialEphemerisTime + 1.5 * physical_constants::JULIAN_DAY ) ) );

which estimated a separate coefficient from t_{0} to t_{0} + 1.5 days, and one from t_{0} + 1.5 days until the end of simulation.

**Comment by ggranato92** [comment]
Hi Dominic,

Thank you very much. In order to pull the code, may I use the command "git merge" to merge my local repository with your personal one? Or another command? 

Thanks

**Comment by DominicDirkx** [comment]
The process would be the same as in previous issues. As I recall, we discussed this already on several occasion, and there is a short explanation in some other issue.

**Comment by DominicDirkx** [comment]
Unit test added and pushed to development branch.
