### ISSUE TITLE
Guide to debugging: example errors and corresponding backtrace

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#253]
It would be nice to include an example of the use of a debugger to find runtime errors. Preferably an error which occurs later in the propagation such that an extensive backtrace is generated. As discussed in the documentation meeting @DominicDirkx.

**Comment by DominicDirkx** [comment]
[DebuggingOutput.txt](https://github.com/Tudat/tudat/files/1359229/DebuggingOutput.txt)
Hi Frank,

I've given an example of a backtrace, see attached figure (Qt screenshot) and text file (gdb output from terminal) for an error occuring in the FlightConditions update.
![screenshot from 2017-10-05 14-10-21](https://user-images.githubusercontent.com/5039068/31226586-f33e9aa6-a9d6-11e7-97fc-0fbae1073afc.png)
