### ISSUE TITLE
Update Documentation of Errors: file COPY cannot find boost_.../stage". CMakeLists.txt:58 (include)

### ISSUE THREAD

**Issue by wildvank** [Tudat/tudat#259]
Hi, 

I tried to build the bundle but I get an error related to boost, does someone maybe know how to fix the issue?
OS : win10
Compiler: MinGW 4.9.2
CMake version: 3.7.2

[output_file.txt](https://github.com/Tudat/tudat/files/1367634/output_file.txt)

**Comment by DominicDirkx** [comment]
Hi,

On this page: 

http://tudat.tudelft.nl/installation/troubleshooting.html?highlight=cmake%20output%20log#troubleshooting-configuration

Could you attach the information mentioned in step 2.2? We will need this to diagnose your issue. It looks like boost did not compile correctly, and it therefore cannot move the libraries to the correct path.

After sending us these file, try changing your boost version to 1.60. In the top-level CMakeLists, comment:

set(BoostVersion 1.53.0)
set(BoostSHA1 e6dd1b62ceed0a51add3dda6f3fc3ce0f636a7f3)

and uncomment:

# set(BoostVersion 1.60.0)
# set(BoostSHA1 7f56ab507d3258610391b47fef6b11635861175a)

Note that CMakle uses the # symbol for comments.

Dominic

**Comment by wildvank** [comment]
There is no "project-config.jam" file in the folder. I changed the extenstion of the "cmake-config.jam" file to .txt since github doesn't support uploading .jam files. I hope this is ok.

[build_bootstrap.log](https://github.com/Tudat/tudat/files/1367784/build_bootstrap.log)
[build_b2.log](https://github.com/Tudat/tudat/files/1367785/build_b2.log)
[cmake-config.txt](https://github.com/Tudat/tudat/files/1367788/cmake-config.txt)

Changing boost version to 1.60 gives the same error unfortunately.

**Comment by DominicDirkx** [comment]
This is a very curious error. It may be related to this:

https://stackoverflow.com/questions/17879350/cannot-build-boost-with-mingw

which refers here:

http://www.blinnov.com/en/2010/06/04/microsoft-was-unexpected-at-this-time/

Could you check if the variables in your path are formatted properly, e.g. whether there are any in double quotes (as is discussed as a fix at the end of the second link)?

I'm afraid I won't be able to get back to this until the end of today.

@magnific0 Any other ideas?

**Comment by wildvank** [comment]
Thanks for the responds, after some fiddling around It seems to be working now. I couldn't find anything in double quotes but the TEMP and TMP location in the build environment was set to something like C:\USERNAME~1\Appdata\Local\longdir\.. which I changed to a shorter dir without a tilde. I'm waiting for it to build at the moment.

**Comment by DominicDirkx** [comment]
Great to hear.This can go on our list of funny errors...

Thanks for the quick reply, and being pro-active in your fix!

**Comment by DominicDirkx** [comment]
@wildvank

**Comment by wildvank** [comment]
In that case i'll provide some extra info. When I use boost version 1.60 I keep getting warnings similar to this:

https://stackoverflow.com/questions/34480467/how-to-compile-boost-with-an-older-std-of-c-c03-in-particular

which is fixed by using boost version 1.57 but gives warnings similar to an earlier mentioned issue:

https://github.com/Tudat/tudat/issues/80

Both times it builds and passes all tests.

**Comment by DominicDirkx** [comment]
@wildvank This is a known issue, and I'm afraid that it's an inherent result of combining certain versions of Boost and gcc/mingw. 

Great to hear that all tests pass in both cases. I assume you are working on the Tudat master branch?

**Comment by DominicDirkx** [comment]
@FrankHogervorst could you find a good place to put this on the wiki? No need to put a long explanation, it's enough to say that the error when running CMake is:

file COPY cannot find 

after attempting to compile boost,  and that both the files:

build_bootstrap.log
build_b2.log

contain little data.

**Comment by FrankHogervorst** [comment]
Two options:
- A seperate page in installation guide, for funny installation errors. 
- A page/paragraph in the new GuideToDebugging section. 

In both cases it should also be linked with corresponding Github issue for extra details.

**Comment by DominicDirkx** [comment]
My preference would go to the second option, where we can link from the installation guide. Probably it should be split by the point where the error occurs, such as:

* Opening CMake (errors sometimes occur on compilers not being found)
* Downloading/compiling boost (various errors can occur, a typical culprit is the boost/compiler consistency)
* Compilation/linking of the code
* Failed unit tests

In the install guide, we could in the corresponding places i link to the relevant 'issues' page

**Comment by FrankHogervorst** [comment]
Yes that would make most sense. I'll add it to my TODO list. 

Is there a list of these common errors? Or should I go through the issues page in order to find them?

**Comment by DominicDirkx** [comment]
I don't think there is a comprehensive list anywhere. Put it on your todo list, but a but at the bottom. There's a variety of common issues that have occured recently (say last 12 months), which are still relatively fresh in my memory. I'll make a preliminary list in the coming week(s).

**Comment by FrankHogervorst** [comment]
Added this error to the error list in pull request https://github.com/Tudat/tudat/pull/264. Closing this issue now, updating the error list is on my TODO list. Could you send the preliminary list in the coming week(s)?
