### ISSUE TITLE
Propagation error with SingleArcDynamicsSimulator::resetPropagationTerminationConditions()

### ISSUE THREAD

**Issue by lupif** [Tudat/tudat#265]
I know this error to appear only when working with a MultitypePropagatorSettings, no issue with
only a TranslationalStatePropagatorSettings.

Before propagating a SingleArcDynamicsSimulator object I need to update the propagationTerminationSettings_ (of type PropagationTimeTerminationSettings) in the propagatorSettings_. Afterwards I proceed to call the function

SingleArcDynamicsSimulator::resetPropagationTerminationConditions( )

and propagate the dynamicsSimulator, as

dynamicsSimulator->integrateEquationsOfMotion(
        dynamicsSimulator->getPropagatorSettings()->getInitialStates() );

The propagation ends after one step instead of propagating until the final simulation epoch.

This issue is only determined by SingleArcDynamicsSimulator::resetPropagationTerminationConditions( ). Even when no other variable has been modified or other functions called.

The propagation works completely fine otherwise.

**Comment by lupif** [comment]
In file: Tudat/SimulationSetup/PropagationSetup/dynamicsSimulator.h
lines 317-319:

     propagationTerminationCondition_ = createPropagationTerminationConditions(
                    propagatorSettings_->getTerminationSettings(), bodyMap_,
                            integratorSettings_->initialTime_ );

integratorSettings_->initialTime_ should be replaced with integratorSettings_->initialTimeStep_

**Comment by DominicDirkx** [comment]
Done in development-json branch
