### ISSUE TITLE
Failure of test_TidalPropertyEstimation

### ISSUE THREAD

**Issue by magnific0** [Tudat/tudat#270]
I have attached the output for this test below. It seems that some of the estimation errors after  the maximum number of iterations was reached is slightly above the the tolerance for this test.

[test_TidalPropertyEstimation.txt](https://github.com/Tudat/tudat/files/1437928/test_TidalPropertyEstimation.txt)

This was obtained using the DominicDirkx/aleixpinardell-json of Tudat.

**Comment by DominicDirkx** [comment]
Thanks, indeed just a small tolerance issue, I'll make sure to update it. On which operating system/compiler was this error obtained?

**Comment by magnific0** [comment]
uname -a
    > Linux spindle 4.13.10-1-ARCH #1 SMP PREEMPT Fri Oct 27 16:16:03 CEST 2017 x86_64 GNU/Linux
    gcc -v
    > gcc version 7.2.0 (GCC)

and boost 1.65.1. Perhaps an extra iteration would push it below the the tolerance?

**Comment by DominicDirkx** [comment]
Maybe, but it seems to be close to the noise limit. Could you try increasing the number of iterations?

**Comment by magnific0** [comment]
You were right, it didn't improve the estimation.

**Comment by DominicDirkx** [comment]
Ok, I'll update it. Note that I'll push all changes from now on to the development-json branch, which is the latest version of the code.

**Comment by DominicDirkx** [comment]
@magnific0  Since you're working on the branch that is to be merged, could you update the tolerance? It will save an extra merge. I checked, and putting this tolerance at 5E-6 instead of 1E-6 is fine. The test concerns the estimation, which has a significant degree of randomness in it (at the level of fine details).

**Comment by magnific0** [comment]
Done, the test now passes. Closing this issue.
