### ISSUE TITLE
libbacktrace could not find executable to open

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#272]
Error during build of tudat development branch on Windows:

[buildoutput.txt](https://github.com/Tudat/tudat/files/1441019/buildoutput.txt)

Where can I find the error output log again? Forgot where it is located.

**Comment by DominicDirkx** [comment]
This error is due to multi-core compilation on Windows. Restarting compilation when it occurs fixes the problem (recursively). @FrankHogervorst could you add this to the error documentation?

**Comment by FrankHogervorst** [comment]
Updated documentation
