### ISSUE TITLE
Negative timestep for variable timestep integrator?

### ISSUE THREAD

**Issue by AMPronk** [Tudat/tudat#277]
Hi, 

Is it possible to run a variable timestep integrator with a negative timestep? I'm currently trying to run the following code but this results in only one step being integrated and then the dynamics simulator stops without errors.

            const numerical_integrators::RungeKuttaCoefficients::CoefficientSets coefficientSet =
                    numerical_integrators::RungeKuttaCoefficients::CoefficientSets::rungeKuttaFehlberg78;
            double minimumStepSize = 1.0E-5;
            double maximumStepSize = 1.0E2;
            double relativeErrorTolerance = 1.0E-20;
            double absoluteErrorTolerance = 1.0E-12;

            const long double PropagationStart = 100 * tudat::physical_constants::SIDEREAL_DAY;
            const long double PropagationEnds = 0.0; 
            long double StepSize = 0.5;

            boost::shared_ptr< IntegratorSettings< > > integratorSettings;
            integratorSettings = boost::make_shared< RungeKuttaVariableStepSizeSettings< > >
                    (rungeKuttaVariableStepSize, PropagationStart, StepSize, coefficientSet,
                     minimumStepSize, maximumStepSize, relativeErrorTolerance, absoluteErrorTolerance );

            boost::shared_ptr< TranslationalStatePropagatorSettings< > > propagatorSettings =
                    boost::make_shared< TranslationalStatePropagatorSettings< > >
                    (centralBodies, ModelMapSE, bodiesToPropagate, systemInitialState, PropagationEnds, cowell );

            SingleArcDynamicsSimulator< > dynamicsSimulator(
                        bodyMap, integratorSettings, propagatorSettings, true, true, false );

            std::map< double, Eigen::VectorXd > tempIntegrationResult = dynamicsSimulator.getEquationsOfMotionNumericalSolution( );

**Comment by DominicDirkx** [comment]
Hi,

Backwards propagation is definitely possible by setting the time step to a negative value. Have you tried setting this? Let me know whether it works,

Best,

Dominic

p.s. To use long double state scalars, the template arguments of the DynamicsSimulator and PropagatorSettings classes also need to be modified

**Comment by AMPronk** [comment]
Hi,

Thanks! Unfortunately I guess I'm still doing something wrong. With the code below, the dynamics simulator seems to keep running forever... I checked it with bigger minimum stepsizes as well, which either results in the exceeding of the minimal step size, or in another endless run. If the minimal step size is exceeded, the returned propagation data start at 0.1 year, and go forward from that... 

Thanks!

	const double PropagationStart = 0.1 * tudat::physical_constants::SIDEREAL_YEAR;
    const double PropagationEnds = 0.0;
	
	const numerical_integrators::RungeKuttaCoefficients::CoefficientSets coefficientSetS1 =
                numerical_integrators::RungeKuttaCoefficients::CoefficientSets::rungeKuttaFehlberg78;
    double StepSizeS1 = -1.0;
    double minimumStepSizeS1 = -1.0E-5;
    double maximumStepSizeS1 = -50.0;
    double relativeErrorToleranceS1 = 1.0E-20;
    double absoluteErrorToleranceS1 = 1.0E-12;

    boost::shared_ptr< IntegratorSettings< > > integratorSettingsS1;
    integratorSettingsS1 = boost::make_shared< RungeKuttaVariableStepSizeSettings< > >
                (rungeKuttaVariableStepSize, PropagationStart, StepSizeS1, coefficientSetS1,
                 minimumStepSizeS1, maximumStepSizeS1, relativeErrorToleranceS1, absoluteErrorToleranceS1 );

    boost::shared_ptr< TranslationalStatePropagatorSettings< > > propagatorSettingsS1 =
                boost::make_shared< TranslationalStatePropagatorSettings< > >
                (centralBodies, ModelMapSE, bodiesToPropagate, systemInitialState, PropagationEnds, cowell);
				
	SingleArcDynamicsSimulator< > dynamicsSimulatorS1(
                    bodyMap, integratorSettingsS1, propagatorSettingsS1, true, true, false );
    std::map< double, Eigen::VectorXd > tempIntegrationResultS1 = dynamicsSimulatorS1.getEquationsOfMotionNumericalSolution( );

**Comment by DominicDirkx** [comment]
Odd. What happens if you dpo the same with a fixed step integrator, such as RK4?

**Comment by DominicDirkx** [comment]
I can have a better look if you push or post your full code.

**Comment by DominicDirkx** [comment]
I played with some settings, and it seems that the variable step-size integrator does not do backwards propagation yet.. The fixed-step integrator (RK4) works fine with backwards propagation, if you put in an initial negative time step. The fix for this should be relatively simple, I'll have a look at it asap.

**Comment by DominicDirkx** [comment]
I had a look, and have pushed a preliminary fix here:

https://github.com/DominicDirkx/tudat/tree/BackwardsPropagationVariableStepSize

This branch is based on the recent giant pull request that includes everything that was in the json and development branches before, so you may not want to pull the whole thing. The relevant changes are shown here:

https://github.com/DominicDirkx/tudat/commit/a86426980ecfc972b7c2ce63225188fe581656c5

I tested it by modifying the perturbed satellite propagator to go back in time with variable step size. It seems to work, but I do not yet have a test written. Could you let me know if these changes solve the problem for you?

**Comment by AMPronk** [comment]
Running with RK4 does give me results in the correct timeframe.

My full code is here: https://github.com/AMPronk/Thesis, you should have an invitation. The propagator is in "WP1.cpp", lines 270-290.

**Comment by AMPronk** [comment]
Yes, this solves it for me! Thanks a lot! :D

**Comment by DominicDirkx** [comment]
Good! I'll leave this issue open until we write a proper unit test for this.

**Comment by DominicDirkx** [comment]
Unit test written; code pushed:

https://github.com/Tudat/tudat/commit/06543fdfc201bf8848e94d4e7acc5a8a85ac13ab
