### ISSUE TITLE
Failed unit test Mac OS 10.10.5 - test_RungeKuttaFehlberg56Integrator

### ISSUE THREAD

**Issue by emooij** [Tudat/tudat#282]
[LastTest.log](https://github.com/Tudat/tudat/files/1453601/LastTest.log)

**Comment by DominicDirkx** [comment]
This has been a problem for some time, and was discussed previously here:

https://github.com/Tudat/tudat/issues/84

The proposed fix was never fully implemented, as it should be part of a larger discussion on how to define the stopping conditions for the integrateTo function. Presently, however, the integrateTo function is not commonly used, instead the performIntegrationStep function is used, which this issue does not affect.

For both functions, however, exact stopping conditions are an issue, and should be resolved. I am closing this issue, and opening a new one for an 'upcoming feature'.

For now, the lines causing this failure have been commented out. Pulling the latest version of tudat from the master branch on Github will (should) correct the problem.
