### ISSUE TITLE
Exact termination conditions

### ISSUE THREAD

**Issue by DominicDirkx** [Tudat/tudat#283]
At present, the termination conditions for numerical propagation are checked every time step, and if the propagation has gone over the final condition (be it a time, altitude, etc.), the propagation stops, and saves the output. 

There is, however, no mechanism to ensure that the propagation finishes _exactly_ at a given condition. For a given final time, this would be relatively easy to implement (define time step for final time 'manually'). For termination on a dependent variation value (or hybrid settings), a more elaborate solution is required, e.g. using a root finder. 

Similarly, the termination conditions used for the integrateTo function are not entirely consistent, as discussed here:

 https://github.com/Tudat/tudat/issues/84

Which has been known to cause a unit test failure (RKF56 integrator test) on Mac. The lines causing the error have been commented out:

https://github.com/Tudat/tudat/commit/34214635a053d24376d33956a2a69a8dfb15005f

But should be corrected once the fix has been implemented.

**Comment by FrankHogervorst** [comment]
It would be convenient, in case of hybrid termination conditions, to have the possibility to request which termination condition was reached. Now it is only possible to request whether it met any of the conditions.

**Comment by DominicDirkx** [comment]
I've made the first iteration, including unit tests, but so far without full documentation, of the exact termination conditions. Code has been pushed here:

https://github.com/DominicDirkx/tudat/tree/AccurateTermination

For the next iteration, I'll include the output on details of how the propagation was terminated.

**Comment by DominicDirkx** [comment]
I added another commit to allow more details on termination, in particular active conditions for the hybrid approach:

https://github.com/DominicDirkx/tudat/commit/4380b74195e761725c6b0800c54249a45faa78ac

No tests/documentation yet.

**Comment by DominicDirkx** [comment]
I pushed some updates to the branch, latest version is:

https://github.com/DominicDirkx/tudat/commit/8542126575aef4e4c2a57db579f1d7010bb969e3

Only thing missing is a test of the more elaborate information for hybrid termination.

**Comment by FrankHogervorst** [comment]
I tried this new option. However, I get errors when building my application, the MultiTypePropagatorSettings does not seem to work anymore.  (I haven't including any exact termination conditions at this point), Ive just rebuild one of my applications.

[copilelog.txt](https://github.com/Tudat/tudat/files/1531571/copilelog.txt)

**Comment by FrankHogervorst** [comment]
I removed the mass propagation from my simulator such that the MultiTypePropagatorSettings are not required. However, this gives undefined references to doesRootFinderRequireDerivatives, and GroundStationState. 
[compilelog.txt](https://github.com/Tudat/tudat/files/1534704/compilelog.txt)

**Comment by FrankHogervorst** [comment]
Never mind, I forgot to include the `tudat_ground_stations` and `tudat_root_finders` libraries to the `target_link_libraries`.

**Comment by DominicDirkx** [comment]
This has been merged into the master.
