### ISSUE TITLE
Failed Unit Test: test_JsonInterfaceDeserialization

### ISSUE THREAD

**Issue by thijsmeneer** [Tudat/tudat#285]
Hi, I just did all the 214 unit tests, but unfortunately one of them failed.

This test failed: 
190 - test_JsonInterfaceDeserialization

I am using windows 10
[LastTest.log](https://github.com/Tudat/tudat/files/1464450/LastTest.log)

**Comment by DominicDirkx** [comment]
Hi, I'm think that this is nothing to worry about. The feature that seems to be causing the error is not used in any of the assignments. Nevertheless, we will investigate it in the coming week to make sure that it is not a problem. We may ask you to rerun this unit test with some modifications, to see if we have correctly fixed the problem,

Best,

Dominic

**Comment by thijsmeneer** [comment]
Ok.

Thanks for your fast reply!

**Comment by DominicDirkx** [comment]
This was actually reported here: #275 already. I'll close this issue. The solution of the problem will be tracked through the original issue.
