### ISSUE TITLE
Failed unit tests - Windows 10

### ISSUE THREAD

**Issue by oramireztorralba** [Tudat/tudat#286]
[LastTest.log](https://github.com/Tudat/tudat/files/1464998/LastTest.log)

The following tests FAILED:
	190 - test_JsonInterfaceDeserialization (Failed)
Errors while running CTest
Makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
19:45:46: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
19:45:46: Elapsed time: 09:49.

**Comment by DominicDirkx** [comment]
Thanks for posting this. The same problem was reported in in #285. When we correct this, well post the solution there.
