### ISSUE TITLE
Failed unit test (QT)

### ISSUE THREAD

**Issue by sangjae-park** [Tudat/tudat#287]
In this issue, attach the file LastTest.log, which should be in the /Testing/Temporary/ directory in your build folder. I cannot seem to find it so i attached a picture. I am using windows!

Errors while running CTest
Makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
21:14:31: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"

This is the error

![help](https://user-images.githubusercontent.com/33625664/32747596-913c7baa-c8b9-11e7-9e7d-f2c5ba25a0dd.png)

**Comment by DominicDirkx** [comment]
Dear Sangjae,

In the same directory as your tudanBundle folder, there should be a folder that has 'build' somewhere in its name. This folder contains the /Testing/Temporary/ folder, where you can find the output file. This error has been reported in #275, please post your output file there, and then close this issue,

Best,

Dominic

**Comment by DominicDirkx** [comment]
Thanks for posting in #275, closing this issue.
