### ISSUE TITLE
Failed Unit Test: test_JsonInterfaceDeserialization

### ISSUE THREAD

**Issue by mchambe** [Tudat/tudat#288]
Good evening, 
JsonInterfaceDeserialization is the only test to have failed. My system is Windows 10 Home (version 10.0.15063).

Below is the error message:
`The following tests FAILED:
	190 - test_JsonInterfaceDeserialization (Failed)
Errors while running CTest
Makefile:70: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
17:45:13: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"`

Please find attached the LastTest.log and LastTestsFailed.log files.

Thank you in advance,
Marie Chambe

[LastTest.log](https://github.com/Tudat/tudat/files/1471741/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1471742/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
This seems to happening for most Windows users. We're tracking this issue here: #275. I'll close this issue and make a note there.
