### ISSUE TITLE
Compilation issue - step 3 of installation

### ISSUE THREAD

**Issue by Alisa2020** [Tudat/tudat#289]
C:\tudatBundle.git\CMakeLists.txt:14: error: The CMAKE_C_COMPILER: cl is not a full path and was not found in the PATH. To use the NMake generator with Visual C++, cmake must be run from a shell that can use the compiler cl from the command line.  This environment is unable to invoke the cl compiler.  To fix this problem, run cmake from the Visual Studio Command Prompt (vcvarsall.bat). Tell CMake where to find the compiler by setting either the environment variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to the compiler, or to the compiler name if it is in the PATH.

**Comment by DominicDirkx** [comment]
@Alisa2020  Did you follow step 6 here at the end of this page:

http://tudat.tudelft.nl/installation/setupDevWindows.html#qt-creator-mingw

Please check if your Build&Run settings are the same as in the screenshot (modify them so that they are if not), clock OK, close Qt creator, and then reopen tudatBundle/CMakeLists.txt with Qt. 

If this does not work, we will have a look tomorrow.

**Comment by Alisa2020** [comment]
That worked, thanx. But now I have a new issue: 

C:\Program Files (x86)\CMake\share\cmake-3.9\Modules\CMakeTestCCompiler.cmake:51: error: The C compiler "C:/Qt/Tools/mingw530_32/bin/gcc.exe" is not able to compile a simple test program. It fails with the following output: Change Dir: C:/Users/AlisA/AppData/Local/Temp/QtCreator-P1XkOA/qtc-cmake-XXrlb71Y/CMakeFiles/CMakeTmp

**Comment by DominicDirkx** [comment]
All right, at least that's progress :) 

There is a CMakeLists.txt.user file in your tudatBundle directory. Close Qt, delete this file, reopen Qt and try again. If this does not work, please copy the full output (probably given in the 'General Messages' tab) into a text file and post it here.

**Comment by wjhuisman** [comment]
Hi Dominic,

I have the same problem, and I checked all the things you said in this post. But I still get this message:

Running Windows Runtime device detection.
No winrtrunner.exe found.
Running "C:\Program Files (x86)\CMake\bin\cmake.exe -E server "--pipe=\\.\pipe\{1b2427e8-7a59-49f9-9bfb-6e2edeb696d2}" --experimental" in C:\Users\whuis\AppData\Local\Temp\QtCreator-P1XkOA\qtc-cmake-XXQbNBG7.
Starting to parse CMake project for Qt Creator.
The C compiler identification is GNU 5.3.0
The CXX compiler identification is GNU 5.3.0
Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "cmTC_45b14\fast"
Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Qt/Tools/mingw530_32/bin/gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/whuis/AppData/Local/Temp/QtCreator-P1XkOA/qtc-cmake-XXQbNBG7/CMakeFiles/CMakeTmp
    
    Run Build Command:"nmake" "/NOLOGO" "cmTC_45b14\fast"
    Het systeem kan het opgegeven bestand niet vinden
    Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "cmTC_45b14\fast"
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:14 (project)


Configuring incomplete, errors occurred!
See also "C:/Users/whuis/AppData/Local/Temp/QtCreator-P1XkOA/qtc-cmake-XXQbNBG7/CMakeFiles/CMakeOutput.log".
See also "C:/Users/whuis/AppData/Local/Temp/QtCreator-P1XkOA/qtc-cmake-XXQbNBG7/CMakeFiles/CMakeError.log".
CMake Project parsing failed.

**Comment by DominicDirkx** [comment]
Are you sure that your 'Generator' is set correctly (see step 6 in the link I posted above). if it is, close Qt creator, delete the CMakeLists.txt.user file (see above post), reopen Qt and try again.

**Comment by DominicDirkx** [comment]
I think we fixed this issue just now, right? Could you verify that you are now compiling?

**Comment by wjhuisman** [comment]
Sadly it gives the same error... Below is a screenshot of step 6 (I think I did it correctly). I closed Qt, removed the file, opened Qt again, tried again, but the same error was there.
![image](https://user-images.githubusercontent.com/33685846/32835307-e3aa0cac-ca05-11e7-9e1e-b20c83b204ea.png)

**Comment by DominicDirkx** [comment]
Have a look at the CMAKE GENERATOR (Green box in the screenshot in step 6). Yours is set to NMake, which is incorrect.

**Comment by DominicDirkx** [comment]
I'll assume that this problem is now resolved, and close the issue.
