### ISSUE TITLE
Failed configuration at step 3

### ISSUE THREAD

**Issue by martijnrozemeijer** [Tudat/tudat#290]
Hi Dominic,

During one of the last steps of part 3, I received the following error:

_C:\Program Files (x86)\CMake\share\cmake-3.10\Modules\CMakeTestCCompiler.cmake:52: error: The C compiler "C:/Qt/Tools/mingw530_32/bin/gcc.exe" is not able to compile a simple test program. It fails with the following output: Change Dir: C:/Users/marti/AppData/Local/Temp/QtCreator-P1XkOA/qtc-cmake-XXEbEkxK/CMakeFiles/CMakeTmp Run Build Command:"nmake" "/NOLOGO" "cmTC_1943d\fast" Het systeem kan het opgegeven bestand niet vinden Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "cmTC_1943d\fast"_

I tried troubleshooting (checking the kit and the directory of all downloaded parts ) and going through the steps however the same error still pops up. What am I doing wrong? I added some screenshots of the program.

![image](https://user-images.githubusercontent.com/33599464/32802973-48691194-c982-11e7-8b93-63d83da0f160.png) 

![image](https://user-images.githubusercontent.com/33599464/32803031-7d0ff8cc-c982-11e7-9432-f067267f2ebb.png)

**Comment by DominicDirkx** [comment]
@martijnrozemeijer This issue is similar to this one: 

https://github.com/Tudat/tudat/issues/289

In your case, the CMake Generator is incorrectly set. The approach to fix it is the same as what I posted in that issue (my first post anyway).

**Comment by DominicDirkx** [comment]
Did this fix your problem?

**Comment by martijnrozemeijer** [comment]
Hi Dominic!

The problem was solved using your approach, thank you! However I stumbled upon the problem of a failed unit test (for Windows) that is already mentoined here.

**Comment by DominicDirkx** [comment]
Ok, thanks!
