### ISSUE TITLE
Unit test 190 - test_JsonInterfaceDeserialization (Failed)

### ISSUE THREAD

**Issue by alexandervdb1995** [Tudat/tudat#291]
Unit test 190 failed on my windows 10 (64 bit) computer.
[LastTest.log](https://github.com/Tudat/tudat/files/1472893/LastTest.log)

**Comment by lstubbig** [comment]
Same for me.
Windows 10, 64-bit
[LastTest.log](https://github.com/Tudat/tudat/files/1473928/LastTest.log)

**Comment by lkoelemij** [comment]
Failed for me too on Windows 7 64-bit

[LastTest.log](https://github.com/Tudat/tudat/files/1473968/LastTest.log)

**Comment by DominicDirkx** [comment]
We are tracking this issue in #275, could you both post your output there?
