### ISSUE TITLE
Failed multiple test (test_Json*, test_SpiceInterface, test_SphericalHarmonicPartials)

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#294]
[LastTest.log](https://github.com/Tudat/tudat/files/1475057/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1475058/LastTestsFailed.log)
![image](https://user-images.githubusercontent.com/33669764/32841267-2cde6ec2-ca1a-11e7-8989-7ec45cbaba33.png)

**Comment by DominicDirkx** [comment]
This will require some more investigation, among the failed unit tests are also some that are likely to impact your ability to do the assignments. A few questions:

- Which compiler are you using? (refer to the screenshot at the end of this page: http://tudat.tudelft.nl/installation/setupDevWindows.html, compiler is shown in the red box)
- Which boost version are you using (tudatBundle/CMakeLists.txt: there will be a single boost version that is uncommented)

**Comment by RajathPai95** [comment]
Hello,

Thank you for the response. I went through the files and this is the compiler im using is
MinGW 5.3.0 32 bit using C++.


[cid:image001.jpg@01D35E5F.4F63F010]

The boost Version is 1.64.0


[cid:image003.jpg@01D35E5F.4F63F010]

I hope this information helps you, and If I could ask for a session to get this fixed as soon as possible, it’d be great.
Thanks,

With regards,
Rajath Pai K

**Comment by J-Westin** [comment]
Hello @DominicDirkx,

I just wanted to mention that I got the same error as @RajathPai95 (Exited with status 2, error code 8). My unit testing process only failed `test_JsonInterfaceDeserialization`, like with so many other Windows users. Is the error code and exit status to be expected when this one test is failed?

-- Johan Westin

**Comment by DominicDirkx** [comment]
@J-Westin The status/error code is the same whether 1 or any other non-zero number of unit tests fail. In your case, it's just the test_JsonInterfaceDeserialization, please post this in #275.

**Comment by DominicDirkx** [comment]
@RajathPai95 Ok, thank you. For any fufute respones, please post in the issue directly, if you reply via e-mail, your figures do not come through.

To identify how much of a problem these failures will be for your assignments, please run the following example applications:

- application_ApolloEntry
- application_ApolloEntryJSON
- application_VariationalEquationsPropagator
- application_SinglePerturbedSatellitePropagator

And let us know if all four of these run correctly.

Make sure to come to the lecture on Friday, we will make time to look at this problem then.

**Comment by magnific0** [comment]
@RajathPai95 can you also post your exact Windows version? Open a terminal and type

    ver

follo

**Comment by RajathPai95** [comment]
Version 10.0.15063

**Comment by RajathPai95** [comment]
@DominicDirkx I am not sure if i ran those apllications but when i did , the same tests were shown as failed. As a alternative, I'm working on using tudat through linux using a virtual box. In the meantime, if we find a fix, it'd be great.

**Comment by DominicDirkx** [comment]
@RajathPai95 That means you left the 'test' command in the build arguments. See the install guide:

"After running the unit tests, make sure to remove the ‘test’ text that you’ve typed in the project tab."

Then, if you go through step 6 of this:

http://tudat.tudelft.nl/installation/configureTudatLibraries.html

For the list of applications I posted above, you can run them.

**Comment by JochimM** [comment]
Hi, I believe to have the same exit code.
[LastTest.log](https://github.com/Tudat/tudat/files/1481833/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1481834/LastTestsFailed.log)
![image](https://user-images.githubusercontent.com/16223990/32941589-90248c56-cb86-11e7-96cd-053300afc591.png)
I'm using the MinGW 5.3.0 32 bit compiler, boost version is 1.64.0.

**Comment by magnific0** [comment]
It seems indeed that same tests fail for yous as fo @RajathPai95 So thanks for reporting this!

Can you go ahead and try running the example applications mentioned above and report whether they work?

Note that the status / exit code is the same for any test failure, see the [previous comment by @DominicDirkx ](https://github.com/Tudat/tudat/issues/294#issuecomment-344852564).

**Comment by RajathPai95** [comment]
![image](https://user-images.githubusercontent.com/33669764/32944065-7b258b36-cb8e-11e7-8dbc-de31628bb311.png)
![image](https://user-images.githubusercontent.com/33669764/32944112-a2a36980-cb8e-11e7-840b-1ec52bf7a326.png)
![image](https://user-images.githubusercontent.com/33669764/32944145-be704bc4-cb8e-11e7-86ef-2a6db8b8d121.png)
![image](https://user-images.githubusercontent.com/33669764/32944190-ef73dbf0-cb8e-11e7-972e-a58d5b40f5ed.png)
 4 example applications run and output in screengrab

**Comment by DominicDirkx** [comment]
Thank you, it seems that the Apollo example using JSON files is failing. We'll have a look after the lecture.

**Comment by liselottemulder** [comment]
I encounter the same problem

![issues](https://user-images.githubusercontent.com/33624453/32950226-e40b6cee-cba5-11e7-809c-86092e0672b2.PNG)

**Comment by JochimM** [comment]
For me all 4 example applications exit normally, also the ApolloEntryJSON example:
![image](https://user-images.githubusercontent.com/16223990/32953882-d24498b2-cbb1-11e7-8f0b-b80c23f81de4.png)
![image](https://user-images.githubusercontent.com/16223990/32953909-ed9d7e8a-cbb1-11e7-84f1-ac3c7fe43880.png)
![image](https://user-images.githubusercontent.com/16223990/32954017-2e995bd4-cbb2-11e7-8ea8-dbbf6d03c2da.png)
![image](https://user-images.githubusercontent.com/16223990/32953950-0ac538b8-cbb2-11e7-8f58-5eed67363c9a.png)

**Comment by DominicDirkx** [comment]
@JochimM In the above, it seems you have only compiled these tests. Could you also run them?

**Comment by JochimM** [comment]
@DominicDirkx Sorry, I didn't show the Application Output, but I have no problem running these applications.
![image](https://user-images.githubusercontent.com/16223990/32955849-6f222c6c-cbb7-11e7-8db8-c49a5f13c3ec.png)
![image](https://user-images.githubusercontent.com/16223990/32955907-9ee5528a-cbb7-11e7-9df8-9a1f5eb1c15d.png)
![image](https://user-images.githubusercontent.com/16223990/32955942-c123ca0c-cbb7-11e7-89c5-08af9b4e0daa.png)
![image](https://user-images.githubusercontent.com/16223990/32955711-07b82a18-cbb7-11e7-9255-993097c7c2f6.png)

**Comment by DominicDirkx** [comment]
Ok, thanks for showing it. This is very curious... Can you run the json_interface execitable in the same manner I demonstrated during the lecture today (slides will be posted before 6)?

**Comment by DominicDirkx** [comment]
For everyone that has encountered this issue, we have made a small modification that should correct it. So far, it has correctly resolved the problem on one of our test systems.

To update your code, pull the latest version of the tudatBundle. Alternatively, you can also make the modifications shown here:

https://github.com/Tudat/tudatBundle/commit/3ed9bd0c441959ceccf4f955f8ee2caf681b6941

manually in your tudatBundle/external/CMake/compiler.cmake file. 

Please, let us know if this resolves your problem or not. Before rerunning the tests, first recompile the code (remove the 'test' build argument).

**Comment by magnific0** [comment]
All tests described in the title of this issue now pass. However, I do have three additional test failures:
```
The following tests FAILED:
	 55 - test_DirectTidalDissipationAcceleration (Failed)
	185 - test_EnvironmentCreation (Failed)
	186 - test_AccelerationModelCreation (Failed)
```
ATTACHING LOG NOW

**Comment by DominicDirkx** [comment]
Looks like all of these are issues due to rounding. We could make the tolerances a bit higher, but let's look at it a bit more in the coming week. These failures don't look very worrying.

This is also known to happen if there is a mix between compilation with different settings. Are these failures from a completely clean compilation?

On a side note: https://xkcd.com/1739/

**Comment by magnific0** [comment]
@DominicDirkx fair point. I just deleted my build folder and am restarting now. I'll update tomorrow.

**Comment by DominicDirkx** [comment]
Sounds good, thanks for all the time you put into this!

Assuming that your CMake fix works for the other Windows users, none of the remaining issues seem to be high priority.

**Comment by magnific0** [comment]
@DominicDirkx all tests pass now, so you were indeed correct that the results were affected by a combination of build settings. So to reiterate the comment for Dominic above:

**To fix the problems in this issue:**

1. Pull the latest version of Tudat Bundle and Tudat from git ([steps 2 and 3 in the docs](http://tudat.tudelft.nl/developerGuide/updatingTudat/updatingTudat.html)).
2. Delete your build folder.
3. Rebuild Tudat and the rerun the test ([steps 1 to 5 in the docs](http://tudat.tudelft.nl/installation/configureTudatLibraries.html))

Instead of following instruction 1 you can also choose to [edit compiler.cmake](https://github.com/Tudat/tudatBundle/commit/3ed9bd0c441959ceccf4f955f8ee2caf681b6941) yourself. Also make sure to [update unitTestDeserialization.cpp](https://github.com/Tudat/tudat/commit/d54205338f7599d024de8667aa694ea67b71a2fc) as this is the solution to #275 which also affects you. 

Make sure that under Projects > Build Settings > Build Steps,  "tool arguments" is empty and only "all" is select before you attempt instruction 3.

**Comment by liselottemulder** [comment]
@magnific0 it works for me now :) (only unitTestDeserialization.cpp still fails)

**Comment by magnific0** [comment]
@liselottemulder that is great to hear! Thanks for reporting back. Note that issue #275 was also already solved. Also pull in the latest version of Tudat to fix this one.

**Comment by DominicDirkx** [comment]
For everyone taking the Numerical Astrodynamics course, copy your:

../tudatBundle/external/CMake/compiler.cmake

file to

../tudatBundle/tudatApplications/numericalAstrodynamics/assignment1/CMakeModules/compiler.cmake

overriding the existing file. Otherwise, there may be issues when moving to part 2 and 3 of assignment 1.

**Comment by AnanthK02** [comment]
For me, the following three unit tests fails: 
1) 86 - test_ParameterInfluenceDetermination
2) 181 - test_SofaFundamentalArguments
3) 190 - test_JsonInterfaceDeserialization

![image](https://user-images.githubusercontent.com/26100416/34388820-472683c2-eb36-11e7-93fe-7e514acef173.png)

Please let me know how I can resolve these issues. 
[System: Windows 8.1 Version 6.3.9600]
[LastTest.log](https://github.com/Tudat/tudat/files/1589568/LastTest.log)

**Comment by DominicDirkx** [comment]
@AnanthK02 The test_JsonInterfaceDeserialization failure is the same one found by others. The test_ParameterInfluenceDetermination and test_SofaFundamentalArguments are due to small rounding errors, and nothing to worry about. Could you please open a separate issue for this?

**Comment by AnanthK02** [comment]
Thank you. The solution for test_JsonInterfaceDeserialization worked. I have opened a new issue #315 for the other two tests.

**Comment by magnific0** [comment]
Thanks for letting us now. I'm closing this issue.
