### ISSUE TITLE
Failed unit test: 1 - sofa-test 

### ISSUE THREAD

**Issue by ARBatchelor** [Tudat/tudat#296]
As the title says, failed unit test 1 - sofa - test. OS: windows 10 64 bit.
Log files:

[LastTest.log](https://github.com/Tudat/tudat/files/1478843/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1478844/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
Closing issue, we have not been able to reproduce it, and it is most likely a result of inconsistent USE_SOFA settings. These have been updated in the latest version of the code.
