### ISSUE TITLE
New functionality implementation (Multi Arc least squares estimation with no overlap between arcs)

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#298]
Hi Dominic,

It seems that it is not possible to perform multi arc least squares estimations when there is no overlap between arcs. Could you please implement this new functionality in the Tudat?

Thank you,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Could you post the exact error you get when you try to do non-contiguous multi-arc estimation? I've tried it, and it seems to work fine for me.

Also, which version of Tudat are you currently on?

Have a nice weekend,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

I have actually been performing different tests and have noticed that sometimes it works fine and sometimes it does not (depending on the time arcs that I choose and their number..). The error that I get is

"Error when getting initial arc state from previous arc: no arc overlap"

and the parameter update is all nan in this case.

I am on the latest version of the development branch.

Thanks a lot,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

This error message is a result of the NaN values, not the other way around. If you get NaN values in your initial state, and then repropagate the dynamics, you can (will?) get this error. 

If you want to be able to continue the code after this has happened, you can use a try/catch block around the estimateParameters function. 

I'm concluding that this particular issue is closed: multi-arc state estimation/propagation with non-contiguous arcs works fine (so long as there are no NaN results, in which case the value of the results is diminished to say the least).

I'm closing this issue, if you have a followup question, for instance on the try/catch stuff, please open a dedicated issue,

Best,

Dominic
