### ISSUE TITLE
Runge Kutta 56 Integrator Unit Test

### ISSUE THREAD

**Issue by Reneh107** [Tudat/tudat#30]
The Runge Kutta 56 integrator is unit tested by comparing it with exact solutions of ODEs and by comparing it with the other RK integrators. 

The current unit test only proves that the integrator can obtain approximate solutions with a high accuracy. However, it does not prove that it is a RK56 integrator. 
It must be noted that simulations have shown that the RK56 integrator results in stepsizes that one would expect from a RK56 integrator when comparing it to the RK45 and the RK78 integrator. 

Therefore, I propose that the unit test will be improved to further verify the integrator. Ways to do this are:
Check that the order of the error is what one would expect. 
Derive an estimate of the truncation error and compare it with the error that is obtained using the integrator. 

Or maybe someone has some other ideas to test the integrator?

**Comment by DominicDirkx** [comment]
There has been a report of the RKF56 unit test failing (#84) when using clang.

**Comment by DominicDirkx** [comment]
I think the issue is solved, a fix will be uploaded to the repo in the coming days. Strangely enough, the issue was in numericalIntegrator.h itself, not if the 56 integrator...
