### ISSUE TITLE
Issue when estimating EEP violation parameter

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#304]
Hi Dominic,

I am having a problem estimating the EEP violation parameter with the Tudat. I have performed a single arc simulation in which I simply estimate the initial satellite state vector and the radiation pressure coefficient and everything works fine; however, when I add the EEP violation parameter  the software crashes (Error: Lagrange interpolator cannot identify zero entry...and the parameter update is all nan). The simulated observables are both one and two way doppler. Do you have any idea why it is crashing?

Thank you,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

It sounds like the data has no/insufficient independent sensitivity to the EEP parameter. Have you looked at your matrix of partial derivatives? Are there any columns that are only 0? What does the inverse of your covariance matrix look like? Does it complain about the condition number?

Does the code run correctly if you do not use the violation parameter? So, does _only_ changing the fact that you estimate the parameter cause the crash

For me to look at it further, could you post
- The full output of your simulation without the violation parameter.
- The full output of your simulation with the violation parameter.
- A link to your Github repository containing the code. If you do not have it on Github, you can attach it here (you have to change the file extension for Github to accept it as an attachment)

Dominic

**Comment by ggranato92** [comment]
The estimation with the EEP violation parameter crashes after the first iteration and the matrix of partial derivatives has a column full of nan (it's the column related to that parameter..). The other estimation (without EEP) works properly and I perform 3 iterations. In attachment I am providing the full outputs of both simulations. I have included in the output also the inverse of the covariance matrix. During both simulations there are some warnings concerning the light time which is unconverged at level 3e-12 and there are no complainings about the condition number.

[RadioAstronODsimulationArcs.zip](https://github.com/Tudat/tudat/files/1497027/RadioAstronODsimulationArcs.zip)

[RAStateEstimationExample.zip](https://github.com/Tudat/tudat/files/1497029/RAStateEstimationExample.zip)

[RAStateEstimationExampleEEP.zip](https://github.com/Tudat/tudat/files/1497035/RAStateEstimationExampleEEP.zip)

Thank you very much

**Comment by DominicDirkx** [comment]
Hi Giovanni,

The problem is that have not specified a proper time rate model d tau/dt, so that automatically  d tau / dt = 1. Since the EEP parameter is part of the proper time rate model, there is no sensitivity. Include a proper time rate model for both the transmitter and receiver:

http://tudat.tudelft.nl/tutorials/tudatFeatures/estimationSetup/observationModelSetup.html#OneWayDopperObservationSettings

And it should work,

Dominic
