### ISSUE TITLE
Spelling mistake in One and Two Way Doppler Observation Settings

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#305]
Hi Dominic,

I have noticed that among the ObservationSettings objects in the Tudat Estimation setup, the derived classes related to the one and two way doppler observation settings contain a spelling mistake: instead of Doppler it is written Dopper.

Best regards,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Thanks for spotting this, I've updated the code and pushed it to the master.
