### ISSUE TITLE
Try catch block in estimateParameters function

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#306]
Hi Dominic,

In the estimateParameters function would it be possible to insert a try catch block in order to prevent the software from crashing in case NaN values are obtained in the initial state and the dynamics is repropagated?

Best regards,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

I've added this to the code, and pushed it to the Tudat master. I've added tow new variables to the PodOutput class:

    //! Boolean denoting whether an exception was caught during inversion of normal equations
    bool exceptionDuringInversion_;

    //! Boolean denoting whether an exception was caught during (re)propagation of equations of motion (and variational equations)
    bool exceptionDuringPropagation_;

They should be self-explanatory, if you have any issues with this new code, don't hesitate to let me know.
