### ISSUE TITLE
Problem in estimating biases

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#308]
Hi Dominic,

I have performed least squares estimations including both absolute and relative biases in the list of parameters to estimate. In both cases the parameter update results in all NaN since the normalization values corresponding to the biases are either zeros or NaN and thus the Information Matrix has columns which contain either inf or NaN as well. It is very strange that this happens in all cases ( I am estimating the biases for every link end and for every observable ) so I'm wondering if there could be any error in the software. 

Best regards,
Giovanni

**Comment by ggranato92** [comment]
To be more clear the biases that I am trying to estimate are related to One and Two Way Doppler observations

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Could you push your code file to Github and post a link here, or add your code here as an attachment?

Best,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

Attached is the code (this one is with relative biases estimation)

[RadioAstronODsimulationArcs.zip](https://github.com/Tudat/tudat/files/1537332/RadioAstronODsimulationArcs.zip)

Thank you very much,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Your code tries to load a file called 'MikhailData.txt', which I don't have. Could you send it?

Thanks,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

I have just sent you an email with the file

Thanks,
Giovanni

**Comment by DominicDirkx** [comment]
I'm looking into it now, and something funny is definitely going on. When estimating only one-way partials, without any two-way _**observations**_, everything is fine. It seems like there is some sort fo interference between the one- and two-way observations. I have a pretty good idea what's wrong, and I'll get back to you with a fix later today (with a little luck).

**Comment by DominicDirkx** [comment]
Hi Giovanni,

I made a patch to the code that, partly, adresses issue:

https://github.com/Tudat/tudat/commit/d8fd1cc01552dfd6cfd178ab18b996bdfd8baef9

It will allow you to estimate one-way biases, even when using both one- and two-way observations. Two-way biases can still not be estimated, I'll get back to you on that.

**Comment by DominicDirkx** [comment]
And now also fixed the two-way biases:

https://github.com/Tudat/tudat/commit/6e01a976b349bc91d0f3dd3e6ccf088d546109f9

Thanks for bringing this to my attention :)

Cheers,

Dominic

**Comment by DominicDirkx** [comment]
FYI, comments have been added, and the whole code has been pushed to master
