### ISSUE TITLE
json_interface does not exist

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#309]
I recieve an error that json_interface does not exist, and i have put the right working directory, but I don't know why this happens. Can someone guide me?

**Comment by DominicDirkx** [comment]
To help you out, we're going to need a little more information:
- When and where does this error occur? Which steps have you taken up until where this occurs?
- Which operating system are you using?
- Have you run all the unit tests? Are they succesful?
- Which, if any, changes have you made after running the tests?

**Comment by RajathPai95** [comment]
So, I created a new json file where i copied the delfipropagation.json and then made delfipropagationPart1.json , with some necessary changes
Current OS: : linux : ubuntu 16.04
The unit tests are successful
The only changes I made were trying to run this new .json and I get one of 2 errors .
1 is the one mentioned above , or 2 , is that my json file isnt found although i have put the right directories,and json_interface was forcefully terminated
P.S. I'm not that familiar with the linux environment and I may be doing some error that i'm not aware of, but I have explained what I've attempted to do as much as i can.

**Comment by DominicDirkx** [comment]
Thanks for the details, some more questions:

- You say that you get one of two errors, when do do you get which?
- Could you show a screenshot of your Projects -> Build&Run -> Run screen? Are you absolutely sure that you have put the input directory and file correctly?

**Comment by RajathPai95** [comment]
![image](https://user-images.githubusercontent.com/33669764/33807491-f3d6e59c-ddd7-11e7-8230-cefe4b886c7d.png)
This caused json to crash, and I dont know if iḿ doing it right.i cannot be sure. iĺl try to come to the open office hours tomorrow, and we can work on this issue. I might be in the wrong here but iḿ not sure where.

**Comment by DominicDirkx** [comment]
This looks close to how it should, and the fact that it crashes does mean that the executable json_interface does exist and can be found by Qt.

In the line 'Working Directory' put _only_ the directory where your input file is. In the line 'Command line arguments', put _only_ the name of the input file. 

If this doesn't work, please, post here the _full_ application output that is provided.

**Comment by magnific0** [comment]
@RajathPai95 was this issue solved for you? If yes, what steps did you take to solve it?

I'm trying to close old and resolved issues.

**Comment by RajathPai95** [comment]
Yes it was, and I solved it by pulling the code ata later stage and all unit tests necessary ran without a htich, thank you and sorry for the late reply

**Comment by magnific0** [comment]
@RajathPai95 no worries and thanks for reporting back! Closing this issue.
