### ISSUE TITLE
Request to create a velocity_observable

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#312]
Hello everyone, I will be working with the estimators in my thesis work. I need to use the state vector as the input to the estimator. To do so, I need the developers of TUDAT to create a 'velocity_observable' as an observation type. This will enable me to combine the 'position_observable' and 'velocity_observable' into one state vector. The following link can guide you to the location of the content in the Tutorials, that I have discussed above:

http://tudat.tudelft.nl/tutorials/tudatFeatures/estimationSetup/observationModelSetup.html#observation-types

**Comment by magnific0** [comment]
Hi @Pugazhenthi-Sivasankar 
As you probably have noticed we are very busy at the moment. So your best bet is to try to expand the functionality yourself.
Luckily, it should be relatively to do so, duplicating:
https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/ObservationModels/positionObservationModel.h
and replacing:
    currentState_.segment( 0, 3 );
with
     currentState_.segment( 3, 3 );
Then [search within Tudat](http://tudat.tudelft.nl/tutorials/troubleshooting/searchingTudat.html) for occurences of ```position_observable```. Duplicating again the functionality of this observable. 
Don't hesitate to ask for more questions here!

**Comment by DominicDirkx** [comment]
Unfortunately, it's a bit more than this, in particular because the estimation also has to be updated (and all associated create functions etc.)

**Comment by DominicDirkx** [comment]
I've written a first iteration of the code, and pushed it here:

https://github.com/DominicDirkx/tudat/tree/VelocityObservable

Unit tests are incomplete, but the observation model and estimation are both tested. Details are not (yet). Interfaces are identical to position observable, but the type is velocity_observable instead of position_observable,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Dear Developers,
                          Thank you for taking my request into consideration!

**Comment by DominicDirkx** [comment]
Code has been written, no feedback, so closing issue and moving code to pull request.
