### ISSUE TITLE
Project Build tudat_observation_partials

### ISSUE THREAD

**Issue by martijnrozemeijer** [Tudat/tudat#314]
Hi Dominic,

I redownloaded the Tudat package again to be sure that I had the right versions of all packages on my computer. Everything was already built during the first lecture. When building 'tudat_observation_partials' package, i stumbled on an error that I had not seen before when I built Tudat. The following error occured:

![image](https://user-images.githubusercontent.com/33599464/34570725-efa123e0-f16c-11e7-9c87-30934f8e0164.png)

I tried looking in the folder if the file did not exist, however it existed as can be seen here:

![image](https://user-images.githubusercontent.com/33599464/34570777-0dd6e82c-f16d-11e7-8107-abab88f7aef6.png)

What do you suggest I do? Leave this problem and build the rest of the files?

Looking forward to hearing from you!

Best regards,

Martijn Rozemeijer

**Comment by martijnrozemeijer** [comment]
Hi,

I just noticed that this build step is critical which makes it impossible to build the other steps. I am working on a windows system by the way.

Best regards,

Martijn Rozemeijer

**Comment by DominicDirkx** [comment]
@martijnrozemeijer  I see that you closed this issue, does that mean it's resolved? Could you give a short description of how you fixed it? This will be useful for others encountering the same problem,

Best regards,

Dominic

**Comment by martijnrozemeijer** [comment]
Hi Dominic,

It seems that my tudat package was installed in a part of my previously installed tudat package. I therefore encountered path names that were too long and it was difficult too find why since my directories looked normal like they did before. After further inspection, it became clear to me that the tudat package was in a previous directory. I removed tudat and then reinstalled the program, this fixed my problem.

Best regards,

Martijn Rozemeijer
