### ISSUE TITLE
Failed Unit Tests (test_ParameterInfluenceDetermination, test_SofaFundamentalArguments)

### ISSUE THREAD

**Issue by AnanthK02** [Tudat/tudat#315]
![unittestfailed2](https://user-images.githubusercontent.com/26100416/34728671-cd5765d2-f55a-11e7-8224-f489e1a0f2e6.JPG)
[LastTest.log](https://github.com/Tudat/tudat/files/1615630/LastTest.log)

**Comment by magnific0** [comment]
As @DominicDirkx mentioned in #294. Both failures don't are not severe as the tolerances are just barely exceeded:

    C:/tudat/tudatBundle/tudat/Tudat/Astrodynamics/OrbitDetermination/UnitTests/unitTestParameterInfluenceDetermination.cpp(234): error: in "test_parameter_influence_estimtation/test_ParameterPostFitResiduals": absolute value of std::fabs( mercuryPositionAdjustmentDifference( index ) ){0.100616455078125} exceeds 0.10000000000000001

    C:/tudat/tudatBundle/tudat/Tudat/External/SofaInterface/UnitTests/unitTestFundamentalArguments.cpp(62): error: in "test_sofa_fundamental_arguments/testSofaFundamentalArguments": absolute value of expectedFundamentalArgumentValues( i ) - fundamentalArgumentValues( i ){-1.092459456231154e-013} exceeds 1e-013

I propose that we increase the tolerance in some future update.

**Comment by DominicDirkx** [comment]
Commited here:

https://github.com/Tudat/tudat/commit/1ef3353134fdb61eda3ad1b23dcb90078809e05e
