### ISSUE TITLE
Norm of "getCurrentAngularVelocityVectorInGlobalFrame" :retrieving rotational velocity of Earth

### ISSUE THREAD

**Issue by janwillemarink** [Tudat/tudat#316]
Dear Dominic,

As mentioned during the open office hours of today: can we retrieve the rotational velocity of the Earth by taking the norm of the "getCurrentAngularVelocityVectorInGlobalFrame" function?

Kindest regards,

Jan-Willem

**Comment by DominicDirkx** [comment]
It is indeed possible to retrieve it using that function.
