### ISSUE TITLE
Github Basics Documentation missing diagrams

### ISSUE THREAD

**Issue by ifodde** [Tudat/tudat#317]
Hello,
 in the GitHub Basics part of the documentation, a figure is referenced a couple of times, which doesn't show up on the page. I think you forgot to add this figure, or maybe there is something wrong with my browser. 

Thanks,
Iosto

**Comment by magnific0** [comment]
Hi @ifodde 
Thanks for reporting this issue. The figure does indeed not show up and is referenced in the docs a few times:
http://tudat.tudelft.nl/developerGuide/githubBasics/githubBasics.html?highlight=diagram
The missing figure can be found here:
https://i.imgur.com/8W3tzP0.png
