### ISSUE TITLE
run configurations are disabled

### ISSUE THREAD

**Issue by Jornopaulus** [Tudat/tudat#318]
I am currently having problems running the delfiVariationalEquation.cpp file. I had it running yesterday but then my laptop suddenly shut down due to unknown reason. Now when I am trying to run the file with the application_DelfiVariationalEquations configuration it keeps giving me the following error:

[100%] Built target tudat_sofa_interface
[100%] Built target tudat_spice_interface
[100%] Linking CXX executable C:\tudatBundle\tudatApplications\numericalAstrodynamics\bin\applications\application_DelfiVariationalEquations.exe
CMakeFiles\application_DelfiVariationalEquations.dir/objects.a: member CMakeFiles\application_DelfiVariationalEquations.dir/objects.a(delfiVariationalEquations.cpp.obj) in archive is not an object
collect2.exe: error: ld returned 1 exit status
tudatApplications\numericalAstrodynamics\assignment1\CMakeFiles\application_DelfiVariationalEquations.dir\build.make:134: recipe for target 'C:/tudatBundle/tudatApplications/numericalAstrodynamics/bin/applications/application_DelfiVariationalEquations.exe' failed
CMakeFiles\Makefile2:14173: recipe for target 'tudatApplications/numericalAstrodynamics/assignment1/CMakeFiles/application_DelfiVariationalEquations.dir/all' failed
CMakeFiles\Makefile2:14185: recipe for target 'tudatApplications/numericalAstrodynamics/assignment1/CMakeFiles/application_DelfiVariationalEquations.dir/rule' failed
Makefile:3619: recipe for target 'application_DelfiVariationalEquations' failed
mingw32-make.exe[3]: *** [C:/tudatBundle/tudatApplications/numericalAstrodynamics/bin/applications/application_DelfiVariationalEquations.exe] Error 1
mingw32-make.exe[2]: *** [tudatApplications/numericalAstrodynamics/assignment1/CMakeFiles/application_DelfiVariationalEquations.dir/all] Error 2
mingw32-make.exe[1]: *** [tudatApplications/numericalAstrodynamics/assignment1/CMakeFiles/application_DelfiVariationalEquations.dir/rule] Error 2
mingw32-make.exe: *** [application_DelfiVariationalEquations] Error 2
16:17:57: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"

I have also noticed that all run configurations are set to disabled, when I try to rebuild the libaries it runs properly until it comes tot "application_DelfiVariationalEquations" and then it gives the same error.

kind regards 

Jorn Vanwesenbeeck

**Comment by DominicDirkx** [comment]
Dear Jorn,

Did your laptop shutdown during compilation?

Please post a screenshot of your build steps (Project -> Build) and run settings (Projects -> Run) and we can see if we can fix it remotely. Otherwise, drop by the open office hours on Tuesday,

Best,

Dominic

**Comment by Jornopaulus** [comment]
not completely sure if it was during compilation but I guess so... 
![tudaterror1](https://user-images.githubusercontent.com/30377149/35197329-e3bef178-fedd-11e7-8b35-3248ed2ab30d.JPG)
![tudaterror2](https://user-images.githubusercontent.com/30377149/35197330-e3d7bd5c-fedd-11e7-9983-eee66ed6b346.JPG)


kind regards 


Jorn

**Comment by DominicDirkx** [comment]
Hi Jorno,
 
Try removing the command line arguments in your 'run' screen. If that doesn't correct it, drop by tomorrow,

Best,

Dominic

**Comment by Jornopaulus** [comment]
doesn't seem to work, I'll drop by tomorrow

**Comment by magnific0** [comment]
Hi Jorn,
Try deleting from C:\build-tudatBundle-Desktop-Default

- file: CMakeCache.txt
- folder: tudatApplications

This will force the complete rebuild of your assignment.

Also note that while the configurations might be labeled as disabled, if the Run and Build buttons are available, they are most certainly not. QtCreator can be a bit misleading.

Did you by any chance move or rename any of your folders?

Regards,

Jacco

**Comment by Jornopaulus** [comment]
Looks like its working now!

Thank you

**Comment by magnific0** [comment]
That's good to hear. Thanks for reporting back.

What did you do to fix it?

**Comment by DominicDirkx** [comment]
As I recall, he followed your instructions, and all went well.
