### ISSUE TITLE
Thrust model

### ISSUE THREAD

**Issue by DominicDirkx** [Tudat/tudat#32]
A thrust model, and the associated consistent handling of vehicle mass changes, is crucial in many astrodynamics/mission analysis applications. This code is under construction and will be added to Tudat in the near future.

**Comment by DominicDirkx** [comment]
As discussed during the meeting on 03-06-2016, one of the main developments that is needed for Tudat is a versatile, but user-friendly, set of models for vehicle thrust.

One of the main complications, which should be handled either concurrently or beforehand, is the inclusion of vehicle mass a state variable. The inclusion of additional state variables is foreseen in the architecture design of the code, but the exact implementation of the link:

Thrust <-> Engine Characteristics <-> Mass Rate <-> Equations of Motion

is TBD

**Comment by magnific0** [comment]
As already discussed in person, there are a lot of choices that need to be made to implement these models.

- What thruster models do we implement (if at all)? This paper describes different models such as CSI, bounded VSI, dual VSI, VSI:

Casalino, L., & Colasurdo, G. (2004). Optimization of Variable-Specific-Impulse Interplanetary Trajectories. Journal of Guidance, Control, and Dynamics, 27(4).

- How do we define the control? Which variable and frames do we use? 

For my MSc thesis I used spherical coordinates in a [control frame](http://file.geul.net:8000/f/098a9b0d0d/?raw=1) (by rotating the orbital frame over the flight path angle). One angle then defines the in-plane direction of the thrust and another the out-of-plane direction. The third parameter is either the magnitude or some throttle setting. This allows for easy cases such as (π,0,1) to define full thrust in tangential direction.

**Comment by DominicDirkx** [comment]
Indeed, the variety of choices that is available for defining/controlling thrust is vast.

Ideally, our implementation should allow each of them to be used. In principle, this can be relatively easily implemented by making the interfaces implementation-independent, but then we are still left with a whole bunch of choices on how to link the various thrust options to the acceleration model.

By the way, I quickly wrote some code to allow for mass propagation in Tudat:

https://github.com/DominicDirkx/tudat/tree/MassPropagation

It's missing some comments, but overall it was quite a bit easier than I'd thought to get it to work. Right now, the only mass rate model that is implemented is 'custom' (i.e. any random function that does not need to be linked to any thrust model). I've unit tested it with some simple cases and it seems to work.

**Comment by DominicDirkx** [comment]
This functionality has now been added to the master branch.
