### ISSUE TITLE
Information Matrix Normalization

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#329]
Hi Dominic,

Concerning the Information Matrix Normalization within the tool for the estimation of parameters, would it be possible to modify the code in a way that when a column of the matrix is all zeros it is not normalized? In this case, in fact, the normalization produces NaN values which then break the algorithm.

Thanks,
Giovanni

**Comment by DominicDirkx** [comment]
I've updated the code here:

https://github.com/DominicDirkx/tudat/tree/SmallODChanges

please let me know if it works as you intend,

Dominic
