### ISSUE TITLE
getFullParameterValues function call when biases are not created yet

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#330]
Hi Dominic,

In case of a bias estimation, when the getFullParameterValues function is called before the biases are actually created in the code (for instance if the function is called right after the definition of the parameters to estimate), the programme crashes. Could you please fix this issue?

Thanks,
Giovanni

**Comment by DominicDirkx** [comment]
I've updated the code here:

https://github.com/DominicDirkx/tudat/tree/SmallODChanges

please let me know if it works as you intend,

Dominic
