### ISSUE TITLE
Optimization branch Unit Test failures

### ISSUE THREAD

**Issue by ifodde** [Tudat/tudat#336]
Hello,

I built the optimization branch with PAGMO 2 included, but when I tried to run the unit tests, there were several that failed, see the file:
[unittesterror.txt](https://github.com/Tudat/tudat/files/1711948/unittesterror.txt)

Cheers,
Iosto

**Comment by DominicDirkx** [comment]
Hi Iosto,

There's a few files with some details that help to figure out what's going on:

http://tudat.tudelft.nl/installation/troubleshooting/installationErrors.html#debuggingfailedunittests

Could you post those here?

Cheers,

Dominic

**Comment by ifodde** [comment]
hey Dominic,

sorry, completely forgot to add them, here they are:

[LastTest.log](https://github.com/Tudat/tudat/files/1715831/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1715832/LastTestsFailed.log)
[CTestCostData.txt](https://github.com/Tudat/tudat/files/1715834/CTestCostData.txt)

**Comment by DominicDirkx** [comment]
Hi Iosto,

Thanks for posting these. The failures in the LastTest.log are quite puzzling. For instance, have a look at line 63 of the file, it seems something is going really very wrong there....

Have you run all the Pagmo examples in tudatExampleApplications? If they all work fine, this does not have very high priority. If some of them also fail, this is something that we'll need to fix within the next couple of weeks,

Cheers,

Dominic

**Comment by ifodde** [comment]
that looks very weird...
I have tested all example applications and they all run fine. So I don't know what these unit test failures could be...

**Comment by DominicDirkx** [comment]
Ok, very good to hear that all example applications run fine. 

The pagmo unit tests seem to fail with segmentation faults, probably memory is being accessed that shouldn't be, and the resulting data ends up being gibberish. Why this is happening on Windows and not Linux, I have no idea.....
