### ISSUE TITLE
Multiple unit test fails with newest build (16.02.18)

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#342]
Hi,
after the lecture today I tried to run all unit tests and was confronted with the following errors:
I'm using cmake-3.10.2 on Windows 10
"Compile high accuracy estimation tests" is set to OFF

[Test error.txt](https://github.com/Tudat/tudat/files/1732627/Test.error.txt)

[CTestCostData.txt](https://github.com/Tudat/tudat/files/1732623/CTestCostData.txt)
[LastTest.log](https://github.com/Tudat/tudat/files/1732624/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1732625/LastTestsFailed.log)

Cheers,
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

The tests seem to be complaining a lot about: "Unable to find executable:....". Did the compilation complete correctly? 

To fox this, could you try:

- Closing/reopening Qt
- Recompiling (make sure that the 'test' argument is removed in the build steps, and that either 'all' or nothing is ticked in the list 'targets')
- Please post the full 'Compile Output' (as a text file), and I'll have a look at what's happening
- After the compilation finishes, rerunning the unit tests 

Have a nice weekend,

Dominic

**Comment by SebastianVillamil** [comment]
Hi Dominic,

recompiling Tudat solved the problem. 
After recompiling all unit test passed. Thanks!

Kind regards,
Sebastian

**Comment by DominicDirkx** [comment]
Happy to hear it!
