### ISSUE TITLE
Error when building Tudat

### ISSUE THREAD

**Issue by oramireztorralba** [Tudat/tudat#343]
Good morning,

As you suggested for the course AE4866 Propagation and Optimization in Astrodynamics, after updating Tudat I have tried to recompile and rerun all unit tests. However, when building the project again (option 'all' in Build steps), I encounter the following error:

![error_build](https://user-images.githubusercontent.com/33600448/36369888-3d2e31c0-155d-11e8-8515-dabb826cf0f8.PNG)

Then, if I try to rerun the unit tests, it seems that I can only run about 78 out of 219 (36% tests passed, 141 tests failed out of 219), since it is said that it cannot find the files:

![error_unittests](https://user-images.githubusercontent.com/33600448/36370072-e7bed64e-155d-11e8-8b94-cfab5c223b16.PNG)

Regarding the homework for the first week, the code seems to run fine. However, I would like to fix this problem asap for the future homeworks.

Thank you very much for your attention.

Best regards,

Olga.

**Comment by wjhuisman** [comment]
Hi,

When re-running the unit tests, I get 2 errrors, listed below. For the assignment, the code seems to run fine. Are these errors something to worry about?

Kind regards

C:/tudatBundle.git/tudat/lib/libtudat_simulation_setup.a(propagationTermination.cpp.obj):propagationTermination.cpp:(.text$_ZN5boost11make_sharedIN5tudat11propagators50SingleVariableLimitPropagationTerminationConditionEJRNS_10shared_ptrINS2_35SingleDependentVariableSaveSettingsEEERNS_8functionIFdvEEERdRbSD_RNS4_INS1_12root_finders18RootFinderSettingsEEEEEENS_6detail15sp_if_not_arrayIT_E4typeEDpOT0_[__ZN5boost11make_sharedIN5tudat11propagators50SingleVariableLimitPropagationTerminationConditionEJRNS_10shared_ptrINS2_35SingleDependentVariableSaveSettingsEEERNS_8functionIFdvEEERdRbSD_RNS4_INS1_12root_finders18RootFinderSettingsEEEEEENS_6detail15sp_if_not_arrayIT_E4typeEDpOT0_]+0x203): undefined reference to `tudat::root_finders::doesRootFinderRequireDerivatives(boost::shared_ptr<tudat::root_finders::RootFinderSettings>)'
collect2.exe: error: ld returned 1 exit status
tudatApplications\tudatAssignments\assignment1\CMakeFiles\application_DelfiNumericalIntegrationJson.dir\build.make:130: recipe for target 'C:/tudatBundle.git/tudatApplications/tudatAssignments/bin/applications/application_DelfiNumericalIntegrationJson.exe' failed
CMakeFiles\Makefile2:14074: recipe for target 'tudatApplications/tudatAssignments/assignment1/CMakeFiles/application_DelfiNumericalIntegrationJson.dir/all' failed
Makefile:139: recipe for target 'all' failed
mingw32-make.exe[2]: *** [C:/tudatBundle.git/tudatApplications/tudatAssignments/bin/applications/application_DelfiNumericalIntegrationJson.exe] Error 1
mingw32-make.exe[1]: *** [tudatApplications/tudatAssignments/assignment1/CMakeFiles/application_DelfiNumericalIntegrationJson.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
08:46:13: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"

**Comment by DominicDirkx** [comment]
Hi Wouter,

These seem to be occurring in the homework assignments from Numerical Astrodynamics. We've made a few changes to Tudat, which require some small modifications to the CMakeLists.txt file. If you'd like, I can push these changes to the NumericalAstrodynamics repository, so you can get the code to compile again. Otherwise, you can simply turn off the Numerical Astrodynamics applications in the top-level CMakeLists.

Best,

Dominic
