### ISSUE TITLE
Compile high accuracy estimation tests

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#347]
Hello everyone!! While installing TUDAT, I got a message from the compiler which read 'out of memory allocating 2130160 bytes'. I followed the relevant suggestion given under the Troubleshooting tab and the installation process continued. After some time, the same error message was shown. So, I commented the 'if ( COMPILE_HIGH_ACCURACY_ESTIMATION_TESTS ).....endif()' portion of the CMakeLists,txt file in the OrbitDetermination folder. This resulted in successful completion of the installation process. Now, will this create a problem while using the batch estimator for orbit determination? I have included the compilation output for your reference. The error message starts from the line 899.
[Compiler_errors.txt](https://github.com/Tudat/tudat/files/1772556/Compiler_errors.txt)

**Comment by DominicDirkx** [comment]
Hi Pugazh,

No need to worry about this for your application. It only disables the unit tests for the estimation where higher than double precision is required. This, for instance, the case for mm-range data on solar system scales, but for Earth orbiters regular double precision will be fine.  Double precision orbit determination is still compiled correctly, even if COMPILE_HIGH_ACCURACY_ESTIMATION_TESTS is set to OFF,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Thank you!!
