### ISSUE TITLE
MATLAB interface problems

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#348]
Hello everyone!! I tried to build the MATLAB interface for the most recent version of TUDAT by following the steps given in the 'Installation' section of the Tutorials and Documentation. When I ran 'build.m', it showed the error 'The C compiler identification is unknown...'. It should be noted that with the help of Aleix Pinadrell, I had been able to set up the MATLAB interface for the older version of TUDAT. When I approached Aleix this time, he said that he could no longer help as TUDAT has changed a lot since he left. Now, how to proceed further in creating the MATLAB interface? I have attached the error message for your reference.
[Errors_when_running_build.m.txt](https://github.com/Tudat/tudat/files/1775812/Errors_when_running_build.m.txt)

**Comment by DominicDirkx** [comment]
Hi Pugazh,

As I recall, the build.m file never really worked properly on Windows. What this script will do (I think) is build the parts of Tudat you need for the Matlab interface. Since you have built Tudat already (from Qt Creator), there is no need to redo this,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Hello Dominic, if what you say is the functionality of build.m, then why am I getting error messages while running the unit tests in MATLAB?

**Comment by DominicDirkx** [comment]
I don't know, you did not mention you were getting these error messages in the unit tests. If you give the details of the commands you enter, and the (error) output you get - in text files, not screenshots - I can have a look.

**Comment by Pugazhenthi-Sivasankar** [comment]
Hello Domminic, I have attached the screen shots of the MATLAB command window with this message. I ran the files 'setup.m' and 'build.m' and got a lot of errors. I also used the command 'tudat.test()' which showed a list of 29 failed tests.
![cmd_and_errors_1](https://user-images.githubusercontent.com/25662615/36975465-774a6982-207a-11e8-88f0-9994a52b1312.jpg)
![cmd_and_errors_2](https://user-images.githubusercontent.com/25662615/36975467-77651e94-207a-11e8-9860-66fc0922677a.jpg)
![cmd_and_errors_3](https://user-images.githubusercontent.com/25662615/36975468-777b1a50-207a-11e8-935d-52708be7fc3c.jpg)
![cmd_and_errors_4](https://user-images.githubusercontent.com/25662615/36975469-7796d70e-207a-11e8-9f93-debd98479d24.jpg)
![cmd_and_errors_5](https://user-images.githubusercontent.com/25662615/36975470-77b3fff0-207a-11e8-90de-42b9bca1170a.jpg)

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Please see my previous post:

" If you give the details of the commands you enter, and the (error) output you get - in text files, not screenshots - I can have a look."

Screenshots are not searchable, text files are, making it easier for me to interpret the results,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Apologies for the inconvenience. Here are the text files:
[Cmd_and_errors_1.txt](https://github.com/Tudat/tudat/files/1780939/Cmd_and_errors_1.txt)
[Cmd_and_errors_2.txt](https://github.com/Tudat/tudat/files/1780940/Cmd_and_errors_2.txt)

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Could you run one of the unit tests separately (for instance the file tudatBundle/matlabInterface/UnitTests/unitTestAcceleration.m) and post the output here in a text file? I'm curious to see why none of the unit tests run,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
The test failed.
[unitTestAcceleration_error.txt](https://github.com/Tudat/tudat/files/1784809/unitTestAcceleration_error.txt)

**Comment by DominicDirkx** [comment]
Please replace the 

.../tudatBundle/matlabInterface/MatlabInterface/+support/systemCommand.m

file with the attached file (change file extension to .m), rerun the unit test, and post the output here
[systemCommand.m.txt](https://github.com/Tudat/tudat/files/1784920/systemCommand.m.txt)

**Comment by Pugazhenthi-Sivasankar** [comment]
The test failed. However, this time there was some more information displayed in the command window.
[unitTestAcceleration_error_2.txt](https://github.com/Tudat/tudat/files/1785246/unitTestAcceleration_error_2.txt)

**Comment by DominicDirkx** [comment]
Hi Pugazh,

So, the test is trying to run the file:

C:\tudat\tudatBundle\tudat\bin\unit_tests\test_JsonInterfaceAcceleration

Can you verify whether this file exists (probably with a .exe extension)? If so, my guess is that the executable requires a number of .dll files that are not included in your path. 

You are using Windows right? When you try to run the .exe from Windows Explorer (or whatever the thing is called nowadays), you'll probably get an error message saying that some .dll file was not found. If so, please add a screenshot of teh error output, and we'll try to fix it,

Best,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Hello Dominic, the file test_JsonInterfaceAcceleration.exe exists. But when I tried to run, it showed an error:
![test_jsoninterfaceacceleration](https://user-images.githubusercontent.com/25662615/37041765-405fb74a-215d-11e8-8c6a-a961dd1a8922.jpg)

**Comment by DominicDirkx** [comment]
As expected, a dll is missing. You can append your PATH variable in Windows, as described here:

https://stackoverflow.com/questions/28907304/cc1-exe-system-error-libwinpthread-1-dll-missing-but-it-isnt

There's probably also a way to add variables to your PATH only while in Matlab.

When you add the directory containing the libwinpthread-1.dll file to your path, this error should go away. You may get a  new one, with another .dll missing. Just keep adding files to your path (those containing the missing dll files), and I think this will solve your problem.

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
I searched for the file 'libwinpthread-1.dll' in my laptop. But there were no results. What to do in this situation?

**Comment by DominicDirkx** [comment]
I'm pretty sure it has to be somewhere, or I don't think the tests would be able to run from Qt either. It should be in your ..../MinGW/bin/ directory.

**Comment by DominicDirkx** [comment]
Problem solved, adding the mingw/bin/ to the path, and then restarting Matlab, did the trick.
