### ISSUE TITLE
Problem in setting up new application

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#349]
Hello everyone!! I followed the procedure given in the 'Setup New Applications' section to create my own application in TUDAT and was successful in running it. I tried to create another application by modifying the existing .cpp file and using 'Save As' to create a new .cpp file. I made corresponding changes to the 'CMakeLists.txt' file and was successful in including the new application in the project tree. However, when I tried to run the newly created application, an error message was shown as: *"The 'application .....exe' does not exist." So I closed the Qt creator and opened it again. When I ran the newly created application this time, there was no problem and I got the output.* Does this mean that I have to close and reopen the Qt creator every time I create a new application?

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Yes, unfortunately this is a known problem. Qt does not need to be restarted, but CMake does need to be rerun after a new application has been _compiled_ to be able to run it from Qt. Restarting Qt automatically reruns CMake, explaining why this works
