### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#355]
Hello all, 
whenever I try to compile Tudat applications, I get the error in the text file. I have also included the output of the unit tests, which shows that a couple tests fail (related to the JSON interface), and that a few tests are not found. 
My laptop is running macOS 10.13.3, and the command line tools are at version 9.2.
Thank you! 
Michele

[tudat_error.txt](https://github.com/Tudat/tudat/files/1821455/tudat_error.txt)
[tudat_test_output.txt](https://github.com/Tudat/tudat/files/1821456/tudat_test_output.txt)

**Comment by mfacchinelli** [comment]
Ok, my apologies, I had forgotten to update the tudatExampleApplications folder, and now the 'Undefined symbols for architecture x86_64' error is fixed. The unit test output, however, is still the same.

**Comment by DominicDirkx** [comment]
Hi Michele,

Are you sure you are compiling -all- unit tests? Your compile output looks like you;re only compiling a single applications. Under Projects -> Build -> Build Steps, make sure that 'all' is ticked. Recompile all unit tests, run them, and if any of them still fail, please post the output files, as described here:

http://tudat.tudelft.nl/installation/troubleshooting/installationErrors.html#failed-unit-tests

Have a nice weekend,

Dominic

**Comment by DominicDirkx** [comment]
Hi Michele,

Thanks, the output does look different now: no unit tests are showing 'Not Run'. There's still something funny going on with the JSON interface though. It's probably due to teh fact that we've added some new features to the Tudat code, without fully extending the JSON interface accordingly.

For completeness: could you let me know which version of the code you're currently using?

Best,

Dominic

**Comment by mfacchinelli** [comment]
Hi Dominic, 

Ok I did it right this time (hopefully), and indeed all the tests are passed now! So, sorry for opening this non-issue, and thanks again for the help!

Kind regards, 

Michele

P.S.: I'm using the latest version of Tudat.

**Comment by DominicDirkx** [comment]
Happy to hear that all is working well :)
