### ISSUE TITLE
Eerror: : System Error: Permission denied

### ISSUE THREAD

**Issue by Jornopaulus** [Tudat/tudat#360]
I am trying to reinstal Tudat on my new laptop and I get the error : "-1: error: : System Error: Permission denied" . I noticed that my building directory was not properly specified, but I can't seem to find what the correct building directory is. Could you help me out?

kind regards,

Jorn Vanwesenbeeck

**Comment by Jornopaulus** [comment]
I dont know what I did wrong, but deleting all files and repositories and reinstalling them worked!

**Comment by DominicDirkx** [comment]
Ok, happy ot hear it :)
