### ISSUE TITLE
[Documentation] cspice with pagmo optimization

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#361]
Hello,

This is not an issue per se, however it would beneficial if this would be mentioned somewhere in the documentation.

If the pagmo problem is including cspice via the standard `spice_interface::loadStandardSpiceKernels( );`, the spice interface is re-included for each run. Each include will take up 4 kernels, and they are not closed after the run. There is a limit to the maximum amount of kernals that cspice will have open at the same time, which is 5300. This means that after 1325 runs the spice_interface will throw an error, stopping the optimisation.

The solution is to include cspice via the standard `spice_interface::loadStandardSpiceKernels( );` outside the problem, in the main file. This is very easy to do, if you know you should do that. Therefore, I think a paragraph about this inside the documentation would be very helpful.

Regards,
Julius

**Comment by DominicDirkx** [comment]
Hi Julius,

Indeed, this is a very good point. @ifodde , could you make a note to update the documentation?

Dominic
