### ISSUE TITLE
Ability to save dependent variables if aerodynamic accleration is absent

### ISSUE THREAD

**Issue by Palash-Patole** [Tudat/tudat#363]
Dear all developers,

During final assignment for the course: Propagation and Optimization in Astrodynamics, I have encountered an issue. I am not subjecting my vehicle to aerodynamic acceleration (being on Moon). However, I wish to save dependent variables such as latitude, longitude, flight path angle, altitude etc. I am unable to do that and as answered by Dominic on brightspace forum, this is indeed not possible in absence of aerodynamic acceleration during the propagation. Help rectify this issue in new update.

**Comment by DominicDirkx** [comment]
Dear Palash,

Preliminary code to do this has been pushed here:

https://github.com/DominicDirkx/tudat/tree/FlightConditionsSplit

There are no changes to the way in which dependent variables are saved. The changes have been made 'under the hood'. 

Best regards,

Dominic

**Comment by DominicDirkx** [comment]
Pull request has been opened: #379
