### ISSUE TITLE
POD

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#374]
How to display the time-tagged orbit data after performing the orbit estimation in TUDAT? In orbit propagation, the outputs are obtained using the following command:
**std::map< double, Eigen::VectorXd > integrationResult = dynamicsSimulator.getEquationsOfMotionNumericalSolution( );**
Is there an equivalent command that can be used in orbit estimation program?

**Comment by DominicDirkx** [comment]
Absolutely, the VariationalEquationsSolved object has a getDynamicsSimulator( ) function, from which you can call the getEquationsOfMotionNumericalSolution function. If this doesn;t answer your question, please post a link to the application you're working on, and let me know where exactly you want to save these data,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
I have one request and two questions:
1) Though I got the output, I want to make sure if I have implemented in the proper way. So, I have uploaded the 'earthOrbiterBasicStateEstimation.cpp' in the repository Pugazh1. Here is the link: https://github.com/Pugazhenthi-Sivasankar/Pugazh1
2) I noticed that in the 'variationalEquationsPropagatorExample.cpp' the parameter estimation happens, but there are no observations (simulated or real) within the script. How is that possible?
3) Is there a provision to implement the 'dependentVariablesToSave' in the orbit estimation program?

**Comment by DominicDirkx** [comment]
Hi Pugazh,

For your first point, you're going to have to be more specific:
- What is the information you want to get out of the simulations
- What are the simulation settings you have used
- What are the physical assumptions that you want to make
- Which steps  have you taken to verify the correct implementation of your application, and which aspects are you in doubt about

For the variationalEquationsPropagatorExample.cpp example, there is actually not estimation being done. The variational equations are propagated, but they are not used in the context of an estimation

For your final question, the short answer is 'I think so', but I don't know if anyone has ever tried it. To check, use the defineEstimationSettings function of the PodInput class, setting the saveStateHistoryForEachIteration input variable to true. This should make sure that dependent variables are kept after the estimation is done. You can retrieve them from the orbit determination manager -> variational eequations solver -> dynamics simulator. If this doesn't work out, open a separate issue requesting this feature, and explaining what you have already tried,

Have a nice weekend,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Thanks and your suggestion worked!! 
In the 'earthOrbiterBasicStateEstimation.cpp', the link ends were created according to the observables and the **observations were simulated and passed into the estimation function.** Now, how to pass 'position_observable' and 'velocity_observable' from an external file into the estimation process?

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Happy to hear that it works :) Concerning your question "how to pass 'position_observable' and 'velocity_observable' from an external file into the estimation process?" This would require you to create input files with your simulation settings, read those files, and define the settings in the code accordingly. The format of the files is up to you, but you may want to consider JSON files for this. When you have a clear list of required inputs and outputs, I can perhaps give some suggestions,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Since I don't know which of the formats are suitable, I have provided a csv format and json format of the input file:
[input_GRACE.zip](https://github.com/Tudat/tudat/files/1954646/input_GRACE.zip)
The input file consists of time in the first column, the position co-ordinates in the next three columns and the velocity co-ordinates in the last three columns. The list of outputs I need to estimate :
1) initial state of the satellite,
2) solar radiation pressure co-efficient,
3) drag co-efficient and 
4) estimation state history.

**Comment by Pugazhenthi-Sivasankar** [comment]
I would like to clarify that the position and the velocity co-ordinates mentioned in the 'input_GRACE.zip' are **not with respect to any ground station.** They are the GPS state vectors of the satellite in the ECEF (Earth Centered Earth Fixed) frame. Now, how to use the 'position_observable' and the 'velocity_observable' in this scenario?

**Comment by DominicDirkx** [comment]
The position_observable and velocity_observable do not use a ground station, but instead denote the inertial position w.r.t. the reference origin. Since your states are defined in ECEF, you'll have to transform them to ECI before using them as observables. Also, note that the time variable should be TT (or TDB).

**Comment by Pugazhenthi-Sivasankar** [comment]
I made the necessary modifications to the source file and tried to run it. There was no problem with compilation, but I got the following message as 'application output':
[Orbit_est_app_error.txt](https://github.com/Tudat/tudat/files/1959947/Orbit_est_app_error.txt)
I have uploaded the script in the following link for your reference:
https://github.com/Pugazhenthi-Sivasankar/Pugazh1

**Comment by DominicDirkx** [comment]
This could be any one of many different possible problems. Which operating system are you running it on?

Try getting a stack trace from the debugger:

http://tudat.tudelft.nl/tutorials/troubleshooting/debuggers.html

This will tell you in which function the problem is occurring,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
I used the debugger, but it didn't show any result. Here is a screenshot of the output:
![orb_est_debug_op](https://user-images.githubusercontent.com/25662615/39424501-54210d20-4c77-11e8-8bf3-11758a5734b7.jpg)
Please use the 'zoom in' option to view the image.

**Comment by DominicDirkx** [comment]
The window you want is called 'Stack' (or something similar). Under Window->Views, turn this window on.

If this is also empty, look under Tools->Options->Kit, select the kit your are using, and check what it says under 'debugger'

![image](https://user-images.githubusercontent.com/5039068/39427975-0d6689c8-4c86-11e8-85aa-f673d2eb88e3.png)

This is a screenshot from my Linux installation, yours will be different.

If this doesn't give you anything useful, you can:
- Run it on a unix-based system (Linux/Mac), on which using the debugger is much more straightforward
- Run reduced versions of your application, to find out which addition of functionality make it crash

**Comment by Pugazhenthi-Sivasankar** [comment]
This is a screen shot of my kit:
![debugger_version](https://user-images.githubusercontent.com/25662615/39467269-86eab7d6-4d2d-11e8-9a1e-7b4a9e78bc64.jpg)
Is the above debugger (GNU gdb...32 bit) not sufficient?

**Comment by DominicDirkx** [comment]
No, this should be fine. Do you get any output at all from the debugger? Have you checked the 'stack' window?

**Comment by Pugazhenthi-Sivasankar** [comment]
The 'stack' window was turned on and the following was the debug output:

_Debugging starts
Parameter start index, Parameter definition
0, translational state of (Vehicle).
6, radiation pressure coefficient of (Vehicle).
7, constant drag coefficient of (Vehicle).

Dependent variables being saved, output vectors contain: 
Vector entry, Vector contents
0, Single acceleration norm of type cannonball radiation pressure , acting on Vehicle, exerted by Sun
1, Single acceleration norm of type aerodynamic , acting on Vehicle, exerted by Earth
Warning, tabulated ephemeris is being reset using data at different precision

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error when computing position observable, associated link end must be observed_body 
Debugging has finished_

This is how I have defined the link ends for observations in the source file:

    _LinkEnds linkEnds;
    linkEnds[ observed_body ] = std::make_pair( "Vehicle", "" );
    std::map< ObservableType, std::vector< LinkEnds > > linkEndsPerObservable;
    linkEndsPerObservable[ position_observable ].push_back( linkEnds );
    linkEndsPerObservable[ velocity_observable ].push_back( linkEnds );_

Is there anything that I am missing or not defining properly?

**Comment by DominicDirkx** [comment]
Hi Pugazh,

The output:

what(): Error when computing position observable, associated link end must be observed_body

tells you what is going wrong. You can search in the code (Ctrl+Shift+f) to find where this error is being printed. In your case, the issue is, I think, in the lines:

measurementSimulationInput[ currentObservable ][ currentLinkEndsList.at( i ) ] =
                        std::make_pair( baseTimeList, receiver );

You are defining 'receiver' as the reference for your observations, which is not allowed for a position_observable.

**Comment by Pugazhenthi-Sivasankar** [comment]
I made the following changes and it worked:

            measurementSimulationInput[ currentObservable ][ currentLinkEndsList.at( i ) ] =
                        std::make_pair( baseTimeList, observed_body );

**Comment by DominicDirkx** [comment]
Good!
