### ISSUE TITLE
Unit test velocity observable

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#377]
Hello everyone!!
I included all the necessary files and folders associated with the 'velocity observable' and ran the unit test in the Qt creator. I got the following errors:
[Unit_test_velocity_error.txt](https://github.com/Tudat/tudat/files/1953353/Unit_test_velocity_error.txt)
How to rectify them?

**Comment by DominicDirkx** [comment]
Hi Pugazh,

We made some changes to the bias setting interfaces in the last month, and this branch had not yet been updated. I just pushed the corrections here:

https://github.com/DominicDirkx/tudat/tree/VelocityObservable
