### ISSUE TITLE
Interpolation Behavior When Independent Variable Out of Range

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#378]
Hi Dominic,

As discussed with Erwin, it would be nice if the user could specify what method the interpolators should apply in case the independent variable is outside the range specified by the user. As Erwin suggested, there should be three modes to choose from: throw exception (default), extrapolation and using the closest available value.

Let me know if and where I can help. 

Thank you!

Kind regards, 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

I was just playing around with the code, and it turns out it was not that difficult (I think). I've written something, and pushed it here:

https://github.com/DominicDirkx/tudat/tree/BoundaryInterpolation

I have not yet added any tests, though, so there's a good chance it's not entirely correct yet. I have not added the link with InterpolatorSettings, but I first wanted to check if all unit tests are still passing (which they are). I have added an extra option, which is now the default:

- Give a warning if beyond the boundary, _and_ extrapolate

This choice is mostly inspired by not wanting to change any of the existing functionality though :)

Dominic

**Comment by DominicDirkx** [comment]
Hi Michele,

Yes, indeed. I'll let you know if I've done a bit more testing.

Dominic

**Comment by mfacchinelli** [comment]
Hi Dominic, 

Thanks for that! I added a unit test for the cubic spline, but I noticed that MATLAB gives different results when extrapolating with the `spline` method. 

I also added boundary handling for the multi-linear interpolator, including a unit test. It seems to be working, but I have no real way of checking the extrapolation results, since MATLAB does not extrapolate when multiple dimensions are used.

**Comment by mfacchinelli** [comment]
Hi Dominic, 

Since the interpolation of the multi-linear array is recursive, I translated the main part of the code (the function `performRecursiveInterpolationStep`) to MATLAB, and checked the results this way (the results match). But I am not sure this is a very good method.

**Comment by DominicDirkx** [comment]
Hi Michele,

This type of testing is a bit 'dodgy': if there is an error in the Tudat code, it will also be in the Matlab code. However, the Tudat code is tested properly for cases where no extrapolation is done. So, the key question is:

- Assuming that the _inter_polation works correctly, does your test verify that the _extra_polation is done correctly?

One possible additional test would be to create the multi-linear interpolator with a single independent variable (I think this should work), and compare it to the linear interpolator: the two should be identical.

**Comment by mfacchinelli** [comment]
Hi Dominic,

That was a good idea :) I added it to the unit tests and the values do indeed match. Thank you!

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I was trying to add a new method for out-of-bound interpolation, i.e. extrapolation, such that the interpolator would output a user-defined value. However, I have problems with setting a default value, since it has to be flexible and match the `DependentVariableType`. Is there a zero or NaN in C++ that can take multiple forms?

If not, I don't really need this feature, and one can get the same result by 'padding' e.g. the tabulated atmosphere with zeros or NaNs after the last available altitude. 

Thank you.

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

There would be a nice generic way to do this, using template specialization. However, the way it's usually done now (example taken from Lagrange interpolator) is:

zeroEntry_ = dependentVariables[ 0 ] - dependentVariables[ 0 ];

which will make zeroEntry_ equal to 0 (or a vector/matrix of zeroes), _except_ if dependentVariables[ 0 ] is NaN,

Dominic

**Comment by mfacchinelli** [comment]
Hey Dominic, 

The method you suggested, I wasn't sure would work, since the default extrapolation value would need to be defined in the input arguments of the interpolating functions. So, instead, I created a new class called `AdditionIdentity` (which you can find [here](https://github.com/mfacchinelli/tudat/blob/extrapolationDefaultValue/Tudat/Basics/additionIdentities.h)), which gives the zero value for the type specified in the template. I am not sure it's a very elegant way, also, I don't know if it works :p I am testing it now. 

I will keep you updated.

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

Great, I've always been to lazy to do this :) It looks like it should work. It is not necessary to have a class for this, though. Free functions can also be templated, so:

template< typename VariableType >
VariableType getZeroValue( );

template< >
int getZeroValue< int >( )
{
    return 0;
}

and so on (I think),

Dominic

**Comment by mfacchinelli** [comment]
I tried that, but it gave me some errors. Right now it works, so I'll keep it for now :) I will update it at some point, though

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I have just pushed some code to:
https://github.com/mfacchinelli/tudat/tree/multiDimensionalInterpolator
where I simply added a new interface class between `Interpolator` and `MultiLinearInterpolator`, called `MultiDimensionalInterpolator`, such that if someone wanted to add more multi-dimensional interpolators (e.g., the cubic spline we discusses somewhere, some time ago), it should be easier.

One weird thing I encountered, is that when assigning the dependent variables to the variable `dependentData_` (which is a private member of `MultiDimensionalInterpolator`), I first have to resize the `boost::multi_array`. Well, ok, it's not so weird, but for the vectors, the resizing seems to be automatic. So right now I added a line for resizing, based on [this](https://stackoverflow.com/questions/30085357/resizing-boostmulti-array-to-match-another?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) StackOverflow post (which you can find in the code [here](https://github.com/mfacchinelli/tudat/blob/9058eede3a1cb52f7a8ceb572d184caac8ea7f96/Tudat/Mathematics/Interpolators/multiLinearInterpolator.h#L96)). If you have encountered the same problem before, did you use some other way of doing this, or is this method fine? 

By the way, the unit tests on multi-linear interpolation are all passed. 

Thank you and kind regards, 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

Again, very nice work! It's been a while since I did anything with multi_arrays, so I', not sure how to do this differently. If it works: good :)

Dominic

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I'm reopening this issue as well, based on what you told me in the meeting we had on Monday, regarding the `MultiDimensionalInterpolator` class (so the class between the base `Interpolator` class and the multi-dimensional interpolators (MDI), such as the multi-linear one). 

The reason why I added it is because in this way, if someone does add another MDI, there would be no need to copy-paste the two functions `checkBoundaryCase( )` and `checkInterpolationBoundary( )` inside the new class. Instead they just use the ones already included in the base class for MDIs. 

Let me know what you think about this, as well,

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

Sounds good, this is indeed a good reason to have extra base class,

Dominic
