### ISSUE TITLE
Request to create a multi-arc estimation module

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#381]
Dear all,
             I am making use of the orbit estimation program to estimate the solar radiation pressure co-efficient (Cr) and drag co-efficient (Cd) of satellites. Currently, only single-arc estimation modules are available in TUDAT. I would like to have a module that is capable of multi-arc estimation. Thank you!!

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Ok, I will make the time in the coming weeks to add these features. I will let you know once it's finished, and before the unit tests are done, which will probably take a bit longer,

Dominic
