### ISSUE TITLE
Attitude data in estimation module

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#382]
Hello everyone! I am using the estimation module of TUDAT to obtain the drag co-efficient (Cd) and solar radiation pressure co-efficient (Cr) of satellites. I would like to know how to use the attitude data of the satellites in the TUDAT estimation modules to get better estimates of Cr and Cd.

**Comment by DominicDirkx** [comment]
Hi Pugazh,

I cannot answer this question without knowing the (type of) mathematical model that you would like to use. I'm happy to provide input on the use of Tudat, but this question is well beyond this scope.

**Comment by Pugazhenthi-Sivasankar** [comment]
I can shed more light on this once I get the attitude data of the satellites.
