### ISSUE TITLE
Rotational model settings

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#383]
In the 'earthOrbiterBasicStateEstimation.cpp', the following block of code appears:

bodySettings[ "Earth" ]->rotationModelSettings = boost::make_shared< SimpleRotationModelSettings >(
                 "ECLIPJ2000", "IAU_Earth",
                 spice_interface::computeRotationQuaternionBetweenFrames(
                     "ECLIPJ2000", "IAU_Earth", initialEphemerisTime ),
                 initialEphemerisTime, 2.0 * mathematical_constants::PI /
                 ( physical_constants::JULIAN_DAY ) );

In the tutorials, it is explained that the above modifications were done so that the rotational properties of Earth could be estimated. However, such properties are not estimated in the program. So, is it necessary to retain the above block or can I change it to the following ?:

    bodySettings[ "Earth" ]->ephemerisSettings->resetFrameOrientation( "J2000" );
    bodySettings[ "Earth" ]->rotationModelSettings->resetOriginalFrame( "J2000" );

**Comment by DominicDirkx** [comment]
For these kinds of questions first:

- Try the modification (like the one you propose above), and see if it works
- If it doesn't work, see if there's error output/debugger output, and use that to find the problem
- If you get stuck there, post an issue here, giving a clear explanation of what you changed, with a link to the code on Github, and compiler/run errors (if any).
