### ISSUE TITLE
Altering the POD input

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#386]
Hello everyone!! After reading the file 'input_GRACE.csv' into the 'earthOrbiterBasicStateEstimation.cpp', I am trying to pass it as input to the estimation process. From the script, I understand that it needs to be passed instead of the map 'observationsAndTimes' in the following lines:

    boost::shared_ptr< PodInput< double, double > > podInput =
            boost::make_shared< PodInput< double, double > >(
                observationsAndTimes, initialParameterEstimate.rows( ),
                Eigen::MatrixXd::Zero( truthParameters.rows( ), truthParameters.rows( ) ),
                initialParameterEstimate - truthParameters );

To do so, I wanted to see the structure and contents of the map 'observationsAndTimes' so that I can modify the file 'input_GRACE.csv'. However, I was not able to view the contents of 'observationsAndTimes' by using the following lines:

    input_output::writeDataMapToTextFile( observationsAndTimes,
                                          "PODinput.dat",
                                          tudat_applications::getOutputPath( ) + outputSubFolder,
                                          "",
                                          std::numeric_limits< double >::digits10,
                                          std::numeric_limits< double >::digits10,
                                          "," );

I got the following error:
[input_file_err1.txt](https://github.com/Tudat/tudat/files/1998011/input_file_err1.txt)

Now, what changes should be made to pass 'input_GRACE.csv' as input to the estimation process? For your reference, I have included the file 'input_GRACE.csv' in the link below:
https://github.com/Pugazhenthi-Sivasankar/Pugazh1

**Comment by DominicDirkx** [comment]
hi Pugazh,  

The observationsAndTimes is a rather complicated thing, which we should really get aroung to restructuring.  The full structure is defined by the following typedefs:

    //! Typedef of vector of observations of a single type
    typedef Eigen::Matrix< ObservationScalarType, Eigen::Dynamic, 1 > ObservationVectorType;

```
    //! Typedef of map of pairs (observation vector and pair (vector of associated times reference link end)), link ends
    //! as map key
    typedef std::map< observation_models::LinkEnds, std::pair< ObservationVectorType,
    std::pair< std::vector< TimeType >, observation_models::LinkEndType > > > SingleObservablePodInputType;

        //! List of SingleObservablePodInputType per observation type
    typedef std::map< observation_models::ObservableType, SingleObservablePodInputType > PodInputDataType;
```
Written out, it's a (omitting the namespaces and assuming doubles for state and time):

map< ObservableType, map< LinkEnds, pair< VectorXd, pair< vector< double >, LinkEndType > > > >


The two map keys ObservableType and LinkEnds allow you to store observations for any set of observables and link ends, in the form of:

pair< VectorXd, pair< vector< double >, LinkEndType > >

The VectorXd represents the vector of observations, vector< double > the list of associated observation times, and LinkEndType the link end associated with this list if times.

I suggest you start with a single observable type, a single set of link ends, and a short list of observations/observation times, and work your way up from there,

Have a nice weekend,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
I made modifications based on the information you had provided and got the following compilation error:
[input_file_err2.txt](https://github.com/Tudat/tudat/files/2005322/input_file_err2.txt)
For your reference, I have included the modified source code and the input files (test_input_time.txt and test_input_pos.txt) in the link below:
https://github.com/Pugazhenthi-Sivasankar/Pugazh1
I was able to read the file into the program. However, I faced problems when I tried to pass it as input to the estimation program.

**Comment by DominicDirkx** [comment]
Hi Pugazh,

If you can post the details we discussed yesterday, I will have a look,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
After taking the files 'test_input_time.txt' and 'test_input_pos.txt' into the program, I made changes in the following lines:

 /*   // Define time of first observation
    double observationTimeStart = initialEphemerisTime + 1000.0;

    // Define time between two observations
    double  observationInterval = 20.0;

    // Simulate observations for 3 days
    std::vector< double > baseTimeList;
    for( unsigned int i = 0; i < 1; i++ )
    {
        // Simulate 500 observations per day (observationInterval apart)
        for( unsigned int j = 0; j < 5; j++ )
        {
            baseTimeList.push_back( observationTimeStart + static_cast< double >( i ) * 86400.0 + static_cast< double >( j ) * observationInterval );
        }
    }

    // Create measurement simulation input
    std::map< ObservableType, std::map< LinkEnds, std::pair< std::vector< double >, LinkEndType > > > measurementSimulationInput; */

    for( std::map< ObservableType, std::vector< LinkEnds > >::iterator linkEndIterator = linkEndsPerObservable.begin( );
         linkEndIterator != linkEndsPerObservable.end( ); linkEndIterator++ )
    {
        // Define observable type and link ends
        ObservableType currentObservable = linkEndIterator->first;
        std::vector< LinkEnds > currentLinkEndsList = linkEndIterator->second;

     /*   // Define observation times and reference link ends
        for( unsigned int i = 0; i < currentLinkEndsList.size( ); i++ )
        {
            measurementSimulationInput[ currentObservable ][ currentLinkEndsList.at( i ) ] =
                        std::make_pair( baseTimeList, observed_body );
        }
    }  */

    // Set typedefs for input (observation types, observation link ends, observation values, associated times with reference
    // link ends.
    typedef Eigen::Matrix< double, Eigen::Dynamic, 1 > ObservationVectorType;
    typedef std::map< LinkEnds, std::pair< ObservationVectorType, std::pair< std::vector< double >, LinkEndType > > >
            SingleObservablePodInputType;
    typedef std::map< ObservableType, SingleObservablePodInputType > PodInputDataType;

    ObservationVectorType GRACE_pos = tudat::input_output::readMatrixFromFile( cppFolder + "test_input_pos.txt" );
    std::cout<<GRACE_pos(10,0)<<std::endl;

    SingleObservablePodInputType InputData[ linkEnds ] = std::make_pair( GRACE_pos, std::make_pair( GRACE_time, observed_body ) );

    PodInputDataType observationsAndTimes[ position_observable ] = InputData;
    // Simulate observations
   // PodInputDataType observationsAndTimes = simulateObservations< double, double >(
     //           measurementSimulationInput, orbitDeterminationManager.getObservationSimulators( ) );

I got the compilation errors as mentioned in the file 'input_file_err2.txt'.

**Comment by DominicDirkx** [comment]
Hi Pugazh,

I think the problem is that your variable:

GRACE_time

is a VectorXd. The list of times should be a vector< double > instead (see my previous post),

Best,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Hello Dominic,
I made the conversion as follows:

    Eigen::VectorXd GRACE_time_0 =
           tudat::input_output::readMatrixFromFile( cppFolder + "test_input_time.txt" );

    std::vector< double > GRACE_time(GRACE_time_0.size()) ;
    Eigen::Map<Eigen::VectorXd>(GRACE_time.data(), GRACE_time_0.rows(), GRACE_time_0.cols()) = GRACE_time_0;

Though it worked, I got issues in the following lines:

    SingleObservablePodInputType InputData[ linkEnds[ observed_body ] ] = std::make_pair( GRACE_pos, std::make_pair( GRACE_time, observed_body ) );

    PodInputDataType observationsAndTimes[ position_observable ] = InputData;

The compilation errors are given in the file below:
[input_file_err3.txt](https://github.com/Tudat/tudat/files/2012703/input_file_err3.txt)

**Comment by DominicDirkx** [comment]
Try:

SingleObservablePodInputType InputData;
InputData[ linkEnds[ observed_body ] ] = std::make_pair( GRACE_pos, std::make_pair( GRACE_time, observed_body ) );

PodInputDataType observationsAndTimes;
observationsAndTimes[ position_observable ] = InputData;

**Comment by Pugazhenthi-Sivasankar** [comment]
I tried it and the issues were reduced. However, there is an issue in the following line:

  InputData[ linkEnds[ observed_body ]  ] = std::make_pair( GRACE_pos, std::make_pair( GRACE_time, observed_body ) );

The compilation errors are given in the file below:
[input_file_err4.txt](https://github.com/Tudat/tudat/files/2012861/input_file_err4.txt)

**Comment by DominicDirkx** [comment]
[ linkEnds[ observed_body ] ]  should be [ linkEnds ].

have a look at the exact definition of the variable InputData, and check entry by entry of if it is correct.

**Comment by Pugazhenthi-Sivasankar** [comment]
Thanks!! I got it!
Regarding the reference frame origin and orientation, when I made the following changes,

/*    bodySettings[ "Earth" ]->rotationModelSettings = boost::make_shared< SimpleRotationModelSettings >(
                    "ECLIPJ2000", "IAU_Earth",
                    spice_interface::computeRotationQuaternionBetweenFrames(
                        "ECLIPJ2000", "IAU_Earth", initialEphemerisTime ),
                    initialEphemerisTime, 2.0 * mathematical_constants::PI /
                    ( physical_constants::JULIAN_DAY ) ); */

the program (earthOrbiterBasicStateEstimation.cpp) ran without any errors. However, when I made the following changes, 

/*    bodyMap[ "Vehicle" ]->setEphemeris( boost::make_shared< TabulatedCartesianEphemeris< > >(
                                            boost::shared_ptr< interpolators::OneDimensionalInterpolator
                                            < double, Eigen::Vector6d > >( ), "Earth", "ECLIPJ2000" ) ); */

I got the following error: 
[Ref_frame_err1.txt](https://github.com/Tudat/tudat/files/2017156/Ref_frame_err1.txt)

Then, I removed the comment marks from the above lines and did the following changes:

    bodyMap[ "Vehicle" ]->setEphemeris( boost::make_shared< TabulatedCartesianEphemeris< > >(
                                            boost::shared_ptr< interpolators::OneDimensionalInterpolator
                                            < double, Eigen::Vector6d > >( ), "Earth", "J2000" ) );

    setGlobalFrameBodyEphemerides( bodyMap, "SSB", "ECLIPJ2000" ); 

Upon running and debugging, I got the following message:
[Ref_frame_err2.txt](https://github.com/Tudat/tudat/files/2017215/Ref_frame_err2.txt)

Next, I made the following changes:

bodyMap[ "Vehicle" ]->setEphemeris( boost::make_shared< TabulatedCartesianEphemeris< > >(
                                            boost::shared_ptr< interpolators::OneDimensionalInterpolator
                                            < double, Eigen::Vector6d > >( ), "Earth", "J2000" ) );

    setGlobalFrameBodyEphemerides( bodyMap, "SSB", "J2000" );

Upon running and debugging, I got the following message:
[Ref_frame_err3.txt](https://github.com/Tudat/tudat/files/2017290/Ref_frame_err3.txt)
 
Either, I need to know how to run the program using Earth Centered Inertial (ECI) reference frame or how to convert the data and the associated time from Earth Centered Earth Fixed (ECEF) frame to the SSB.

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Since there's no error output, I don't know why the program is crashing. You can define the states in the environment w.r.t. the Earth by using:

setGlobalFrameBodyEphemerides( bodyMap, "Earth", "J2000" );

The ECI<->ECEF transformation can be done using the Earth's rotational ephemeris. Depending on teh accuracy you need, you may need to use a high-accuracy rotation model.

**Comment by Pugazhenthi-Sivasankar** [comment]
I made the modifications you had suggested and got the following error output:
[Ref_frame_err4.txt](https://github.com/Tudat/tudat/files/2023512/Ref_frame_err4.txt)

**Comment by Pugazhenthi-Sivasankar** [comment]
I also found a minor error in the TUDAT wiki page. The following piece of instruction appears in the page: http://tudat.tudelft.nl/tutorials/tudatFeatures/astroTools/framestateTransformations.html?highlight=conversion

the inverse rotation is done as follows:

NamedBodyMap bodyMap = ...
double currentTime = ...
Eigen::Vector6d bodyFixedState = ...
Eigen::Vector6d inertialState = transformStateToGlobalFrame( inertialState, bodyFixedState, bodyMap.at( "Earth" )->getRotationalEphemeris( ) );

When I ran this, it produced a compilation error without even mentioning the line number of the error source. Then, I figure out that it should be as follows:

NamedBodyMap bodyMap = ...
double currentTime = ...
Eigen::Vector6d bodyFixedState = ...
Eigen::Vector6d inertialState = transformStateToGlobalFrame( bodyFixedState, currentTime, bodyMap.at( "Earth" )->getRotationalEphemeris( ) );

Please make this correction as it would help other students!!

**Comment by DominicDirkx** [comment]
Thanks for picking this up! @ifodde : could you update the wiki in a future commit?

**Comment by Pugazhenthi-Sivasankar** [comment]
According to the explanation provided in the application walkthroughs, the following block of code is to perturb the 'parameters to be estimated' a bit, since the simulated observations are noise free:

    // Perturb parameter estimate
    Eigen::Matrix< double, Eigen::Dynamic, 1 > initialParameterEstimate =
            parametersToEstimate->template getFullParameterValues< double >( );
    Eigen::Matrix< double, Eigen::Dynamic, 1 > truthParameters = initialParameterEstimate;
    Eigen::Matrix< double, Eigen::Dynamic, 1 > parameterPerturbation =
            Eigen::Matrix< double, Eigen::Dynamic, 1 >::Zero( truthParameters.rows( ) );
    parameterPerturbation.segment( 0, 3 ) = Eigen::Vector3d::Constant( 10.0 );
    //parameterPerturbation.segment( 0, 2 ) = Eigen::Vector3d::Constant( 10.0 );
    parameterPerturbation.segment( 3, 3 ) = Eigen::Vector3d::Constant( 1.0E-2 );
    //parameterPerturbation.segment( 3, 5 ) = Eigen::Vector3d::Constant( 1.0E-2 );
    parameterPerturbation( 6 ) = 0.01;
    parameterPerturbation( 7 ) = 0.01;
    initialParameterEstimate += parameterPerturbation;

    // Define estimation input
    boost::shared_ptr< PodInput< double, double > > podInput =
            boost::make_shared< PodInput< double, double > >(
                observationsAndTimes, initialParameterEstimate.rows( ),
                Eigen::MatrixXd::Zero( truthParameters.rows( ), truthParameters.rows( ) ),
                initialParameterEstimate - truthParameters );

Now, what modifications are required for using the real data as input?

**Comment by DominicDirkx** [comment]
Hi Pugazh,

This is a question that you should first think about yourself: the real data should replace the simulated data. Go through the code and documentation and form a plan on how to do this. Try things out, and reopen this issue if you truly get stuck. Make a clear overview of what you tried, why you tried it, what didn't work, what you want to achieve, etc..

Best,

Dominic

p.s. For at least the next 1-2 weeks, I will only be available in a reduced capacity.
