### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by FloorMelman** [Tudat/tudat#387]
**I currently have a error in building the libraries. There is nog LastTest.log file yet on my computer. The problem seems to originate because there is not enough memory. Is this referring to RAM or storage memory? The compile output lists the following:**

[ 90%] Building CXX object tudat/Tudat/Astrodynamics/OrbitDetermination/CMakeFiles/test_EstimationFromPositionDoubleLongDouble.dir/UnitTests/unitTestEstimationFromIdealDataDoubleLongDouble.cpp.obj

cc1plus.exe: out of memory allocating 8388572 bytes
tudat\Tudat\Astrodynamics\OrbitDetermination\CMakeFiles\test_EstimationFromPositionDoubleLongDouble.dir\build.make:62: recipe for target 'tudat/Tudat/Astrodynamics/OrbitDetermination/CMakeFiles/test_EstimationFromPositionDoubleLongDouble.dir/UnitTests/unitTestEstimationFromIdealDataDoubleLongDouble.cpp.obj' failed
mingw32-make.exe[2]: *** [tudat/Tudat/Astrodynamics/OrbitDetermination/CMakeFiles/test_EstimationFromPositionDoubleLongDouble.dir/UnitTests/unitTestEstimationFromIdealDataDoubleLongDouble.cpp.obj] Error 1
CMakeFiles\Makefile2:4553: recipe for target 'tudat/Tudat/Astrodynamics/OrbitDetermination/CMakeFiles/test_EstimationFromPositionDoubleLongDouble.dir/all' failed
mingw32-make.exe[1]: *** [tudat/Tudat/Astrodynamics/OrbitDetermination/CMakeFiles/test_EstimationFromPositionDoubleLongDouble.dir/all] Error 2
Makefile:139: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
12:41:57: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
12:41:57: Elapsed time: 3:02:41.

**Comment by DominicDirkx** [comment]
Hi Floor,

See this page:

http://tudat.tudelft.nl/installation/troubleshooting/installationErrors.html#compilation-linking-of-code

Entry: Error "out of memory allocating XXXX bytes"

I think this will fix your problem,

Dominic

**Comment by FloorMelman** [comment]
**Is it necessary to remove the build-tudatBundle_Desktop-Default folder when building again? This as I changed the proposed COMPILE_HIGH_ACCURACY_ESTIMATION_TESTS to OFF in the file CMakeChache.txt. However this gives rise to new error at lower building percentages.** 

mingw32-make.exe[2]: *** [C:/tudatBundle/tudatBundle/tudat/bin/unit_tests/test_TabulatedAtmosphere.exe] Error 1
mingw32-make.exe[1]: *** [tudat/Tudat/Astrodynamics/Aerodynamics/CMakeFiles/test_TabulatedAtmosphere.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
14:05:44: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
14:05:44: Elapsed time: 26:39.

**Comment by DominicDirkx** [comment]
Could you post the full compile output in a file?

**Comment by FloorMelman** [comment]
After a couple of tries it worked finally. All unit tests are passed thus I am good to go!
