### ISSUE TITLE
Undefined reference to ...

### ISSUE THREAD

**Issue by FloorMelman** [Tudat/tudat#388]
**I am currently creating a new application within Tudat. To check whether the setup works I just copied example program (inner solar system) into a file (thesis.cpp). However, no matter what I get the same error every time:**
 (undefined reference to tudat::root_finders::doesRootFinderRequireDerivatives(boost::shared_ptr<tudat::root_finders::RootFinderSettings>)

**Furthermore I changed all requirsted parameters in both top level and application folder CMake files. I tried different programs but they all give the same error (the example applications work though). The newest version of my application folder is available on my github account.**

**Comment by FloorMelman** [comment]
**Compile Output**

14:44:37: Running steps for project TudatBundle...
14:44:37: Starting: "C:\Program Files (x86)\CMake\bin\cmake.exe" --build . --target application_thesis
[  1%] Built target tudat_simulation_setup
[  2%] Built target tudat_gravitation
[  2%] Built target tudat_mission_segments
[ 10%] Built target sofa
[ 10%] Built target nrlmsise00
[ 11%] Built target tudat_reference_frames
[ 11%] Built target tudat_aerodynamics
[ 12%] Built target tudat_basic_astrodynamics
[ 96%] Built target cspice
[ 96%] Built target tudat_ephemerides
[ 97%] Built target tudat_electro_magnetism
[ 97%] Built target tudat_propagators
[ 97%] Built target tudat_relativity
[ 97%] Built target tudat_propulsion
[ 97%] Built target tudat_ground_stations
[ 98%] Built target tudat_system_models
[ 98%] Built target tudat_earth_orientation
[ 98%] Built target tudat_basic_mathematics
[ 98%] Built target tudat_geometric_shapes
[100%] Built target tudat_input_output
[100%] Built target tudat_basics
[100%] Built target tudat_statistics
[100%] Built target tudat_spice_interface
[100%] Built target tudat_sofa_interface
[100%] Built target tudat_numerical_integrators
[100%] Linking CXX executable C:\tudatBundle\tudatBundle\tudatApplications\Thesis\bin\applications\application_thesis.exe
C:/tudatBundle/tudatBundle/tudat/lib/libtudat_simulation_setup.a(propagationTermination.cpp.obj):propagationTermination.cpp:(.text$_ZN5boost11make_sharedIN5tudat11propagators50SingleVariableLimitPropagationTerminationConditionEJRNS_10shared_ptrINS2_35SingleDependentVariableSaveSettingsEEERNS_8functionIFdvEEERdRbSD_RNS4_INS1_12root_finders18RootFinderSettingsEEEEEENS_6detail15sp_if_not_arrayIT_E4typeEDpOT0_[__ZN5boost11make_sharedIN5tudat11propagators50SingleVariableLimitPropagationTerminationConditionEJRNS_10shared_ptrINS2_35SingleDependentVariableSaveSettingsEEERNS_8functionIFdvEEERdRbSD_RNS4_INS1_12root_finders18RootFinderSettingsEEEEEENS_6detail15sp_if_not_arrayIT_E4typeEDpOT0_]+0x203): undefined reference to `tudat::root_finders::doesRootFinderRequireDerivatives(boost::shared_ptr<tudat::root_finders::RootFinderSettings>)'
collect2.exe: error: ld returned 1 exit status
tudatApplications\thesis\Thesis\CMakeFiles\application_thesis.dir\build.make:120: recipe for target 'C:/tudatBundle/tudatBundle/tudatApplications/Thesis/bin/applications/application_thesis.exe' failed
CMakeFiles\Makefile2:14071: recipe for target 'tudatApplications/thesis/Thesis/CMakeFiles/application_thesis.dir/all' failed
CMakeFiles\Makefile2:14083: recipe for target 'tudatApplications/thesis/Thesis/CMakeFiles/application_thesis.dir/rule' failed
Makefile:3593: recipe for target 'application_thesis' failed
mingw32-make.exe[3]: *** [C:/tudatBundle/tudatBundle/tudatApplications/Thesis/bin/applications/application_thesis.exe] Error 1
mingw32-make.exe[2]: *** [tudatApplications/thesis/Thesis/CMakeFiles/application_thesis.dir/all] Error 2
mingw32-make.exe[1]: *** [tudatApplications/thesis/Thesis/CMakeFiles/application_thesis.dir/rule] Error 2
mingw32-make.exe: *** [application_thesis] Error 2
14:45:03: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
14:45:03: Elapsed time: 00:26.

**Comment by DominicDirkx** [comment]
Hi Floor,

It looks like you're using an outdated version of a CMakeLists.txt file. Specifically, your definition of the TUDAT_APPLICATION_PROPAGATION_LIBRARIES and TUDAT_APPLICATION_ESTIMATION_LIBRARIES seem to be off. If you copy the lines:

list(APPEND TUDAT_APPLICATION_PROPAGATION_LIBRARIES tudat_simulation_setup tudat_ground_stations tudat_propagators
    tudat_aerodynamics tudat_system_models tudat_geometric_shapes tudat_relativity tudat_gravitation tudat_mission_segments
    tudat_electro_magnetism tudat_propulsion tudat_ephemerides ${TUDAT_APPLICATION_ITRS_LIBRARIES} tudat_numerical_integrators tudat_reference_frames
     tudat_statistics tudat_propagators ${TUDAT_APPLICATION_EXTERNAL_INTERFACE_LIBRARIES} tudat_basic_astrodynamics tudat_basic_mathematics
     tudat_root_finders tudat_input_output tudat_basics ${TUDAT_APPLICATION_EXTERNAL_LIBRARIES})

list(APPEND TUDAT_APPLICATION_ESTIMATION_LIBRARIES tudat_simulation_setup tudat_observation_models tudat_ground_stations
    tudat_torque_partials tudat_acceleration_partials
    tudat_observation_partials tudat_estimatable_parameters tudat_orbit_determination  tudat_propagators
    tudat_aerodynamics tudat_system_models tudat_geometric_shapes tudat_relativity tudat_gravitation tudat_mission_segments
    tudat_electro_magnetism tudat_propulsion tudat_ephemerides ${TUDAT_APPLICATION_ITRS_LIBRARIES} tudat_numerical_integrators tudat_reference_frames
    tudat_statistics tudat_propagators ${TUDAT_APPLICATION_EXTERNAL_INTERFACE_LIBRARIES} tudat_basic_astrodynamics tudat_basic_mathematics
    tudat_root_finders tudat_input_output tudat_basics ${TUDAT_APPLICATION_EXTERNAL_LIBRARIES})

to replace the old lines in your CMakeLists.txt for your application, it should work,

Dominic

**Comment by DominicDirkx** [comment]
@ifodde : could you update the CMakeLists of the templateApplication to be compatible with the latest code (see above)?

**Comment by DominicDirkx** [comment]
Changes addressed in:

**https://github.com/Tudat/tudatExampleApplications/pull/23**
