### ISSUE TITLE
StateDerivativeModels are being removed 2017-01-01

### ISSUE THREAD

**Issue by magnific0** [Tudat/tudat#39]
This is a notice that  Tudat/Astrodynamics/StateDerivativeModels and all it's contents are currently deprecated. Users are adviced to checkout the new Tudat/Astrodynamics/Propagators. Propagators does everything StateDerivativeModels provided and much much more. See the tudatExampleApplications on how it is used if you have old code that needs to be ported.

As long as this issue is open it means the old code is still part of Tudat master. The code will be removed on 2017-01-01. If you see this issue open past this date, feel free to issue a pull request to delete the code or notify us.

**Comment by DominicDirkx** [comment]
StateDerivativeModel folder has been removed (Issue #118).
