### ISSUE TITLE
Addition of Kalman Filters

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#390]
Hi Dominic,

I have stated adding Kalman filters to Tudat, which I will need during my thesis. The implementation is going well, but I have a few questions (these are not really a priority, so it is not important if I have a late answer). I have stated with the linear and extended filters, and will soon start on the unscented one. You can find the code here:
https://github.com/mfacchinelli/tudat/tree/kalmanFilter

The first question is about the integrator. Now the user has to input the integration settings, which are then used to create an integrator for the state. However, the state derivative function may also have a control vector as input, and not only time and state. The integrators, though, only accept a state derivative function that only depends on two parameters (i.e., time and state). For now, I am using a workaround, so I just multiply the state derivative by the time step, but it would be more elegant (and flexible) if one would use the integrator settings. Is there a simple solution to this, or would the integrators need to be slightly changed?
I don't really need the control vector for now, so it's not a big issue. I had tried something else before forcing the integration inside the Kalman filter class, which was to replace one of the inputs of the state derivative with a constant `Eigen::Vector::Zero( )` of the correct size, such that only two inputs are actually needed, but it would give me many errors. 

The second problem is how to test the implementations. I have found some C++ adaptation of the filters, and I am using them to verify the implementation. Also, I am using a MATLAB version of the EKF, but the results are always slightly different, especially for the second element x<sub>2</sub> (however, if I let the simulation run for longer, the two converge). In the figure you can see the comparison of the C++ and MATLAB implementations. 
![untitled](https://user-images.githubusercontent.com/19731497/40623868-7cd25614-62a9-11e8-9a7d-f68b08a11f99.jpg)
Do you have any recommendations or ideas on how else to test it? 

Thank you!

Kind regards, 

Michele

**Comment by Pugazhenthi-Sivasankar** [comment]
It is interesting to know that you are working on implementing Kalman filter in TUDAT. Is it possible to have a meeting with you to discuss more about it?

**Comment by mfacchinelli** [comment]
Hi :) Yes, of course. If you study in the faculty, you can find me virtually everyday in room 10.10 (in the flex spaces of the 10th floor). If you want, you can drop by now
