### ISSUE TITLE
Request - Add functionality to save different kinds of direct tidal accelerations

### ISSUE THREAD

**Issue by FloorMelman** [Tudat/tudat#393]
**Request**
_For my current research I require to model the tidal acclerations due both_

- _Tidal accelerations caused by the tidal deformation of the planet_
- _Tidal accelerations caused by the tidal deformation of the satellite_

_This is possible, however, it is not possible to save both accelerations independently. Moreover, an error is returned when attempting to save both accelerations as the type direct_tidal_dissipation_acceleration_

To this end, a possibility to save both accelerations independently is desired. 

Thanks in advance.

**Comment by DominicDirkx** [comment]
Hi Floor,

I've pushed the required modifications to this branch:

https://github.com/DominicDirkx/tudat/tree/SaveDissipationAccelerations

What I've done is remove the 

direct_tidal_dissipation_acceleration

acceleration identifier, and replaced it with the following two:

direct_tidal_dissipation_in_central_body_acceleration
direct_tidal_dissipation_in_orbiting_body_acceleration

You should now be able to use these to save both accelerations separately. 

Let me know if this works correctly for you,

Dominic

**Comment by FloorMelman** [comment]
It works correctly for me, thanks again!
