### ISSUE TITLE
Reference to non existent repository RLovelett

### ISSUE THREAD

**Issue by FloorMelman** [Tudat/tudat#401]
As discussed, I open an issue  regarding non-existent repository which is required when  initiating and fetching submodules in terminal environment. 

Change

[submodule "eigen"]
path = eigen
url = https://github.com/RLovelett/eigen.git

To

[submodule "eigen"]
path = eigen
url = https://github.com/tudat/eigen.git

**Comment by DominicDirkx** [comment]
Has been pushed to tudatBundle repository.
