### ISSUE TITLE
Request to include new gravity field model

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#405]
Dear Dominic,
                    In the 'Environment setup' page of TUDAT, I found that EGM96 gravity model is used for Earth in TUDAT. For my thesis work, I would like to use a recent and more precise version of the gravity model of Earth, preferrably SGG-UGM-1 from the ICGEM website. I have provided the link below:
http://icgem.gfz-potsdam.de/tom_longtime
I request you to include this capability in TUDAT.

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Sorry, I missed this message. You can read the file into C++ yourself, and use it to define the settings for the spherical harmonity gravity field settings. You may be able to use the existing functionality for reading gravity field files,

Dominic
