### ISSUE TITLE
Guidance, Navigation and Control in Tudat

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#406]
Hi Dominic, 

As I have already told you, I am currently working on implementing a GNC system for aerobraking in Tudat. I have two main questions right now:

- For the control system, I would need to provide the dynamics with a control vector for the rotational motion. And of course this would need to be done for every time step (0.1 s). Is there a way that does not involve stopping the propagation each step? I don't know how the orbit determination part of Tudat works, but can I maybe get some inspiration from there, or the aerodynamic guidance? For now I will run it with no attitude control.
- For the navigation system, I need a more simplified model for onboard propagation. What I have now is a function that I wrote which uses the mathematical formulations of the accelerations, but I also need the state transition matrix, which would take longer to derive, type and debug. I know that there is a `createAccelerationModel` function in Tudat (which I use to simulate the onboard IMU), but it is updated with the actual state of the spacecraft, whereas I would need to update it with the estimated state. Do you know if there's an easy way of doing this (maybe by taking inspiration from the orbit determination part, again)?

Otherwise, it would be very nice to have some sort of basic GNC (just like for the aerodynamic guidance) that is already integrated in Tudat, and one only needs to add their own functions. 

Kind regards, 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

* Indeed, the aerodynamic guidance is a good place to get inspiration on how to achieve this (orbit determination works in a rather different way). Typically, the control system will influence the parameters of the dynamical model, but not its formulation (e.g. change direction, magnitude of thrust, but not remove/add acceleration models altogether). The first step is to determine the functional relationship between your control vector and the accelerations, and then work from there to design the code to achieve the control. My first 'in-person' availability (except maybe very short talks) will be next Wednesday, but hopefully I can give some feedbakc through here before then if needed.
*  Tudat can actually calculate the state transition matrix for you (see variational equations propagation example). Using the estimated state as input to the acceleration models used inside the guidance model can be done in several ways. The most straightforward would be, I think, to create an extra body map that represents the 'estimated environment/system', as opposed to the 'real environment/system'. This body map should be independent (e.g. don't copy Earth, Sun etc. from one to the other, but create them anew). During each time step, the state of the vehicle should be reset from the estimator, instead of by the environment updater. 

I really like these ideas, for the next days let's use this thread to discuss any issues that may arise, and discuss it in person during the second half of next week,

Dominic

**Comment by mfacchinelli** [comment]
Hi Dominic, 

- For the control system I was thinking of adding it as a new property for a `Body`, and then bind the output of a function that retrieves all the current control vectors of the simulated bodies (and concatenates them) to the `stateDerivativeFunction_` in the dynamics simulator. Then I would need to add a new input to the dynamics derivatives that represents the control vector. But I am not sure this is the best method and I am not sure how it will play out if more than one body is propagated and/or hybrid propagation is used, so next week we could discuss how to do this in more detail. Also, as you mentioned, the way the control vector is added to the state derivative is a very good question. For rotational motion it should be relatively easy, since the control is achieved by means of control torque, which can be simply added to the external ones. For translational motion, however, it's a bit more complicated. For Cowell it would be easiest to simply use the Delta V, but this becomes harder for the other propagators. So maybe it would be best to add the thrust acceleration, but that complicates the use of impulsive shots. So maybe we could use both? Or I could just leave the translational control out, since there already is a thrust guidance class, and for my application simply stop the propagation. I guess we'll see next week :)
- I think I get what you mean for the new body map thing, so I'll try it out. Before our next meeting hopefully I will have something figured out, although I think it would be a bit too early for a working prototype :p 

Thank you, as always, for your help!

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

Adding the control object(s) somewhere to the Body object is a good choice, I think. I'm still not convinced that the control vector needs to be passed through the integrator: the integration scheme itself does not use the control vector, it only comes into play in the computation of the state derivative. If you have a block diagram/flow chart, we can try to make it more concrete how to implement this in terms of software architecture.

I don't think the translational propagation scheme has an influence on how the translational motion is controlled. In the case of impulsive shots, you're going to have to either stop the propagation, or implement some sort of event handling. In case of continuous thrust, you can use the thrust acceleration, which is handled equally by each propagator.

Good luck!

Dominic

**Comment by DominicDirkx** [comment]
Hi Michele,

* Ok, that is bit less invasive them I thought it would be. But, my question remains, but is then shifted: why would the computeStateDerivative function of DynamicsStateDerivativeModel need to get the control vector as input. As I understand it:
    * The control action is determined by your GNC system, which includes a Kalman Filter to estimate the current state.
    * This control action can be one of various things, but will typically (?) be a thrust magnitude/direction, or a torque magnitude/direction. 
     * Both of these control actions can be incorporated directly into an AccelerationModel/TorqueModel. 

By binding the output of your GNC to the acceleration models/ torque models directly, the control action (except impulsive thrust) does not need to go through the DynamicsStateDerivativeModel. Instead, it is equivalent to the custom thrust acceleration, with the added complication that the 'custom' thrust function now binds to your GNC. 

Quite possibly I'm missing some of the nuances here, and I think further discussion on this will be more efficient face-to-face

* Your second question is a lot easier to answer :). Propagating variational equations (STM as function of time), requires the creation of a VariationalEquationsSolve object. This object requires everything that a DynamicsSimulator requires and a:

boost::shared_ptr< estimatable_parameters::EstimatableParameterSet< double > >

input, which determines the parameter vector w.r.t. which you want your partials (in your case vehicle initial state),

Best,

Dominic

**Comment by mfacchinelli** [comment]
Hi Dominic, 

- That is indeed a much less invasive and more elegant solution :) I will try to implement it right now, actually, for the control torque. If I encounter any problems I do agree that meeting face-to-face would be more efficient. I can send you an email in case I get stuck with something.
- Ok, I will take a look at that!

Thank you again!

Michele

PS: since I started writing the reply, I have tried implementing your approach and it seems to be working :)

**Comment by mfacchinelli** [comment]
Hi Dominic,

I can confirm that the control torque as a custom torque model works well :) 
However, I am having some problems with the onboard body map, in particular when retrieving the accelerations. The way I update the onboard map is by creating an `EnvironmentUpdater` which updates the state of the spacecraft, and then by using the `AccelerationMap` to first update and then retrieve the accelerations. However, the onboard accelerations always have a very weird magnitude. For instance, the gravitational acceleration is in the order of 10<sup>-9</sup>, whereas the actual value should be in the order of 10<sup>-2</sup>. 
I checked an the state of the spacecraft is updated correctly, so I guess that the problem is then in how I update and/or retrieve the accelerations. The function I have now looks like this:

```
    //! Function to update the body and acceleration map with the current time and state information.
    void updateOnboardModel( )
    {
        // Update environment
        std::unordered_map< propagators::IntegratedStateType, Eigen::VectorXd > mapOfStatesToUpdate;
        mapOfStatesToUpdate[ propagators::translational_state ] = currentEstimatedCartesianState_;
        mapOfStatesToUpdate[ propagators::rotational_state ] = currentEstimatedRotationalState_;
        onboardEnvironmentUpdater_->updateEnvironment( currentTime_, mapOfStatesToUpdate );

        // Loop over bodies exerting accelerations on spacecraft
        for ( accelerationMapIterator_ = onboardAccelerationModelMap_.at( spacecraftName_ ).begin( );
              accelerationMapIterator_ != onboardAccelerationModelMap_.at( spacecraftName_ ).end( );
              accelerationMapIterator_++ )
        {
            // Loop over each acceleration
            for ( unsigned int i = 0; i < accelerationMapIterator_->second.size( ); i++ )
            {
                // Update acceleration model
                accelerationMapIterator_->second[ i ]->updateMembers( );
            }
        }
    }
```
Is there something I am missing about how the accelerations are updated?

Thank you :)

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

There's a couple of places this could be going wrong:
- How are you creating the environment updater?
- Before updating the acceleration models, first reset them, for instance:

for( unsigned int i = 0; i < accelerationModelList_.size( ); i++ )
        {
            accelerationModelList_.at( i )->resetTime( TUDAT_NAN );
        }

Calling the resetTime( TUDAT_NAN ) ensures that the update is actually performed (which it won;t be if the current time is teh same as during the previous update)
- Are the states in the correct reference frame? The translational states should be in the frame define by the setGlobalFrame... function.

Dominic

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I set the environment like this:
```
//! Function to create the onboard environment updater.
void NavigationSystem::createOnboardEnvironmentUpdater( )
{
    // Set integrated type and body list
    std::map< propagators::IntegratedStateType, std::vector< std::pair< std::string, std::string > > > integratedTypeAndBodyList;
    integratedTypeAndBodyList[ propagators::translational_state ] = { std::make_pair( spacecraftName_, "" ) };
    integratedTypeAndBodyList[ propagators::rotational_state ] = { std::make_pair( spacecraftName_, "" ) };

    // Create environment settings
    std::map< propagators::EnvironmentModelsToUpdate, std::vector< std::string > > environmentModelsToUpdate =
    propagators::createTranslationalEquationsOfMotionEnvironmentUpdaterSettings( onboardAccelerationModelMap_, onboardBodyMap_ );

    // Create environment updater
    onboardEnvironmentUpdater_ = boost::make_shared< propagators::EnvironmentUpdater< double, double > >(
                onboardBodyMap_, environmentModelsToUpdate, integratedTypeAndBodyList );
}
```
Since I do not propagate the rotational motion of the spacecraft onboard, it is not added to the environment via the `createRotationalEquationsOfMotionEnvironmentUpdaterSettings`, but I still add it to the map of states to be updated. Maybe this causes some internal problems, too. I did it this way because I did not want to create an onboard `propagationSettings` object, but I might change it later, since I will need it for the STM. 

Your last question made me think, and I think that the acceleration model thinks that the spacecraft is orbiting the SSB. I have done a very rough calculation and indeed an object at the SSB would feel an acceleration due to Mars gravity in the order of 10<sup>-9</sup> m s<sup>-2</sup>. I guess one way to fix this is to add the position of Mars to the state (which I just tested and does indeed work), or maybe I should just start using the `propagationSettings` right now.

Thank you as always :) 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

Adding the rotational state to the list of propagated states (when updating the environment) seems to be the right approach to me, as instead of taking it from the propagation, you're taking it rom the navigation (?)

The states are w.r.t. the global origin, which you probably set at SSB. You can change it to see if it has any effect on your results,

Dominic
