### ISSUE TITLE
Failed unit test: 83 - test_SphericalHarmonicPartials (Failed)

### ISSUE THREAD

**Issue by woeterb** [Tudat/tudat#411]
While running the unit tests, one failed:

```
99% tests passed, 1 tests failed out of 221

Total Test time (real) = 1474.23 sec

The following tests FAILED:
	 83 - test_SphericalHarmonicPartials (Failed)
Errors while running CTest
Makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
23:47:13: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
23:47:13: Elapsed time: 24:34.
```
Operating system: **Windows 8.1**

Is there a fix for this?

The log-files:
[CTestCostData.txt](https://github.com/Tudat/tudat/files/2164452/CTestCostData.txt)
[LastTest.log](https://github.com/Tudat/tudat/files/2164453/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/2164454/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
This is a very peculiar failure. It seems that partial derivatives of the spherical harmonic partials (used to propagate variational equations) are incorrect. However, tests of a full estimation including this functionality do work correctly.....

A few questions:
- which version of Tudat are you using (what is the last commit)
- are you compiling in default or debug mode?
- could you try to run on the test_SphericalHarmonicPartials, and post the output here?

**Comment by woeterb** [comment]
In response to your questions:

- Last Commit: 9c6202afb852cfcc6ce9dc379e3115a0447b522b
- Default
- Output: [test_SphericalHarmonicPartials_output.txt](https://github.com/Tudat/tudat/files/2173647/test_SphericalHarmonicPartials_output.txt)

Output running the tests:

```
12:52:23: Running steps for project TudatBundle...
12:52:23: Starting: "C:\Program Files (x86)\CMake\bin\cmake.exe" --build . --target application_HelloWorld -- test
Running tests...
Test project C:/build-tudatBundle-Desktop-Default
        Start   1: sofa-test
  1/221 Test   #1: sofa-test ................................................   Passed    0.03 sec

[...]

        Start 221: test_JsonInterfaceVariable
221/221 Test #221: test_JsonInterfaceVariable ...............................   Passed    0.21 sec

99% tests passed, 1 tests failed out of 221

Total Test time (real) = 1246.14 sec

The following tests FAILED:
	 83 - test_SphericalHarmonicPartials (Failed)
Errors while running CTest
Makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
13:13:09: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
13:13:09: Elapsed time: 20:46.
```
Screenshot of Build Settings:

![schermafdruk 2018-07-08 12 54 20](https://user-images.githubusercontent.com/40529083/42419107-96d60914-82ae-11e8-9bac-d0f4df09240a.png)

**Comment by ifodde** [comment]
@DominicDirkx I got exactly the same results as @woeterb (after I updated Tudat to the latest commit). Here it is: 
[spherHarmonicsError.txt](https://github.com/Tudat/tudat/files/2175434/spherHarmonicsError.txt)

**Comment by DominicDirkx** [comment]
Thanks!

Could you check if it also occurs with https://github.com/Tudat/tudat/commit/1640a34a55fa8e2cf41c630fe248357bdd217cd8?

**Comment by ifodde** [comment]
Same results... 
[spherHarmonicsError.txt](https://github.com/Tudat/tudat/files/2175758/spherHarmonicsError.txt)

**Comment by ifodde** [comment]
sorry wrong file: 
[spherHarmonicsError2.txt](https://github.com/Tudat/tudat/files/2175760/spherHarmonicsError2.txt)
