### ISSUE TITLE
json-kernels, json-documentation, failed unit tests

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#414]
Hi Dominic,

while attempting to include several additional kernels when using the json interface I was unable to make more than 1 alternativeKernel work. Attached is the json file in question. That attempt also failed when making use of a metakernel instead.
[JUICE_perturbed.zip](https://github.com/Tudat/tudat/files/2176022/JUICE_perturbed.zip)

Unfortunately, I am unable to access the doxygen json-documentation to check whether I am trying to pass multiple kernels correctly. The function I am trying to access is tudat::json_interface::loadSpiceKernels() under the link http://doxygen.tudat.tudelft.nl/d1/d2d/spice_8cpp_source.html#l00077
The error I get is "404 File not found The site configured at this address does not contain the requested file". How can I add several alternativeKernels or Kernels when using a json file?
While rerunning the same simulation via a cpp-application I managed to implement several kernels. I did not manage to do so via a metakernel however. I noticed this was already mentioned briefly in issue #227 . Is it possible to make use of a metakernel on windows?

Hoping to resolve these problems I updated tudat to the newest version (this should be visible in my repositories if I updated everything correctly). Upon re-building tudat and re-running all unit tests the following ones failed:
	 4 - algorithm_type_traits (SEGFAULT)
	 12 - custom_comparisons (SEGFAULT)
	 22 - hypervolume (Failed)
	 28 - island (SEGFAULT)
	 36 - problem_type_traits (SEGFAULT)
	 48 - type_traits (SEGFAULT)
Should I be concerned by those?
[LastTest.log](https://github.com/Tudat/tudat/files/2176102/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/2176103/LastTestsFailed.log)

Kind regards
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

Don't worry about the unit test failures, they're known to occur on Windows, and only pertain to Pagmo itself. 

Concerning the Spice issue: I assume you're working on Windows, where loading multiple spice kernels can cause conflicts (I think it's a matter of the order of the kernels). Your best bet is to use the SPKMERGE tool:

https://naif.jpl.nasa.gov/naif/utilities_PC_Linux_64bit.html

which you can use to merge multiple Spice kernels into a single kernel. Make sure to merge de430 (or another planetary ephemeris kernel) into your total spice kernel. Setting your new kernel as 'alternative kernel' should load the data you want. You can always make a (temporary!) modification to spiceInterface.cpp to print (std::cout) the names of the alternative kernels that are being loaded, to see if the JSON data is being properly read,

Best,

DOminic

**Comment by SebastianVillamil** [comment]
Hi Dominic,

thank you for the infos. Is there a way to access the doxygen documentation on the json interface?

Best regards
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

Indeed, it seems like the  Doxygen for the JSON interface is indeed down. You can find the documentation in-code in the header files (just search for the function you need, and have a look at the description). 

Best regards,

Dominic

**Comment by DominicDirkx** [comment]
@ifodde Could you update the doxygen repository with the latest version of the code>
