### ISSUE TITLE
Difficulties setting up tidal accelerations

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#417]
Good morning,

I am trying to analyse the effects of tidal accelerations of both Jupiter and Ganymede on a satellite orbiting Ganymede. Unfortunately, I have semantic issues already during the definition of the bodySettings. Bellow, my current best guess making use of the documentation. I'm guessing my vector definition is faulty, I don't know how to fix it though. Could you please point out my error?

std::vector< std::string > TideOrigins{"Jupiter"}; 
std::complex<double> lovN(0.0, 0.5);
std::vector< std::vector< std::complex< double > > > loveNums;
loveNums[ 0 ].push_back( lovN );
bodySettings[ "Ganymede" ]->gravityFieldVariationSettings = boost::shared_ptr< BasicSolidBodyGravityFieldVariationSettings >
            ( TideOrigins, loveNums, 2.6312e+006);

Best regards
Sebastian

**Comment by mfacchinelli** [comment]
Hi Sebastian, 
I think that the problem is in the line `loveNums[ 0 ].push_back( lovN );`. You are trying to access the first vector element, although the vector has no entries. I would recommend adding `loveNums.resize( 1 );` just before this line. Let me know if this works!
Michele

**Comment by SebastianVillamil** [comment]
Hi Michele,
thanks for your reply. Unfortunately it did not solve the issue. After consulting the documentation once more I created a vector of the minimum size for degree 2 and order 2 in this manner:

    std::vector< std::string > TideOrigins;
    TideOrigins.push_back( "Jupiter" );
    std::complex< double > lovN( 0.5 );
    std::vector< std::vector< std::complex< double > > > loveNums(3);
    loveNums[ 0 ].push_back( lovN );
    loveNums[ 0 ].push_back( 0.0 );
    loveNums[ 0 ].push_back( 0.0 );
    bodySettings[ "Ganymede" ]->gravityFieldVariationSettings = boost::make_shared< BasicSolidBodyGravityFieldVariationSettings >
            ( TideOrigins, loveNums, refDataGan.second );

the error I receive is "no viable overloaded '='". Do I maybe need to initialize the settings differently?

**Comment by SebastianVillamil** [comment]
Hi Michelle,
the definition of BodySettings you proposed did indeed work out for me. Unfortunately, I am now stuck at the next step of implementing tidal accelerations. I want to model the accelerations on my satellite, which is orbiting Ganymede, caused by the tides on Ganymede due to Jupiter. After the creation of the BodySettings of Ganymede I try to implement the mentioned acc. the following way:

    SelectedAccelerationMap accelerationMap;
    std::map< std::string, std::vector< boost::shared_ptr< AccelerationSettings > > > accelerationsOfSat;
    accelerationsOfSat[ "Ganymede" ].push_back( boost::make_shared< DirectTidalDissipationAccelerationSettings >
                                                  ( lovN, 0.0, false, true ));

Doing so yields the error "no matching function for call to 'tudat::simulation_setup::DirectTidalDissipationAccelerationSettings'"
Following the documention on 4.1 acc. set-up also leads to errors unfortunately, with the formulation being 
    accelerationMap[ "Sat" ][ "Ganymede" ] = boost::make_shared< DirectTidalDissipationAccelerationSettings >(
       lovN, 0.0, false, false );
The error is "no viable overloaded '='"
    accelerationMap[ "Sat" ][ "Ganymede" ].push_back( boost::make_shared< DirectTidalDissipationAccelerationSettings >(
       lovN, 0.0, false, true ) );
Also returns the matching function error.

Looking ahead already, how would I best save the resulting accelerations? Keeping Issue #393 in mind I'd try with 

    dependentVariablesList.push_back( boost::make_shared< SingleAccelerationDependentVariableSaveSettings >
                                      ( basic_astrodynamics::direct_tidal_dissipation_in_central_body_acceleration,
                                        "Sat", "Ganymede", true ));
Or should I rather use direct_tidal_dissipation_in_orbiting_body_acceleration instead as Jupiter is the central body causing the tidal deformation?
Kind regards
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian, 

The modified SH coefficients are automatically incorporated into the SH acceleration. No need to change the acceleration settings 

Dominic

**Comment by SebastianVillamil** [comment]
Hi Dominic,
thank you for the clarification. How do I access the resulting tidal accelerations? with direct_tidal_dissipation_in_central_body_acceleration or direct_tidal_dissipation_in_orbiting_body_acceleration I get that the accelerations of type 12 or 13 respectively cannot be found.

**Comment by DominicDirkx** [comment]
Hi Sebastian,

If you are using time-varying gravity fields, the total spherical harmonic acceleration can be saved, or the total acceleration due to a single spherical harmonic term. Saving the acceleration due to only the time-dependent part of teh acceleration is not currently supported. 

The accelerations direct_tidal_dissipation_in_central_body_acceleration and direct_tidal_dissipation_in_orbiting_body_acceleration operate in a different manner, and explicitly computes the acceleration due to teh tide. It is _only_ applicable to a tide raised on a planet my a moon (or vice versa) causing an acceleration on said moon,
