### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by transferorbit** [Tudat/tudat#418]
When trying to build libraries in TUDAT, I encounter the follow errors:
```
...
[ 97%] Built target tudat_statistics
[100%] Built target tudat_simulation_setup
[100%] Linking CXX executable /Users/kevin/tudatBundle/tudatApplications/assignments_ae4867/bin/applications/application_DelfiNumericalIntegrationJson
Undefined symbols for architecture x86_64:
  "tudat::root_finders::doesRootFinderRequireDerivatives(boost::shared_ptr<tudat::root_finders::RootFinderSettings>)", referenced from:
      tudat::propagators::SingleVariableLimitPropagationTerminationCondition::SingleVariableLimitPropagationTerminationCondition(boost::shared_ptr<tudat::propagators::SingleDependentVariableSaveSettings>, boost::function<double ()>, double, bool, bool, boost::shared_ptr<tudat::root_finders::RootFinderSettings>) in libtudat_simulation_setup.a(propagationTermination.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/kevin/tudatBundle/tudatApplications/assignments_ae4867/bin/applications/application_DelfiNumericalIntegrationJson] Error 1
make[2]: *** [tudatApplications/assignments_ae4867/assignment1/CMakeFiles/application_DelfiNumericalIntegrationJson.dir/all] Error 2
make[1]: *** [tudatApplications/assignments_ae4867/assignment1/CMakeFiles/application_DelfiNumericalIntegrationJson.dir/rule] Error 2
make: *** [application_DelfiNumericalIntegrationJson] Error 2
10:57:15: The process "/Applications/CMake.app/Contents/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
10:57:15: Elapsed time: 00:04.
```
This error occurs both when I compile *only* `application_DelfiNumericalIntegrationJson` as well as when I run *all* the unit tests.
This appears similar to issue #144 , and I have tried removing my top-level `CMakeLists.txt.user` file, to no avail. I also checked in *Settings* (aka *Preferences*) > *Build & Run* > *Kits* > *Desktop (default)* for *CMake Configuration*, which appears correct: `CMAKE_CXX_COMPILER:STRING=%{Compiler:Executable:Cxx}; [... etc.]`

I’ve recently been working in the files `.../assignment1/delfiPropagationJson.cpp` and `.../assignment1/delfiIntegratorAnalysis.json`. Could simple errors in these files lead to such compilation errors?

**Comment by transferorbit** [comment]
For what it’s worth, I can confirm that when I remove the lines which add the assignment folders ...
```add_subdirectory( "${PROJECTROOT}/tudatApplications/assignments_ae4867/assignment1”)```
... from the top-level `CMakeLists.txt` file, that all unit tests pass.

**Comment by DominicDirkx** [comment]
I think you need to updat the TUDAT_APPLICATION_PROPAGATION_LIBRARIES. Copy the bottom part of the example application Cmakelists (excluding the application definitions) and I think it should work

**Comment by transferorbit** [comment]
Thanks Dominic! As it happens, I managed to figure this out this morning. My solution was to add `tudat_root_finders` to the list of `TUDAT_APPLICATION_PROPAGATION_LIBRARIES` in the `CMakeLists.txt` files of the assignments.
_If_ this is the correct way to solve this problem, then this library should probably be added to the TUDAT assignments on GitHub. I’d have done this myself, but I didn’t want to be responsible for introducing [FOD](https://en.wikipedia.org/wiki/Foreign_object_damage). Let me know if and where to do this and I’ll take care of it.

**Comment by giussepemeazza** [comment]
I had the same problem and your solution solved it, many thanks.
