### ISSUE TITLE
Propagation of various element types

### ISSUE THREAD

**Issue by DominicDirkx** [Tudat/tudat#42]
As discussed during the meeting on 03-06-2016, one of the main developments that is needed for Tudat is the implementation of the propagation of different types of orbital elements/equations of motion. 
 These include, but are not limited to:
- Propagation of relative vehicle motion
- Propagation of orbital elements, such as Kepler, equinoctial, unified state, etc.
- Encke propagator

The setup of the propagators at present requires a derived class of the NBodyStateDerivative for each different form of the equations of motion (currently only Cowell: propagation of Cartesian components). The exact implementation of the derived class is TBD however (e.g. single class for orbital element propagation, or one class per element set).

**Comment by magnific0** [comment]
I would be interested in implementing / overseeing:

- Keplerian elements
- Modified Equinoctial elements
- DROMO (regularized)

The previous two Kep & MEEs were already implemented once for the old StateDerivative models by me. Albeit not unit tested. http://tudat.tudelft.nl/issues/703 At least the equations can be copy pasted from here.

**Unit testing** can we agree now to o unified approach to different element types? Can we just compare them to previously know results? 

These two books are excellent for sourcing some benchmarking problems (that are also widely used in literature):
- Bond, V. R., & Allman, M. C. (1996). Modern Astrodynamics. Princeton University Press.
- Stiefel, E. L., & Scheifele, G. (1971). Linear and Regular Celestial Mechanics. Springer-Verlag.

**Comment by DominicDirkx** [comment]
Excellent, those models would be a great start to extending the list or propagators.

For the unit tests, I think we can indeed compare the results from these propagators to, for instance, the Cowell propagator, or even an externally generated orbit. Also, propagating a pure Kepler orbit would be a good way to test them. Probably it's easiest to set up a generic unit test where you provide the type of propagator that you want to use, and then compare against the benchmark. This would also make the addition of future models a lot easier.

**Comment by DominicDirkx** [comment]
The code has included an Encke propagator now for some time. Gauss propagation using MEE and Kepler elements is in pull request #165. Information on these propagators will be communicated through the pull request. Plans for future additions to the list of propagators will be communicated through dedicated issues.
