### ISSUE TITLE
AE4867 - Assignment 2 - resit

### ISSUE THREAD

**Issue by giussepemeazza** [Tudat/tudat#421]
When implementing a thrust acceleration in the code developed for Assignment 1, part 3, the following error appears. 
Application output: "Error, body-fixed frame to propagation frame not yet implemented for DirectionBasedForceGuidance"
It seems to be connected to the drag acceleration, as in the absence of it the code gives a consistent output. However, I have not been able to make it work including the drag. Any advice will be welcomed.

**Comment by DominicDirkx** [comment]
In that case, just run the code omitting the drag acceleration, clearly stating the error you obtain in your report,

Best,

Dominic
