### ISSUE TITLE
Functionality request

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#422]
Hi Dominic,

I would like to request the implementation of a function to save the acceleration due to the time-dependent part of the acceleration when using time-varying gravity fields. I require this functionality to analyse the tidal-acceleration effects on a satellite orbiting a moon which itself experience tidal forces due to the planet it is orbiting.

Best regards
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

I've written the required code, and pushed it here:

https://github.com/DominicDirkx/tudat/tree/SaveSHCorrections

see differences w.r.t. master here:

https://github.com/Tudat/tudat/compare/master...DominicDirkx:SaveSHCorrections. I've added three types of dependent variables:

total_gravity_field_variation_acceleration (difference between acceleration with and without all corrections)
single_gravity_field_variation_acceleration (difference between acceleration with a single correction)
single_gravity_field_variation_acceleration_terms (difference between acceleration with a single correction, separately per coefficient entry)

Only the first one has been tested so far, I can't guarantee the validity of the second two yet. 

Let me know if you have trouble using the new code,

Dominic

**Comment by DominicDirkx** [comment]
Just so you know, I've added all three dependent variable types, and pushed them to the branch linked above. I'm keeping this issue open, as some small comments in the code are still required before it can be merged into the master.

**Comment by SebastianVillamil** [comment]
Hi Dominic,
thanks for updating the code. I'll let you know once I've tried it out as I am currently preparing the literature study.
Best regards
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

Ok, thats fine. For the literature study, we should have a chat to discuss the process, and meet (via Skype/Google hangout) about once every 2 weeks to discuss the progress,

Dominic

**Comment by DominicDirkx** [comment]
Code has been merged, closing issue.
