### ISSUE TITLE
Failing to include <cspice/include/SpiceUsr.h>

### ISSUE THREAD

**Issue by zennoastro** [Tudat/tudat#440]
When running application_SingleSatellitePropagator after installation the following error occurs:

/Users/maxarshavsky/drive/storage/projects/tudat/tudatBundle/tudat/Tudat/External/SpiceInterface/spiceInterface.h:37: error: 'cspice/include/SpiceUsr.h' file not found
    #include <cspice/include/SpiceUsr.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~

All tests pass; macOS X 10.13.3.

**Comment by DominicDirkx** [comment]
Thank you for your interest in Tudat. Before I can answer your question, I;ll need some more information:
- Does the error occur during run-time or compile-time?
- If at compile-time (which is what it looks like), how were all unit tests successfully built?
- If at compile-time, attached the full compile output in a text file.
- Please attach the full CMake Output (given in 'General Messages; wen opening the CMakeLists in Qt in a text file.

Finally, be aware that we'll be pushing an updated version of the code to Github  before mid-November,

**Comment by zennoastro** [comment]
Thank you Dominic,

- error occurs during compile-time
- unit tests are built successfully & passed 
- compile-time error (wrt cspice) occurs when building application_SingleSatellitePropagator or any other example application
- output files attached below

Thank you,

Max

[LastTest.log](https://github.com/Tudat/tudat/files/2512104/LastTest.log)

[Compile Output.docx](https://github.com/Tudat/tudat/files/2512112/Compile.Output.docx)

[Cmake General Messages Output.docx](https://github.com/Tudat/tudat/files/2512131/Cmake.General.Messages.Output.docx)

**Comment by zennoastro** [comment]
Adding the following line into SatellitePropagatorExamples/CMakeLists.txt (after line 155) resolves the problem:

> include_directories(${PROJECTROOT})

Is there a better solution? What would such problem arise from?

**Comment by DominicDirkx** [comment]
@zennoastro It sounds like you opened the CMakeLists.txt in thet tudatExampleApplications as a separate project. Is this the case? The examples, and unit tests, are set up to be run from the tudatBundle project (which automatically finds and includes all necessary dependencies).

Could you elaborate a bit on the workflow you've used? Have you followed our install guide, which tools have you used, etc.

Finally, you add the version of the code you are working on (hash for tudatBundle, tudat and tudatExampleApplications repositories)?

**Comment by DominicDirkx** [comment]
Poster unresponsive, closing issue
