### ISSUE TITLE
Unit Test Failures with MinGW 64-bit

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#443]
Hi Dominic, 

Here, [LastTest.log](https://github.com/Tudat/tudat/files/2518941/LastTest.log), you can find the log of the unit tests that fail when using Qt 4.7.2 with MinGW 7.3.0 (64-bit).

The tests that fail are:
- 88:test_HybridArcStateEstimation
- 89:test_ParameterInfluenceDetermination
- 190:test_UnscentedKalmanFilter

Kind regards, 

Michele

**Comment by DominicDirkx** [comment]
Failures solved/tracking in other issues.
