### ISSUE TITLE
Unit Test Failures with MinGW 32-bit

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#444]
Hi Dominic, 

Here, [LastTest.log](https://github.com/Tudat/tudat/files/2518949/LastTest.log), you can find the log of the unit tests that fail when using Qt 4.7.2 with MinGW 5.3.0 (32-bit).

The tests that fail are:
- 32:test_UnifiedStateModelModifiedRodriguesParameterElementConversions
- 61:test_GravitationalTorques
- ~~88:test_HybridArcStateEstimation~~
- 95:test_TorquePartials
- 112:test_VariationalEquations
- 187:test_UnscentedKalmanFilter
- 245:test_JsonInterfaceParameter

Kind regards, 

Michele

**Comment by different91988** [comment]
Hi Michele

I want to ask you that if your  QT creator works fine? My program won‘t stop at breakpoint I set and directly to the end. How to fix it?

Best wishes

Min Wang 
@mfacchinelli

**Comment by mfacchinelli** [comment]
Hi Min,

Unfortunately I have never managed to make the breakpoints work, but I haven’t spent much time in figuring out why that is.

I don’t really have any recommendations to give, since I have no idea where it goes wrong. To be honest I started thinking that with C++ it was not possible, but I read your other issue, so I guess it should be doable. 

Maybe you can try and write an email to Qt support explaining that it doesn’t always work and figure out which settings need to be changed. Being able to debug with breakpoints would indeed be an awesome feature to have! 

I’m sorry I couldn’t help much. Good luck!

Michele :)

**Comment by DominicDirkx** [comment]
Since 32 bit Mingw will no longer be supported, closing this issue.
