### ISSUE TITLE
The program won't stop at debug mode

### ISSUE THREAD

**Issue by different91988** [Tudat/tudat#445]
Hi Dominic,

I set the QT creator mode to debug , change the build settings from default to debug and choose to run application_helloworld, but after pressing F5 the debugger won't stop at any one of the breakpoints set by me in the source code of folder '*\tudatExampleApplications\templateApplication\TemplateApplication'.  Moreover, if I create a other new c++ console project, the debugger could stop as my command. So the debugger is fine.  I am a new user to the QT creator IDE, do I miss some settings? How do I properly set breakpoint to debug the source code? Any help will be greatly appreciated.

Beat wishes

Min Wang

**Comment by DominicDirkx** [comment]
I have little experience in using the debugger in Qt, eseIpecially on Windows,  I generally use the terminal. There may be old default build files being used. To ensure all is compiled in debug mode, clean the code, and rebuild. Note: this will mean rebuilding Tudat from scratch!
