### ISSUE TITLE
unit test failure #115 on  macOS 10.13.2

### ISSUE THREAD

**Issue by shfmartens** [Tudat/tudat#446]
[LastTest.log](https://github.com/Tudat/tudat/files/2534202/LastTest.log)

Dear admins,

When running the unit tests,  test #115 unfortunately failed. Attached you can find the LastTest.log.
My operating system is macOS  10.13.2.

Hopefully you can figure out the reason for this failure.

Thanks in advance.

Kind regards,
Sjors

**Comment by DominicDirkx** [comment]
Hi Sjors,

I've pushed a fix to github (hopefully):

https://github.com/Tudat/tudat/commit/0f8c119879f58fb3a61f643bcbbc6f0e7e15c27d

Update your Tudat version to the latest master (only Tudat, not TudatBundle), recompile, and rerun the tests. Hopefully that will fix it. Let me know what happens,

Best,

Dominic

**Comment by shfmartens** [comment]
Hi Dominic,

The fix solved the problem. I followed your instructions and all unit tests were passed.

Thanks a lot!

Kind regards,
Sjors
