### ISSUE TITLE
The program won't hit breakpoint with gdb

### ISSUE THREAD

**Issue by different91988** [Tudat/tudat#447]
Hi @DominicDirkx 

I find the program won't hit breakpoint even with the gdb.exe under the directory "...\Qt\Tools\mingw730_64\bin" included in QT installation folder.

The gdb.exe hints "Single stepping until exit from function main, which has no line number information." when stepping into the application_HelloWorld.exe in folder "...\tudatExampleApplications\templateApplication\bin\applications". 

Is there something wrong with the compiling process? How to fix it? 

Best,

Min

**Comment by DominicDirkx** [comment]
Hi Min,

As I posted in the previous issue, I don't have much experience with debugging under Windows, nor do I intend to dive into it. If you want to do proper software development with Tudat, install it on a Unix-based system (personally I use Ubunutu).

I posted an idea to get it working there, which you have not replied to (cleaning the code, then setting it in debug mode, rerunning cmake, and trying again). It's best to try it on an example application that does not have many link libraries (e.g. application_TabulatedAtmosphereUsage; only compile single executable) to speed the test process up.

Also: for which goal do you want to use the debugger?

Dominic
