### ISSUE TITLE
Failed Unit Test: 88 - test_HybridArcStateEstimation

### ISSUE THREAD

**Issue by MattTurnock** [Tudat/tudat#450]
Running on Ubuntu 18.04, 64-bit

[LastTest.log](https://github.com/Tudat/tudat/files/2568869/LastTest.log)

**Comment by DominicDirkx** [comment]
I've checked, and it's just a very minor tolerance failure. I've pushed a correction to the code, so that it shouldn't occur anymore. You can pull the new code for tudat, but it's not necessary, this unit test failure does not indicate that anything is broken.
