### ISSUE TITLE
Unit Test failure (test_UnscentedKalmanFilter)

### ISSUE THREAD

**Issue by tommyesse** [Tudat/tudat#451]
I had a problem with the test of the libraries but I didn't find the file .log that you mentioned in the guide. 

I attached the error message.
[Error message.txt](https://github.com/Tudat/tudat/files/2569493/Error.message.txt)

 It's the only test that failed.

Windows 8.1, 64 bit. 

Thank you!

**Comment by DominicDirkx** [comment]
This unit test failure is nothing to worry about, it's a new feature, and this test has been known to fail on Windows. We're looking into it, but it will have no consequences for Numerical Astrodynamics (or Propagation and Optimization).

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
