### ISSUE TITLE
Problem with the example. 

### ISSUE THREAD

**Issue by tommyesse** [Tudat/tudat#453]
Despite a failed test I tried to run the example suggested by the online guide.
It was written that in fact a failed test could also be of little importance.

However, I also had problems with the example of propagation of a single satellite.
In about 2 hours I did not get anything in "Application Output" and I got this error in "General message"
[Error message.txt](https://github.com/Tudat/tudat/files/2569816/Error.message.txt)
.
What should I do?
I'm following the AE4868 course so if it's easier for you, you could also look to my computer during the lesson on Tuesday.

Thank you!

**Comment by DominicDirkx** [comment]
Please read the install guide carefully..... See the note in Part 6 of:

http://tudat.tudelft.nl/installation/configureTudatLibraries.html#compile-and-test-tudat-libraries

**Comment by tommyesse** [comment]
Good morning,

Thank you again for the answer. Yeah, I read the intall guide carefully,
the note in part 6 says that I have to delete the "test" text and that's
what I did. Anyway, I have also other problems when I open the project
every time, so I think I could just wait for the lesson tomorrow or on
thursday to try so solve all of them.

Thanks again,

Tommaso

Il giorno lun 12 nov 2018 alle ore 09:32 DominicDirkx <
notifications@github.com> ha scritto:

**Comment by DominicDirkx** [comment]
Dear Tomosso,

Ok, then let's have a look tomorrow. To save time: what other problems do you encounter?

Best,

Dominic

**Comment by tommyesse** [comment]
I think that i have made some confusion to clone two times tudat due to
error in the firts one (cloned in Desktop). I don't know, maybe it's
everything ok, but I'd like to learn very well this software so I do want
consider evrything.

Thank you very much,  Best regards,

Tommaso

Il giorno lun 12 nov 2018 alle ore 15:03 DominicDirkx <
notifications@github.com> ha scritto:
