### ISSUE TITLE
Error (Unable to find) when testing

### ISSUE THREAD

**Issue by AlvaroCT** [Tudat/tudat#454]
I have got the following error while testing the libraries to start using Tudat. I have tried to compile and test them three times without success.

My operating system is Windows 10 Pro, intel Core i7-2670QM CPU @2.2GHz and my Compiler version is Qt Creator 4.7.2.

Please find attached .txt file with Error log, compile output.

[Error.txt](https://github.com/Tudat/tudat/files/2572242/Error.txt)

**Comment by AlvaroCT** [comment]
Hello Dominic, 
Sure sorry, I was re-building the libraries again. This is the compile output. 

Even if it seems there is no important error that stops the building process, the tests are not successful. Nevertheless, I think every time I have run the tests, results are different. Not sure why. Hope you can 

help me out since I have been trying to recompile, change directory location and some other alternatives without success. :(

Thank you so much, 
Alvaro. 

[Building Libraries Error.txt](https://github.com/Tudat/tudat/files/2573269/Building.Libraries.Error.txt)

**Comment by AlvaroCT** [comment]
Now, only one of the test failed. The rest were fine. But still getting same error at the end of the command execution. Is it important I guess, right? 

[Error.txt](https://github.com/Tudat/tudat/files/2573326/Error.txt)

**Comment by DominicDirkx** [comment]
Hi Alvaro,

This unit test failure is nothing to worry about (see #455). Your Tudat code is working properly. When we have a fix for this unit test, we'll post a quick update,

Best,

Dominic
