### ISSUE TITLE
Failed Unit Test Windows 10 - test_UnscentedKalmanFilter

### ISSUE THREAD

**Issue by ptorrente** [Tudat/tudat#455]
[LastTest.log](https://github.com/Tudat/tudat/files/2573896/LastTest.log)

99% tests passed, 1 tests failed out of 246

Total Test time (real) = 606.72 sec

The following tests FAILED:
	187 - test_UnscentedKalmanFilter (Failed)
Errors while running CTest
mingw32-make.exe: *** [Makefile:72: test] Error 8
23:30:29: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"

**Comment by robrikken4** [comment]
got the same problem so I will keep checking this post for updates instead of making my own

**Comment by jackakyle** [comment]
See here: https://github.com/Tudat/tudat/issues/451

**Comment by DominicDirkx** [comment]
Thanks!
