### ISSUE TITLE
CMake warning due to number of object file directory characters [Windows 10 x64]

### ISSUE THREAD

**Issue by jackakyle** [Tudat/tudat#456]
Good afternoon, I would just like to draw attention to the following warning that I am receiving while parsing.  This does not seem to be a critical issue, as I am having no problems with the building and unit tests, but does seem to me to be something that could be easily resolved by giving shorter names? I am also uncertain as to why CMake is using the absolute path instead of relative path in this case.

```CMake Warning in tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeLists.txt:
  The object file directory

    C:/build-tudatBundle-Desktop-Default/tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeFiles/test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir/

  has 164 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    UnitTests/unitTestUnifiedStateModelModifiedRodriguesParameterElementConversions.cpp.obj

  cannot be safely placed under this directory.  The build may not work
  correctly.```

**Comment by DominicDirkx** [comment]
Thanks for posting this. Indeed, it won't have any consequences for you, but it would be best to prevent this warning from occurring. I'll leave this issie open zo that we're reminded to address it.

**Comment by J-M-Smith-Aero** [comment]
I am also having this issue. I have attached the output seen in general messages below:

[Configure - General Messages.txt](https://github.com/Tudat/tudat/files/3851776/Configure.-.General.Messages.txt)

**Comment by DominicDirkx** [comment]
Thanks, just to be clear, your code is compiling, and unit tests are passing right?

**Comment by J-M-Smith-Aero** [comment]
Yes, all tests have passed.

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
