### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Walt1995** [Tudat/tudat#457]
[building_error.txt](https://github.com/Tudat/tudat/files/2578943/building_error.txt)

Good morning,
I tried building the libraries three times, but the same error occurs.
My operating system is Windows 10 and my compiler MinGW 7.3.0 64bit.

Kind regards,
Walter Campo

**Comment by DominicDirkx** [comment]
Dear Walter,

It seems like something on your computer (anti-virus?) is preventing the compiler from doing its job. In particular:

mingw32-make.exe[2]: unlink: C:/tudatBundle/cspice/lib/libcspice.a: Permission denied

implies this. Check your operating system (read/write authority) and virus scanner settings,

Best,

Dominic

**Comment by DominicDirkx** [comment]
Troubleshooting guide has been updated
