### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by jonasprovoost** [Tudat/tudat#458]
Goodmorning,

An error has occurred while building. After a few reruns it still occurs as shown in the text file. My operating system is Windows 10 and my compiler is MinGW 7.3.0 64bit.

King regards,
Jonas Provoost

[Buildingerrortudat.txt](https://github.com/Tudat/tudat/files/2580355/Buildingerrortudat.txt)

**Comment by DominicDirkx** [comment]
Dear Jonas,

To make sure I sned you in the right direction: could you also post everything under "General messages" in Qt (in a text file),

Dominic

**Comment by jonasprovoost** [comment]
Of course. 
[Generalmessages.txt](https://github.com/Tudat/tudat/files/2581306/Generalmessages.txt)

**Comment by DominicDirkx** [comment]
You have installed Tudat in:

 C:/Users/Jonas/Documents/Tudat/tudatBundle

Which leads to this error. See the warning given in:

http://tudat.tudelft.nl/installation/downloadTudatBundle/index.html#cloning-tudat
