### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by morgado14** [Tudat/tudat#464]
I have had troubles building the libraries. My computer is a Lenovo G510 with Intel Core i7-4702MQ @ 2.20GHz and 4GB of RAM running windows 10 home version 1803. Compiler version is MinGW 7.3.0 64bit. Please, find attached the compiler output.

[CompileError.txt](https://github.com/Tudat/tudat/files/2582756/CompileError.txt)

**Comment by morgado14** [comment]
Problem solved. As stated in issue #457 the problem seems to come from the antivirus settings. Building is resumed.

**Comment by lmajerustudelft** [comment]
Hello, 

Could you please tell me how exactly you solved your problem ? I have tried many different things (changing the sharing properties of the file, or removing the windows firewall) but nothing works. 

Thanks, 
Louis

**Comment by morgado14** [comment]
Hi,

I have the McAfee antivirus and all I had to do was to disable the real-time scanning and firewall and try building again and it worked, I can't really help with much else. I hope you get it to work.

Good luck,
Miguel

**Comment by lmajerustudelft** [comment]
Hi,

Thanks so much for your help, I'll  try it out asap !
________________________________

**Comment by DominicDirkx** [comment]
Troubleshooting guide has been updated
