### ISSUE TITLE
Building Libraries

### ISSUE THREAD

**Issue by ialforjaruiz** [Tudat/tudat#465]
Hi, when building the libraries I get a compiler error stating:

[ 84%] Building CXX object tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeFiles/test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir/UnitTests/unitTestUnifiedStateModelModifiedRodriguesParameterElementConversions.cpp.obj
Assembler messages:
Fatal error: can't create CMakeFiles\test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir\UnitTests\unitTestUnifiedStateModelModifiedRodriguesParameterElementConversions.cpp.obj: No such file or directory
mingw32-make.exe[2]: *** [tudat\Tudat\Astrodynamics\BasicAstrodynamics\CMakeFiles\test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir\build.make:63: tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeFiles/test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir/UnitTests/unitTestUnifiedStateModelModifiedRodriguesParameterElementConversions.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:1862: tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeFiles/test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir/all] Error 2
mingw32-make.exe: *** [Makefile:140: all] Error 2
00:28:48: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"

**Comment by DominicDirkx** [comment]
Could you check if the problem is the same as #449?

**Comment by ialforjaruiz** [comment]
It was the same problem. Installing Tudat directly into C:// worked. Thank you!!
