### ISSUE TITLE
Cmake error: Target DependInfo.cmake file not found

### ISSUE THREAD

**Issue by lmtoonen** [Tudat/tudat#466]
[error.txt](https://github.com/Tudat/tudat/files/2584171/error.txt)
In the 99th percentage of my installation, I got this error. 

CMake Error in C:/Users/Liv Mare Toonen/Documents/2018-2019/Numerical Astrodynamics/build-tudatBundle-Desktop-Default/tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeFiles/application_SinglePerturbedSatellitePropagator.dir/DependInfo.cmake:
  cmListFileCache: error can not open file.

CMake Error: Target DependInfo.cmake file not found
CMake Error: Directory Information file not found
Scanning dependencies of target application_SinglePerturbedSatellitePropagator
mingw32-make.exe[2]: *** No rule to make target 'tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeFiles/application_SinglePerturbedSatellitePropagator.dir/includes_CXX.rsp', needed by 'tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeFiles/application_SinglePerturbedSatellitePropagator.dir/singlePerturbedSatellitePropagator.cpp.obj'.  Stop.
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:16383: tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeFiles/application_SinglePerturbedSatellitePropagator.dir/all] Error 2
mingw32-make.exe: *** [Makefile:140: all] Error 2
01:16:19: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
01:16:19: Elapsed time: 15:54.

**Comment by DominicDirkx** [comment]
This issue seems to be the same as #449
