### ISSUE TITLE
Julian date error

### ISSUE THREAD

**Issue by fmorra** [Tudat/tudat#469]
Hello,
I would like to address an error that does not let the code compile if I input both the Julian date or the modified Julian date for the assignment. The error is displayed in the file below:
[EphemerisDataError.txt](https://github.com/Tudat/tudat/files/2585975/EphemerisDataError.txt)
I think it has to do with the length of the Julian date expressed in seconds, because if I start the propagation from 0 to 3 days later it works fine. Is there any way to address this issue?
Thank you for you time.
Fabrizio

**Comment by DominicDirkx** [comment]
Good to see that you solved this and, in this case, it's indeed good not to post how you solved it (as this would give the answer to question 1 :) )

In the future, for these kinds of questions on teh assignments, it's best to use Brightspace.
