### ISSUE TITLE
Error during build test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir

### ISSUE THREAD

**Issue by jjordiiii** [Tudat/tudat#471]
Hi,

When building the library, I get the following error:

:-1: error: [tudat\Tudat\Astrodynamics\BasicAstrodynamics\CMakeFiles\test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir\build.make:63: tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeFiles/test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir/UnitTests/unitTestUnifiedStateModelModifiedRodriguesParameterElementConversions.cpp.obj] Error 1

I can't find anything related on this issue, and I have no clue what to do with the error.

Best,
Jordi

**Comment by DominicDirkx** [comment]
Please check whether this:

https://github.com/Tudat/tudat/issues/458

is the origin of your issue;

**Comment by jjordiiii** [comment]
Yes, thank you. The solution solved my problem!
