### ISSUE TITLE
Problem with committing the code

### ISSUE THREAD

**Issue by tommyesse** [Tudat/tudat#472]
![problem to commit](https://user-images.githubusercontent.com/44911189/48676300-056c2d80-eb65-11e8-80c4-1275de85832e.JPG)

I followed all the instructions to committ the code.  I tried also to configure as the program tudat_shell told me but it doesn't work, it keeps generating this message. What could I do?

Thank you, Tommaso

**Comment by DominicDirkx** [comment]
Can you try it without the --global?

**Comment by tommyesse** [comment]
Hi! Sorry I wil try when I'll do everything ready in Ubuntu because I couldn't work anymore in Windows, I'll let you know
