### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by Simon-van-Diepen** [Tudat/tudat#475]
In the documentation, under Tutorials and Documentation >> JSON Interface >> 4. List of Keys, there is a typo in the Export section. The boolean onlyFinalStep is explained as follows in the documentation:

boolean onlyFinalStep (optional). Whether to save only the values corresponding to the initial integration step. Does not override onlyInitialStep. Default value: false

The onlyFinalStep option, however, saves the final integration step, not the initial integration step as is stated in the documentation.

**Comment by DominicDirkx** [comment]
Thanks for spotting this, error has been fixed.
