### ISSUE TITLE
Unable to push code on github

### ISSUE THREAD

**Issue by fmorra** [Tudat/tudat#476]
Hello, 
I am having problems when trying to push my code on github. When I try to follow the instructions for part 4.2, I get the following errors:
![commiterror](https://user-images.githubusercontent.com/44974090/48953944-d92b2500-ef47-11e8-80e1-ad96e03831f3.JPG)
![pusherror](https://user-images.githubusercontent.com/44974090/48953948-da5c5200-ef47-11e8-910d-6281ddcaaf97.JPG)
related to the very first commands we should use for 4.2.1 and 4.2.2, even after following the additional steps recently added to the guide. I don't know why I am getting these errors, since I followed the instructions for part 4.1 and everything seems to work fine. The only thing that could cause the errors (as far as I know) might be this message that I get every time I open gt:
![gterror](https://user-images.githubusercontent.com/44974090/48954055-38893500-ef48-11e8-8c8d-8d91aef7d75a.JPG)
If anyone could help me, I'd be very grateful, also because I would like to ask a question about the last part of the assignment and if I can't push the code on github it is no use to provide a link to my private repository to address it. 
Thank you for your time.
Fabrizio

**Comment by DominicDirkx** [comment]
Dear Fabrizio,

The git commands are to be made in the repository where you want to make commits, not in C:/.

The warning you get in Qt can safely be ignored (click Do Not Show Again),

Dominic
