### ISSUE TITLE
Missing #if use_cspice in createEmphemeris.h

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#478]
I tried to compile tudat without cspice by unticking USE_CSPICE 
The compilation failed at createEmphermeris.h since it included spiceInterface.h
Adding the #if solved the problem, and tudat compiled fine.
```
...
#if USE_CSPICE
#include "Tudat/External/SpiceInterface/spiceInterface.h"
#endif
...
```
So I am guessing that the #if is missing and should be included.

**Comment by DominicDirkx** [comment]
Thanks! We'll update this in an upcoming commit.
