### ISSUE TITLE
json_interface: RadiationPressure not clear at tudat.tudelft.nl

### ISSUE THREAD

**Issue by Oliviervanbon** [Tudat/tudat#479]
When assigning a radiationPressure to my body ("Delfi") in a json file, I tried to use the method explained in the list of keys at http://tudat.tudelft.nl/tutorials/jsonInterface/keys/rst/index.html. Sadly this didn't work, but we found a working example in a unit test.
Based on the explanation in the documentation, I would set it up like this:

```
"radiationPressure": {
                "type": "cannonBall", 
                "sourceBody": "Sun",
                "occultingBodies": [
                "Earth"
                ],
                "radiationPressureCoefficient": 1.2
            }
```

This results in the following error:

> terminate called after throwing an instance of 'tudat::json_interface::ValueAccessError'
> Undefined key: referenceArea
>   what():  Undefined key: referenceArea

DD edit: Could the documentation be modified to make the correct syntax more clear?

**Comment by DominicDirkx** [comment]
Thanks for pointing this our. Documentation has been corrected.
