### ISSUE TITLE
Wrong variableType in tudat.tudelft.nl in 3.3.2 Propagator Settings: dependent Variables

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#480]
The below section is copied straight from the website from section 3.3.2. Available Dependent Variables:

> 
> **Local temperature** in atmosphere of body exerting aerodynamic acceleration (at position of body undergoing acceleration). Requires an aerodynamic acceleration to be acting on the vehicle. Defined by creating a SingleDependentVariableSaveSettings object with input local_temperature_dependent_variable as variableType.
> 
> **Local dynamic pressure** felt by the vehicle based on the current velocity and atmospheric conditions, i.e., computed with 1/2 ρV2. Requires an aerodynamic acceleration to be acting on the vehicle. Defined by creating a SingleDependentVariableSaveSettings object with input local_temperature_dependent_variable as variableType.
> 
> **Local aerodynamic heat rate** felt by the vehicle based on the current velocity and atmospheric conditions, i.e., computed with 1/2 ρV3. Requires an aerodynamic acceleration to be acting on the vehicle. Defined by creating a SingleDependentVariableSaveSettings object with input local_temperature_dependent_variable as variableType.

The variableType for dynamic pressure should be local_dynamic_pressure_dependent_variable
The variableType for Local aerodynamic heat rate should be local_aerodynamic_heat_rate_dependent_variable

**Comment by JuliusWeinmiller** [comment]
The same for relative distance. The variableType should be relative_distance_dependent_variable, however is relative_position_dependent_variable.

**Comment by DominicDirkx** [comment]
Thanks for pointing this our. Documentation has been corrected.
