### ISSUE TITLE
Problem of "Unused key" in 5_2

### ISSUE THREAD

**Issue by tommyesse** [Tudat/tudat#482]
[Problem for 5_2.txt](https://github.com/Tudat/tudat/files/2637142/Problem.for.5_2.txt)

When I try to propagate the Earth with all the accelerations of the other bodies, I get the attached error message. Interpreting the results, I realized that basically the program does not propagate the Earth and continues to use ephemeris. 
Is there a problem in my json file? Or maybe my PC doesn't read some libraries of Tudat? 

thank you for your help, 

Tommaso

**Comment by DominicDirkx** [comment]
Dear Tomosso,

I'm pretty sure this is just a matter if errors in your JSON file. Push your code files to a private repository, and post a link here, and we can have a look,

Dominic
