### ISSUE TITLE
Commiting code

### ISSUE THREAD

**Issue by tommyesse** [Tudat/tudat#483]
I don't why but I can't commit the code. I should have configured correctly my Github account (in the photo that I attached). I tried either Tommaso and tommyesse that are my name and my username, but It doesn't work and the terminal keeps tell me that I have to configure my account. 

What could I do?  Thank you, cordially,

Tommaso 

![problemcommit](https://user-images.githubusercontent.com/44911189/49385184-1ef0a600-f71d-11e8-88eb-a7e84b037375.jpg)

**Comment by DominicDirkx** [comment]
Please check the Brightspace announcements for the course

**Comment by tommyesse** [comment]
Yeah, I saw that and I followed the instructions. 
As you can see from the photo I should have configured my account. I tried also without global, but nothing changed

**Comment by DominicDirkx** [comment]
Sorry, I replied to soon without taking a detailed look. I think what has happened is that you've typed user.mail, it should be user.email.

Let me know if this resolves it,

Dominic

**Comment by tommyesse** [comment]
Don't worry. Actually I contacted Github support and the problem was that I had a private email.
For this reason,  Github used a default email for the configuration did not recognize mine. At the end I solved, I wrote it because maybe it could be useful for someone,
thank you vety much, Tommaso

**Comment by DominicDirkx** [comment]
Thank you for posting this, and good to hear that you solved it.
