### ISSUE TITLE
Failed Unit Test (Windows)

### ISSUE THREAD

**Issue by contantsteph** [Tudat/tudat#484]
[LastTest.log](https://github.com/Tudat/tudat/files/2640910/LastTest.log)

When running unit tests, I received the following message:

99% tests passed, 1 tests failed out of 304

Total Test time (real) = 1068.82 sec

The following tests FAILED:
	245 - test_UnscentedKalmanFilter (Failed)

**Comment by DominicDirkx** [comment]
Thanks, this is a known failure (#451). It's nothing to worry about, we are investigating the origins.
