### ISSUE TITLE
SOFA not found during installation

### ISSUE THREAD

**Issue by Casperbru** [Tudat/tudat#485]
During the reinstallation it shows that SOFA can not be found, before continuing I wanted to check if something has to be fixed. I attached the CMakeLists and compileOutput.

[CMakeLists.txt](https://github.com/Tudat/tudat/files/2646014/CMakeLists.txt)
[compileOutput.txt](https://github.com/Tudat/tudat/files/2646020/compileOutput.txt)

Thanks!

**Comment by DominicDirkx** [comment]
The file 'compileOutput.txt' actually contains the CMake output. Can you try to compile the code and let me know what happens?

**Comment by Casperbru** [comment]
[compOut.txt](https://github.com/Tudat/tudat/files/2652588/compOut.txt)
It seems to be doing ok

**Comment by DominicDirkx** [comment]
Good, then the SOFA output was just a warning, an nothing to worry about.
