### ISSUE TITLE
Wrong error checking in flightConditions.cpp

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#492]
The error checking in case altitude_dependent in AtmosphericFlightConditions::getAerodynamicCoefficientIndependentVariable is wrong. The check looks for aerodynamicAngleCalculator (the same as for the slideslip, one case above), however the aerodynamicAngleCalculator has nothing to do with the altitude.
```
case altitude_dependent:
        if( aerodynamicAngleCalculator_== nullptr )
        {
            throw std::runtime_error( "Error, aerodynamic angle calculator is nullptr, but require angle of sideslip" );
        }
        currentIndependentVariable = getCurrentAltitude( );
        break;
```

**Comment by DominicDirkx** [comment]
Thanks! We'll update it in a commit in teh near future.
