### ISSUE TITLE
[Documentation] 3.2.1 Single-arc Propagation

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#493]
In the section of `TranslationalStatePropagatorSettings`
`StateScalarType`, has a bug with the long double making it show as :literal`long double`
`dependentVariablesToSave` has a bug where the text is its own bullet point. Also the info regarding that the default is an empty list is mentioned twice. also another  :literal`  ` bug.
`initialBodyStates `should have a link to the blue note box below, since that is vital information.

In the section of `MassPropagationSettings`
missing explanation for termination settings and dependent variables, a reference to the `TranslationalStatePropagatorSettings `would suffice. 

Also, can the termination settings be different from each other? If yes, why would you want to do that? Is it possible to have an empty terminationSettings, such in case when using a multitype propagator and termination is determined via the translational state propagator

In the section of `MultiTypePropagatorSettings`
The first part with using a std::vector, the code shows propagatorSettingsMap as a variable name. While techincally correct, the naming is confusing. 
dependentVariablesToSave of the hybrid overwrites any of the included propagator settings. What about the termination settings?

**Comment by DominicDirkx** [comment]
Hi Julius,

Again thanks for the input, we'll modify it soon.

Concerning your question: you can only use a single termination settings for your propagation when propagating multiple state types concurrently.

Dominic

**Comment by DominicDirkx** [comment]
@mchambe : Remind me on Friday that we briefly discuss these points, in particular how to modify the documentation for the last few points.
