### ISSUE TITLE
[Documentation] 3.1. Integrator Settings TimeType

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#494]
The `TimeType` cannot be `long double`. Writing it here just leads to someone trying it and being frustrated that it doesn't work.

The `TimeType` that are allowable by tudat are `double` and the tudat `Time`. This is checked in DynamicsSimulator constructor via `std::enable_if< is_state_scalar_and_time_type< StateScalarType, TimeType >::value, int >::type = 0`

With the relevant code shown below. As can be seen, the check returns true if both a valid `StateScalarType` is given, assumed to be true, and that the `TimeType` is either `double` or `Time`.
```
template< typename T >
struct is_time_type {
  static const bool value = false;
};

template< >
struct is_time_type< double > {
  static const bool value = true;
};

template< >
struct is_time_type< Time > {
  static const bool value = true;
};

template< typename StateScalarType, typename TimeType >
struct is_state_scalar_and_time_type {
  static const bool value = ( is_time_type< TimeType >::value && is_state_scalar< StateScalarType >::value );
};
```

Of course it is possible to use the tudat `Time` and then cast it to `long double` if it is needed.

**Comment by DominicDirkx** [comment]
Thanks! We'll update this in the documentation soon,

Best,

Dominic
