### ISSUE TITLE
unitConversions unexpected behaviour

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#495]
The current implementation of the templated unitConversion functions can have unexpected behaviour.
For example: `convertDegreesToRadians(90)` returns `1` instead of the expected `1.5708`

This is because of how the template is implemented:
```
template< typename T >
T convertDegreesToRadians( T angleInDegrees )
{ return angleInDegrees / 180.0 * mathematical_constants::PI; }
```
The function returns the same type that is given. Which means that when passing an int, an int is returned. For example:
```
    std::cout << "Deg to rad (90)  :" << unit_conversions::convertDegreesToRadians(90) << std::endl;
    std::cout << "Deg to rad (90.0):" << unit_conversions::convertDegreesToRadians(90.0) << std::endl;
    std::cout << "Deg to rad (90)  :" << unit_conversions::convertDegreesToRadians<double>(90) << std::endl;
```
Returns 
```
Deg to rad (90)  :1
Deg to rad (90.0):1.5708
Deg to rad (90)  :1.5708
```

Is this an intended feature or unwanted behaviour?
Could this be solved by using double as default type?

**Comment by DominicDirkx** [comment]
Dear Julius,

This behaviour is to be expected. In C++, a floating point variable should always be defined as 90.0, not 90. The quantity 90 is parsed as an int, unless otherwise specified. Thia may be a nuisance in some cases, but I'm afraid it is the nature of C++,

Dominic
