### ISSUE TITLE
Missing !isLatitudeAndLongitudeSet_ check in getCurrentLongitude( )

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#496]
Hi,
I needed the longitude to determine if a simulation should be terminated. 
So I used the function `Body->getFlightConditions()->getCurrentLongitude()` to get it. 
I called `getCurrentLongitude` inside the termination determination function.
To my surprise it returned 0.

What I think happened is this: (Relevant functions are shown below)
1. `updateAtmosphereInput` is called
2. Longitude is not set yet
therefore `scalarFlightConditions_.count( longitude_flight_condition ) == 0 ` is true
3. `updateLatitudeAndLongitudeForAtmosphere_` is false
And therefore `scalarFlightConditions_[ longitude_flight_condition ] = 0.0;` is executed
4. `getCurrentLongitude` is called from the termination determination function
5. `scalarFlightConditions_.count( longitude_flight_condition ) == 0 ` is false
Since it was set to 0 in `updateAtmosphereInput`
And therefore `computeLatitudeAndLongitude( )` is not run
6. Thus `getCurrentLongitude` returns 0

```
void updateAtmosphereInput( )
    {
        if( ( scalarFlightConditions_.count( latitude_flight_condition ) == 0 ||
              scalarFlightConditions_.count( longitude_flight_condition ) == 0 ) )
        {
            if( updateLatitudeAndLongitudeForAtmosphere_ )
            {
                computeLatitudeAndLongitude( );
            }
            else
            {
                scalarFlightConditions_[ latitude_flight_condition ] = 0.0;
                scalarFlightConditions_[ longitude_flight_condition ] = 0.0;
            }
        }
[...]
```
```
    double getCurrentLongitude( )
    {
        if( scalarFlightConditions_.count( longitude_flight_condition ) == 0 )
        {
            computeLatitudeAndLongitude( );
        }
        return scalarFlightConditions_.at( longitude_flight_condition );
    }
```
This should be fixed by including `!isLatitudeAndLongitudeSet_` as an or condition in checking whether longitude was previously defined.
```
    double getCurrentLongitude( )
    {
        if( scalarFlightConditions_.count( longitude_flight_condition ) == 0  || !isLatitudeAndLongitudeSet_)
        {
            computeLatitudeAndLongitude( );
        }
        return scalarFlightConditions_.at( longitude_flight_condition );
    }
```

**Comment by JuliusWeinmiller** [comment]
Hi Dominic, 

I'll try doing that when I have the chance to.
Right now I am getting the latitude and longitude via:
```
Body->getFlightConditions()->getAerodynamicAngleCalculator()->getAerodynamicAngle(reference_frames::latitude_angle ),
Body->getFlightConditions()->getAerodynamicAngleCalculator()->getAerodynamicAngle(reference_frames::longitude_angle )
```
which is fine. What I did notice is that when calling 
`Body->getFlightConditions()->getCurrentGeodeticLatitude()`, it updates the latitude and longitude correctly (relevant code is below). However if both of them are called in the same line, the longitude still returns 0. Since, the geodeticLatitudeFunction must not be set for the latitude and longitude to update, I would rather not rely on that.
 
```
    void computeGeodeticLatitude( )
    {
        if( !( geodeticLatitudeFunction_ == nullptr ) )
        {
            scalarFlightConditions_[ geodetic_latitude_condition ] = geodeticLatitudeFunction_(
                        currentBodyCenteredAirspeedBasedBodyFixedState_.segment( 0, 3 ) );
        }
        else
        {
            if( scalarFlightConditions_.count( latitude_flight_condition ) == 0 || !isLatitudeAndLongitudeSet_ )
            {
                computeLatitudeAndLongitude( );
            }
            scalarFlightConditions_[ geodetic_latitude_condition ] = scalarFlightConditions_[ latitude_flight_condition ] ;
        }
    }
```

**Comment by JuliusWeinmiller** [comment]
I needed to pass the latitude and longitude to a function, so I called the functions via:
```
func(Body->getFlightConditions()->getAerodynamicAngleCalculator()->getAerodynamicAngle(reference_frames::latitude_angle ), 
     Body->getFlightConditions()->getAerodynamicAngleCalculator()->getAerodynamicAngle(reference_frames::longitude_angle );
```
Therefore both latitude and longitude are called in the same line. 
Reading left to right, the latitude is given first, which to us humans looks it should evaluate latitude first and therefore update longitude, but since longitude is passed as a 0, the compiler thinks differently. Nor do I trust that it will always calculate one before the other. 
While technically functional, it's also risky to write them separately in two lines above the function call since since accidentally swapping lat and long call order would break it again.
```
double lat = Body->getFlightConditions()->getAerodynamicAngleCalculator()->getAerodynamicAngle(reference_frames::latitude_angle);
double long = Body->getFlightConditions()->getAerodynamicAngleCalculator()->getAerodynamicAngle(reference_frames::longitude_angle);
func(lat,long);
```

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
