### ISSUE TITLE
problem building assignment 3 

### ISSUE THREAD

**Issue by lmtoonen** [Tudat/tudat#497]
I performed the steps to pull the new assignments and I put the extra  line in the .txt file. I am able to see the file in my directory, but when I try to build in Qt creater I get the following error: 

Assembler messages:
Fatal error: can't create CMakeFiles\tudat_propagation_setup.dir\createAccelerationModels.cpp.obj: No such file or directory
mingw32-make.exe[3]: *** [tudat\Tudat\SimulationSetup\PropagationSetup\CMakeFiles\tudat_propagation_setup.dir\build.make:63: tudat/Tudat/SimulationSetup/PropagationSetup/CMakeFiles/tudat_propagation_setup.dir/createAccelerationModels.cpp.obj] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:13257: tudat/Tudat/SimulationSetup/PropagationSetup/CMakeFiles/tudat_propagation_setup.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:17321: tudatApplications/NumericalAstrodynamics2018Assignment/src3/CMakeFiles/application_DelfiVariationalEquations.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:4152: application_DelfiVariationalEquations] Error 2
09:52:35: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"

**Comment by DominicDirkx** [comment]
When you try to compile another application (e.g. code for assignment 2), does it still work?

To fix this, I'll need to see your code, if you come to the lecture this morning, I'll have a look,

Best,

Dominic
