### ISSUE TITLE
Problem Output Question 2 of Assignment 3

### ISSUE THREAD

**Issue by ialforjaruiz** [Tudat/tudat#499]
When computing the state transition matrix and the sensitivity matrix, the output files are incomprehensible. I attach the sensitivity matrix output file and add a link to the code in my GitHub
![outputex3](https://user-images.githubusercontent.com/45011185/51030492-da68ed80-1599-11e9-904f-4e7e4053b98a.jpg)

https://github.com/ialforjaruiz/NumericalAstrodynamics2018Assignment
.

**Comment by DominicDirkx** [comment]
This seems to be an issue of the editor, not the data (for a fellow student). If you load the data into Matlab, it should show up fine.
