### ISSUE TITLE
No CMAKE_C_COMPILER could be found.

### ISSUE THREAD

**Issue by PabloAlia** [Tudat/tudat#502]
I am running Tudat on a MacBook Pro with macOS mojave. I was trying to propagate the orbit of assignment 4 with a step of 0.001 s (for question 5) when my computer unexpectedly restarted. Now when I open Qt Creator and the tudatbundle file I get the following errors:

> The C compiler identification is unknown
The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:21 (project):
  No CMAKE_C_COMPILER could be found.

>  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

> CMake Error at CMakeLists.txt:21 (project):
  No CMAKE_CXX_COMPILER could be found.

 > Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

> Configuring incomplete, errors occurred!
> See also "/Users/PabloAlia/Documents/build-tudatBundle.nosync-Desktop-Du00e9faut/CMakeFiles/CMakeOutput.log".
> See also "/Users/PabloAlia/Documents/build-tudatBundle.nosync-Desktop-Du00e9faut/CMakeFiles/CMakeError.log".
> CMake Project parsing failed.

[CMakeError.log](https://github.com/Tudat/tudat/files/2755725/CMakeError.log)
[CMakeOutput.log](https://github.com/Tudat/tudat/files/2755727/CMakeOutput.log)

**Comment by DominicDirkx** [comment]
Hi Pablo,

That's very peculiar.... Try closing Qt, removing the tudatBundle/CmakeLists.txt.user file, and reopening Tudat in Qt. 

If this doesn't work, check whether the settings described here:

http://tudat.tudelft.nl/installation/troubleshooting/installationErrors.html#verify-build-run-options

are still correct (note that the screenshot is for Windows, teh correct settings for Mac are given in the text),

Dominic

**Comment by PabloAlia** [comment]
Ok, the build and run options were lost but now it seems to work again.
