### ISSUE TITLE
Failed unit tests on Windows

### ISSUE THREAD

**Issue by elmarputs** [Tudat/tudat#508]
Hi all,

After updating the Tudat code, two of the unit tests failed: VariationalEquations and UnscentedKalmanFilter. For details, see the test log attached below:

[LastTest.log](https://github.com/Tudat/tudat/files/2854967/LastTest.log)

I read that the failed unit test of the UnscentedKalmanFilter is not that critical, but the failing VariationalEquations unit test may be problematic for the Propagation & Optimisation course, so for that reason I decided to open this issue.

Thank you in advance for looking at this,

Elmar

N.b. I'm working on a Windows 10 (64-bit) machine.

**Comment by DominicDirkx** [comment]
Hi Elmar,

This seems to be a problem with the test, not the code. I've pushed a small modification, could you see if it properly passes now?

Best.

Dominic

p.s. Indeed, don't worry about the UnscentedKalmanFilter test

**Comment by elmarputs** [comment]
Hi Dominic,

Thank you for the quick response! I'll check it right away.

Cheers,

Elmar

**Comment by elmarputs** [comment]
Even with the updated test code the unit test fails:

[LastTest.log](https://github.com/Tudat/tudat/files/2855337/LastTest.log)

**Comment by elmarputs** [comment]
I recompiled the unit tests in 'Release' mode and now the VariationalEquations test runs successfully, so I'll close the issue!

Thank you for your help and have a nice (sunny) Sunday,

Elmar
