### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by tommyesse** [Tudat/tudat#509]
I updated the code and tried to compile but I got this error.

[Compile Error.txt](https://github.com/Tudat/tudat/files/2866059/Compile.Error.txt)

Could you help me out?

**Comment by DominicDirkx** [comment]
Hi, could you post your full compile output? Then I can have a look.

**Comment by tommyesse** [comment]
Here you are 
[Compile Error.txt](https://github.com/Tudat/tudat/files/2869921/Compile.Error.txt)

**Comment by tommyesse** [comment]
Here you are 
[Compile Error.txt](https://github.com/Tudat/tudat/files/2869925/Compile.Error.txt)

**Comment by DominicDirkx** [comment]
Hi,

It seems to be complaining about the template application for some reason. Perhaps it was modified during Numerical Astrodynamics? You don't need it now, so if yoiu comment out:

add_subdirectory( "${PROJECTROOT}/tudatExampleApplications/templateApplication/TemplateApplication")

in the tudatBundle/CMakeLists.txt file, thsi error should no longer pop up.

Let me know if this resolves your problem,

Best,

Dominic

**Comment by tommyesse** [comment]
Good afternoon, 

Yeah, we modified together the template application because I have asked you how to generate a file to do some things with C++. Anyway the configuration failed after I add that text in CMakeLists, I got this error, could you help me out? 
[Error.txt](https://github.com/Tudat/tudat/files/2872067/Error.txt)

**Comment by DominicDirkx** [comment]
Hi, I'm not sure what you did to get this particular error message. You say you 'added' some text to the CMakeLists. In my post, I suggested that you remove it, perhaps this went wrong?

Best,

Dominic

**Comment by tommyesse** [comment]
Good afternoon, 

Yeah I tried that, but it doesn't work. I'll bring the PC today.

**Comment by tommyesse** [comment]
Yeah I tried that but it didn't work. This one is the compile error, I don't know if it changed. Anyway, I'll bring the PC today for the lecture. 
[Error.txt](https://github.com/Tudat/tudat/files/2875889/Error.txt)


Best, Tommaso
