### ISSUE TITLE
Mangled SVG schematic in Firefox (docs > Simulator Set-up)

### ISSUE THREAD

**Issue by mcejp** [Tudat/tudat#511]
As seen on https://tudat.tudelft.nl/tutorials/tudatFeatures/propagationSetup/index.html#tudatfeaturessimulatorindex:

![screenshot](https://imgur.com/7CMKnyu.png)

Firefox 65 on Fedora linux 29. Chrome 72 displays the page correctly.

Presumably the cause of the problem is that the SVG declares `font-family="FontAwesome"` for alphanumeric text. As FontAwesome doesn't provide alphanumeric glyphs (AFAIK), the browser needs to substitute them from another font. Firefox picks something that is close to FontAwesome (by some definition of "close"), which happens to be Wingdings or an equivalently unintelligible font.

**Comment by DominicDirkx** [comment]
Thanks for spotting this!

@mchambe Could you modify this during your next wiki update (no rush)

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
