### ISSUE TITLE
Error with the example application: multi objective Earth - Mars transfer

### ISSUE THREAD

**Issue by Palash-Patole** [Tudat/tudat#512]
Dear Developers,

I am facing an application error with one of the example applications: application_PagmoMultiObjectiveEarthMarsTransferExample.

Following message appears at the application output tab of the Qt Creator, which is not insightful.

13:09:48: C:/tudatBundle/tudatExampleApplications/libraryExamples/bin/applications/application_PagmoMultiObjectiveEarthMarsTransferExample.exe exited with code 3

Other PaGMO example applications are working fine. What can be the possible cause of this error?

**Comment by DominicDirkx** [comment]
Dear Palash,

Could you provide a little bit more information:
-Which version of tudatBundle, tudat and teh example applications are you using?
-Which operating system do you use?
-Which compiler do you use?
-Which modifications (if any) have you made to the code?

Try to generate a stack trace:

http://tudat.tudelft.nl/tutorials/troubleshooting/debuggers.html

which will give us more insight into what's going wrong,

Best,

Dominic

**Comment by Palash-Patole** [comment]
Dear Dominic,

Following are the details:

1. Version of Tudat: Major 3, Minor 1 (found in "tudatVersion.h"). I was unable to determine versions for other two.

2. OS: Windows 10 Home, 64 bit

3. Compiler and Debugger:
![capture](https://user-images.githubusercontent.com/34187846/53338144-42ce1d00-3903-11e9-9a9e-6bc976859987.JPG)

4. No modifications made to the code.

I tried using the debugging mode. But, I couldn't find any information useful, neither could I generate a stack.
![capture2](https://user-images.githubusercontent.com/34187846/53339521-e3720c00-3906-11e9-827a-c7714963bb64.JPG)

**Comment by DominicDirkx** [comment]
Hi Palash, 

For the stack trace, go to Window->Views->Stack, after running the debugger. With a little luck, this will give you your stack trace. For the versions of the repositories, please give the number (and date) of the last commit for each,

Best,

Dominic

**Comment by Palash-Patole** [comment]
Dear Dominic,

I am unable to generate the stack in the debugging mode, as seen in this screenshot. I think that this is because Debugger is unable to find errors, but I can be completely wrong about this.
![stack](https://user-images.githubusercontent.com/34187846/53410817-25618780-39c5-11e9-9840-39ad97b9baea.jpg)

For finding the versions of repositories, I used the smart-git. I hope following screenshots will help.
Tudat:
![tudat](https://user-images.githubusercontent.com/34187846/53410714-d87db100-39c4-11e9-8d86-b2ff047d6b52.JPG)

TudatBundle:
![tudatbundle](https://user-images.githubusercontent.com/34187846/53410743-ecc1ae00-39c4-11e9-8e78-11d282f481c7.JPG)

Example applications:
![tudatexample](https://user-images.githubusercontent.com/34187846/53410757-fa773380-39c4-11e9-9fd6-7aff32e3873b.JPG)

I did a quick analysis which line is not executing in the code (by printing some statement in the application output). It is the line number 65 (isl.wait_check( ); // Raises errors)

https://github.com/Tudat/tudatExampleApplications/blob/59cee5d94085c174bd5ea71d22edb7360a7da260/libraryExamples/PaGMOEx/multiObjectiveEarthMarsTransferExample.cpp#L65

**Comment by Palash-Patole** [comment]
Dear Dominic,

Here is the last commit details of the Pagmo2 library.
![image](https://user-images.githubusercontent.com/34187846/53415845-804dab80-39d2-11e9-9e9a-57f409816b93.png)

**Comment by DominicDirkx** [comment]
@mchambe Hi Marie, could you try to run this example application on your (Windows) Tudat version, and let us know if it works correctlyt? No need to modify the version of the code, you can just run it as is. 

If it does work fine for you, my best guess is that this is a versioning problem

**Comment by mchambe** [comment]
Hi Dominic,
We already discussed it with Palash yesterday after the lecture and this example is indeed working fine on my Windows machine so I don't know what is going on here.

**Comment by DominicDirkx** [comment]
Hi Marie,
Ok, good, and thanks for the quick reply!
@Palash-Patole : In that case, please update your tudat, tudatExampleApplications and tudatBundle to the latest version. In the terminal use:

git fetch origin
git merge origin/master

And let me know if it works, or if the terminal gives errors when updating.

**Comment by Palash-Patole** [comment]
Dear Dominic,

The error still persists even after updating.  Example application is exiting with code 3.

**Comment by DominicDirkx** [comment]
That is very strange.... I don't have time today to look into this. Drop by tomorrow afternoon, and we can have a look,

Dominic

**Comment by Palash-Patole** [comment]
I will. Thanks. See you tomorrow.

**Comment by Palash-Patole** [comment]
Dear Dominic,

Updating tudat and re-opening the Qt creator has resolved the issue with this example application. Thanks for your help.

I also run the units tests again and following are the results:

```
99% tests passed, 2 tests failed out of 306

Total Test time (real) = 824.77 sec

The following tests FAILED:
	 96 - test_ApproximatePlanetPositions (Failed)
	247 - test_UnscentedKalmanFilter (Failed)
```
Should I be worried about these failures? I am not using approximate planet position ephemeris class but tabulated spice ephemeris class in my analysis.
