### ISSUE TITLE
Failed Unit Test: test_OrbitalElementsConversions

### ISSUE THREAD

**Issue by davidfdzp** [Tudat/tudat#513]
Test #15 failed on "Ubuntu 18.04.2 LTS" on Windows Subsystem for Linux (Windows 10 64 bit).

15/248 Testing: test_OrbitalElementConversions
15/248 Test: test_OrbitalElementConversions
Command: "/home/david/tudatBundle/tudatBundle/tudat/bin/unit_tests/test_OrbitalElementConversions"
Directory: /home/david/tudatBundle/build-tudatBundle-Desktop-Default/tudat/Tudat/Astrodynamics/BasicAstrodynamics
"test_OrbitalElementConversions" start time: Mar 04 14:38 STD
Output:
----------------------------------------------------------
Running 12 test cases...
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(447): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [0, 0] not within expected tolerance (delta 1.862645e-09): expected 13356280.000000, was 13356280.000000, tolerance 4.882812e-19 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(447): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [2, 0] not within expected tolerance (delta 1.091249e-16): expected 0.785398, was 0.785398, tolerance 4.882812e-19 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(456): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [0, 0] not within expected tolerance (delta 9.313226e-10): expected 6678140.000000, was 6678140.000000, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(456): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [4, 0] not within expected tolerance (delta 2.728484e-12): expected 7725.759061, was 7725.759061, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(498): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": difference{4.54747e-16} between keplerianElements( semiMajorAxisIndex ){8000} and recomputedKeplerianElements( semiMajorAxisIndex ){8000.00000000000363798} exceeds 4.88281249999999999997e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(500): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": absolute value of recomputedKeplerianElements( eccentricityIndex ){4.57756679852223745191e-16} exceeds 4.88281249999999999997e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(506): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": absolute value of recomputedKeplerianElements( argumentOfPeriapsisIndex ){4.95736764351155390074} exceeds 1.08420217248550443401e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(516): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": difference{48.8559} between std::fmod( keplerianElements( argumentOfPeriapsisIndex ) + keplerianElements( longitudeOfAscendingNodeIndex ) + keplerianElements( trueAnomalyIndex ), 2.0 * PI ){5.05883683690556473778} and recomputedKeplerianElements( trueAnomalyIndex ){0.101469193394010773586} exceeds 1.08420217248550443401e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(525): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [0, 0] not within expected tolerance (delta 3.183231e-12): expected 2716.470916, was 2716.470916, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(525): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [1, 0] not within expected tolerance (delta 1.818989e-12): expected -7524.678449, was -7524.678449, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(525): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [3, 0] not within expected tolerance (delta 2.910383e-11): expected 209951.148557, was 209951.148557, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(525): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [4, 0] not within expected tolerance (delta 1.018634e-10): expected 75794.094424, was 75794.094424, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(565): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": difference{6.82121e-16} between keplerianElements( semiMajorAxisIndex ){8000} and recomputedKeplerianElements( semiMajorAxisIndex ){8000.00000000000545697} exceeds 4.88281249999999999997e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(567): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": absolute value of recomputedKeplerianElements( eccentricityIndex ){5.57613093214914502047e-16} exceeds 4.88281249999999999997e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(571): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": difference{1.61623e-16} between keplerianElements( inclinationIndex ){3.07369934568721392409} and recomputedKeplerianElements( inclinationIndex ){3.07369934568721442088} exceeds 4.88281249999999999997e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(574): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": absolute value of recomputedKeplerianElements( argumentOfPeriapsisIndex ){0.0893976709919114893214} exceeds 1.08420217248550443401e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(585): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": difference{1.15196} between std::fmod( keplerianElements( argumentOfPeriapsisIndex ) + keplerianElements( trueAnomalyIndex ), getFloatingInteger< ScalarType >( 2 ) * getPi< ScalarType >( ) ){0.164933614313463405062} and recomputedKeplerianElements( trueAnomalyIndex ){0.0766434812805438423793} exceeds 4.88281249999999999423e-18
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(594): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [0, 0] not within expected tolerance (delta 8.839362e+00): expected 135.615346, was 126.775984, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(594): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [1, 0] not within expected tolerance (delta 1.383622e-01): expected -7998.354085, was -7998.492447, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(594): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [2, 0] not within expected tolerance (delta 5.928812e-01): expected 89.109010, was 89.701891, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(594): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [3, 0] not within expected tolerance (delta 4.054231e+00): expected -222683.794004, was -222687.848235, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(594): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [4, 0] not within expected tolerance (delta 2.471686e+02): expected -3609.276205, was -3362.107572, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(594): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [5, 0] not within expected tolerance (delta 2.762822e+00): expected 14937.554796, was 14934.791973, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(632): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": difference{3.41061e-16} between keplerianElements( semiMajorAxisIndex ){8000} and recomputedKeplerianElements( semiMajorAxisIndex ){8000.00000000000272848} exceeds 4.88281249999999999997e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(636): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": difference{4.16334e-16} between keplerianElements( eccentricityIndex ){0.200000000000000011102} and recomputedKeplerianElements( eccentricityIndex ){0.199999999999999927836} exceeds 4.88281249999999999997e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(650): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": difference{1.7557e-16} between keplerianElements( longitudeOfAscendingNodeIndex ) + keplerianElements( argumentOfPeriapsisIndex ) + keplerianElements( trueAnomalyIndex ){5.05883683690556473778} and recomputedKeplerianElements( argumentOfPeriapsisIndex ) + recomputedKeplerianElements( trueAnomalyIndex ){5.0588368369055638496} exceeds 1.08420217248550443401e-19
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(660): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [0, 0] not within expected tolerance (delta 3.637979e-12): expected 2959.468606, was 2959.468606, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(660): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [1, 0] not within expected tolerance (delta 1.818989e-12): expected -8197.786882, was -8197.786882, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(660): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [4, 0] not within expected tolerance (delta 9.458745e-11): expected 33692.734613, was 33692.734613, tolerance 4.882812e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(702): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [0, 0] not within expected tolerance (delta 5.456968e-12): expected 8000.000000, was 8000.000000, tolerance 2.441406e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(702): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [1, 0] not within expected tolerance (delta 1.387779e-16): expected 0.200000, was 0.200000, tolerance 2.441406e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(702): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [2, 0] not within expected tolerance (delta 1.084853e-15): expected 3.000000, was 3.000000, tolerance 2.441406e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(702): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [3, 0] not within expected tolerance (delta 8.881784e-16): expected 4.241150, was 4.241150, tolerance 2.441406e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(702): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [5, 0] not within expected tolerance (delta 1.024137e-15): expected 2.206969, was 2.206969, tolerance 2.441406e-18 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(712): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [0, 0] not within expected tolerance (delta 9.094947e-13): expected 158.589341, was 158.589341, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(712): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [1, 0] not within expected tolerance (delta 1.818989e-12): expected -8711.844423, was -8711.844423, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(712): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [2, 0] not within expected tolerance (delta 1.421085e-12): expected 201.941519, was 201.941519, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(712): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [3, 0] not within expected tolerance (delta 5.820766e-11): expected -198102.530778, was -198102.530778, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(712): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [4, 0] not within expected tolerance (delta 2.910383e-11): expected -39604.667143, was -39604.667143, tolerance 4.882813e-17 .
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestOrbitalElementConversions.cpp(712): error: in "test_orbital_element_conversions/testCartesianToKeplerianElementConversionBackAndForth": Element [5, 0] not within expected tolerance (delta 2.146407e-10): expected 28794.030828, was 28794.030828, tolerance 4.882813e-17 .

 146378739288.0336  -32851886854.1209 -14241055658.24648  6603.183449760695  26444.27948911581  11463.63694918501
 146378739287.7867 -32851886855.22089 -14241055658.24648  6603.183449959419  26444.27948906619    11463.636949185

  149614115637.0027 0.01636341269609823  0.4090490755385121   1.802512417580207   6.283180991344357   4.240777009021143
  149614115637.0026 0.01636341269609839  0.4090490755385121   1.802512417580233   6.283180991318632   4.240777009021118

*** 40 failures are detected in the test module "Master Test Suite"
<end of output>
Test time =   0.06 sec
----------------------------------------------------------
Test Failed.
"test_OrbitalElementConversions" end time: Mar 04 14:38 STD
"test_OrbitalElementConversions" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by DominicDirkx** [comment]
Dear David,

All your errors seem to originate from Cartesian<->Keplerian conversions where the data is represented in long double (80 bits), instead of double (64 bits). 

A few questions:

Which compiler are you using? 
Also, do all of the other unit tests pass on your system?

Best,

Dominic

**Comment by davidfdzp** [comment]
Dear Dominic,

I am using gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

The only failed test is 15, but after 17 is passed, no more tests are
completed. The test 18 process has been running all night and still
did not finish (?!)

Thank you for the support.

Best,

David

2019-03-05 16:33 GMT+01:00, DominicDirkx <notifications@github.com>:

**Comment by DominicDirkx** [comment]
Dear David,

That's very curious, needless to say it's not supposed to do that. The numbering the tests differs, depending on the settings. What is the name of test 18 on your system?

Best,

Dominic

**Comment by davidfdzp** [comment]
Dear Dominic,

I have completed the unit tests on a native Ubuntu 16.04 without any
major issue. All tests passed and completed. But on the WSL Ubuntu
18.04 for Windows 10 this is what happens (?!)

Test 18 is test_MeanToEccentricAnomalyConversion

The last lines at LastTest.log.tmp are from test 17:

17/248 Testing: test_UnitConversions
17/248 Test: test_UnitConversions
Command: "/home/david/tudatBundle/tudatBundle/tudat/bin/unit_tests/test_UnitConversions"
Directory: /home/david/tudatBundle/build-tudatBundle-Desktop-Default/tudat/Tudat/Astrodynamics/BasicAstrodynamics
"test_UnitConversions" start time: Mar 05 19:23 STD
Output:
----------------------------------------------------------
Running 14 test cases...

*** No errors detected
<end of output>
Test time =   0.05 sec
----------------------------------------------------------
Test Passed.
"test_UnitConversions" end time: Mar 05 19:23 STD
"test_UnitConversions" time elapsed: 00:00:00
----------------------------------------------------------

Best,

David

2019-03-06 9:26 GMT+01:00, DominicDirkx <notifications@github.com>:

**Comment by DominicDirkx** [comment]
Dear David,

I'm happy to hear that the code is working well for you on Ubuntu 18.04. I think you're the first one to try Tudat on WSL Ubuntu, meaning these errors you get are 'new' to us. The issue with the long double may be difficult to solve. The C++ standard does _not_ require long double to be 80 bit, but to be 'at least' 64 bit. My guess is that the long double is a 64 bit floating point on your system. To get it to skip over the test_MeanToEccentricAnomalyConversion, you can comment it (for now) in the CMakeLists here:

https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/BasicAstrodynamics/CMakeLists.txt#L102-L104

Alternatively, you could try to remove the long double tests in test_MeanToEccentricAnomalyConversion, by commenting:

https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestConvertMeanAnomalyToEccentricAnomaly.cpp#L393-L395
https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestConvertMeanAnomalyToEccentricAnomaly.cpp#L400-402

The double/long double issue may cause some other problems in running your unit tests, but should not limit your use of Tudat for most applications. Please let us know how your testing proceeds, and we'd be happy to help you out further,

Best,

Dominic

**Comment by davidfdzp** [comment]
Dear Dominic,

I installed Tudat very quick and all tests passed in Ubuntu 16.04 native. I haven't upgraded yet, but the WSL installed version is 18.04, on Windows 10.

When commenting lines from 102 to 104 at /tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeLists.txt, test 15 still fails, but now test 18 has finished in 11.04 s, although failed too. Here are the contents of LastTest.log about test 18:

18/247 Testing: test_MeanToHyperbolicEccentricAnomalyConversion
18/247 Test: test_MeanToHyperbolicEccentricAnomalyConversion
Command: "/home/david/tudatBundle/tudatBundle/tudat/bin/unit_tests/test_MeanToHyperbolicEccentricAnomalyConversion"
Directory: /home/david/tudatBundle/build-tudatBundle-Desktop-Default/tudat/Tudat/Astrodynamics/BasicAstrodynamics
"test_MeanToHyperbolicEccentricAnomalyConversion" start time: Mar 06 16:04 STD
Output:
----------------------------------------------------------
Running 5 test cases...
/home/david/tudatBundle/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/unitTestConvertMeanAnomalyToHyperbolicEccentricAnomaly.cpp(337): error: in "test_mean_to_hyperbolic_eccentric_anomaly_conversion/test_convertMeanAnomalyToEccentricAnomaly_nearParabolic_random_double": check failedMeanAnomalies.empty( ) has failed
One or multiple errors occurred during random sampling.
The values leading to these errors have been written to the following file:
/home/david/tudatBundle/tudatBundle/tudat/Tudat/../Tudat/Astrodynamics/BasicAstrodynamics/UnitTests/ErrorReportConversionMeanToHyperbolicEccentricAnomalyLongDoubleParabolicRunAt20190306T160500.txt
*** 1 failure is detected in the test module "Master Test Suite"
<end of output>
Test time =  11.04 sec
----------------------------------------------------------
Test Failed.
"test_MeanToHyperbolicEccentricAnomalyConversion" end time: Mar 06 16:05 STD
"test_MeanToHyperbolicEccentricAnomalyConversion" time elapsed: 00:00:11
----------------------------------------------------------

Then, test 19 (test_KeplerPropagator) has not finished after half an hour...

Removing the long double tests in test_MeanToEccentricAnomalyConversion test 15 (OrbitalElementConversions) still fails, in 0.04 s:
Test 18 (MeanToEccentricityAnomalyConversion) never ends...

If I do both things, then it is the same, it fails at tests 15 and 18, then 19 never ends.

main(){
printf("Storage size for long double: %d \n", sizeof(long double)); /* says 16 */
printf("Storage size for double : %d \n", sizeof(double)); /* says 8 */
printf("Storage size for int : %d \n", sizeof(int)); /* says 4 */
}

uname -a
Linux 4.4.0-17134-Microsoft #523-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

Best,

David

**Comment by DominicDirkx** [comment]
Dear David,

These errors are most curious. We have a range of users on various versions of Linux, Windows and mac OS, and I'm afraid you've uncovered a 'new' bug. My advice to find our what the issue is: turn off the tests that run 'forever' as you encounter them, and let us know which tests go wrong. This may allow us to identify the common element between the offending tests that are causing these errors.

For the rest of this week, I'm afraid my response will be quite slow (all day in meetings),

Best,

Dominic

**Comment by davidfdzp** [comment]
Dear Dominic,

Originally, test 15, OrbitalElementConversions, failed, then test 18
took a lot of time. It never finished.

Then, I commented test 18 MeanToEccentricAnomalyConversion on
tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeLists.txt

Test 18 becomes MeanToHyperbolicEccentricAnomalyConversion, which
fails, and the test KeplerPropagator never finished.

After that I have commented KeplerPropagator test. Test 19 becomes
AccelerationModel. test_TimeConversions fails and more, but all tests
finished (in 2447 s).

The list of failed tests is at
~/tudatBundle/build-tudatBundle-Desktop-Default/Testing/Temporary/LastTestsFailed.log
and it is:
15:test_OrbitalElementConversions
18:test_MeanToHyperbolicEccentricAnomalyConversion
22:test_TimeConversions
76:test_DopplerModels
148:test_TimeScaleConverter
150:test_TimeTypes
187:test_UnscentedKalmanFilter
210:test_SofaTimeConversions

I am not in a hurry, just playing, so answer when it is possible for
you, of course. Thank you very much.

Best,

David

2019-03-07 10:42 GMT+01:00, DominicDirkx <notifications@github.com>:

**Comment by DominicDirkx** [comment]
Thanks, that doesn't look so bad, and does seem to point to an issue with the use of long double. If you post the LastTest.log file from this run of all tests:

http://tudat.tudelft.nl/installation/troubleshooting/installationErrors.html#failed-unit-tests

I'll have a look,

Best,

Dominic

**Comment by davidfdzp** [comment]
Find it attached.

[LastTest.log](https://github.com/Tudat/tudat/files/2945594/LastTest.log)

Best,

David

**Comment by DominicDirkx** [comment]
Dear David,

I can confirm that all the unit test failures (with the exception of one, which is known to fail in some cases), is due to long double floating point variables not being handled correctly (most likely due to 64-bit instead of 80-bit representation).

The failures you have, you can safely ignore for now. The remaining issue is the fact that you had to remove several unit tests, preventing you from testing some of the conversion functions.

Ideally, we would have a CMAKE argument (something like INCLUDE_EXTENDED_PRECISION_FUNCTIONALITY), which is set to true by default, but can be set to false, preventing all long double tests from being run, and making all the tests pass in your situation.

I will keep this issue open to remind us to make this modification, but it may take us a while to get to it. If you are not planning to use the extended precision functionality, I think you can safely proceed with the code. Which type of applications were you considering for Tudat?

Best,

Dominic

**Comment by davidfdzp** [comment]
Dear Dominic,

I have been executing the Application Tutorial without any issue. I am planning to use Tudat this way. I also think I can safely proceed, thank you!

Best,

David

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
