### ISSUE TITLE
Unable to find the requested Boost libraries: boost_date_time boost_serialization

### ISSUE THREAD

**Issue by lievebouwman** [Tudat/tudat#515]
Hello,

When trying to make a new project in QT creator on a Mac by installing the Pykep toolbox (https://github.com/ChrisAndre/pykep ), it seems unable to find the requested boost libraries for this toolbox. I set the python version to the latest (3.7.2) and run CMake in the terminal, which gives me the following:

```
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OS detected: Darwin
-- CXX Compiler detected: Clang
-- CMake additional search path for libraries: /usr/local/boost/usr/lib
-- Performing Test CLANG_TEMPLATE_DEPTH
-- Performing Test CLANG_TEMPLATE_DEPTH - Success
-- Enabling '-ftemplate-depth=256' compiler flag required since boost 1.54.
-- Performing Test ALL_C11
-- Performing Test ALL_C11 - Success
-- Enabling '-std=c++11' compiler flag
-- Performing Test CXX_FPIC_FLAG
-- Performing Test CXX_FPIC_FLAG - Success
-- Enabling '-fPIC' compiler flag
-- CXX compilation flags:  -ftemplate-depth=256 -std=c++11
-- C compilation flags:  -fPIC
-- Found PythonInterp: /usr/local/bin/python3.7m (found version "3.7.2") 
-- Python interpreter: /usr/local/bin/python3.7m
-- Python interpreter verison: 3.7
-- Python includes path: /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m
-- Python modules install path: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
-- Python library name: /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib
-- Required Boost libraries: serialization;date_time;python3
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (FIND_PACKAGE)


CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (FIND_PACKAGE)


CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (FIND_PACKAGE)


CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1587 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:66 (FIND_PACKAGE)


CMake Error at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1900 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_serialization
          boost_date_time
          boost_python3

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:66 (FIND_PACKAGE)


-- Detected Boost version: 106900
-- Boost include dirs: /usr/local/include
-- Boost libraries: 
-- Configuring incomplete, errors occurred!
```

I have downloaded the latest version of boost (1_69_0) and followed the installation steps (https://www.boost.org/doc/libs/1_69_0/more/getting_started/index.html). Before, I have also tried it with an older version of boost, but with the same problems. I have tried several lines of code to set the boost root and boost librarydir, but although it recognizes these directories, it still is not able to find the libraries (which are actually located there). So something like:

```
SET(BOOST_LIBRARYDIR usr/local/boost_1_69_0/boost/usr/lib)
SET(BOOST_ROOT usr/local/boost_1_69_0/boost)
```

does not seem to resolve the problem. Also, defining the libraries as "static" did not work.

Any help on this problem?
Thanks!

**Comment by DominicDirkx** [comment]
Hi Lieve,

Turn the USE_PAGMO cmake argument to ON (Projects->CMake in Qt), and rerun CMake. This will compile the boost libraries you need,

Best

Dominic

**Comment by lievebouwman** [comment]
Hi Dominic,

As my "configuration failed" it seems that I am not able to turn the USE_PAGMO on. I tried adding it manually as a boolean (see picture), but this doesn't seem to change anything.

Best,
Lieve
<img width="926" alt="Schermafbeelding 2019-03-11 om 10 11 14" src="https://user-images.githubusercontent.com/33669892/54112322-30b1ab80-43e6-11e9-9fb1-b93ecbf57f0a.png">

**Comment by DominicDirkx** [comment]
I need a little bit more information. What is the Cmake output from this?

**Comment by lievebouwman** [comment]
Running "/Applications/CMake.app/Contents/bin/cmake -E server --pipe=/tmp/cmake-mvNIrs/socket --experimental" in /Users/lievebouwman/build-pykep-master-Desktop-Default.
Starting to parse CMake project for Qt Creator.
OS detected: Darwin
CXX Compiler detected: Clang
CMake additional search path for libraries: /usr/local/boost/usr/lib
Enabling '-ftemplate-depth=256' compiler flag required since boost 1.54.
Enabling '-std=c++11' compiler flag
Enabling '-fPIC' compiler flag
CXX compilation flags:  -ftemplate-depth=256 -std=c++11
C compilation flags:  -fPIC
Python interpreter: /usr/bin/python
Python interpreter verison: 2.7
Python includes path: /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
Python modules install path: /Library/Python/2.7/site-packages
Python library name: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
Required Boost libraries: serialization;date_time;python
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (FIND_PACKAGE)


CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (FIND_PACKAGE)


CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (FIND_PACKAGE)


CMake Error at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1900 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_serialization
          boost_date_time
          boost_python

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:66 (FIND_PACKAGE)


Detected Boost version: 106900
Boost include dirs: /usr/local/include
Boost libraries: 
Configuring incomplete, errors occurred!
See also "/Users/lievebouwman/build-pykep-master-Desktop-Default/CMakeFiles/CMakeOutput.log".
CMake Project parsing failed.

**Comment by transferorbit** [comment]
This may not help the main issue, but it appears that the older version of Python is being used:
>...
>`Python interpreter: /usr/bin/python`
>`Python interpreter verison: 2.7`
>...

When you installed python v3.7.2, didn’t Anaconda automatically adjust your `$PATH` to include the new version? My `$PATH` includes the following, for example: `/Users/kevin/anaconda3/bin`

It may be worth figuring out how to get CMake to use the new python version as using Apple’s built-in python comes with limitations for development purposes. Maybe these links could help:
- [Using Boost Python with CMake on OS X (stackoverflow)](https://stackoverflow.com/questions/40554607/using-boost-python-with-cmake-on-os-x)
- [A minimal CMake boost::python example for MacOS (see the readme)](https://github.com/mkirchner/boost-python-cmake-macos-helloworld)

**Comment by lievebouwman** [comment]
Indeed, Anaconda does not adjust the path automatically, but I have forced CMake to use the latest python version by including:

`SET(PYTHON_EXECUTABLE /usr/local/bin/python3.7)`

in my CMakelists.txt. 
Unfortunately, this does not resolve the problem.

**Comment by DominicDirkx** [comment]
Hi Lieve,

With this issue and issue #514 (and the e-mail conversation) I'm a bit confused on what your status exactly is at the moment. The issues seem to be strongly related. Could you condense your issue into a single Github thread?

Best,

Dominic

**Comment by lievebouwman** [comment]
Hi Dominic,

With both issues I haven't made progress so far. The goal is to install the Pykep module into QTcreator, either within tudatBundle or as a new project, dependent on which of them is the easiest to solve. So probably the best would be to close the other issue if I have this specific issue (Pykep as a new project) solved, or the other way around?

Best,
Lieve

**Comment by DominicDirkx** [comment]
The first thing to fix is, I think, this one. Could you elaborate a bit more on what happens when you set 'USE_PAGMO' to ON in Qt? What output does it provide? It should be trying to compile your mission boost libraries. I think that the CMake output you provided is not the right error output. Could you explain the process you go through that leads to 'Configuration failed'?

**Comment by lievebouwman** [comment]
What I do is I import the CMakelists.txt file as a new project in QT Creator. So I don't use anything from either Tudat or TudatBundle (am I supposed to)? Furthermore, I have manually downloaded the boost_1_69_0 version in my directory usr/local. 

When opening this project, it immediately starts running the CMakelists.txt file and as it cannot find the requested boost libraries, the configuration fails. Then I go to project --> CMake, which shows the "configuration failed" and does not provide any options to turn on or off. I manually added a boolean where I write USE_PAGMO as setting and turn it on. However, when I rerun CMake, it seems like nothing has been changed. The output from "general messages" is then the following:

Running "/Applications/CMake.app/Contents/bin/cmake -E server --pipe=/tmp/cmake-1D9wwd/socket --experimental" in /Users/lievebouwman/build-pykep-master-Desktop-Default.
Starting to parse CMake project for Qt Creator.
The C compiler identification is AppleClang 10.0.0.10001044
The CXX compiler identification is AppleClang 10.0.0.10001044
Check for working C compiler: /usr/bin/clang
Check for working C compiler: /usr/bin/clang -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /usr/bin/clang++
Check for working CXX compiler: /usr/bin/clang++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
OS detected: Darwin
CXX Compiler detected: Clang
CMake additional search path for libraries: /usr/local/boost/usr/lib
Performing Test CLANG_TEMPLATE_DEPTH
Performing Test CLANG_TEMPLATE_DEPTH - Success
Enabling '-ftemplate-depth=256' compiler flag required since boost 1.54.
Performing Test ALL_C11
Performing Test ALL_C11 - Success
Enabling '-std=c++11' compiler flag
Performing Test CXX_FPIC_FLAG
Performing Test CXX_FPIC_FLAG - Success
Enabling '-fPIC' compiler flag
CXX compilation flags:  -ftemplate-depth=256 -std=c++11
C compilation flags:  -fPIC
Found PythonInterp: /usr/local/bin/python3.7 (found version "3.7.2") 
Python interpreter: /usr/local/bin/python3.7
Python interpreter verison: 3.7
Python includes path: /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m
Python modules install path: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Python library name: /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib
Required Boost libraries: serialization;date_time;python3
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:68 (FIND_PACKAGE)


CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:68 (FIND_PACKAGE)


CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:786 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:892 (_Boost_COMPONENT_DEPENDENCIES)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1523 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:68 (FIND_PACKAGE)


CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1587 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:68 (FIND_PACKAGE)


CMake Error at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindBoost.cmake:1900 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_serialization
          boost_date_time
          boost_python3

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:68 (FIND_PACKAGE)


Detected Boost version: 106900
Boost include dirs: /usr/local/include
Boost libraries: 
Configuring incomplete, errors occurred!
See also "/Users/lievebouwman/build-pykep-master-Desktop-Default/CMakeFiles/CMakeOutput.log".
CMake Project parsing failed.

Is this enough information, or do I need to provide anything else?
[CMakeLists.txt](https://github.com/Tudat/tudat/files/2952922/CMakeLists.txt)

**Comment by DominicDirkx** [comment]
In that case, check whether the three missing boost libraries are indeed missing in the boost include path. When you say you've 'manually downloaded boost', have you also compiled boost?

**Comment by lievebouwman** [comment]
The three boost libraries are present in the folder usr/local/include/boost as .hpp files and also in usr/local/boost_1_69_0/usr/lib as .dylib.
I followed the boost getting started manual (https://www.boost.org/doc/libs/1_69_0/more/getting_started/unix-variants.html#prepare-to-use-a-boost-library-binary) and then specifically step 5.1. This took about ±30 min, where warnings but no errors were generated.

**Comment by DominicDirkx** [comment]
In that case, my guess is that you need static libraries, instead of dynamic libraries, for Boost. Check the boost compilation guide for how to do this. If you choose to use Pykep within the tudatBundle directory, you may be able to use the Tudat setup to compile boost (but will need to update to 1.69).

**Comment by lievebouwman** [comment]
Hi Dominic,

- When trying to build static libraries, I used the following commands in the terminal:

```
cd boost_1_69_0/
./bootstrap.sh --prefix=usr/local
./b2 install link=static
```

But errors are generated:
```
In file included from ./boost/python/detail/prefix.hpp:13:
./boost/python/detail/wrap_python.hpp:50:11: fatal error: 'pyconfig.h' file not found
# include <pyconfig.h>
          ^~~~~~~~~~~~
1 error generated.

    "g++"   -fvisibility-inlines-hidden -m64 -O3 -Wall -fvisibility=hidden -gdwarf-2 -fexceptions -Wno-inline  -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE -DBOOST_PYTHON_STATIC_LIB -DNDEBUG  -I"." -I"/Users/lievebouwman/anaconda3/include/python3.7" -c -o "bin.v2/libs/python/build/darwin-4.2.1/release/link-static/python-3.7/threading-multi/visibility-hidden/list.o" "libs/python/src/list.cpp"

...failed darwin.compile.c++ bin.v2/libs/python/build/darwin-4.2.1/release/link-static/python-3.7/threading-multi/visibility-hidden/list.o...
darwin.compile.c++ bin.v2/libs/python/build/darwin-4.2.1/release/link-static/python-3.7/threading-multi/visibility-hidden/long.o
In file included from libs/python/src/long.cpp:5:
In file included from ./boost/python/long.hpp:8:
In file included from ./boost/python/detail/prefix.hpp:13:
./boost/python/detail/wrap_python.hpp:50:11: fatal error: 'pyconfig.h' file not found
# include <pyconfig.h>
          ^~~~~~~~~~~~
1 error generated.

    "g++"   -fvisibility-inlines-hidden -m64 -O3 -Wall -fvisibility=hidden -gdwarf-2 -fexceptions -Wno-inline  -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE -DBOOST_PYTHON_STATIC_LIB -DNDEBUG  -I"." -I"/Users/lievebouwman/anaconda3/include/python3.7" -c -o "bin.v2/libs/python/build/darwin-4.2.1/release/link-static/python-3.7/threading-multi/visibility-hidden/long.o" "libs/python/src/long.cpp"

...failed darwin.compile.c++ bin.v2/libs/python/build/darwin-4.2.1/release/link-static/python-3.7/threading-multi/visibility-hidden/long.o...
darwin.compile.c++ bin.v2/libs/python/build/darwin-4.2.1/release/link-static/python-3.7/threading-multi/visibility-hidden/dict.o
```

- When trying to compile boost within tudatBundle I tried to follow these steps (http://tudat.tudelft.nl/installation/troubleshooting/compilingBoostManually.html). I downloaded again 1.64.0 as it is the newest version that seems available in the CMakelists.txt and I couldn't find the SHA1 code for 1.69.0. However, I seems like it is not able to compile the libraries (I have tried all of them seperately, but same error):

```
(base) mbp-van-lieve:boost_1_64_0 lievebouwman$ ./b2 toolset=gcc link=static threading=multi –build-dir=Build stage variant=release –layout=tagged cxxflags=-std=c++11 –with-date_time
notice: could not find main target –with-date_time
notice: assuming it is a name of file to create.
/Users/lievebouwman/boost_1_64_0/tools/build/src/build/property.jam:293: in validate1 from module property
error: Invalid property '<–layout>tagged': unknown feature '–layout'.
/Users/lievebouwman/boost_1_64_0/tools/build/src/build/property.jam:302: in property.validate from module property
/Users/lievebouwman/boost_1_64_0/tools/build/src/build/build-request.jam:228: in convert-command-line-element from module build-request
/Users/lievebouwman/boost_1_64_0/tools/build/src/build/build-request.jam:179: in build-request.convert-command-line-elements from module build-request
/Users/lievebouwman/boost_1_64_0/tools/build/src/build-system.jam:691: in load from module build-system
/Users/lievebouwman/boost_1_64_0/tools/build/src/kernel/modules.jam:295: in import from module modules
/Users/lievebouwman/boost_1_64_0/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/Users/lievebouwman/boost_1_64_0/boost-build.jam:17: in module scope from module
```

Also, when they would have compiled correctly, is it necessary to place any of the build folders into the tudatBundle directory?

**Comment by DominicDirkx** [comment]
I don't know where this error comes from, with the automatic Tudat build, everything runs smoothly. For Tudat, we've gone through a lot of effort to automate the compilation of boost. If you want to use our workflow, I can provide support, but for general boost compilation support, this is not the right place. 

After opening tudatBundle, set the USE_PAGMO variable to on (and apply configuration changes). When you recompile boost, it should also compile teh boost libraries you need.

**Comment by lievebouwman** [comment]
Hi Dominic,

When recompiling boost in the tudatBundle environment, I think the required libraries have been found. However, when I try to run an application I am still getting the error with respect to the serialization.h (see issue #514). I attached the compile output. Could this problem be caused by any of the libraries or any incorrect link in the CMakelists.txt files? 
For clarity I will remove issue #514, because it has now been merged into this issue.

[compile_output.txt](https://github.com/Tudat/tudat/files/2957184/compile_output.txt)

**Comment by DominicDirkx** [comment]
Hi Lieve,

What exactly are you compiling when you get this error?

**Comment by lievebouwman** [comment]
I am trying to compile/run the file main.cpp that I cloned from: https://github.com/ChrisAndre/pykep

**Comment by DominicDirkx** [comment]
Please add the CMake output you get when opening your project. Are you compiling Pykep separately, or through tudatBundle?

**Comment by lievebouwman** [comment]
Hi Dominic,

The CMake output when opening the TudatBundle project (with the Pykep folder as subdirectory) is attached. There appears to be some error about using PAGMO and PYGMO, but I turned USE_PYGMO to OFF so I am not sure where this error is coming from.
I am only running the main CMake from TudatBundle, so I think Pykep is not compiled seperately. However, I turned "Build Pykep" in CMake settings to on.

I also attached the CMakelists.txt from TudatBundle and the CMakelists.txt from the Pykep module.

[CMake_output.txt](https://github.com/Tudat/tudat/files/2960877/CMake_output.txt)
[CMakeLists.txt](https://github.com/Tudat/tudat/files/2960908/CMakeLists.txt)
[CMakeLists.txt](https://github.com/Tudat/tudat/files/2960910/CMakeLists.txt)

**Comment by DominicDirkx** [comment]
Hi Lieve,

I can confirm that on my system, the https://github.com/ChrisAndre/pykep  repository gives the same error as for you (serialize in boost::array), while the esa Pykep works fine. My guess is that our boost versions (both 1.64) are both too old, and don't yet include the boost::array serialize,

Dominic

**Comment by lievebouwman** [comment]
Hi Dominic,

Thankyou for pointing this out. I will try to install pykep from the ESA repository and potentially merge the additional features manually!

**Comment by lievebouwman** [comment]
> Hi Dominic,
> 
> Thankyou for pointing this out. I will try to install pykep from the ESA repository and potentially merge the additional features manually!

The above worked. However, some small additions are necessary for anyone trying to do this:
- change the main.cpp in the esa pykep bundle to the main.cpp from Chris Andre and add: #include "src/exposin/lambert_exposin.h"
- add the folder exposin and include this in CMakeLists.txt
- Replace the file "Array3D_operations.h" with the one from Chris Andre, because it has extra functionalities that are required

**Comment by DominicDirkx** [comment]
Great, happy to hear that you got it running!
