### ISSUE TITLE
State transition and sensitivity matrices

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#516]
Hi everyone,

for verification purposes of a POD scheme I would like to retrieve the respective state transition and sensitivity matrices but have been unable to do so so far. How can I access them?

Kind regards
Sebastian

**Comment by DominicDirkx** [comment]
From an OrbitDeterminationManager object, you can do:

```
OrbitDeterminationManager< double, double > orbitDeterminationManager =....
std::shared_ptr< propagators::CombinedStateTransitionAndSensitivityMatrixInterface > matrixInterface = 
            orbitDeterminationManager.getStateTransitionAndSensitivityMatrixInterface( );
```

The matrixInterface object then has functions (with current time as input), which return the concatenated Phi and S:

getCombinedStateTransitionAndSensitivityMatrix
getFullCombinedStateTransitionAndSensitivityMatrix

Which are equal for the single-arc case. For the multi-arc case, the getFullCombinedStateTransitionAndSensitivityMatrix includes all arc (initial) states in x and x0, and will have a lot of zeros,

Let me know if this helps you out sufficiently,

Dominic
