### ISSUE TITLE
Memory issue with multi-objective optimization

### ISSUE THREAD

**Issue by Palash-Patole** [Tudat/tudat#518]
@DominicDirkx 
Dear Dominic,

I am trying to find the optimum solution(s) to a Lambert targeting problem using the Multi Objective Evolutionary Algorithms by Decomposition (MOEA/D) algorithm of the _PaGMO_ toolbox. The iteration loop (maximum 5 iterations) for evolving the _island_ of _population size_ (25 individuals) begins but the program crashes after 3 iterations. When the PC memory performance is analyzed, I observed that at the crash, the usage reaches peak value where almost all the available memory is being used. [Option-1]

To resolve this issue, **I followed the solution suggested by you** on the Brightspace forum for one of the old post regarding the same issue- 

> What could help is defining your bodyMap outside of your fitness function. Create it as a member variable in your problem class, and reuse the same body map for each function evaluation

I implemented this solution [Option-2]. However, my application still crashes (even when it is not consuming large memory usage). The reason is unknown (debugger in windows didn't help), but I suspect that it is when the _island_ object is created (i.e even before the iteration loop begins).

I checked my header file, main cpp file containing the definition of fitness function, but I was unable to identify the error. 

I also tried using a "mutable" type "NamedBodyMap" object, but it didn't help either. [Option -3].

Can you please have a look at the code and give me some direction? I have added you as the collaborator on a private repository.

Thanks.

**Comment by DominicDirkx** [comment]
Hi Palash, please add the link to your repository here

**Comment by Palash-Patole** [comment]
Dear Dominic,

I am sorry about that. I forgot to include it.

https://github.com/Palash-Patole/Issue_resolver

Thanks.

**Comment by DominicDirkx** [comment]
A few points/questions:

- On Github, push all the necessary files, so that all I have to do to run it is pull your repository, and add your CMakeLists.txt to tudatBundle.
- Please specify which lines in which file you think are causing the error
- I see that your main function is structured a bit differently than in the example applications. Take one of the example applications, use the _**exact**_ same structure, and only change it to your problem. If this still fails, the issue lies in your problem definition. If it works, the problem lies in your current main function.

**Comment by Palash-Patole** [comment]
Dear Dominic,

- I have pushed all the necessary files on Github. I hope you can pull the repository and run the application now.

- I believe following line in the main cpp is causing problem.
https://github.com/Palash-Patole/Issue_resolver/blob/c02c9d3e36db39cd7eef47f302a2763a804bec26/Opt/iOpt_SLT_v2_3.cpp#L97
However, as I said before, I was unable to identify where exactly the error lies - definition of problem class or the fitness function. 

- I can surely try this. Thanks for the suggestion. Before I do this, I want to bring your attention to  some strange behavior of my tudatapplications/Qt Creator tool I have noticed. I hope, I can explain it properly:

1.  When you asked me to push all the necessary files to Github, I added these files to my local repository (which is different than my personal working repository), added the application to my CMakeLists.txt file and run it to make sure everything works fine with this new repository.

2. To my surprise, there was only one error and when I rectified it, I was able to get the results without the application crashing when [Option-2] mentioned in my original issue post was implemented.

3. When the same error was rectified in original .cpp file of the application in my personal working repository (not the one shared with you), I still face the issue of application crashing.

4. So, my concern now is finding out what exactly I am doing wrong with my personal working repository. I am pretty sure the application from this repository is correctly added to the CMakeLists.txt file and eventually to Qt environment (as [Option-1] mentioned in my original issue post works until it crashes due to limited available memory).    

I will try to resolve this (probably a trivial) problem on my own. Before I close this Github issue, can you just the run application once and let me know whether it works on your system?

**Comment by DominicDirkx** [comment]
Hi Palash,

Without running anything myself, doesn't this mean that you have now solved your problem? Apparently there is a difference between the two repositories (why do you have two?) you have, and you now have on that works!

Dominic

**Comment by Palash-Patole** [comment]
Dear Dominic,

Yes, I have (almost) resolved my problem.

I created two repositories to avoid sharing plethora of other files in my personal working repository which are irrelevant to this issue and to cause less confusion. I keep these multiple other files on Github personal working repository for my own use. :)

Nevertheless, many thanks for your input. I hope to identify differences between two repositories. 👍
