### ISSUE TITLE
Instalation - CXX and C Compiler could not be found

### ISSUE THREAD

**Issue by mrozemeijer** [Tudat/tudat#520]
I've followed the installation guide but I get this response when I try to configure the tudat libraries. 

![image](https://user-images.githubusercontent.com/17251685/55008912-082ed180-4fe2-11e9-9ded-2183e7e65d35.png)
![image](https://user-images.githubusercontent.com/17251685/55008934-12e96680-4fe2-11e9-9a90-706606991525.png)
[CMakeError.log](https://github.com/Tudat/tudat/files/3008789/CMakeError.log)
[CMakeOutput.log](https://github.com/Tudat/tudat/files/3008790/CMakeOutput.log)
[CMakeCache.txt](https://github.com/Tudat/tudat/files/3008792/CMakeCache.txt)

**Comment by DominicDirkx** [comment]
Dear Mark,

When asking for support, please provide sufficient information. For instance:

- Which operating system are you using
- Where in the installation guide are you when this error occurs.
- Any other information you may think is useful.

**Comment by mrozemeijer** [comment]
Sorry, I followed the instruction below the Github instead of following the manual. However now there is an error at 85% during the building of the Tudat libraries during step 5 of **3. Compile and Test Tudat Libraries**
![image](https://user-images.githubusercontent.com/17251685/55020477-2f43ce00-4ff7-11e9-8fb7-93fe332df8d1.png)

**Comment by DominicDirkx** [comment]
Hi Mark,

In which directory did you install Tudat? Did you follow the instructions here:

http://tudat.tudelft.nl/installation/downloadTudatBundle/index.html#cloning-tudat

in the warning box?

Best,

Dominic
