### ISSUE TITLE
opencv compile error

### ISSUE THREAD

**Issue by degawong** [Tudat/tudat#521]
**platform : windows 10
cmake version : 3.14.0
gcc version : gcc for x86_64-w64-mingw32 8.1.0**
error log : 
[build] [ 32%] Generating precomp.hpp.gch/opencv_flann_Debug.gch
[build] E:/opencv/build/modules/core/precomp.hpp:209:1: internal compiler error: in gt_pch_note_object, at ggc-common.c:276
[build]  }
[build]  ^
[build] libbacktrace could not find executable to open
[build] Please submit a full bug report,
[build] with preprocessed source if appropriate.
[build] See <https://sourceforge.net/projects/mingw-w64> for instructions.
[build] make.exe[2]: *** [modules/core/CMakeFiles/pch_Generate_opencv_core.dir/build.make:64: modules/core/precomp.hpp.gch/opencv_core_Debug.gch] Error 1
[build] make.exe[1]: *** [CMakeFiles/Makefile2:1412: modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
[build] make.exe[1]: *** Waiting for unfinished jobs....
[build] In file included from E:/opencv/build/modules/features2d/precomp.hpp:51:
[build] E:/opencv/modules/core/include/opencv2/core/internal.hpp:793:2: internal compiler error: in gt_pch_note_object, at ggc-common.c:276
[build]  }}
[build]   ^
[build] libbacktrace could not find executable to open
[build] Please submit a full bug report,
[build] with preprocessed source if appropriate.
[build] See <https://sourceforge.net/projects/mingw-w64> for instructions.
[build] make.exe[2]: *** [modules/features2d/CMakeFiles/pch_Generate_opencv_features2d.dir/build.make:64: modules/features2d/precomp.hpp.gch/opencv_features2d_Debug.gch] Error 1
[build] make.exe[1]: *** [CMakeFiles/Makefile2:2730: modules/features2d/CMakeFiles/pch_Generate_opencv_features2d.dir/all] Error 2
[build] In file included from E:/opencv/modules/ts/include/opencv2/ts/ts.hpp:638,
[build]                  from E:/opencv/build/modules/ts/precomp.hpp:3:
[build] E:/opencv/modules/ts/include/opencv2/ts/ts_perf.hpp:616:1: internal compiler error: in gt_pch_note_object, at ggc-common.c:276
[build]  } //namespace perf
[build]  ^
[build] libbacktrace could not find executable to open
[build] Please submit a full bug report,
[build] with preprocessed source if appropriate.
[build] See <https://sourceforge.net/projects/mingw-w64> for instructions.
[build] make.exe[2]: *** [modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/build.make:64: modules/ts/precomp.hpp.gch/opencv_ts_Debug.gch] Error 1
[build] make.exe[1]: *** [CMakeFiles/Makefile2:7208: modules/ts/CMakeFiles/pch_Generate_opencv_ts.dir/all] Error 2
[build] In file included from E:/opencv/build/modules/flann/precomp.hpp:22:
[build] E:/opencv/modules/flann/include/opencv2/flann/flann_base.hpp:300:1: internal compiler error: in gt_pch_note_object, at ggc-common.c:276
[build]  }
[build]  ^
[build] libbacktrace could not find executable to open
[build] Please submit a full bug report,
[build] with preprocessed source if appropriate.
[build] See <https://sourceforge.net/projects/mingw-w64> for instructions.
[build] make.exe[2]: *** [modules/flann/CMakeFiles/pch_Generate_opencv_flann.dir/build.make:64: modules/flann/precomp.hpp.gch/opencv_flann_Debug.gch] Error 1
[build] make.exe[1]: *** [CMakeFiles/Makefile2:1704: modules/flann/CMakeFiles/pch_Generate_opencv_flann.dir/all] Error 2
[build] [ 32%] Built target pch_Generate_opencv_imgproc
[build] E:/opencv/build/modules/highgui/precomp.hpp:198:45: internal compiler error: in gt_pch_note_object, at ggc-common.c:276
[build]  double cvGetOpenGlProp_GTK(const char* name);
[build]                                              ^
[build] libbacktrace could not find executable to open
[build] Please submit a full bug report,
[build] with preprocessed source if appropriate.
[build] See <https://sourceforge.net/projects/mingw-w64> for instructions.
[build] make.exe[2]: *** [modules/highgui/CMakeFiles/pch_Generate_opencv_highgui.dir/build.make:64: modules/highgui/precomp.hpp.gch/opencv_highgui_Debug.gch] Error 1
[build] make.exe[1]: *** [CMakeFiles/Makefile2:2366: modules/highgui/CMakeFiles/pch_Generate_opencv_highgui.dir/all] Error 2
[build] make.exe: *** [Makefile:163: all] Error 2
[build] Build finished with exit code 2
 

help me,please

**Comment by DominicDirkx** [comment]
I don't know why you post this here. This is the Tudat Github page, and is unrelated to opencv. Moreover, posting error output, followed by "help me please", is _**not**_ the way to get people to help you.

**Comment by degawong** [comment]
i am so sorry,its a big mistake,sorry.
