### ISSUE TITLE
Request to solve the compilation errors for the new version of TUDAT

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#524]
Hi everyone!
I am trying to install the new version of TUDAT that includes the arc-wise drag coefficient estimation. I managed to solve many compilation errors, but I am unable to build the estimation tools. I made modifications to the following files:

Tudat/Astrodynamics/CMakeLists.txt,
Tudat/SimulationSetup/CMakeLists.txt

and compiled the entire project to include the estimation tools such as orbit determination, observation partials and estimation set up. However, I got compilation errors when building the unit tests corresponding to estimation toolbox. Upon inspection of compilation errors, I learned that the estimation tools were still not built. I have attached the modified files and the compilation errors for your perusal.
[CMakeLists.txt](https://github.com/Tudat/tudat/files/3029197/CMakeLists.txt)
[CMakeLists.txt](https://github.com/Tudat/tudat/files/3029198/CMakeLists.txt)
[compilationErrors.txt](https://github.com/Tudat/tudat/files/3029199/compilationErrors.txt)

 Kindly help me solve this problem!

**Comment by DominicDirkx** [comment]
Hi Pugazh,

For your case, you want BUILD_WITH_ESTIMATION_TOOLS set to ON. The changes you have made effectively do teh opposite. Undo the changes you've made in the CMakeLists.txt, modify the BUILD_WITH_ESTIMATION_TOOLS (set to ON), and rerun. 

If this does not work, please post the compile error output,

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
I followed your suggestions and got the following compilation errors:
[compilationErrors.txt](https://github.com/Tudat/tudat/files/3029720/compilationErrors.txt)
These are the modified cmake files:
[CMakeLists.txt](https://github.com/Tudat/tudat/files/3029725/CMakeLists.txt)
[CMakeLists.txt](https://github.com/Tudat/tudat/files/3029726/CMakeLists.txt)

**Comment by DominicDirkx** [comment]
Could you clarify how exactly you set BUILD_WITH_ESTIMATION_TOOLS to ON, and how you have verified that CMake thinks it is on? I think this is where the problem is.

**Comment by Pugazhenthi-Sivasankar** [comment]
After checking CMake documentation, I used the command 'option' to set the value of BUILD_WITH_ESTIMATION_TOOLS to ON and 'message' command to display the value for verification. Here are the modified cmake files:
[CMakeLists.txt](https://github.com/Tudat/tudat/files/3030421/CMakeLists.txt)
[CMakeLists.txt](https://github.com/Tudat/tudat/files/3030426/CMakeLists.txt)

The compilation output displays the messages '' << Estimation Tools: ON >>" and "Estimation toolbox enabled!", which then results in building of estimation libraries. However, there are compilation errors due to the file 'variationalEquationsSolver.h'. It says that the class DependentVariableSaveSettings has no member named stateDerivativePartials_. I verified this by checking the corresponding files. Beyond this point, I don't know what to do. Here is the compilation output:
[compilationErrors.txt](https://github.com/Tudat/tudat/files/3030441/compilationErrors.txt)

**Comment by DominicDirkx** [comment]
Hi Pugazh, 

The problem seems to be that the BUILD_WITH_ESTIMATION_TOOLS is set to on in the CMakeLists (?), but not in the C++ code. 

How have you set up this version of Tudat? What are the versions (latest commit) of tudat and tudatBundle, and what are the differences w.r.t. this last version? Please check these manually using the terminal.

How have you 'verified by checking the corresonding files'?

Can you show the full output that includes  '' << Estimation Tools: ON >>" and "Estimation toolbox enabled!"?

**Comment by Pugazhenthi-Sivasankar** [comment]
Here is the full output:
[compilationErrors.txt](https://github.com/Tudat/tudat/files/3033573/compilationErrors.txt)
In the above file, lines 36 to 43 show  '' << Estimation Tools: ON >>" and "Estimation toolbox enabled!".

In the above file, lines 691 to 760 show the building of estimation tools. The problem arises when building 'createNumericalSimulator.cpp.o'. I checked the variationalEquationsSolver.h file and the following lines appear in the file:

            // Create simulation object for dynamics only.
            if( propagatorSettings_->getDependentVariablesToSave( ) != nullptr )
            {
                propagatorSettings_->getDependentVariablesToSave( )->stateDerivativePartials_ = stateDerivativePartials;
            }

The getDependentVariablesToSave( ) function returns the dependentVariables_ which, according to the description provided in the file propagationOutputSettings.h, has no member named stateDerivativePartials_.

I set up this version of Tudat by downloading the Tudat folder from the arc-wise drag coefficient estimation branch in GitHub. I created a backup of the old Tudat folder in my laptop and replaced the new Tudat folder. Then, I compiled the entire tudatBundle. 

In the terminal, I entered the tudatBundle folder and typed the command 'ls -l -a > recentModifications.txt' and got the following output:

[recentModifications.txt](https://github.com/Tudat/tudat/files/3033706/recentModifications.txt)

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Copying/pasting whole repositories is rarely a good idea. Please, use git merge/pull to set the repositories as you want them, let me know what the latest commit is (git log), and what the differences wrt the HEAD are (git diff)

**Comment by Pugazhenthi-Sivasankar** [comment]
I got my problem solved by re-installing the entire tudatBundle. I used the most recent version of the tudatBundle and the Tudat folder with the velocity_observable functionality included. My estimation application is working fine. Thanks for the help!
