### ISSUE TITLE
Failed unit test: test_RotationalStateEstimation

### ISSUE THREAD

**Issue by pgabor** [Tudat/tudat#525]
Unit test test_RotationalStateEstimation is failing (as an only test). Test log:
[LastTest.log](https://github.com/Tudat/tudat/files/3054025/LastTest.log)

At first glance it seems to be a precision issue:
```cpp
std::fabs( podOutput->parameterEstimate_( 10 ) - truthParameters( 10 ) ){1.0269204491525177e-13} exceeds 1e-13
```

Details about my system:
Arch Linux 64 bit
Linux version 5.0.2-arch1-1-ARCH (builduser@heftig-15298) (gcc version 8.2.1 20181127 (GCC)) #1 SMP PREEMPT Thu Mar 14 18:47:49 UTC 2019

CPU:
[cpu.txt](https://github.com/Tudat/tudat/files/3054048/cpu.txt)

If anything else is needed,  let  me know.

Best regards,
Gábor

**Comment by DominicDirkx** [comment]
Dear Gabor,

Indeed, this is nothing to worry about. It is simply a matter of different rounding error on your system, compared to others that have used the code. We'll update the tolerance in a future commit.

@mchambe Could you modify this tolerance in a future commit?

**Comment by pgabor** [comment]
Sounds nice! Thanks for the fast response!
