### ISSUE TITLE
Small error in observation viability checks

### ISSUE THREAD

**Issue by mchambe** [Tudat/tudat#527]
Hi Dominic,
As discussed earlier, I have noticed a small issue in the function getLinkEndIndicesForObservationViability (https://github.com/Tudat/tudat/blob/master/Tudat/SimulationSetup/EstimationSetup/createObservationModel.cpp#L86-L234), defined in file createObservationModel.cpp.

When dealing with multiple-way tracking, and if the link end identifier of the transmitter is identical to that of the receiver, then the observation viability is only checked once while it should be done twice. That occurs because of the if... else if... structure that prevents the "receiver" link end from being verified if the link end to be checked has already been identified as corresponding to the "transmitter" one. Changing the structure to if...if ... might (I think) solve it? It seems to work for my own POD application.

Best regards,

Marie

**Comment by DominicDirkx** [comment]
Thanks for pointing this out! I had a look, and think your approach for the fix is the best idea, I've just update the code, reran all the unti tests, and pushed the bug fix.
