### ISSUE TITLE
Failed Unit Test : test_UnifiedStateModelModifiedRodriguesParameterElementConversions

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#530]
Operating System : Windows 10 64 bit

Unit test failed and the error occured during build as well. Modified rodrigues parameter element conversions failed during build and was not found during unit test. 
[Error_010519.txt](https://github.com/Tudat/tudat/files/3134654/Error_010519.txt) is a file with the complie errors. 

Please let me know what to do to fix it.

**Comment by DominicDirkx** [comment]
The error is due to the path where you have installed Tudat. See the warning in the install guide when downloading Tudat.

**Comment by RajathPai95** [comment]
I shall try installing it directly into the directory and will close the issue if this does not recur. Thank you

**Comment by RajathPai95** [comment]
The unit tests completed after installation directly into the directory but multiple unit tests failed. Here is the compile output and error  file.
[Error_010519_02.txt](https://github.com/Tudat/tudat/files/3135877/Error_010519_02.txt)

**Comment by DominicDirkx** [comment]
Hi Rajath,

Could add the full error  log files (see tudat website for where to find them). Also, could you verify that you are using the latest version of tudat, by posting the identifier for the last tudat commit?

Thanks,

Dominic

**Comment by RajathPai95** [comment]
Hey Dominic,

Thanks for the response, the tudat was pulled the day before, so I believe it is the latest. I pulled the code from the command line so I'm unsure where to check for the identifier.

The error files are 
[LastTest.log](https://github.com/Tudat/tudat/files/3137404/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/3137405/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
Hi Rajath,

If you type 'git log', you'll get a list of the last commits,

Dominic

**Comment by RajathPai95** [comment]
Hey Dominic,

Thank you, here you go 
[Gitlog_020518.txt](https://github.com/Tudat/tudat/files/3137444/Gitlog_020518.txt)

**Comment by DominicDirkx** [comment]
Hi Rajath,

There have been some updates since. Could you update tudat (not tudatBundle, just tudat) to the latest version, and recompile, then rerun, all unit tests?

Dominic

**Comment by RajathPai95** [comment]
Hey Dominic,

I apologise that I bother you with this, but what exactly do you mean by updating tudat. I went through the doucmentation all over to understand it. I'm not sure I follow. I would really appreciate some more information or a section of the documentation that refers to this. 

Regards,
Rajath

**Comment by DominicDirkx** [comment]
Have a look here:

http://tudat.tudelft.nl/installation/creatingNewApps.html#updating-your-local-repository-from-github

**Comment by RajathPai95** [comment]
Hey Dominic,

I'm not sure what exactly went wrong, but i tried to follow the instructions followed for tudatAssignment for the tudat code itself. I found that the remote repository didn't work out the same way. You can check what i did here. It ended up not merging but the fetch and pull did not work out. I'm not sure what I'm doing wrong. If this is due to my misunderstanding of the instructions, please correct me.

[tudat_update_error.txt](https://github.com/Tudat/tudat/files/3138385/tudat_update_error.txt)

**Comment by RajathPai95** [comment]
Error was traced to the usgae of an older version of MinGW(5.3.0)
