### ISSUE TITLE
CMake Build Error  after installation MacOS  

### ISSUE THREAD

**Issue by NickPoelstra** [Tudat/tudat#531]
Operating System: MacOS Mojave version: 10.14.4
Qt creator: 4.9.0 

Error below, full text file of compile output is attached

Error in initial build of CMake:
2 errors generated. 
make[2]: ***[tudat/Tudat/SimulationSetup/EstimationSetup/CMakeFiles/tudat_estimation_setup.dir/createNumericalSimulator.cpp.o] Error 1
make[1]: *** [tudat/Tudat/SimulationSetup/EstimationSetup/CMakeFiles/tudat_estimation_setup.dir/all] Error 2
make: *** [all] Error 2
11:54:17: The process "/Applications/CMake.app/Contents/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"

[Compile Error Initial Build N_Poelstra MacOS10_14_4 QT4_9_0.txt](https://github.com/Tudat/tudat/files/3156831/Compile.Error.Initial.Build.N_Poelstra.MacOS10_14_4.QT4_9_0.txt)

**Comment by Perchenko** [comment]
Good evening! 
I have absolutely the same problem. Could you tell please how it was solved?

**Comment by DominicDirkx** [comment]
Hi, Could you also post your error output, and the details of your setup. Then we can have a look,

Dominic

**Comment by Perchenko** [comment]
I have macOS Mojave 10.14.5
Clang version:
(base) MacBook-Pro-Lisa:~ lisaperchenko$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
GCC version:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Kit settings:
<img width="807" alt="Снимок экрана 2019-07-22 в 10 57 17" src="https://user-images.githubusercontent.com/44770092/61619652-94d75c80-ac6f-11e9-8dcc-953c5acf290b.png">
 
And attached file with errors:
[compile error.txt](https://github.com/Tudat/tudat/files/3416481/compile.error.txt)

**Comment by DominicDirkx** [comment]
Thanks, a few other small questions to diagnose your problem:

- Which version of Tudat are you using (what is the last commit in the .../tudatBundle/tudat directory, and in the .../tudatBundle directory?)
- Could you also post the CMake output (General Messages when reopening Qt and tudatBundle)?

**Comment by Perchenko** [comment]
.../tudatBundle: Latest commit 9e06e12  on 10 Feb
.../tudatBundle/tudat: Latest commit c6b162e  on 10 Feb
[General_message_errors.txt](https://github.com/Tudat/tudat/files/3416794/General_message_errors.txt)

**Comment by DominicDirkx** [comment]
Hi,

Could you try:
- Updating tudatBundle/tudat to the latest commit in the master branch
- Updating tudatBundle/tudatExampleApplications to the latest commit in the master branch

Also, could you attach the clean General messages after closing and reopening Qt? Your file seems to contain the concatenated output of several runs of CMake

Dominic

**Comment by DominicDirkx** [comment]
If the above steps don't work, try uninstalling XCode, and then installing -only- the command line tools, using the terminal command:

xcode-select --install

We have had some problems in the past with XCode versions/types (I'm not a Mac guy, so I can't tell you about any of the how/why of this),

Dominic

**Comment by DominicDirkx** [comment]
Problem has been identified: use of template keyword before calling updateStateDerivativeModelSettings in variationalEquationsSolver. Removing template keywords solves the problem.
