### ISSUE TITLE
Cmake parsing failed

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#533]
Hey Dominic,

I received the following error after attempting to install tudat and build it. 
"Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error at tudat/Tudat/CMakeLists.txt:119 (message):
  Doxygen is needed to build the documentation.  Please install it correctly."

System Information :
QT 4.9.0 
Cmake 3.14.2
Windows 10 64 bit 

Error files 
[CMakeOutput.log](https://github.com/Tudat/tudat/files/3166862/CMakeOutput.log)
[CMakeError.log](https://github.com/Tudat/tudat/files/3166863/CMakeError.log)

I was configuring the build and after applying the changes(switching on documentation and Pagmo,) the configuration failed and the above error logs were created. Hopefully, it's a simple fix but I didnt find any  similar issues raised.

**Comment by DominicDirkx** [comment]
Hi Rajath,

Well, if you switch on 'BUILD_DOCUMENTATION', I'd suggest switching it off. That should take care of this issue,

Dominic

**Comment by RajathPai95** [comment]
I think it worked, but this was in "General messages". 

_CMake Project was parsed successfully.
C++ Indexer: Skipping file "D:/tudatBundle/pagmo2/include/pagmo/detail/cec2014_data.hpp" because it is too big.
C++ Indexer: Skipping file "D:/tudatBundle/pagmo2/include/pagmo/detail/cec2013_data.hpp" because it is too big.
C++ Indexer: Skipping file "D:/tudatBundle/pagmo2/include/pagmo/detail/cec2013_data.hpp" because it is too big._

CEC is used as a PAGMO comparison test and I feel that this affects it. Should I open a new issue with this? Is there anything I can do to avoid this at this point? Or will windows always fail to work because of the character limits.

**Comment by DominicDirkx** [comment]
Hi Rajath,

No, that's ok, this is known to happen. This pagmo issue is not a file path length issues, but a file size issue. Nothing to be done abou it for now,

Dominic
