### ISSUE TITLE
Failed tests on Ubuntu 18.04

### ISSUE THREAD

**Issue by przecze** [Tudat/tudat#534]
After fresh clone and build of tudatBundle I have numerous failed tests.
See log:
https://gist.githubusercontent.com/przecze/5b8f9c51652d7dfd9719ccdf2f70f63c/raw/9e0473c121030dee868f3e73a63c318e3f5353d1/LastTest.log

Errors include messages like this:
```
Toolkit version: N0065
 
SPICE(NOSUCHFILE) --
 
The attempt to load
"../tudat/Tudat/../Tudat/External/SpiceInterface/Kernels/pck00010.tpc" by the
routine FURNSH failed. It could not be located.
 
A traceback follows.  The name of the highest level module is first.
furnsh_c --> FURNSH --> ZZLDKER
 
Oh, by the way:  The SPICELIB error handling actions are USER-TAILORABLE.  You
can choose whether the Toolkit aborts or continues when errors occur, which
error messages to output, and where to send the output.  Please read the ERROR
"Required Reading" file, or see the routines ERRACT, ERRDEV, and ERRPRT.
```

OS: Ubuntu 18.04
tudatBundle version: 9e06e129ec97c687eaadcfb1513f8675764cfe28
tudat version: c6b162e066b834019b133f8fe89ef8f4ff1047b1
compiler: g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by DominicDirkx** [comment]
Could you please provide some details on:
- Operating System
- Tudat version
- Compiler version

Also, the link you post does not seem to work for me. When you post this extra information, we'll have a look to see what's going wrong,

Dominic

**Comment by przecze** [comment]
hi, I updated the issue with the required info. Check if you can view the gist now.

**Comment by DominicDirkx** [comment]
Can you verify that the Spice kernels that it's complaining don't exixt, actually do exist?

**Comment by przecze** [comment]
They're present, at least one of them:
```
~/repos/tudatBundle:master$ find . -name  pck00010.tpc
./tudat/Tudat/External/SpiceInterface/Kernels/pck00010.tpc
```

**Comment by DominicDirkx** [comment]
Hmmm, very strange. It's not really a nice fix, but could you try modifying this line:

https://github.com/Tudat/tudat/blob/master/Tudat/External/SpiceInterface/spiceInterface.cpp#L285

so that the path to your Spice kernels is hard-coded, instead of retrieved automatically.?

**Comment by przecze** [comment]
I tired setting the hardcoded path, but neither relative nor absolute path to kernels dir worked.
I added the line:
```
std::cout<<"kernelPath: "<<input_output::getSpiceKernelPath()<<std::endl;
```
And it turns out the path is found correctly:
```
kernelPath: ../tudat/Tudat/../Tudat/External/SpiceInterface/Kernels/
```
I try to do `ls ../tudat/Tudat/../Tudat/External/SpiceInterface/Kernels/` in the build directory, where I did `cmake ..` and where I do `ninja test` and it works correctly. Two `..` in the path seem intriguing, but well, it should work.

I also noticed other errors in the log, like this one:
```
unknown location(0): fatal error: in "test_aerodynamic_acceleration_force_moment_models/testAerodynamicForceDirectionInPropagation": std::runtime_error: Pds gravity field data file could not be opened: ../tudat/Tudat/../Tudat/External/GravityModels/Earth/egm96.txt
```
and this:
```
unknown location(0): fatal error: in "test_tabulated_atmosphere/testTabulatedAtmosphereAtSeaLevel": std::runtime_error: Data file could not be opened:../tudat/Tudat/../Tudat/External/AtmosphereTables/USSA1976Until100kmPer100mUntil1000kmPer1000m.dat
```
(they are in the gist I shared)

So it seems like the problem isn't only with spice kernels, resolving relative paths to External is a general problem.

For clarity, I'm doing:
```
cd tudatBundle
mkdir build
cd build
cmake -G Ninja ..
ninja
ninja test
```
So the tests should be executed in build dir, so relative paths should work correctly.

**Comment by przecze** [comment]
Ok, so it turns out that pwd for tests in not `build`. I checked it, and for example for `unitTestAerodynamicMomentAndAerodynamicForce` it is `build/tudat/Tudat/Astrodynamics/Aerodynamic`. So relative paths to resources are invalid. Is this expected? Shouldn't pwd be the build directory?

**Comment by DominicDirkx** [comment]
It seems you are not using the workflow for Tudat that we recommend, as we do not make use of ninja. If you want to use Ninja, that's fine, but then we are not going to troubleshoot your issues. We simply do not have the manpower to solve all issues for alternative workflows.

**Comment by przecze** [comment]
okay, will try to build it using make.
