### ISSUE TITLE
Thrust not applied correctly (Implementation DirectionBasedForceGuidance )

### ISSUE THREAD

**Issue by mrozemeijer** [Tudat/tudat#536]
During the writing of my thesis code, I have stumbled upon an issue. How does the DirectionBasedForceGuidance function be linked to the ThrustAccelerationSettings I could not find it on the doxygen page. I have applied the thrust according to the thrustAccelerationFromFileExample however it keeps throwing this warning:
Warning, body-fixed frame to propagation frame not yet implemented for DirectionBasedForceGuidance. The function will return a unit rotation to represent the rotation from body-fixed to inertial frame. 
However, it does not calculate the orientation correctly since if the body starts at 0m and 0m/s. The code is in my fork of Tudat

**Comment by DominicDirkx** [comment]
Hi Mark,

Could you:
- Provide a link to your application code on Github
- Provide a link to your Tudat code, if you've made any modifications to Tudat itself,
- Give a short explanation what you want the current version of yor code ti do

I'm not sure what you mean with: "However, it does not calculate the orientation correctly since if the body starts at 0m and 0m/s"

why is this an indication that it is not working?

**Comment by mrozemeijer** [comment]
The link for the code
https://github.com/mrozemeijer/tudatBundle.git

It is under:
tudatBundle\thesisTool\ThesisTool\ThesisTool.ccp
As far as I know, I have not made any changes to the Tudat code itself.

The current version of the code should do nothing more than launch a vehicle from the ground and land back on earth.

With regard to the second to last sentence I forgot to finish it. It should have said that the even though I applied an initial flight path angle to the vehicle when starting from an initial altitude of 0m and an initial velocity of 0m/s the vehicle goes down instead of up.

**Comment by DominicDirkx** [comment]
Hi Mark,

The fact that the vehicle is going down could simply be due to the fact that gravity is greater than thrust. Save the gravitational acceleration and thrust acceleration as dependent variables, and check to see whether this is the case.

Concerning the thrust, please be more specific:
- Which exact thrust direction/magnitude algorithm you want to use with this code
- How the numerical results do/don't correspond to this
- Where/how in the code you are accomplishing this, with links to the lines in your code, for instance:

https://github.com/mrozemeijer/tudatBundle/blob/master/thesisTool/ThesisTool/ThesisTool.cpp#L217-L220

Dominic

**Comment by mrozemeijer** [comment]
For this ascent, there is no control yet so the thrust should be alligned with the body/velocity vector. The acceleration is about 70 m/s^2 so this should be more than enough to get off the ground.
Here the thrust acceleration as implemented
https://github.com/mrozemeijer/tudatBundle/blob/master/thesisTool/ThesisTool/ThesisTool.cpp#L275-L291
this is read from a file here
https://github.com/mrozemeijer/tudatBundle/blob/master/thesisTool/ThesisTool/ThesisTool.cpp#L264-L268

I have also made a start of implementing DirectionBasedForceGuidance however it is not yet linked to the ThrustAccelerationSettings 
the code:
https://github.com/mrozemeijer/tudatBundle/blob/master/thesisTool/ThesisTool/ThesisTool.cpp#L270-L273
the unit vector functions:
https://github.com/mrozemeijer/tudatBundle/blob/master/thesisTool/ThesisTool/ThesisTool.cpp#L45-L53

But it was unclear to me how to link the DirectionBasedForceGuidance function to the ThrustAccelerationSettings.

**Comment by DominicDirkx** [comment]
Hi Mark,

Let's take it one question at a time, starting with your strange behaviour with the _current_ settings. Like I said, save the thrust and gravity accelerations that the code is actually using (save as dependent variables) and check whether this is indeed the 70 m/s2 that you mention. 

Dominic

**Comment by mrozemeijer** [comment]
The thrust is indeed saved. This is the result. This is as expected for a empying rocket starting from 340 kg with 24kN thrust and after 24s a 100kg rocket with the same thrust.
![altitude   velocity vs time](https://user-images.githubusercontent.com/17251685/57778419-4d3ecc80-7724-11e9-9a13-506b160cb4d8.png)
And the altitude vs time and velocity vs time for the same case
![Thrust acceleration](https://user-images.githubusercontent.com/17251685/57778420-4dd76300-7724-11e9-8216-f763c380b2e5.png)

**Comment by DominicDirkx** [comment]
Ok, good. In that case, what is the direct of the thrust acceleration? My guess is that it will be downwards(-ish).

**Comment by mrozemeijer** [comment]
as it is right now the thrust is defiened like this
0	24e3 0 0
24	24e3 0 0
24.1	0 0 0
100e6	0 0 0
in the lvlh frame

**Comment by mrozemeijer** [comment]
These are the total accelerations in the inertial frame as saved as dependent variable total_acceleration_dependent_variable
![accelerations](https://user-images.githubusercontent.com/17251685/57779999-9b090400-7727-11e9-9996-5dbbbed823d7.png)

**Comment by DominicDirkx** [comment]
These directions don't tell me much. Analyze whether the thrust is upwards or downwards w.r.t. the local frame, using the actual propagation results.

**Comment by mrozemeijer** [comment]
These are the accelerations in lvlh frame using the transformation matrix from the dependent variables list
![accelerations lvlh](https://user-images.githubusercontent.com/17251685/57782797-3486e480-772d-11e9-81ce-cdd4686f2b07.png)
