### ISSUE TITLE
SPICE Thread Safety

### ISSUE THREAD

**Issue by Sceki** [Tudat/tudat#541]
Hello,

I do not know if this can be considered appropriate here, in case not, feel free to close the issue. 

I have tried to apply a parallelization scheme for the fitness computation using pagmo and tudat, however SPICE returns an error due to the fact that it is not thread-safe. Is there a mechanism to make SPICE usable with parallelization schemes?

Kind regards,
Giacomo

**Comment by DominicDirkx** [comment]
Hi Giacomo,

Unfortunately, this is a fundamental problem when using Spice. You can circumvent it by calling all required Spice functions before entering the parallelized phase of your code. Most likely this is limited to ephemerides, gravitational coefficients and body radii,

Best,

DOminic

**Comment by Sceki** [comment]
Hello,

Since the whole optimization is parallelized, and I need the relative position of different celestial bodies at certain epochs (which depend on the variables passed to the fitness), I am afraid I cannot do that.

But thanks anyway for the tip!

Kind regards,
Giacomo

**Comment by DominicDirkx** [comment]
Hi Giacomo,

That's not necessarilly true, you can initialize interpolators from Spice data before running the optimization, and then call these interpolators during the optimization runs,

Dominic

**Comment by Sceki** [comment]
Hello.

Okay, I will try to see if that would actually be worthy or not. Thanks.

Kind regards,
Giacomo
