### ISSUE TITLE
Warnings during thrust implementation in fitness function

### ISSUE THREAD

**Issue by wjhuisman** [Tudat/tudat#544]
Hi, 

I want to create an optimizer that solves for the minimum amount of (constant) thrust needed to reach a certain target from a low-Earth orbit. For this I use pagmo. I keep getting the following warning, however:

`Warning, cannot reset dependentOrientationCalculator, incompatible object already exists`

I can't find the code in the doxygen either where this warning is given. What causes this, and how can I solve it?

Kind regards,

Wouter

P.S. you can find my code at [https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/c9798d61f0665a17a77eeb71f5ec3841f1dde1da/problems/deOrbit.cpp#L43](url)

**Comment by DominicDirkx** [comment]
This is a warning that you can safely ignore, it is telling you that the object that defines the orientation of teh vehicle (implicit in thrust model definition) is being reset. If it is bothering you, simply comment out the code that produces this.

**Comment by wjhuisman** [comment]
Thanks you! I can't find the code that produces this error however. Do you know where it is located? (I tried looking it up at doxygen, and in the different folders...)

**Comment by DominicDirkx** [comment]
Use the 'search all' function (Ctrl+Shift+f in Qt), and you'll find it
