### ISSUE TITLE
Custom thrust guidance model gives error using std::bind()

### ISSUE THREAD

**Issue by wjhuisman** [Tudat/tudat#545]
Hi,

I'm trying to implement a simple thrust guidance model, where thrust is implemented based on some arbitrary parameter. In this example I use time as a factor. I'm trying to implement a impulsive thrust along the velocity vector, opposite to the direction of the velocity vector after 5 minutes of propagation. I use the theory explained at [http://tudat.tudelft.nl/tutorials/tudatFeatures/accelerationSetup/thrustModels.html#FromFunctionThrustMagnitudeSettings](url) as a reference to construct my own `customUpdateFunction`. However, when I try to implement my own update function, described in a seperate class, I get the following error:

`/home/wouter/Documents/Studie/TU Delft/Tudat/tudatBundle/tudatApplications/Thesis_WJ_Huisman/headers/header_imports.h:150: error: conversion from ‘std::_Bind_helper<false, double (DeOrbitGuidance::*)()>::type {aka std::_Bind<std::_Mem_fn<double (DeOrbitGuidance::*)()>()>}’ to non-scalar type ‘std::function<double()>’ requested
     function<double()> updateMagnitudeGuidance = bind(&DeOrbitGuidance::updateGuidance);
                                                      ^`                      

This error is caused by the line I wrote here: [https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/bf30c06c34fc02eb79cedd2181b65df6a1bfbec3/headers/header_imports.h#L150](url). I feel like it has something to do with the way I wrote my update function and how I use bind, but I'm not sure. Also I create a `function<Eigen::Vector3d()>` called `bodyFixedThrustDirection`, which I want to refer to my `shared_ptr<ThrustDirectionGuidanceSettings> thrustDirectionSettings`. How do I do this? The creation of the environment, accelerations and the propagation of the model is written in [https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/master/sources/test.cpp](url).

Kind regards

**Comment by DominicDirkx** [comment]
Hi Wouter,

If you want to incldue an impulseive burn, you cannot use the thrust acceleration model. An added acceleration model modifies the differential equation governing the motion of your body. But, impulsive thrust cannot be captured by a numerically integrating a differential equation. To perform an imoulsive burn, stop the propagation at your required conditions, retrieve the final state, modify it in such a way that your impulsive burn is performed, and restart the propagation with that initial state.

Best,

Dominic

**Comment by kartikkumar** [comment]
Just to weigh in on this, you could technically include an impulsive shot on the right-hand side of the ODEs by using something like the Kronecker delta: https://en.wikipedia.org/wiki/Kronecker_delta

In practice, it's indeed easier to just stop and start the integration, however this can lead to local truncation issues depending on the numerical integrator you're using, so you have to be careful about how you stop and start.

**Comment by DominicDirkx** [comment]
What you would want for this is probably a Dirac Delta, not a Kronecker Delta. This would work fine for writing down the differential equation, but it's not something that a numerical integrator (or at least our integrator) could work with.

To stop the propagation, you can use the option to terminate at an exact condition, which will cause the last time step to be shorter than that which the integrator 'wants' to take.

**Comment by kartikkumar** [comment]
Dirac delta indeed if the independent variable is non-discrete, like time.

Classic integrators can't handle it, but there are a couple of ways to solve that:
1) approximate the discrete event with a continuous function
2) Regularize around the discrete event to get rid of the first-derivative problem

The termination can be tricky if you're not careful and lead to solution instability. It depends on a number of factors like the degree of non-linearity, propagation time, etc. (these happen to be "extreme" in cases I've worked on, which is why I'm pointing out the issue).
