### ISSUE TITLE
readGravityFieldFile Error

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#547]
Hi everyone,

when reading a gravity field file with the function _simulation_setup::readGravityFieldFile_ up to a degree n, the file must also include the full degree n+1. Otherwise the following error message shows up:
_Error when reading pds gravity field file, number of fields is 1_

Kind regards
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

Can you give an example of a file/code that gives this error?

**Comment by SebastianVillamil** [comment]
Hi Dominic,

I obtained said error when reading up to degree & order 12 for this file:
[GanGravField.txt](https://github.com/Tudat/tudat/files/3257572/GanGravField.txt)

However, when using this file said error does not occur:
[GanGravFieldExtended.txt](https://github.com/Tudat/tudat/files/3257580/GanGravFieldExtended.txt)

Kind regards
Sebastian

**Comment by DominicDirkx** [comment]
Could you show the piece of C++ code you use to load these files?

**Comment by SebastianVillamil** [comment]
std::string SHfileGan = FileDir + "GravityModels/" + GanymedeField + ".txt";
    int maxDegreeGan = 12;
    int maxOrderGan = 12;
    std::pair< Eigen::MatrixXd, Eigen::MatrixXd > SHcoeffsGan;
    std::pair< double, double > refDataGan =
            readGravityFieldFile(SHfileGan, maxDegreeGan, maxOrderGan, SHcoeffsGan, 0, 1);
    bodySettings[ "Ganymede" ]->gravityFieldSettings = std::make_shared< SphericalHarmonicsGravityFieldSettings >
            ( refDataGan.first, refDataGan.second, SHcoeffsGan.first, SHcoeffsGan.second, "IAU_Ganymede" );

**Comment by DominicDirkx** [comment]
Hmm, that's odd. This is probably a small 'off by one' bug. Thanks for pointing it out,

Dominic

@mchambe Could you have a look at this sometime in the coming months?

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version  (this error has been fixed in the meantime, I think)
