### ISSUE TITLE
Setting up constraints during orbit estimation

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#548]
Hi everyone,

how can I set up a Kaula constraint when estimating spherical harmonic coefficients?
Furthermore, how can I set up a constraint for the estimation of empirical accelerations?

Kind regards
Sebastian

**Comment by DominicDirkx** [comment]
You can add a priori information to the PodInput, as is done here:

https://github.com/Tudat/tudat/blob/master/Tudat/SimulationSetup/EstimationSetup/orbitDeterminationTestCases.h#L274-L277

The input to add is the inverse of the a priori covariance (unnormalized). Typically, all off-diagonal entries of this matrix (size NxN, when estimating N parameters) are zero. Entry (N,N) of the matrix represents the inverse a priori covariance of parameter N. If parameter N has an a priori uncertanity of X, this entry (N,N) should have the value 1/(X*X).

For setting the kaula constraint on the gravity field coefficients, I have some code to help with this here:

https://github.com/DominicDirkx/tudat/blob/HybridArcExtension/Tudat/Astrodynamics/OrbitDetermination/EstimatableParameters/sphericalHarmonicCosineCoefficients.cpp

But for your case, it might be easier to set it manually, as merging this branch with your code will likely lead to some failures/conflicts,

Dominic
