### ISSUE TITLE
Feature request: Estimation of the tidal coefficient h_2

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#551]
Hi Dominic,

please change the settings within _altimeterCrossoverPartial_ so that Ganymede is no longer hard-coded as central body for the calculation of altimetry crossover partials.

Kind regards
Sebastian

**Comment by DominicDirkx** [comment]
Could you add a link to the latest branch with the crossover partials?

**Comment by SebastianVillamil** [comment]
The branch can be found here:
https://github.com/SebastianVillamil/tudat/tree/Xovers
The file in question is:
https://github.com/SebastianVillamil/tudat/blob/Xovers/Tudat/SimulationSetup/EstimationSetup/createAltimeterCrossoverPartials.cpp

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version  (h2 estimation is now supported, but only from lander data at the moment)
