### ISSUE TITLE
How to acess the optimisation 

### ISSUE THREAD

**Issue by akum04** [Tudat/tudat#556]
Hi,

In the examples folder, there is a satellite Rendezvous sample code and within the code it includes, 
`#include <Tudat/Optimization/missionLinker.h>`.

however the Optimization folder is not found within the master branch. Can you let me where can I find it, or how to run the satelliteRendezvous example.

Thanks,
-Arun.

**Comment by mchambe** [comment]
Dear Arun,

You are perfectly right and the Optimization folder is missing to run this example. My best guess would be that this example worked with the previous way Tudat handled optimization. As far as I know, optimization is now always done using Pagmo and this optimization folder you mentioned is not used anymore.
If you want to have a closer look at some optimization examples, you can find a bunch of them here: tudatBundle/tudatExampleApplications/libraryExamples/PaGMOEx/ (the associated documentation is http://tudat.tudelft.nl/tutorials/applicationWalkthroughs/index.html#pagmo-optimization-tutorials).
As mentioned, this answer is based on my understanding of the current workings of Tudat and it is possible that I am missing some information here. Unfortunately, the Tudat support is limited during the summer period but the most knowledgeable contributor of the project will be back in about 1 month and will be able to answer you more firmly.  
My advice would be to focus on other satellite propagator examples, or to have a look at the optimization examples mentioned above if you are more interested in the optimization aspect of this "Satellite rendez-vous" application.

Anyway, thank you very much for pointing this out! This example has to be updated, either to make it consistent with the other optimization examples, or to add the missing part of the code. 

Best regards,

Marie

**Comment by akum04** [comment]
Dear Marie, 
Thanks for the information. I'll look into the PAGMO optimization tutorials and see if I can get the required info for the satellite rendezvous optimization problem.
regards,
Arun.
