### ISSUE TITLE
Multi-objective pagmo optimization uses all of CPU power

### ISSUE THREAD

**Issue by wjhuisman** [Tudat/tudat#557]
Hi, 

When performing my multi-objective optimization with either of the following algorithms: nsga2, moead, ihs, it starts off fine, but after a while the calculations freeze (after a few generations of the optimization algorithm). No error message is generated. After inspecting the active processes on my computer I see that the calculations use up all the CPU power. At first I thought that I was maybe storing very large matrices into my memory, but the memory is fine. What could be the problem? 

Kind regards,

Wouter

**Comment by DominicDirkx** [comment]
Hi Wouter,

To try to find the problem, you can use the debugger:

http://tudat.tudelft.nl/tutorials/troubleshooting/debuggers.html?highlight=gdb#debugging-in-terminal

Once the program gets stuck, terminate the process, and you can get a stack trace. This will tell the function it is in at the time when you terminate, giving you information on what is going wrong,

Best,

Dominic

**Comment by wjhuisman** [comment]
Hi,

Thanks for your reply! I ran the debugger using gdb and terminated the program once it got stuck. I then used _backtrace_ to trace the error causing the problem. However, I don't quite understand the message it gives me:

`
(gdb) run
`
`
Running program...
`
`
Thread 1 "application_The" received signal SIGINT, Interrupt.
syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
`
`
(gdb) backtrace
`
`
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
`
`
#1  0x00007ffff78a5091 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
`
`
#2  0x00000000006d1322 in main ()
`

I thought the problem might be caused by me having set to use all 4 cores in the build steps (-j4) while my computer only has 4. Thus I changed this to -j2 to limit the number of cores, but this had no effect. Then program always gets stuck at the same point in the calculation. What might be the problem?

Kind regards,

Wouter

**Comment by DominicDirkx** [comment]
Hi Wouter,

Could you post a link to the code you used to generate this?

Best,

Dominic

**Comment by wjhuisman** [comment]
Hi,

I'm running the following program: [main.cpp](https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/master/sources/main.cpp) with the debugger. At first everything works fine, but after a few generations the program just freezes.

Kind regards,

Wouter

**Comment by DominicDirkx** [comment]
Hi Wouter,

From the looks of your error output and code, the error is occuring here:

https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/master/sources/main.cpp#L93-L97

There are Pagmo functions and, to be perfectly honest, I'm not sure about teh details of their working. Essentially, they ensure that the island has finished evolving before moving on (I think). This is especially important if you're using multiple cores to run your simulations (the -j2/-j4 you mentioned concerns the number of cores used form _compilation_ and won't (shouldn't?) influence your results. My naive suggestion would be to comment out the first or second part of the code block I reference above (or both), and see if this corrects your problem.

Best,

Dominic
