### ISSUE TITLE
Unit tests 189, 247 and 248 failed

### ISSUE THREAD

**Issue by thijsmeneer** [Tudat/tudat#558]
I just reinstalled and built the entire bundle, but when running the unit tests, I received the following message:

99% tests passed, 3 tests failed out of 248

Total Test time (real) = 979.59 sec

The following tests FAILED:
	189 - test_UnscentedKalmanFilter (Failed)
	247 - test_JsonInterfaceParameter (Not Run)
	248 - test_JsonInterfaceSimulationSingleSatelliteVariational (Not Run)

The LastTest.log file is attached. I am using Windows 10. I am not planning to use Json, but is it something to worry about?

[LastTest.log](https://github.com/Tudat/tudat/files/3555898/LastTest.log)

**Comment by DominicDirkx** [comment]
Hi Thijs,

I don't think this is anything to worry about, but I'd like to make sure. The fact that two of the tests have not run, could be a sign of a deeper problem.

Could you, click the 'compile' button again (removing the 'test' command), and attach the compile output that you get? This should give us an idea of whether or not this is a problem,

Best,

Dominic

**Comment by thijsmeneer** [comment]
Hi Dominic,

Thanks. I assume the file you are talking about is the CMakeOutput.log?

[CMakeOutput.log](https://github.com/Tudat/tudat/files/3557405/CMakeOutput.log)

**Comment by DominicDirkx** [comment]
Hi Thijs,

What I'm referring to is not written to an output file, but the output that is given in the 'Compile Output' tab in Qt (at the bottom), after clicking compile (the hammer symbol). If you could run the compilation, and then copy/pasted teh output to a file and post it here, I'll have a look,

Best,

Dominic

**Comment by thijsmeneer** [comment]
Hi Dominic,

The problem has been resolved. Yesterday I compiled again and attached this CMake logfile. To fully redo the procedure I started to run the unit tests again this morning and this time only 189 failed, so that should be fine now, I think?

Thanks!
