### ISSUE TITLE
189 - test_UnscentedKalmanFilter (Failed)

### ISSUE THREAD

**Issue by Tiago26PT** [Tudat/tudat#559]
While testing my tudat build by running the tests, I encountered a problem. Test no. 189 was not passed. Here's the LastTest.log related to that test:
[LastTest.log](https://github.com/Tudat/tudat/files/3576547/LastTest.log)

**Comment by DominicDirkx** [comment]
This is a known bug, and unless you are using this filter specifically for your work, nothing that has any consequences for your use of Tudat.

Dominic
