### ISSUE TITLE
Build Error windows

### ISSUE THREAD

**Issue by Casperbru** [Tudat/tudat#560]
During the building of the library it gives me errors. I thought it had to do with the filepaths that were too long, but Dominic and I looked at it and he removed the longer names from the building process, but it still gives issues. The following text files give the entire output.

[file1.txt](https://github.com/Tudat/tudat/files/3602393/file1.txt)
[file2.txt](https://github.com/Tudat/tudat/files/3602394/file2.txt)

**Comment by Casperbru** [comment]
After some tries, I figured out it had something to do with the building directory, which was too long by default (which was caused by a very long default name of the kit). With a shorter building directory I built tudat and had no major issues.

With test_UnifiedStateModelModifiedRodriguesParameterElementConversions turned off
[compileOutput3.txt](https://github.com/Tudat/tudat/files/3610356/compileOutput3.txt)
[generalMessages3.txt](https://github.com/Tudat/tudat/files/3610357/generalMessages3.txt)

with test_UnifiedStateModelModifiedRodriguesParameterElementConversions turned on
[generalMessages4.txt](https://github.com/Tudat/tudat/files/3610349/generalMessages4.txt)
[compileOutput4.txt](https://github.com/Tudat/tudat/files/3610350/compileOutput4.txt)

**Comment by Casperbru** [comment]
I get the following errors with the unit test however:
99% tests passed, 2 tests failed out of 248

Total Test time (real) = 1227.78 sec

The following tests FAILED:
	112 - test_VariationalEquations (Failed)
	189 - test_UnscentedKalmanFilter (Failed)
Errors while running CTest
mingw32-make.exe: *** [Makefile:72: test] Error 8
16:43:37: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Dtop)
When executing step "CMake Build"
16:43:37: Elapsed time: 20:28
[LastTest.log](https://github.com/Tudat/tudat/files/3610552/LastTest.log)

**Comment by DominicDirkx** [comment]
Hi Casper,

Neither of these is anything to worry about. The test_UnscentedKalmanFilter is a known issue on Windows, and the test_VariationalEquations seems to be a minor incompatibility in the testing code. 

Best,

Dominic
