### ISSUE TITLE
3-clause BSD not applied to all files

### ISSUE THREAD

**Issue by rodyo** [Tudat/tudat#561]
A quick `grep` through all code for the term "commercial" reveals that the BSD license does not seem to apply to all code. The following files: 

- `Astrodynamics/TrajectoryDesign/CMakeLists.txt`
- `Mathematics/BasicMathematics/UnitTests/unitTestRotationPartials.cpp`
- `Mathematics/NumericalIntegrators/bulirschStoerVariableStepsizeIntegrator.cpp`
- `Mathematics/NumericalIntegrators/bulirschStoerVariableStepsizeIntegrator.h`

all explicitly state that 

> (...) Commercial and non-private application of the software in any form is strictly prohibited unless otherwise granted by the authors

which is in direct disagreement with the project's 3-clause BSD license. 

Is this a mistake, or should these files really be treated differently from the rest?

**Comment by DominicDirkx** [comment]
No, this is most definitely a mistake. We will update the license statements in our next code update. Thank you very much for catching this.

**Comment by DominicDirkx** [comment]
This has been corrected in the current working branch, which will be merged into the Tudat master in the coming weeks:

https://github.com/Tudat/tudat/tree/NA_2019_master
