### ISSUE TITLE
15/310 Failed Unit tests

### ISSUE THREAD

**Issue by Morgonz** [Tudat/tudat#563]
Dear

I recently updated my TUDAT by merging the Tudat/tudat master branch with the one I forked,
I already got some errors at the end of the tudat compilation at the line shown below (full file in TudatCompileLog.txt)
```

[ 99%] Building CXX object tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeFiles/application_SingleSatellitePropagator.dir/singleSatellitePropagator.cpp.obj
```

I then ran the unit tests and got the following result (full log in UnitTestLog.txt)s:

```
95% tests passed, 15 tests failed out of 310
Total Test time (real) = 1112.07 sec

The following tests FAILED:
	  4 - algorithm_type_traits (SEGFAULT)
	 12 - custom_comparisons (SEGFAULT)
	 22 - hypervolume (Failed)
	 28 - island (SEGFAULT)
	 36 - problem_type_traits (SEGFAULT)
	 48 - type_traits (SEGFAULT)
	 88 - test_UnifiedStateModelModifiedRodriguesParameterElementConversions (Failed)
	105 - test_SynchronousRotationalEphemeris (Failed)
	120 - test_GravitationalTorques (Failed)
	157 - test_TorquePartials (Failed)
	174 - test_VariationalEquations (Failed)
	195 - test_FullPropagationPatchedConicsTrajectory (BAD_COMMAND)
	251 - test_UnscentedKalmanFilter (Failed)
	276 - test_EnvironmentCreation (Failed)
	309 - test_JsonInterfaceParameter (Failed)
```

I assume something went wrong with merging or possibly something else?

Regards,
Andres

[TudatCompileLog.txt](https://github.com/Tudat/tudat/files/3648408/TudatCompileLog.txt)
[UnitTestLog.txt](https://github.com/Tudat/tudat/files/3648409/UnitTestLog.txt)

**Comment by DominicDirkx** [comment]
Hi Andres,

The compile error occured in the example applications. If you also update these, the compilation may/should proceed properly. Let me know if this works,

Best,

Dominic

**Comment by Morgonz** [comment]
Hello Dominic,

I used smartgit to update my tudatbundle, so all folders not just tudat. The compilation ended succesfully although with some warnings (yellow triangle), full logs shown in TudatCompileLog2

I then ran the unit tests, full log in UnitTestLog2.

```
96% tests passed, 13 tests failed out of 306

Total Test time (real) = 991.16 sec

The following tests FAILED:
	  4 - algorithm_type_traits (SEGFAULT)
	 12 - custom_comparisons (SEGFAULT)
	 22 - hypervolume (Failed)
	 28 - island (SEGFAULT)
	 36 - problem_type_traits (SEGFAULT)
	 49 - type_traits (SEGFAULT)
	 90 - test_UnifiedStateModelModifiedRodriguesParameterElementConversions (Failed)
	119 - test_GravitationalTorques (Failed)
	153 - test_TorquePartials (Failed)
	170 - test_VariationalEquations (Failed)
	191 - test_FullPropagationPatchedConicsTrajectory (BAD_COMMAND)
	247 - test_UnscentedKalmanFilter (Failed)
	305 - test_JsonInterfaceParameter (Failed)
Errors while running CTest
Makefile:71: recipe for target 'test' failed
mingw32-make.exe: *** [test] Error 8
13:04:08: The process "C:\Program Files (x86)\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
```

Regards,
Andres

[TudatCompileLog2.txt](https://github.com/Tudat/tudat/files/3652216/TudatCompileLog2.txt)
[UnitTestLog2.txt](https://github.com/Tudat/tudat/files/3652217/UnitTestLog2.txt)

**Comment by DominicDirkx** [comment]
Hi Andres,

Please note that updating tudat bundle will not automatically update all dependencies. Since you are using SmartGit, I assume your installation was first done 2 years ago. Please note that we do bot support the use of SmartGit anymore.

You can try to update all dependencies, or reinstall Tudat altogether  (follow new install guide). If you are on Windows, Id also recommend to reinstall Qt Creator, as it now comes with a much improved compiler,

Best,

Dominic

**Comment by Morgonz** [comment]
Hello Dominic,

I indeed installed TUDAT a long time ago. As compilation can take a long time for a new installation I would first try the update method, How do I update the dependencies?

I assume 'http://tudat.tudelft.nl/installation/setupDevWindows.html#' is the new guide were I to reinstall it? I also see smartgit is now only needed to be installed in order not to break tudat?

Regards,
Andres

**Comment by Morgonz** [comment]
Hello Dominic,

I reinstalled qt, but other problems were coming up so I decided to do a complete tudat reinstall. 

A quick question: it says to install:  "cmake-[version]-win32-x86.msi", however I have 64bit, so do i still need to install the win32 or is it important for tudat?

Regards,
Andres

**Comment by Morgonz** [comment]
Hello Dominic,

Ok, I installed TUDAT, and I'm only left with one failed unit test: 
test_UnscentedKalmanFilter.
I saw on another issue thread that this is known with windows.

Regards,
Andres

**Comment by DominicDirkx** [comment]
Great, indeed this one failure is fine.
