### ISSUE TITLE
Unit test failure: test_VariationalEquations 

### ISSUE THREAD

**Issue by fab343** [Tudat/tudat#565]
After testing on my Windows 10 (64-bit) computer I got the following result:
[LastTest.log](https://github.com/Tudat/tudat/files/3661641/LastTest.log)

> 99% tests passed, 2 tests failed out of 248
> 
> Total Test time (real) = 1521.67 sec
> 
> The following tests FAILED:
> 	112 - test_VariationalEquations (Failed)
> 	189 - test_UnscentedKalmanFilter (Failed)

Thank you,
Fabian

**Comment by DominicDirkx** [comment]
Hi Fabian,

This is nothing to worry about, one is known to fail on Windows, the other seems to be due to a small error in the test itself,

Dominic

**Comment by fab343** [comment]
Thanks for the quick answer Dominic
