### ISSUE TITLE
Solar activity data could not be found for this julian date: 2458850.500000 in nrlmsiseInputFunction

### ISSUE THREAD

**Issue by wjhuisman** [Tudat/tudat#567]
Hi,

It seems that there is no solar activity data for 2020 in the NRLMSISE-00 atmospheric model. Is there an extra file that I can download and import just like the spice kernel de430.bsp file?

Kind regards,

Wouter

**Comment by DominicDirkx** [comment]
Hi Wouter,

The required data for NRLMSISE is given in this file:

https://github.com/Tudat/tudat/blob/master/Tudat/External/SpaceWeatherData/sw19571001.txt

You can try to find an updated version, or create one yourself. Note that any extrapolation to 2020 would be based on predictions, not observations, significantly reducing your model fidelity

Dominic

**Comment by wjhuisman** [comment]
Thank you!
