### ISSUE TITLE
Reminder: Using observation models without setting ephemeris for satellites

### ISSUE THREAD

**Issue by Casperbru** [Tudat/tudat#568]
When trying to use observation models, it is required to add an ephemeris to the satellite used in the observations you want to do.

**Comment by DominicDirkx** [comment]
Thanks for posting this. Indeed, this is needed, and error output should be given when an ephemeris is not present.

**Comment by DominicDirkx** [comment]
This issue could be traced back to the TabulatedCartesianEphemeris not checking if an interpolator is defined before accessing it. It has been corrected in the current working branch, which will be merged into the Tudat master in the coming weeks:

https://github.com/Tudat/tudat/tree/NA_2019_master
