### ISSUE TITLE
minimum_elevation_angle exclusively for groundstations

### ISSUE THREAD

**Issue by Casperbru** [Tudat/tudat#569]
It appears that the function/setting minimum_elevation_angle from Observation Viability Setttings can only be used for ground stations and not for spacecraft, is this correct? This is not explicitly mentioned.
A work around could be using the body avoidance angle with 90 degrees is a 0 degree minimum elevation angle and the body the spacecraft is orbiting as body to avoid.

**Comment by DominicDirkx** [comment]
Hi Casper,

Yes, the minimum elevation angle is computed in a topocentric frame. Since no topocentric frame is defined on the spacecraft (as it has no corresponding shape model, this viability setting cannot be used). For which type of constraint are you trying to use it?

**Comment by Casperbru** [comment]
Hi Dominic,
Ah that explains it!
I want my constellation of satellites to only be able to communicate with satellites above it, that is why I wanted to use the setting, but the other method I mentioned also works for this. 

The problem I encountered now however is that I want that my constellation should be able to communicate with each other, so here I don't want to have the elevation mask (they would never be able to see each other), but you can give the visibility calculator one rule or add to that rule, it is not really possible to make it exclusive/inclusive of certain links.
Is there a know way to work with this? 
Right now, I could only think of creating a completely new additional observation model, but this would come with a whole lot of other complications.

**Comment by DominicDirkx** [comment]
Hi Casper,

A few questions:

- You say "I want my constellation of satellites to only be able to communicate with satellites above it". What do you mean by this exactly?
- You can give any number of viability settings, and all of them have to be met for an obsevation to be simulated. You can specify distinct (sets of) viability settings for different LinkEnds and/or ObservableTypes
- I don't understand why a new observation model would be needed here, can you elaborate here?

I think that part of my confusion stems from a lack of understanding of what exactly you want to model. If you can provide a comprehensive description of the model you want to implement, I would be able to help you out better,

Dominic

**Comment by Casperbru** [comment]
Hi,
I understand the confusion.
Let's say I have a PECMEO constellation in an orbit below GPS satellites. I want the PECMEO sats to communicate with the GPS sats, but the PECMEO sats can only look up for this link, so no omnidirectional signal, but only when there is a 90 deg or higher angle with the radius of its orbit. So from its horizon and higher.
With another antenna directed the other way I want to enable the PECMEO constellation to communicate with each other. (The previous explained link would never be able to facilitate this, because it can only "look up" and satellites in the same or lower orbital height can never be seen). With this other antenna I therefore want different settings, namely solely avoiding Earth occult. e problem however is that when I set the viability settings I can give the PECMEO link end the body avoidance angle of with Earth of 90 deg, so the first requirement is set, but the rules are set per satellite, so I can not tell the application that for links as PECMEO1-GPS2, PECMEO3-Galileo5, it should use both the settings, but that for links as PECMEO2-PECMEO4 it should only avoid the Earth.
I hope that this clears the situation up a bit.

**Comment by DominicDirkx** [comment]
Hi Casper,

Thanks, that clears it up. So, if I understand correctly, the PECMEO-PECMEO links can be handled with existing settings, while the PECMEO-GPS/Galileo/... can not. 

For the latter, you could either write your own viability settings, or simulate the observations without vaibility settings, and then write a separate function that filters out all infeasible observations,

Bst,

Dominic

**Comment by Casperbru** [comment]
Hi Dominic,

Well the problem is that I can handle both links, but not at once. For both links body occultation (used for Earth) is used, but the body avoidance angle (used for the elevation mask) only for the second. The program, however, let's you only use one set of rules per satellite (while PECMEO sats are used in both links).

Just to make sure this is not possible with the existing tools, otherwise indeed have to write something myself.

Cheers,
Casper

**Comment by DominicDirkx** [comment]
Hi Casper,

Ok, that's good. In that case, you can call the createObservationViabilityCalculators function _twice_. Once using only the PECMEO-PECMEO links, and once using the PECMEO-GPS/Galileo links. You can then merge the resulting PerObservableObservationViabilityCalculatorList data structures before calling the simulateObservations function,

Dominic

**Comment by DominicDirkx** [comment]
Hi Casper, Please be a little bit more precise: what do you mean exactly by 'run it'?

**Comment by Casperbru** [comment]
with run it I mean, call the function createObservationViabilityCalculators!

**Comment by DominicDirkx** [comment]
Hi Casper,

Indeed, you will have to run createObservationViabilityCalculators twice, with different observationViabilitySettings and link ends input.

After that, you either choose to merge the resulting PerObservableObservationViabilityCalculatorList data structures, and then call the simulateObservations function a single time, or to call the simulateObservations function twice, once for each set of PerObservableObservationViabilityCalculatorList (and observables/link ends). I would opt for the latter, as it involves less merging of complex data structures,

Best,

Dominic

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
