### ISSUE TITLE
Problem in Build the libraries 

### ISSUE THREAD

**Issue by Robot233** [Tudat/tudat#572]
![捕获](https://user-images.githubusercontent.com/55019890/67615552-72218a80-f800-11e9-8f42-3f25271cb631.JPG)
[新建文本文档.txt](https://github.com/Tudat/tudat/files/3774528/default.txt)
[General Messages.txt](https://github.com/Tudat/tudat/files/3774532/General.Messages.txt)
Operating system and compiler are in picture.The problem is in text.

**Comment by Robot233** [comment]
Assembler messages:
Fatal error: can't create CMakeFiles\test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir\UnitTests\unitTestUnifiedStateModelModifiedRodriguesParameterElementConversions.cpp.obj: No such file or directory
mingw32-make.exe[2]: *** [tudat\Tudat\Astrodynamics\BasicAstrodynamics\CMakeFiles\test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir\build.make:63: tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeFiles/test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir/UnitTests/unitTestUnifiedStateModelModifiedRodriguesParameterElementConversions.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:2775: tudat/Tudat/Astrodynamics/BasicAstrodynamics/CMakeFiles/test_UnifiedStateModelModifiedRodriguesParameterElementConversions.dir/all] Error 2
mingw32-make.exe: *** [Makefile:140: all] Error 2
16:32:09: 进程"D:\Program Files\CMake\bin\cmake.exe"退出，退出代码 2 。
Error while building/deploying project TudatBundle (kit: Desktop (x86-windows-msys-pe-64bit))
When executing step "CMake Build"

**Comment by Robot233** [comment]
I have  Clone Tudat again in:C:\tudatBundle.
But its no use.
When I try again ,it always stop at 84%.

**Comment by Robot233** [comment]
In other computer ，I save this problem.
Later I will try again in mine.

**Comment by DominicDirkx** [comment]
When posting an issue, please make sure to ask a clear question, providing as much information as possible.

I'm glad to see that you've solved this issue,

Dominic
