### ISSUE TITLE
Failed Unit Test

### ISSUE THREAD

**Issue by Robot233** [Tudat/tudat#573]
Good evening.
there have 3 test failed. My system is Windows 7 Enterprise.
Thanks.
[LastTest.log](https://github.com/Tudat/tudat/files/3775959/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/3775960/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
These unit test failures have recently been identified, and we hope to commit a correction in the coming week,

Dominic
