### ISSUE TITLE
Failed unit tests related to JSON interface

### ISSUE THREAD

**Issue by tbocanegra** [Tudat/tudat#575]
Hello Dominico!

I have several failed unit tests (attached are the logs) related to the json interface. I actually had a compiling error when building the libraries, that I solved by updating the json.hpp file to the 3.5.0 version. That solved the compiling error but now the unit tests are failing.

I believe I won't be needing the json interfaces, but I wanted to let you know about this anyways. I'm assuming I can safely use the code as is (right?).

Greetings from the other side of the world!

Oh, I'm using macOs Mojave btw.
[LastTest.log](https://github.com/Tudat/tudat/files/3806456/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/3806458/LastTestsFailed.log)

Tati

**Comment by DominicDirkx** [comment]
Hi Tati!

Great to hear from you, how are things going? I'm guessing that you downloaded the code mid last week (or earlier). We've been hard at work making modifications to the code to get it all to work on various operating systems.

For the JSON issue, which also popped up on Kevin's Mac, we have made a quick and dirty modification to the Tudat code, but good to know that updating our json submodule will also work :) 

If you update your tudat code, all unit tests should pass. However, the unit test failures will most likely not be any issue for you. What were you planning to do with Tudat again? If it's only for orbit propagations, the JSON interface may well be the most straightforward,

Greetings from a small, cold, country,

Dominic
