### ISSUE TITLE
Failed unitTestLightTimeCorrectionPartials.cpp

### ISSUE THREAD

**Issue by Nosudrum** [Tudat/tudat#578]
Hello, I have encountered a compiling error while building the tudat libraries in qt for the first time.
I am running Windows 10 version 1903 18362.449 and MinGW 7.3.0 64-bit.

-1 error: [tudat\Tudat\Astrodynamics\OrbitDetermination\ObservationPartials\CMakeFiles\test_LightTimeCorrectionPartials.dir\build.make:63: tudat/Tudat/Astrodynamics/OrbitDetermination/ObservationPartials/CMakeFiles/test_LightTimeCorrectionPartials.dir/__/LightTimeCorrectionPartials/UnitTests/unitTestLightTimeCorrectionPartials.cpp.obj] Error 1

[CompileOutput.txt](https://github.com/Tudat/tudat/files/3827170/CompileOutput.txt)

**Comment by DominicDirkx** [comment]
Hi,

Thanks for providing all the required output and settings. You seem to be compiling using multiple cores, which is recommended. But, please take note of this point in the installation guide:

When encountering a compilation error during multi-core compilation, try reinintializing the compilation (clicking the hammer again). If the same errors occurs, and you wish to open an issue, rerun with a SINGLE thread, and post the output that this produces. Multi-core compilation output can often be garbled, and difficult to interpret.

Please let me know if the issue persists, and if it does, post the error output from a single-core compilation,

Best,

Dominic

**Comment by Nosudrum** [comment]
Hello, thanks for the answer. I'll do that this evening and let you know how it goes !

**Comment by Nosudrum** [comment]
Hello @DominicDirkx,
I have tried compiling again, this time in single threaded mode, and encountered an error at the same test.

Here is the latest compiler output :
[CompileOutput.txt](https://github.com/Tudat/tudat/files/3832283/CompileOutput.txt)

**Comment by DominicDirkx** [comment]
Thank you, I think this is a Windows path length issue. We've pushed some small modifications to Github. To update your code, navigate to **...../tudatBundle/tudat**  your tudat_shell.dat, and type:

git fetch origin
git merge origin/master

Just to be on the safe side, please save the output that the terminal gives from these command in a text file.

Then, recompile your code. Hopefully, this will resolve the issue. 

Best,

Dominic

**Comment by Nosudrum** [comment]
Hello @DominicDirkx,

I followed your instructions and successfully compiled in multi threaded mode.

There is only one warning at the end of the compilation, you can find the compiler output and warning attached here if you want to investigate.

Thanks for the help !

[Warning.txt](https://github.com/Tudat/tudat/files/3835239/Warning.txt)
[CompileOutput.txt](https://github.com/Tudat/tudat/files/3835240/CompileOutput.txt)

**Comment by DominicDirkx** [comment]
Great! I'll keep this issue open, so other people who have already downloaded Tudat can also use these instructions to correct their installation, if needed.

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
