### ISSUE TITLE
Project parsing failed - Compiler is broken

### ISSUE THREAD

**Issue by DannyG20** [Tudat/tudat#581]
Hi,

I encountered an issue during the configuration step. The problem seems to be that, although Qt can find the compiler, the C compiler seems to be "broken". Hence, compilation of the test program failed. How can I fix this? I have attached the general messages, and I am using Windows 10.
[error_tudat.txt](https://github.com/Tudat/tudat/files/3830640/error_tudat.txt)

Thank you.

Kind regards,

Danny

**Comment by DominicDirkx** [comment]
Hi Danny,

Could you verify that your settings described in Step 6 of:

https://tudat.tudelft.nl/installation/setupDevWindows.html#qt-creator-mingw

are indeed correct? Pay special attention to the 'CMake Generator'.

Best,

Dominic

**Comment by DannyG20** [comment]
Hi Dominic,

The only difference is that CMake is located in Program Files instead of Program Files (x84), I assumed this would not be an issue. Could this be causing the problem? Other than that, everything is the same.

Thank you.

Kind regards,

Danny

**Comment by DominicDirkx** [comment]
As an update to this issue, we have come to the conclusion that this is most likely caused by multiple compilers being installed on this system (independently from Qt), and that Qt is incorrectly used the settings defined in the kit.

When this is verified, and when a solution is found, we will post it here.

**Comment by bastiaan155** [comment]
Hi, 

I happen to have the exact same problem (with the same messages). Has this problem been solved yet?

Kind regards,
Bastiaan

**Comment by DominicDirkx** [comment]
This was solved by manually adding an already compiled boost version onto this person's computer. Send me an e-mail, and I'll send you a wetransfer link and instructions

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
