### ISSUE TITLE
failed unit test, system intel core i5 windows 8.1 2013

### ISSUE THREAD

**Issue by jurrienvos** [Tudat/tudat#585]
unfortunately, the following command "attach the file LastTest.log, which should be in the /Testing/Temporary/ directory in your build folder" I could not found in qt creator. Therefore I copied the following to make the problem clear:

In 4. Compile output, there was the following:

Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_RungeKuttaFehlberg56Integrator
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_RungeKuttaFehlberg78Integrator
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_RungeKutta87DormandPrinceIntegrator
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_BulirschStoerVariableStepSizeIntegrator
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_RootFinders
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_SimpleLinearRegression
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_BasicStatistics
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_MultiVariateProbabilityDistributions
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_BoostDistributions
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_KernelDensityDistribution
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_RandomSampling
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_TrapezoidalIntegrator
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_GaussianQuadrature
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_SofaEarthOrientation
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_SofaFundamentalArguments
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_SofaTimeConversions
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_SpiceInterface
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_EnvironmentCreation
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_AccelerationModelCreation
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceAcceleration
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceAerodynamics
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceAtmosphere
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceBody
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceDeserialization
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceEphemeris
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceExport
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceGravityField
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceGravityFieldVariation
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceGroundStation
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceIntegrator
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceInterpolation
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceMassRateModel
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfacePropagator
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceRadiationPressure
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceReferenceFrames
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceRotationModel
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceShapeModel
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationSingleSatellite
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationSinglePerturbedSatellite
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationInnerSolarSystem
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationGalileoConstellation
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationThrustAlongVelocityVector
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationThrustAccelerationFromFile
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSpice
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceState
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceTermination
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceThrust
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceTorque
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceVariable
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceObservation
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceParameter
Unable to find executable: C:/tudatBundle/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationSingleSatelliteVariational
Errors while running CTest
mingw32-make.exe: *** [Makefile:72: test] Error 8
20:11:42: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop (x86-windows-msys-pe-64bit))
When executing step "CMake Build"
20:11:42: Elapsed time: 02:20.

Also:
![image](https://user-images.githubusercontent.com/57714621/68797210-73521480-0654-11ea-96d3-1d60a8581f7e.png)

![image](https://user-images.githubusercontent.com/57714621/68797245-8664e480-0654-11ea-9c2f-fe82ba2dd631.png)

I hope the problem is clear, thank you in advance

**Comment by DominicDirkx** [comment]
I think something went wrong during your compilation, based on your test output. Please restart the compilation, and post the compile output here

**Comment by jurrienvos** [comment]
I restarted the building process, and after some 17.5 hours the program 'says' its at level 100% (see provided output) but on the lower right the program still shows the 'build' bar which is nearly filled but still not completely. Is this normal?

[comple output after 17 and half hours of building.txt](https://github.com/Tudat/tudat/files/3850251/comple.output.after.17.and.half.hours.of.building.txt)

**Comment by jurrienvos** [comment]
Dear Dominic,
After repeating the build and test procedure, I get the same error as during the previous test. You can find the error as an attachment. 

[LastTest.log](https://github.com/Tudat/tudat/files/3851657/LastTest.log)

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
