### ISSUE TITLE
Errors while running CTest. Error while building/deploying project TudatBundle (kit: Desktop (x86-windows-msys-pe-64bit)) When executing step "CMake Build"

### ISSUE THREAD

**Issue by chen-mingwei** [Tudat/tudat#587]
[LastTest.log](https://github.com/Tudat/tudat/files/3863842/LastTest.log)
Errors while running CTest. 
Error while building/deploying project TudatBundle (kit: Desktop (x86-windows-msys-pe-64bit)) When executing step "CMake Build"

**Comment by DominicDirkx** [comment]
I don't see any failures in your test log file. Could you elaborate on why you opened the issue?

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
