### ISSUE TITLE
Use Visual Studio 2019 as my IDE

### ISSUE THREAD

**Issue by Robot233** [Tudat/tudat#588]
![1](https://user-images.githubusercontent.com/55019890/69217138-d38f0c00-0ba8-11ea-9bf7-dd32f7fe09bb.JPG)

When Check if C POSIX library is present，it always wrong.
FATAL_ERROR "C POSIX libraries not found on system. Please (re)install development environment."
I want to know how to solve this problem .
Thanks.

**Comment by DominicDirkx** [comment]
To get some input how to solve this problem, please provde much more information. What have you done, what are doing, when is this occuring, etc.

For issue with Tudat installation and usage, we can try to help out.

**Comment by Robot233** [comment]
Just use Visual Studio 2019 to open “CMakeLists.txt”.
Like this:
![无标题](https://user-images.githubusercontent.com/55019890/69221897-4a310700-0bb3-11ea-9adc-31c9d3e391a3.jpg)
But it couldn't work.
The problem is "FATAL_ERROR "C POSIX libraries not found on system. Please (re)install development environment."

**Comment by DominicDirkx** [comment]
If you wish to use a different workflow from the one we recommend, that is fine, but we do not provide any support. If you wish to get support and input from us, please use the workfllow described on our website.

**Comment by Robot233** [comment]
Thanks for your reply.

**Comment by elmarputs** [comment]
Hi,

In the past, I have tried to get Tudat working with VS2019 but I did not succeed. Tudat uses quite a few external libraries and relies heavily on templated code, with which the MSVC compiler does not really work well. Even after tweaking the CMake scripts, compiling remains a pain. 
If, however, you manage to get it working, I would be happy to hear how!

In case you want something else than QtCreator, you could also try Jetbrains' CLion (my personal favourite), which works both on Linux and Windows. Unfortunately, we still offer support for QtCreater only.

Elmar
