### ISSUE TITLE
Error with space in input. 

### ISSUE THREAD

**Issue by bodjie** [Tudat/tudat#589]
In my files for juicePropagation_Q1.json I get the following error:

15:55:59: Starting /Users/bodjie/tudatBundle/tudat/bin/json_interface juicePropagation_Q1.json...
15:55:59: The program has unexpectedly finished.
15:55:59: The process was ended forcefully.
15:55:59: /Users/bodjie/tudatBundle/tudat/bin/json_interface crashed.

The reason for this error was because my input was: " Ganymede" instead of: "Ganymede".

The link to my private repository is: https://github.com/bodjie/NumericalAstrodynamicsAssignments_2019.

If it would be possible to add an error explanation, that would be very helpful!

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
