### ISSUE TITLE
Orbit Determination and Parameter Estimation

### ISSUE THREAD

**Issue by Robot233** [Tudat/tudat#590]
Hello .
In the application tutorials,I  want to know  whether tudat can solve the optical measurement data of asteroid or Jupiter satellite to calculate the ephemeris of such target.
And how to load real data  into Tudat as input?

**Comment by DominicDirkx** [comment]
This functionality is not in the example applications. But, you can simulate optical (astrometric) observations by using the angular_position observable.

Loading real data will require a custom-built function, depending on the file format. Note that Tudat does not (yet) contain all the required functionality for estimation from real optical data.

Best,

Dominic

**Comment by Robot233** [comment]
Thanks Dominic.
I will Keep learning and trying.

**Comment by DominicDirkx** [comment]
Hi,

Good luck, I am curious to hear what you are working on, its always nice when people find our software and use it for their own work. As you may have noticed, our time available for basic software support is rather limited. If you would like to collaborate on a research project, I may be able to find more time. If you would like to discuss further, please send me an e-mail, see:

https://www.tudelft.nl/staff/d.dirkx/

Best,

Dominic

**Comment by Robot233** [comment]
I am so sorry that i reopen this issue.A problem I could not understand.As follows:
I want to test the measureement simulation data.

//craet ground station ................
createGroundStation( bodyMap.at( "Earth" ),"Y",
                           (Eigen::Vector3d( ) << 1344e3, 6069e3, 1429e3 ).finished( ), cartesian_position );

And set Initial orbit like this，r(-6345.0,-3728.0,-579.0)km;v(2.169,-9.266,-1.079)km/s
![image](https://user-images.githubusercontent.com/55019890/70234011-a9d60780-179a-11ea-8034-0f214e9abcc5.png)
Time is 1995/03/30 00：00UTC.
The ObservationMeasurements of one_way_range is  "9118031.366895031m" at this time.
But I have  calculated with the same data and got other answer of the distance between ground station and satellite."6471082.264302m".I believe my the later is correct and I have no idea what's wrong with my code.
Here is my code.
[code.txt](https://github.com/Tudat/tudat/files/3926771/code.txt)

I'm sorry for the interruptions.I am working on a design in which I need to estimate  initial orbit.
Thanks.

**Comment by DominicDirkx** [comment]
Please, see my previous post. We can provide some support for the installation and usage of Tudat, but we do not have the capacity to debug all your issues. Work on Tudat in the context of a collaboration could make it easier for us to free up resources, though.

Finally, when posting code, please push it to your own repository, and refer to it,

Dominic

**Comment by Robot233** [comment]
I got it.Thank you!
