### ISSUE TITLE
Error after running Json file , no output is given

### ISSUE THREAD

**Issue by jurrienvos** [Tudat/tudat#592]
After running the Json file no output is given in the C:\tudatBundle\numericalastro_jurrienvos map and there is a message in the "Application Output" file. The message in the "Application Output" is attached here together with the "Compile Output", please see below (in txt file).

Link to depositry: https://github.com/jurrienvos/numericalastro_jurrienvos, Json file is attached here with the name aangewerktjuicePropagation.json.

[Application Output.txt](https://github.com/Tudat/tudat/files/3905662/Application.Output.txt)
[Compile Output.txt](https://github.com/Tudat/tudat/files/3905664/Compile.Output.txt)

Thank you in advance for helping me out!
.

**Comment by DominicDirkx** [comment]
Quick reply before the weekend:

Input is case-sensitive, don't confuse Juice and JUICE. I think this is causing your problem

Also, these kind of specific questions on the assignments are best posted on Brightspace. Github is meant more for general Tudat (installation) issues.
