### ISSUE TITLE
Problem using matlabinterface

### ISSUE THREAD

**Issue by StefanTremm** [Tudat/tudat#593]
Dear Mr Dirkx,

I want to use tudat for my mastersthesis (simulating satellites orbits to predict the observability of satellites) but there is a little problem getting it to work. Since I'm not very experienced with c/c++ but with matlab I would like to use the matlab interface. Especially since the example of the GALILEO-simulation would bring me a huge step further.

First I followed the instructions to compile tudat on my local workstation (windows 7 professional, matlab 2016b) and that went perfectly fine. Running the test within QT right after compiling was no problem at all. Furthermore I am able to run some of the examples as long as they are from the folder "InputOutput". Export to and import from json is no problem. I think this shows, that the compiling was sucessfull.

The problem starts if I want to use tudat from within matlab seamlessly. While I am able to use the function "tudat.load()" everytime the file "simulation.m" is used I get following exception:

```
Error using Simulation/run (line 127)
Error while running Tudat.
              "if status ~= 0
                    error('Error while running Tudat.'); <-- 127
               end"

Error in galileoConstellation (line 58)
simulation.run();
 
```
To solve this I read through some posted issues and commented line 152 (%deleteIfExists(Simulation.defaultInputFileName);) and switched the "Systemcommand.m" to the one you already suggested to another user for getting more information about the processing.

[Report.txt](https://github.com/Tudat/tudat/files/3906444/Report.txt)

Even though I know that the matlab interface is not supported any longer, could you be so kind please and and give me some hints if I am missing something important to get it working? It would really be a huge help for getting my work done.

Best regards

**Comment by CarlosEntrerraz75** [comment]
Same here but with win10. Help would be much appreciated.

**Comment by DominicDirkx** [comment]
Hi,

I'm afraid that, due to maintainability issues, and very limited capacity in the Tudat support staff. We no longer support the use of the Matlab interface. You can achieve much the same functionality through the use of our JSON interface. 

If you are a student of TU Delft using this for your M.Sc. thesis, please contact me by e-mail to discuss your use of Tudat,

Best,

Dominic
