### ISSUE TITLE
QT warning after OSX Catalina update

### ISSUE THREAD

**Issue by AntoineClout** [Tudat/tudat#595]
Hello, 

Yesterday I updated the OS of my laptop and today when I open QT I have the following error message : 

/Users/Antoine/tudatBundle/external/CMake/add_boost.cmake:98: error: C POSIX libraries not found on system.  From command line execute: xcode-select --install. /Library/Developer/CommandLineTools"

However when I try to run this command, the terminal says it is not valid. I tried to follow again the steps on "http://tudat.tudelft.nl/installation/downloadTudatBundle/index.html" but all step 2 is OK, and when I try do redo it it tells me I already have the library, but step on step 3 the first step is to open the CMakeList and run it, but as you may see in the pictures I can't run anything. I don't know what to do and that's why I came for help. 
I joined to the post a .txt containing the general message output that's written just after opening TudatBundle from the home page of QT.

Thank you in advance, 

Antoine Clout
[general_message_output.txt](https://github.com/Tudat/tudat/files/3928208/general_message_output.txt)

![Capture d’écran 2019-12-05 à 18 17 55](https://user-images.githubusercontent.com/57559520/70257920-90798f00-178b-11ea-9a06-8f4ead3b9b1f.png)
![Capture d’écran 2019-12-05 à 18 18 52](https://user-images.githubusercontent.com/57559520/70257988-b1da7b00-178b-11ea-9148-a0e57357d315.png)
![Capture d’écran 2019-12-05 à 18 19 06](https://user-images.githubusercontent.com/57559520/70258008-bb63e300-178b-11ea-97e8-53b4c41e619b.png)

**Comment by transferorbit** [comment]
I believe we have solved this now.
Executing the command `xcode-select --install` seems to have been the trick. Doing this also corrected the errors you were seeing regarding the path to the developer tools.
