### ISSUE TITLE
Variational equations

### ISSUE THREAD

**Issue by gijsleemans1** [Tudat/tudat#596]
As discussed over email, opening this issue to see where I'm going wrong with my variational equations in the code, since my analytical approach seems te be correct. Link to private repository: https://github.com/gijsleemans1/NumericalAstrodynamics2019_GijsLeemans/tree/master/src2

**Comment by DominicDirkx** [comment]
Hi Gijs,

My mistake, I meant open a Brightspace issue. Could you repost this issue there?

Please, add this reply from my side in the Brightspace issue

Hi Gijs,

Contrary to what I said during the open-office hours, you are on the right track with your derivation. 

To track down your error, try plotting the corrected - lambert, and uncorrected - lambert, for your first arc only, in the same plot. This will give you more insight into what your correction is achieving, and will hopefully give you a better handle on what's going on.

Best,

Dominic

p.s. To all: please consider this evening-response an exception.
