### ISSUE TITLE
Error in hybrid termination settings, 

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#598]
Error message reads,
"terminate called after throwing an instance of 'std::runtime_error'
Error in hybrid termination settings, terminateExactlyOnFinalCondition_ is inconsistent "

What can cause such an error? 

Please let me know what information is required, and I shall provide. 
Thanks,

With regards,
Rajath

**Comment by DominicDirkx** [comment]
Hi Rajath,

You can "search all" in the code to find out where this error is thrown. If this doesnt resolve things for you, please post an update with your findings here,

Best,

Dominic

**Comment by RajathPai95** [comment]
hey Dominic,

I apologise to bother you with this, but can you elaborate on what you mean by "search all". Where can I look up on how to perform such a search.

There is no output so I'm unable to determine the termination. I'm trying to understand why this error gets thrown. 
Thank you for your patience,


With regards,
Rajath

**Comment by DominicDirkx** [comment]
Hi Rajath,

This is really something you can find by just googling. The first hit when googling "qt creator search all files" is this very useful page:

https://doc.qt.io/qtcreator/creator-editor-finding.html

Dominic

**Comment by RajathPai95** [comment]
Hey Dominic,

I apologise for the late response, as I've been sick past couple of days. 

I did search the code, but I did not understand what you meant by searching the code. I'm not sure on what you wanted me to look for. 

My error tracing has lead to conclude altitude_dependent variable setting causing the error
           termSettList.push_back(std::make_shared< PropagationDependentVariableTerminationSettings >(
                                                    std::make_shared< SingleDependentVariableSaveSettings >(altitude_dependent_variable, "Vehicle" , "Earth" ), targetVector_[0], false, true, terminationRootFinderSettings) );

I'm not sure why this creates and inconsistency in the termination settings.  The targetVector(0) refers to the target altitude for the spacecraft. 
Was it an initialisation error? 
Was it an error where my multiple termination settings are contradicting somehow?
I was and am looking for specifics that perhaps the error message can tell you when it says
_"Error in hybrid termination settings, terminateExactlyOnFinalCondition_ is inconsistent "_

Thanks again,


With regards,
Rajath

**Comment by DominicDirkx** [comment]
Hi Rajath,

If you 'search all' in the code for this error message, you'll quickly find that the error is thrown here:

https://github.com/Tudat/tudat/blob/master/Tudat/SimulationSetup/PropagationSetup/propagationTerminationSettings.h#L235-L247

Dominic

**Comment by RajathPai95** [comment]
Hey Dominic,

Yes, I already knew where the error message is generated from. I had checked the file already and knew what was causing the problem in terms of code. It shows inconsistencies when the variable terminateExactlyOnFinalCondition isn't the same for all dep. variables. 

However, I am to understand that it checks for termination for each of the dependent variables setup. Can i clarify the true and false implications for the following parameter, as I might be misunderstanding what's stated here and feel that this is creating the problems. 

* \param terminateExactlyOnFinalCondition Boolean to denote whether the propagation is to terminate exactly on the final condition, or whether it is to terminate on the first step where it is violated.

True for first condition and false for second condition? or do you mean it stays false till the condition is met(final or first violation) and true for final and termination? This would be helpful. 

Thank you,

With regards,
Rajath

**Comment by DominicDirkx** [comment]
Hi Rajath,

I don't think I understand your question(s), can you clarify?

Concerning this error, your settings have to be such that it requires termination on an **exact** condition for all of the constituent conditions, or none of them. So, if it is set to false for all constituent conditions, the propagation will terminate the first time it has crossed one of the conditions. If it is set to true for all constituent conditions, it will terminate exactly on whichever condition occurs first,

Dominic

**Comment by RajathPai95** [comment]
Hey Dominic,

I see. So, If i understand correctly, all of the dependent variable based termination settings have to have the same termination condition and the inconsistency between them is not allowed in TUDAT. I understand. I had set one of them to true and the rest to false, and was wondering if this was allowed. Thank you for clarifying. I apologise that it took some time to come forth and discuss this issues. I had a hard time understanding what you were implying, and i wasn't sure what you needed from me. I think the issue will be resolved and I will initiate all settings with 'false' and it should work.
Thank you,


With regards,
Rajath
