### ISSUE TITLE
CR3BP not working with Earth/Moon System

### ISSUE THREAD

**Issue by wcyoung08** [Tudat/tudat#600]
Hi, I'm trying to model an NRHO at the L2 point, based closely on the "Targeting Cislunar NRHO" paper I'll attach to this issue. I have taken the CR3BP example application that deals with the Sun and Jupiter, and simply replaced all of the instances of "sun" with "earth, and "jupiter" with moon. I took out the perturbed case because I'm simply interested in getting a 3-d plot of the position of the satellite and the moon around an Earth-centered frame. Building the application works fine, but running it gives nonsensical results. I will attach the code I rewrote and the results as well. 
[Tudat_Issue.zip](https://github.com/Tudat/tudat/files/3974939/Tudat_Issue.zip)

**Comment by DominicDirkx** [comment]
Dear William,

Can you confirm that the original CR3BP example (unmodified) does work fine, and produces results you would expect?

If so, please attach figures for your results of the case you are running and explain in some detail why you conclude that the results you get are nonsensical, as compared to your theoretical expectations.

Dominic

**Comment by wcyoung08** [comment]
I'll attach images of 3 different cases. The first was using the normal CR3BP code and getting the expected results. The second is the results from the modified code I made, replacing every instance of "Sun" with "Earth" and "Jupiter" with "Moon", and replacing the accompanying variables and values. I also got rid of the perturbed case since I was trying to simply get this simpler case to work first.

I assume the issue may be due to my own misunderstanding of the code or setting up the problem rather than anything on tudat's side. Perhaps I also interpreted the initial state from the paper I gave earlier incorrectly as well. Let me know if I can help out with anything else to solve this.
[CR3BP_Results.zip](https://github.com/Tudat/tudat/files/3995349/CR3BP_Results.zip)

**Comment by DominicDirkx** [comment]
Dear William,

Thank you for the additional details. I'm afraid that to properly determine what is going on with your code, I would have to dive quite deep into your code and the paper you sent, which is well outside the level of support that we can offer for Tudat. Based on your results, I can say that the code seems to function as expected for the example application. 

My best guess is that there is an issue with the manner in which you are interpreting/applying the initial condition from the paper. I would advice you to set up your own simulation, using a simpler initial state that you derive yourself to produce a simple orbit, and take it from there,

Best,

Dominic
