### ISSUE TITLE
Terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by gijsleemans1** [Tudat/tudat#602]
Hi,
I'm currently working on the group assignment for AE4868, and have tried implementing the code for the first question. I do not get any errors before running, but while running I get the following message:

![image](https://user-images.githubusercontent.com/57616775/71965232-94bc2080-31ff-11ea-8d28-b42fe8bebe5d.png)

I believe that this means that I'm somewhere trying to access a part of a map that does not exists, but in my code I do not see where this could be the case.

link to my repository: https://github.com/gijsleemans1/NumericalAstrodynamics2019_GijsLeemans

**Comment by DominicDirkx** [comment]
Hi Gijs,

For these specific questions concerning the assignment code, please use the Brightspace forum.

Dominic
