### ISSUE TITLE
System error: Invalid argument, Failed to compute build system

### ISSUE THREAD

**Issue by Casperbru** [Tudat/tudat#603]
After making a cloning my code in a new repository and putting it on my system I rebuild everything, then my computer sort of froze, so I turned it off. After restarting I opened Qt again and the tudat project, but during the scanning of the project tree and te configuring of the project it crashes. I commented the new clone out in the CMakelist and reversed some minor changes I made this morning. But I keep getting the same problem. 
In the issues tap it just says:
: System Error: Invalid argument
Failed to compute build system.
with no explanation.
The general message tab output is attached.
This morning I ran the code without any issues.
[errorMessage.txt](https://github.com/Tudat/tudat/files/4039892/errorMessage.txt)

**Comment by DominicDirkx** [comment]
Hi Casper,

Could you give a short summary of how you resolved this?

Dominic

**Comment by Casperbru** [comment]
Yes of course.
Apparently a temporary file is made in dir:
C:\build-tudatBundle-Desktop_Debug\tudat\Tudat\Astrodynamics\BasicAstrodynamics\CMakeFiles\test_UnifiedStateModelExponentialMapElementConversions.dir
which is called depend.make.tmp if I remember correctly.
I think that normally this file is deleted after building, but because of my computer freezing and turning it off this file was still there. It was a corrupted file, so Qt couldn't open/write/read or do anything with it. I couldn't delete or open it either because it was corrupted. In the end I had to restart the computer in recovery mode to detect corrupted files and delete them. Afterwards Qt was able to rebuild everything again.

**Comment by DominicDirkx** [comment]
Clear. Thank you!
