### ISSUE TITLE
Failed Unit Tests 78/333

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#606]
OS: Windows 10 64 bit
QT version : 4.11.0

A majority of unit tests failed 

I recently reinstalled tudat (less than 2 weeks ago). Many are related to PaGMO, I believe which has not been working. Here is the Compile Output file. 

Do i need to rebuild the tudatBundle? 

Please let me know what Info I can provide to detect what is wrong?

[Compile Output_2601.txt](https://github.com/Tudat/tudat/files/4118204/Compile.Output_2601.txt)

**Comment by DominicDirkx** [comment]
Dear Rajath,

Many of the tests are not run, indicating that compilation of the tests did not finish succesfully. Please compile everything, and send the compilation output. From that, we should be able to find the best next steps to take,

Best,

Dominic

**Comment by RajathPai95** [comment]
A clean and rebuild has taken care of the issue. The tests were not being run because although the files were present, the build could not find them. I'm not sure why this occured, but it has been taken care of. PaGMO was enabled but the build could not access it somehow. All 333 tests have now passed.
