### ISSUE TITLE
Linking Errors with PaGMO and custom tudatApplication

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#607]
The PaGMO applications from custom tudatapplications have a linking error with the pagmo bundle. Unit tests and example applications still work normally. I'm unable to detect the linking error and correct for it.  The compile output is given below.

[Compile Output 2901.txt](https://github.com/Tudat/tudat/files/4129293/Compile.Output.2901.txt)

The code can be found in the link, 
https://github.com/RajathPai95/thesis 

I'm trying the PaGMO in application_simulation and it shows linking errors with PaGMO

**Comment by DominicDirkx** [comment]
Your repository is empty, please review.

**Comment by RajathPai95** [comment]
I'm sorry, It has been updated now. Please have a look

**Comment by DominicDirkx** [comment]
I think your target_link_libraries list is incomplete. Have a look at the corresponding lines for the provided Pagmo example applications,

Best,

Dominic

**Comment by RajathPai95** [comment]
Thank you.
