### ISSUE TITLE
No unit test can be found using the server

### ISSUE THREAD

**Issue by Casperbru** [Tudat/tudat#608]
Hi,

I just installed and built tudat on the eudoxos server and I followed the manual on the site. When I try to run the unit tests it say that none of the tests is ran and that it is unable to find the executables. I attached the log, can you help me finding out what goes wrong?
[LastTest.log](https://github.com/Tudat/tudat/files/4147271/LastTest.log)

**Comment by DominicDirkx** [comment]
Hi Casper, 

Could you post:

- terminal output when running cmake
- terminal output when compiling

in two separate files. From those, we should be able to get some idea what us going wrong,

Best,

Dominic

**Comment by Casperbru** [comment]
[running cmake.txt](https://github.com/Tudat/tudat/files/4147503/running.cmake.txt)
[test output.txt](https://github.com/Tudat/tudat/files/4147511/test.output.txt)

This is the file when i use the command cmake CMakeLists.txt and for the command cmake --build . --target all -- test
Is this what you mean?

**Comment by DominicDirkx** [comment]
Hi Casper,

From the looks of it, you are running CMake, and subsequently immediately trying to run the tests. Before running the tests, first compile all the code. If this is not explained correctly/clearly in the guide, please let us know,

Best,

Dominic

**Comment by Casperbru** [comment]
Yes you were right, by first running the command cmake --build . --target all --, tudat was built first after whcih i passed all the tests without any problems.
This step is missing in the guide at the moment.
