### ISSUE TITLE
Unit tests error after update

### ISSUE THREAD

**Issue by thepedrobl** [Tudat/tudat#610]
Hello, professor. I have just followed the update guide on the Propagation and Optimization in Astrodynamics brightspace page and encountered the following error (compile output) when I tried to build with unit tests:

```
99% tests passed, 2 tests failed out of 257

Total Test time (real) = 1691.15 sec

The following tests FAILED:
	154 - test_HodographicShaping (Not Run)
	155 - test_SphericalShaping (Not Run)
Errors while running CTest
mingw32-make.exe: *** [Makefile:72: test] Error 8
14:14:45: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop (x86-windows-msys-pe-64bit))
When executing step "CMake Build"
```
When I build without the "test" argument, I just get warnings, no errors.
Any idea of what I should do next?

**Comment by DominicDirkx** [comment]
Hi Pedro,

Thanks for doing this update so quickly.

From the looks of it, you are using a Windows system (?)

Could you post the log files described here:

http://tudat.tudelft.nl/installation/troubleshooting/installationErrors.html#failed-unit-tests

Then, we can have a look  to see if this is anything serious,

Best,

Dominic

**Comment by zabibbo** [comment]
Dear professor,
I am having the same problem as Pedro. As you requested, these are my log files.
I am using a Window system.

[LastTest.log](https://github.com/Tudat/tudat/files/4176870/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/4176871/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
Dear Benedetta, Pedro,

Before running the tests, did you recompile? That is: did you compile Tudat _without_ having 'test' command written under Build steps->Tool arguments?

![image](https://user-images.githubusercontent.com/5039068/74102284-6ef9a280-4b42-11ea-8d26-5331d704b8c9.png)

If not, please do so, and then rerun all unit tests. You can use the -jX, with X the number of parallel threads, to speed up the compilation process (as with the original compilation of Tudat).

If you have compiled without the 'test' argument, please do so again, and post the 'Compile output' you get here,

Best,

Dominic

**Comment by zabibbo** [comment]
I rerun without the 'test' command and then with it. These are the log files and the compile output.

[LastTest.log](https://github.com/Tudat/tudat/files/4177201/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/4177202/LastTestsFailed.log)
[CompiledOutput.txt](https://github.com/Tudat/tudat/files/4177206/CompiledOutput.txt)

**Comment by thepedrobl** [comment]
When building without the testing: 
[Compile Output no test.txt](https://github.com/Tudat/tudat/files/4177574/Compile.Output.no.test.txt)
After that, with testing on:
[Compile Output with test.txt](https://github.com/Tudat/tudat/files/4177576/Compile.Output.with.test.txt)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/4177577/LastTestsFailed.log)
[LastTest.log](https://github.com/Tudat/tudat/files/4177578/LastTest.log)

**Comment by DominicDirkx** [comment]
@zabibo: Could you please add your compile output when compiling _without_ the test command.

@thepedrobl Please compile 'all' applications (instead of 'current executable') that you seem to have set now

**Comment by gijsleemans1** [comment]
[compileoutput.txt](https://github.com/Tudat/tudat/files/4180836/compileoutput.txt)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/4180838/LastTestsFailed.log)

Hello,
Not sure if I'm right in posting in this already existing thread, but I am also getting a failed unit test since updating.

`The following tests FAILED:
	185 - test_UnscentedKalmanFilter (Failed)
Errors while running CTest
mingw32-make.exe: *** [Makefile:72: test] Error 8
13:47:56: The process "D:\Programs\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop (x86-windows-msys-pe-64bit))
When executing step "CMake Build"`

 I did re-fetch the code roughly an hour ago since I saw some changes were made, and I also first compiled the application without the test command, which didnt give any errors. 

Gijs

**Comment by DominicDirkx** [comment]
Hi Gijs,

This looks fine, the test failure is nothing to worry about,

Best,

Dominic

**Comment by thepedrobl** [comment]
> @thepedrobl Please compile 'all' applications (instead of 'current executable') that you seem to have set now

That seems to have solved the problem
Built "all" without "test", then "all" again with" test" and passed all unit tests
Thank you!
(I'll keep the issue open until @zabibbo confirms this)

**Comment by zabibbo** [comment]
Also in my case, this solved the issue. 
Thank you very much!
