### ISSUE TITLE
Error test_HodographicShaping 

### ISSUE THREAD

**Issue by bodjie** [Tudat/tudat#611]
[Compile_output.txt](https://github.com/Tudat/tudat/files/4179738/Compile_output.txt)

Dear Dominic,

When running the Hodographic Shaping Test it gave the error attached in the .txt file. 
I hope you can help me solve this!

Kind regards,
Bodjie

**Comment by DominicDirkx** [comment]
Dear Bodjie,

I've pushed some changes to the tudat repository that will hopefully correct his issue. Please redo step 1 in the announcement on Brightspace, recompile, and let us know if this corrects the issue,

Best,

Dominic

**Comment by bodjie** [comment]
[Compile_output.txt](https://github.com/Tudat/tudat/files/4180198/Compile_output.txt)
 
Dear Dominic,

I followed the steps and there are less errors now, bit I still obtain the following errors.

Kind regards,
Bodjie

**Comment by DominicDirkx** [comment]
Hi Bodjie,

I've pushed some more modifications, please get the latest changes (redo step 1) and recompile. Let's hope this fixes the issue(s),

Best,

Dominic

**Comment by bodjie** [comment]
It works now, thank you!!

**Comment by marsala97** [comment]
Dear Dominc,

I am writing here to avoid opening a similar thread about Unit test failures. As an attachment you can find the compile output, where the test   "98 - test_DesaturationDeltaVsEstimation" failed.

Thanks in advance for your support,
Kind regards,
Marco Sala


[Tudat_Error.txt](https://github.com/Tudat/tudat/files/4185360/Tudat_Error.txt)

**Comment by DominicDirkx** [comment]
Hi Marco,

This error should now have been resolved when updating the code. However, there is no need to do this update for P&O,

Best,

Dominic
