### ISSUE TITLE
Error: 10 - test_ControlSurfaceIncrements (Failed) -Windows

### ISSUE THREAD

**Issue by andrewia3** [Tudat/tudat#613]
[LastTest.log](https://github.com/Tudat/tudat/files/4204582/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/4204584/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
Hi Andrea,

I think you may have inadvertently made a change to the code. Could you go to ..../tudatBundle/tudat/ in your terminal, type

git diff

and post the results in a text file here?

Best,

Dominic

**Comment by andrewia3** [comment]
Dear Dominic,
thank you.

I am attaching the results up to ":". I guess I should type something afterwards, but I do not know what exactly. 
[results.txt](https://github.com/Tudat/tudat/files/4208861/results.txt)

**Comment by DominicDirkx** [comment]
Hi Andrea,

At the end you should hit the Enter key until the output finished, then copy paste the full output into a file. From the looks of it, there are some modifications in the code for this unit test, most likely explaining your problem,

Best,

Dominic

**Comment by andrewia3** [comment]
Dear Dominic, 
thank you for your help and patience. I have confronted my test file with a colleague's and I run the tests again, getting again the same error. 
I have attached again the text file. 
[gitdiff.txt](https://github.com/Tudat/tudat/files/4213541/gitdiff.txt)
