### ISSUE TITLE
Environment models modifications-LunarAscent

### ISSUE THREAD

**Issue by andrewia3** [Tudat/tudat#614]
Dear Dominic,

after having unsuccessfully tried the implementation of the rotational model of the moon, I have tried to implement  a function to get tidal deformation model for the moon, exactly as shown in the examples here on GitHub. Nonetheless, I get another (similar?) error: 
Toolkit version: N0066
 
SPICE(DAFNEGADDR) --
 
Negative value for BEGIN address: -2147314469
 
A traceback follows.  The name of the highest level module is first.
spkezr_c --> SPKEZR --> SPKEZ --> SPKGEO --> SPKPVN --> SPKR02 --> DAFGDA

Is it possible that I am doing something wrong? I hope you can help me.

Furthermore, I have tried to push my code as shown in brighspace and my tudat_shell  says that everything is up-to-date, but it seems it is not.

Thank you for you help in advance,
Andrea Iannone

**Comment by DominicDirkx** [comment]
Hi Andrea,

Please post this question on Brightspace, it will be easier for others to find there. Also, without being able to look at your code, I cannot do much to help you out in this,

Best,

Dominic
