### ISSUE TITLE
[test] Error 8

### ISSUE THREAD

**Issue by bushraky8** [Tudat/tudat#615]
Dear Dominic, 

I am having the above mentioned test error. I reinstalled tudat yesterday, but the unit test is failing. Initially I thought its due to the virus scanner which started running in the background. So I excluded the tudatbundle from this scan in the settings, recompiled and then started the unit tests again. However this is not solving the problem. Also I looked into the similar issue created for the propagation course, however I cannot register for the course right now to view it. 
I did not reinstall Qt creater (compiler is MinGw 5.3.0 32 bit for windows 10 operating `system).

**Comment by bushraky8** [comment]
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/4312400/LastTestsFailed.log)
[LastTest.log](https://github.com/Tudat/tudat/files/4312402/LastTest.log)

**Comment by DominicDirkx** [comment]
Hi Bushra,

In that case, please reinstall Qt with the newer compiler. With a little luck, that will solve this issue,

Best,

Dominic

**Comment by bushraky8** [comment]
The Qt creator asks for an account, skip option is not there anymore.  Should I make an account?

**Comment by bushraky8** [comment]
Hi Dominic, 

I had to reinstall everything including tudat, and now all test passed!

Bushra

**Comment by roosmartens** [comment]
Dear Dominic,

I am getting the same error (error 8). I have a new computer so had to reinstall tudat and qt creator, so this does not work to fix the error. When installing everything the way it was supposed to for the course Numerical Astrodynamics, all unit tests worked, but after I tried building with socis_2019 this error occurred. Also, I tried to update the tudat code again and rerun unit tests, which did not help again. My failed unit tests were different as Bushra's though: I attached a log so you can see.
[failedtestslog.txt](https://github.com/Tudat/tudat/files/4386664/failedtestslog.txt)

**Comment by erickam0324** [comment]
Dear Dominic, 

I have the same issue when  using "test" and "all", the previous unit testing using "-j2" did not give me any errors. 
The only that outputs is " [test] Error 8 ". 

As I saw this post, I re-installed both tudat and QT Creater but still gives me the error. I am using Mac version 10.14.6. 

Do you have any other suggestions ? 

Thank you. 
Ericka

**Comment by DominicDirkx** [comment]
Hi Ericka,

First, please compile without the 'test' command, and post the full compile output in a text file.

If there are no errors, then run _with_ the 'test' command, and again post the full compile output in a text file. In either case, there will be a lot more output than the line you show in your post,

Best,

Dominic

**Comment by erickam0324** [comment]
Dear Dominic, 

Previously I had no errors when compiling with -j2, but now that I have re-installed everything I get an error. Please see the text file below for the full compile output. 

Kind regards, 
Ericka Martin 
[Compileoutput_j2.txt](https://github.com/Tudat/tudat/files/4395429/Compileoutput_j2.txt)

**Comment by DominicDirkx** [comment]
This looks like the same error as was reported here:

https://github.com/Tudat/tudat/issues/619
