### ISSUE TITLE
Error when using Pagmo

### ISSUE THREAD

**Issue by bodjie** [Tudat/tudat#617]
Dear Dominic,

I get the following tests that didn't run or failed aften I toggled USE_PAGMO to on:
The following tests FAILED:
	  2 - ackley (Not Run)
	  3 - algorithm (Not Run)
	  4 - algorithm_type_traits (Not Run)
	  5 - archipelago (Not Run)
	  6 - archipelago_torture_test (Not Run)
	  7 - base_bgl_topology (Not Run)
	  8 - base_sr_policy (Not Run)
	  9 - bee_colony (Not Run)
	 10 - cec2006 (Not Run)
	 11 - cec2009 (Not Run)
	 12 - compass_search (Not Run)
	 13 - constrained (Not Run)
	 14 - custom_comparisons (Not Run)
	 15 - cstrs_self_adaptive (Not Run)
	 16 - de (Not Run)
	 17 - de1220 (Not Run)
	 18 - decompose (Not Run)
	 19 - discrepancy (Not Run)
	 20 - dtlz (Not Run)
	 21 - fair_replace (Not Run)
	 22 - fully_connected (Not Run)
	 23 - gwo (Not Run)
	 24 - gaco (Not Run)
	 25 - generic (Not Run)
	 26 - golomb_ruler (Not Run)
	 27 - gradients_and_hessians (Not Run)
	 28 - griewank (Not Run)
	 29 - hypervolume (Not Run)
	 30 - hock_schittkowsky_71 (Not Run)
Errors while running CTest
make: *** [test] Error 8
	 31 - inventory (Not Run)
	 32 - lennard_jones (Not Run)
	 33 - migration_torture_test (Not Run)
	 34 - minlp_rastrigin (Not Run)
	 35 - ihs (Not Run)
	 36 - io (Not Run)
	 37 - island (Not Run)
	 38 - island_torture (Not Run)
	 39 - luksan_vlcek1 (Not Run)
	 40 - mbh (Not Run)
	 41 - moead (Not Run)
	 42 - multi_objective (Not Run)
	 43 - nsga2 (Not Run)
	 44 - nspso (Not Run)
	 45 - population (Not Run)
	 46 - problem (Not Run)
	 47 - problem_type_traits (Not Run)
	 48 - pso (Not Run)
	 49 - pso_gen (Not Run)
	 50 - r_policy (Not Run)
	 51 - rastrigin (Not Run)
	 52 - ring (Not Run)
	 53 - rng (Not Run)
	 54 - rng_serialization (Not Run)
	 55 - rosenbrock (Not Run)
	 56 - s_policy (Not Run)
	 57 - sade (Not Run)
	 58 - simulated_annealing (Not Run)
	 59 - sga (Not Run)
	 60 - schwefel (Not Run)
	 61 - sea (Not Run)
	 62 - select_best (Not Run)
	 63 - threading (Not Run)
	 64 - thread_island (Not Run)
	 65 - topology (Not Run)
	 66 - translate (Not Run)
	 67 - type_traits (Not Run)
	 68 - unconnected (Not Run)
	 69 - unconstrain (Not Run)
	 70 - wfg (Not Run)
	 71 - zdt (Not Run)
	 72 - cmaes (Not Run)
	 73 - eigen3_serialization (Not Run)
	 74 - xnes (Not Run)
	 75 - fork_island (Not Run)
	 76 - getting_started (Not Run)
	 77 - nsga2_example (Not Run)
	 78 - problem_basic (Not Run)
	 79 - problem_basic_gh (Not Run)
	 80 - problem_basic_s (Not Run)
	193 - test_LightTimePartials (Not Run)
	233 - test_SimsFlanagan (Not Run)
	309 - test_JsonInterfaceDeserialization (Failed)

I saw the issue opened by Benedetta, but what seemed to fix the error for her doesn't for me. 

When compiling 'all' (no test argument) I get the following output:
[CompileOutput.txt](https://github.com/Tudat/tudat/files/4370923/CompileOutput.txt)

Do you maybe have an idea on how to fix this error?

Kind regards,
Bodjie

**Comment by DominicDirkx** [comment]
Hi Bodjie,

The problem seems to occur when compiling your code for the group assignment of Numerical Astrodynamics. Remove the link to the Numerical Astrodynamics code in the tudatBundle/CMakeLists.txt file, and this error should go away,

Best,

Dominic

**Comment by bodjie** [comment]
Thank you, this seemed to fix most errors!
I still get the following test failed:
The following tests FAILED:
	233 - test_SimsFlanagan (Failed)
Errors while running CTest
make: *** [test] Error 8
	309 - test_JsonInterfaceDeserialization (Failed)
09:57:59: The process "/Applications/CMake.app/Contents/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop (x86-darwin-generic-mach_o-32bit))
When executing step "CMake Build"

When compiling 'all' (no test argument) I get the following output:
[CompileOutput.txt](https://github.com/Tudat/tudat/files/4374311/CompileOutput.txt)

Do you have an idea how I could fix this error?

Thank you very much in advance!

Kind regards,
Bodjie

**Comment by DominicDirkx** [comment]
Hi Bodjie,

That's looking better. Try commenting out these lines (with #496 :

https://github.com/Tudat/tudatExampleApplications/blob/master/libraryExamples/PaGMOEx/CMakeLists.txt#L177-L179

To try to correct this remaining error. Make sure to recompile all without the test command after making this change,

Best,

Dominic

**Comment by bodjie** [comment]
Hi Dominic,

I commented these lines out and recompiled them all without the test command. This gave no errors!
[CompileOutput.txt](https://github.com/Tudat/tudat/files/4375174/CompileOutput.txt)

After this I ran all unit tests and that gave the following tests that failed: 
The following tests FAILED:
	233 - test_SimsFlanagan (Failed)
	309 - test_JsonInterfaceDeserialization (Failed)
Errors while running CTest
make: *** [test] Error 8
13:20:08: The process "/Applications/CMake.app/Contents/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop (x86-darwin-generic-mach_o-32bit))
When executing step "CMake Build"

Do you have an idea how I could fix these unit Tests?

Kind regards,
Bodjie

**Comment by DominicDirkx** [comment]
Hi Bodjie,

Good to hear that his worked. I don't think these unit test failures are any problem, but please post the unit test log files and I'll have a look,

Dominic

**Comment by bodjie** [comment]
Hi Dominic,

This are the log files: 
[LastTest.log](https://github.com/Tudat/tudat/files/4375228/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/4375230/LastTestsFailed.log)

Kind regards,
Bodjie

**Comment by DominicDirkx** [comment]
Hi Bodjie,

These unit test failures are nothing to worry about, you can continue with the assignment.

To better understand this error, can you verify that this code:

https://github.com/Tudat/tudatExampleApplications/blob/master/libraryExamples/PaGMOEx/CMakeLists.txt#L176-L180

looks the same in your computer? In particular: is the if statement present for you? Please us know,

Best,

Dominic

**Comment by bodjie** [comment]
Hi Dominic,

This part, the if statement is present. But previously you told me to comment out these lines, so what is in the if statement is commented out as follows:

 if( NOT MINGW )
   # add_executable(application_PagmoCEC2013Comparison "${SRCROOT}/cec2013OptimizerComparison.cpp")
   # setup_executable_target(application_PagmoCEC2013Comparison "${SRCROOT}")
   # target_link_libraries(application_PagmoCEC2013Comparison pagmo pagmo2_library_example_problems tudat_input_output pthread ${Boost_LIBRARIES} )
 endif()

Kind regards,
Bodjie

**Comment by DominicDirkx** [comment]
Ok, thank you. Leave it as it is for now, you can do the assignment without any problem with this commented. I just wanted to check this so we can diagnose and correct the situation in the future.
