### ISSUE TITLE
Error: unrecognized command line option when building with PAGMO on

### ISSUE THREAD

**Issue by nmdekorte** [Tudat/tudat#618]
Dear Dominic,

When trying to compile with PAGMO I get the following error in my Compile Output:

```
21:07:07: Running steps for project TudatBundle...
21:07:07: Starting: "C:\CMake\bin\cmake.exe" --build . --target all -- -j1
[ 63%] Built target cspice
[ 63%] Built target nrlmsise00
[ 69%] Built target sofa
[ 69%] Built target sofa-test
[ 69%] Building CXX object pagmo2/CMakeFiles/pagmo.dir/src/algorithms/cmaes.cpp.obj
g++.exe: error: unrecognized command line option '-fdiagnostics-show-template-tree'; did you mean '-fdiagnostics-show-caret'?
mingw32-make.exe[2]: *** [pagmo2\CMakeFiles\pagmo.dir\build.make:80: pagmo2/CMakeFiles/pagmo.dir/src/algorithms/cmaes.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:2099: pagmo2/CMakeFiles/pagmo.dir/all] Error 2
mingw32-make.exe: *** [Makefile:157: all] Error 2
21:07:09: The process "C:\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
21:07:09: Elapsed time: 00:02.
```

I use a 64-bit Windows 8.1 operating system. MingW 7.3.0. 64-bit compiler is installed.
I checked that Qt is correctly configured (step 6 of windows install guide) and tried building both with build steps empty and with -j1 argument. (This error is with -j1 input argument)

I hope you can help solving this issue.

Regards,
Nico

**Comment by DominicDirkx** [comment]
Hi Nico,

For some reason, one of the Pagmo compiler flags is not recognized on your computer. You should be able to turn it off without consequences by comment (using #) this line in your code:

https://github.com/Tudat/pagmo2/blob/master/cmake_modules/yacma/YACMACompilerLinkerSettings.cmake#L153

Rerun CMake (if youre not sure how, you can do this by closing and reopening Qt), and then recompile.

Let me know if this works,

Best,

Dominic

**Comment by nmdekorte** [comment]
Hi Dominic,

I commented out the line you suggested and closed and re-opened Qt. I tried to build again (Hammer icon) with no input arguments and with -j1, but I get the exact same error (to the letter).

Don't know if it helps, but if I input -j2 I get a slightly different error:

```
12:28:50: Running steps for project TudatBundle...
12:28:50: Starting: "C:\CMake\bin\cmake.exe" --build . --target all -- -j2
[  0%] Built target nrlmsise00
[  6%] Built target sofa
[  6%] Building CXX object pagmo2/CMakeFiles/pagmo.dir/src/algorithms/cmaes.cpp.obj
g++.exe: error: unrecognized command line option '-fdiagnostics-show-template-tree'; did you mean '-fdiagnostics-show-caret'?
mingw32-make.exe[2]: *** [pagmo2\CMakeFiles\pagmo.dir\build.make:80: pagmo2/CMakeFiles/pagmo.dir/src/algorithms/cmaes.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:2099: pagmo2/CMakeFiles/pagmo.dir/all] Error 2
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
[ 69%] Built target cspice
mingw32-make.exe: *** [Makefile:157: all] Error 2
12:28:51: The process "C:\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build"
12:28:51: Elapsed time: 00:01.
```

Regards,
Nico

**Comment by DominicDirkx** [comment]
In that case, can you please attach your CMakeCache.txt file? It should be located in your build folder,

Dominic

**Comment by nmdekorte** [comment]
Here it is.
[CMakeCache.txt](https://github.com/Tudat/tudat/files/4375160/CMakeCache.txt)

Regards,
Nico

**Comment by DominicDirkx** [comment]
Hi Nico,

In the file, change the line:

YACMA_CXX_FLAGS:INTERNAL=-fdiagnostics-color=auto;-ftemplate-depth=1024;-fdiagnostics-show-template-tree;-Wno-attributes

to

YACMA_CXX_FLAGS:INTERNAL=-fdiagnostics-color=auto;-ftemplate-depth=1024;-Wno-attributes

and recompile. 

Let me know if this works,

Best,

Dominic

**Comment by nmdekorte** [comment]
Hello Dominic,

This worked, tudat compiled with PAGMO and all unit tests succesful.
Thanks for the help, much appreciated!

Regards,
Nico
