### ISSUE TITLE
Error: CEC 2013 problem is not supported on the current platform

### ISSUE THREAD

**Issue by ahjbakx** [Tudat/tudat#619]
Dear Dominic,

When trying to compile with "USE_PAGMO" on, I get this error:

/Users/aaron/tudatBundle/pagmo2/include/pagmo/problems/cec2013.hpp:36: error: The cec2013.hpp header was included but the CEC 2013 problem is not supported on the current platform.

When compiling with "all", I get the following output:
[pagmo-error.txt](https://github.com/Tudat/tudat/files/4376214/pagmo-error.txt)

I hope you can help me fix this problem.

Best, Aaron

**Comment by DominicDirkx** [comment]
Error was reported and resolved here:

https://github.com/Tudat/tudat/issues/617

**Comment by ahjbakx** [comment]
Hi Dominic,

Compiling with "all" gave me no errors. When running the tests I get the same as reported here:

https://github.com/Tudat/tudat/issues/617#issuecomment-603208528

I can conclude from your replies in that issue that I will be able to do the group assignment for P&O. Correct?

Best, Aaron

**Comment by DominicDirkx** [comment]
Correct :)
