### ISSUE TITLE
g++.exe: error: CreateProcess: No such file or directory

### ISSUE THREAD

**Issue by stasevicius** [Tudat/tudat#620]
Hello,

After checking out PropagationOptimizationAssignments/groupAssignment and also turning on USE_PAGMO in the CMake build settings I tried to build all code and got the error: CreateProcess: No such file or directory.
It has something to do with "tudat/Tudat/Astrodynamics/LowThrustTrajectories/CMakeFiles/tudat_low_thrust_trajectories.dir/", but I cannot figure out what it is.
How can I fix this?

Thanks,
Simas

I attach the compile output.
[CompileOutput.txt](https://github.com/Tudat/tudat/files/4376611/CompileOutput.txt)

**Comment by DominicDirkx** [comment]
Hi Simas,

Could you add a screenshot of your build settings, as shown below. Also, please verify that:

- You are compiling on Windows 10
- You are using the Mingw 7.3.0 compiler
- You have put tudat C:/tudatBundle (or D, E, ...)

![image](https://user-images.githubusercontent.com/5039068/77516518-dbbec700-6e7a-11ea-9a08-321bcdab3bb1.png)

**Comment by stasevicius** [comment]
Hi,
I am using windows 10, the compiler is MinGW 7.3.0 64-bit for C++ and tudatBundle is in C:/
The build settings are these

![image](https://user-images.githubusercontent.com/58564325/77518870-cc417d00-6e7e-11ea-941a-2f6624f4668f.png)

**Comment by DominicDirkx** [comment]
Please recompile without the -j2, and post the compile output again.

Which topic are you working on for the course?

**Comment by stasevicius** [comment]
I am working on low thrust. Thank you, I removed the -j2 and it compiled normally. 

[CompileOutputNo-j2.txt](https://github.com/Tudat/tudat/files/4380339/CompileOutputNo-j2.txt)
