### ISSUE TITLE
Option "BUILD_WITH_SOCIS_2019" not properly propagated

### ISSUE THREAD

**Issue by rodyo** [Tudat/tudat#622]
Line 76-ish of `Tudat/Astrodynamics/CMakeLists.txt` 

```
get_target_property(LOWTHRUSTTRAJECTORIESDIRSOURCES tudat_low_thrust_trajectories SOURCES)
```
should be wrapped by an `if` block: 

```
if( BUILD_WITH_SOCIS_2019 )
get_target_property(LOWTHRUSTTRAJECTORIESDIRSOURCES tudat_low_thrust_trajectories SOURCES)
if( BUILD_WITH_SOCIS_2019 )
endif()
```
similar to lines ≈26 and ≈54. 

Without it, CMake will issue warning `get_target_property called on non-existent target` when `BUILD_WITH_SOCIS_2019 ` is `OFF`. 

Should be treated as a bug since CMake is likely to render this into an error in upcoming versions.

**Comment by DominicDirkx** [comment]
Hi Rody, 

Thanks for spotting this! Since you seem to have found the fix for this bug, could you open a pull request with the modifications? 

Best,

Dominic
