### ISSUE TITLE
standalone tudat depends on file in tudatBundle 

### ISSUE THREAD

**Issue by rodyo** [Tudat/tudat#623]
CMake looks for `compiler.cmake` as per line ≈52 in `Tudat/CMakeLists.txt`. This file is part of `tudatBundle` (`external/CMake/compiler.cmake`), rendering out-of-the-box standalone builds of `tudat` impossible.

**Comment by DominicDirkx** [comment]
Hi Rody,

Indeed, this is the case. We have no plans to support a standalone build of Tudat at present. But, if you can make modifications that make this possible, without compromising any existing functionality, we'd be happy to merge it into the repository,

Best,

Dominic

**Comment by rodyo** [comment]
Even if you don't have plans to support it, I reckon it would still benefit modularity if it is able to be standalone. Also, this missing file seems to be the _only_ blocking point for it, so ... low hanging fruit 😊

**Comment by DominicDirkx** [comment]
Hi Rody,

Don't get me wrong, I'm not at all opposed to these changes. If you have verified that this is indeed the only change required to use Tudat as a stand-alone build, I'm all for it! 

I see you've made a pull request with the changes, many thanks!

Best,

Dominic
