### ISSUE TITLE
Add option to exclude unit tests

### ISSUE THREAD

**Issue by rodyo** [Tudat/tudat#624]
Feature request / enhancement: 

Similar to [this SO question](https://stackoverflow.com/questions/23713650), I would love to see an option in `Tudat/CMakeListst.txt` that allows me to exclude `tudat` tests.

Currently, when including `tudat` as a library in other projects, `test`-like build targets will also trigger all `tudat` tests. It would be great to be able to issue `set(TUDAT_DISABLE_TESTS OFF)` or so to bypass the tests.

As far as I could find, this would amount to wrapping said option around: 

* `Tudat/CMakeLists.txt`: line ≈65 (`enable_testing( )`)
* `Tudat/CMakeLists.txt`: lines ≈74–76 (the body of `macro(setup_custom_test_program)`)
* `Tudat/Astrodynamics/TrajectoryDesign/CMakeLists.txt`: lines ≈24–26 (the body of `macro(setup_unit_test_executable_target)`)

**Comment by DominicDirkx** [comment]
Hi Rody,

This would indeed be a nice piece of functionality, but at the moment would not be high on our todo-list. We may get to it in the coming ~months. If you already have been playing with adding this functionality, please do open a pull request :) 

Best,

Dominic
