### ISSUE TITLE
Errors after reinstalling tudatBundle

### ISSUE THREAD

**Issue by TimRotmans** [Tudat/tudat#629]
Hi,

This morning my laptop crashed while running an optimization. Eventually, i had to delete tudat and reinstall it, following the same steps as i did when first installing it. When i now open QT Creator and open the CMakelist file, i get the following errors: 

Running /Applications/CMake.app/Contents/bin/cmake '/Users/timrotmans 1/Desktop/Spaceflight1/tudatBundle' '-GCodeBlocks - Unix Makefiles' in /Users/timrotmans 1/Desktop/Spaceflight1/tudatBundle.
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:21 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:21 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/Users/timrotmans 1/Desktop/Spaceflight1/tudatBundle/CMakeFiles/CMakeOutput.log".
See also "/Users/timrotmans 1/Desktop/Spaceflight1/tudatBundle/CMakeFiles/CMakeError.log".
CMake process exited with exit code 1.
[CMakeError.log](https://github.com/Tudat/tudat/files/4469794/CMakeError.log)

I also attached the error.log file. I don't understand why this happens, only thing i can think of is that tudatBundle is now on a different location on my computer. 

Thanks in advance! 

Tim

**Comment by DominicDirkx** [comment]
Hi Tim,

It would have been very useful for you if you had been present at the working lecture to fix this.....

Check if your Kit is set up as required in the installation guide, there seems to be a problem there.

Dominic

**Comment by TimRotmans** [comment]
Hi,

Unfortunately i wasn't able to attend the working lecture, but i looked into what you said and indeed these settings were not as they should be. I think now it is resolved, i'm building the libraries now and so far nothing went wrong.
Thanks!


Kind regards,

Tim

________________________________
Van: DominicDirkx <notifications@github.com>
Verzonden: dinsdag 14 april 2020 10:32
Aan: Tudat/tudat <tudat@noreply.github.com>
CC: TimRotmans <tjr_96@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Tudat/tudat] Errors after reinstalling tudatBundle (#629)


Hi Tim,

It would have been very useful for you if you had been present at the working lecture to fix this.....

Check if your Kit is set up as required in the installation guide, there seems to be a problem there.

Dominic
