### ISSUE TITLE
Panelled solar pressure radiation - body-fixed reference frame

### ISSUE THREAD

**Issue by stphano** [Tudat/tudat#633]
Good morning,
I am using as a baseline the Single Perturbed Satellite Propagator example, with few changes: I changed the reference frame from J2000 to ECLIPJ2000 (changing also the initial condition to 1.3 AU from the Sun), I increased the number of bodies exerting gravitational attraction, I removed the aerodynamic drag, and other minor changes such as satellite mass.
All the simulations went pretty smoothly, also changing the integration and propagation settings.

Now, I am trying replace the cannonball radiation pressure with the paneled radiation pressure, and I am having some troubles. I replaced the cannonball radiation code section with the code lines that are available in section 1.2.6 of the wiki:

    std::string sourceBody = "Sun";
    std::vector< double > emissivities = { 0.1, 0.0, 0.1, 0.1 };
    std::vector< double > areas = { 4.0, 6.0, 2.3, 2.3 };
    std::vector< double > diffusionCoefficients = { 0.46, 0.06, 0.46, 0.46 };
    std::vector< std::string > occultingBodies;
    occultingBodies.push_back( "Earth" );

    std::vector< std::function< Eigen::Vector3d( const double ) > > panelSurfaceNormals;
    panelSurfaceNormals.push_back( [ = ]( const double ){ return Eigen::Vector3d::UnitZ( ); } );
    panelSurfaceNormals.push_back( [ = ]( const double ){ return - Eigen::Vector3d::UnitZ( ); } );
    panelSurfaceNormals.push_back( [ = ]( const double ){ return Eigen::Vector3d::UnitX( ); } );
    panelSurfaceNormals.push_back( [ = ]( const double ){ return - Eigen::Vector3d::UnitX( ); } );

    std::shared_ptr< RadiationPressureInterfaceSettings > asterixRadiationPressureSettings = std::make_shared< PanelledRadiationPressureInterfaceSettings >(sourceBody, emissivities, areas, diffusionCoefficients, panelSurfaceNormals, occultingBodies );

   bodyMap[ "CubeSat" ]->setRadiationPressureInterface(
               "Sun", createRadiationPressureInterface(
                   asterixRadiationPressureSettings, "CubeSat", bodyMap ) );

Please note that I left asterixRadiationPressureSettings as in the tutorial and I still did not change the radiation settings (areas, emissivities), but I changed the name of the object from Asterix to CubeSat.

When I run the code, it compiles, but it gives me back the following error:

10:19:20: Starting C:\tudatBundle\tudatExampleApplications\satellitePropagatorExamples\bin\applications\application_DeepSpaceCubeSatPropagator.exe ...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error when making environment model update settings, could not find rotational ephemeris or dependent orientation calculator of body CubeSat
10:19:24: C:\tudatBundle\tudatExampleApplications\satellitePropagatorExamples\bin\applications\application_DeepSpaceCubeSatPropagator.exe exited with code 3

I totally understand the error, but I am not able to ‘assign’ a body-fixed reference frame to the body CubeSat. I tried also to call the dependent orientation calculator, but the syntax is not entirely clear to me.
What do you suggest me? I do not need still implement the attitude dynamics, it is sufficient to have a fixed LVLH frame, with the same face always looking towards the Sun. In the TUDAT guide I did not understand how to solve this small problem.

Thank you,
Stefano

**Comment by DominicDirkx** [comment]
Hi Stefano,

I think that this rotation model:

https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/Ephemerides/synchronousRotationalEphemeris.h

is exactly what you're looking for. For a body named 'Vehicle', you can use:

bodyMap[ "Vehicle" ]->setRotationalEphemeris( createRotationModel( std::make_shared< SynchronousRotationModelSettings >( "Sun", "ECLIPJ2000", "VehicleFixedFrame" ), "Sun", bodyMap ) );

which you can use just after creating your Vehicle object in the body map. Here, the "VehicleFixedFrame" is the name chosen for the frame fixed to the vehicle (feel free to choose whichever name you like), and the global frame orientation is assumed to be ECLIPJ2000.

In this case, the vehicle-fixed x-axis always points towards the Sun, and the vehicle-fixed z-axis always points along the orbital angular momentum vector.

This model is quite new, so unfortunately, it has not been shown yet in the documentation. Normally, this would be described here:

http://tudat.tudelft.nl/tutorials/tudatFeatures/environmentSetup/availableSettings.html#rotational-model

If you have any more questions, please don't hesitate to contact us,

Best,

Dominic
