### ISSUE TITLE
CMake issues

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#636]
Dear all,

a while back I successfully set up tudat on linux and could use it without issues.
Now trying to use it again leads to the General Messages output below.
Do you have any suggestions what I could look into?
The CMake I use has version 3.18.1 & I already made sure that CodeBlocks & Unix Makefiles are set as generator.

Running /lcl/pradmin/vicsys/utils_rh7/cmake/bin/cmake '-GCodeBlocks - Unix Makefiles' /marsr/xover/code/tudatBundle in /marsr/xover/code/build-tudatBundle-Desktop-Default.
-- /marsr/xover/code/tudatBundle
-- BOOST: Using gnu.
-- Looking for include file unistd.h
-- Looking for include file unistd.h - not found
-- Configuring incomplete, errors occurred!
See also "/lcl/marsr/xover/code/build-tudatBundle-Desktop-Default/CMakeFiles/CMakeOutput.log".
See also "/lcl/marsr/xover/code/build-tudatBundle-Desktop-Default/CMakeFiles/CMakeError.log".
CMake Warning (dev) at CMakeLists.txt:21 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at external/CMake/add_boost.cmake:100 (message):
  C POSIX libraries not found on system.  Please (re)install development
  environment.
Call Stack (most recent call first):
  CMakeLists.txt:89 (include)

CMake process exited with exit code 1.

Kind regards,
Sebastian

**Comment by MarieFayolle** [comment]
Hi Sebastian,

I am not sure what's going on here as I'm not familiar with installing Tudat on Linux. But just to let you know, Dominic will be back in about a few weeks and he will be able to help you with this. Sorry about the delay, the Tudat support is unfortunately a bit limited during the summer period.

Best,

Marie

**Comment by SebastianVillamil** [comment]
Hi Marie,

no worries, it can wait. Thanks for looking into it!

Kind regards,
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

I saw from an e-mail I just sent you that you're on holiday, do enjoy it and reply when you get back (like I did :) ). Can you give some specifics on the system you're installing it on (Linux? Through Qt or terminal?)

Best,

Dominic

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
