### ISSUE TITLE
Use git lfs / generate datafiles

### ISSUE THREAD

**Issue by rodyo** [Tudat/tudat#637]
Making a fresh clone of `tudat` can take...quite a while. Running `ncdu` on `tudat/` shows why: 

<img width="563" alt="Screenshot from 2020-08-21 15-12-14" src="https://user-images.githubusercontent.com/1283690/90848502-2197a100-e3c1-11ea-8709-76bed6f32276.png">

There's a few ways to improve this situation:
1.  Have `git-lfs` manage them. This is probably the lowest hanging fruit. With `git-lfs`, at least diff'ing stuff will be faster, and the repository db (i.e., the `.git` folder) will be significantly smaller. Drawback: that's yet another dependency, needs a documentation change, and is fairly easy to screw up (also, ideally, you'd `git lfs migrate` the whole repository (rewriting history + force push), which is not without its risks, but this can be skipped)
1.  create some CMake targets that downloads/generates these files on the fly (e.g., CSPICE kernels are not needed if `USE_CSPICE` is off). This is probably the nicest way to deal with this sort of thing, but requires the most effort. 
1. Something I didn't think of 😊 

I'm happy to help out; I just need to know what to do.

**Comment by DominicDirkx** [comment]
Indeed, this is a nuisance, and one of the things we will address in our new version!
