### ISSUE TITLE
Body Creation - Rotational Model

### ISSUE THREAD

**Issue by ptorrente** [Tudat/tudat#642]
Hello,

I am having a hard time trying to implement the environment model for an asteroid, any help would be very appreciated.

For the implementation of the rotational model, I thought I would use something similar as found in the documentation: http://tudat.tudelft.nl/tutorials/tudatFeatures/environmentSetup/availableSettings.html#SimpleRotationModelSettings 

My problem here is about the target reference frame, as it is not already built-in like IAU_Earth, how can it be transposed to my case? Does it have to come from an available FK Kernel file or I am going in the wrong direction here?

**Comment by MarieFayolle** [comment]
Hi Paul,

The SimpleRotationModelSettings class indeed asks for the so-called "targetFrame" but it is just the name you want to give to your target frame. So you can choose whatever name suits you best there, but I would advise to include the name of your asteroid in it for the sake of clearity. The rotation from the original frame to your newly named target frame will then be defined from the rotational rate and the constant orientation of the rotational axis.

I hope this can help you a bit :)

Cheers,

Marie

**Comment by ptorrente** [comment]
Hi Marie,

Thank you for the answer.
For the constant orientation of the rotational axis however, can I use the function spice_interface::computeRotationQuaternionBetweenFrames ? But then the new target frame for this function cannot be just any name, right?
Or would I need to compute the orientation differently?

Paul

**Comment by MarieFayolle** [comment]
Then it becomes a bit of a different issue. The class SimpleRotationModelSettings requires a quaternion as input for the orientation of the rotational axis. If there is a rotational model available in the spice kernels for the body you're interested in, then you can indeed retrieve it with the function computeRotationQuaternionBetweenFrames the spice interface indeed. And in that case, you need to use the same target frame as the one used in the kernels (i.e. IAU_bodyName so IAU_Earth for example). 
Now the orientation data are not available for all the celestial bodies and especially if you're modelling an asteroid, chances are high that there will be no orientation data for your body of interest (you can check that here: https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00010.tpc )
In that case, you need to provide the rotational axis orientation yourself. You can compute the corresponding quaternion from the Euler angles for instance (see function getQuaternionFrom313EulerAngles for example in Tudat/Mathematics/BasicMathematics/rotationRepresentations.h ).

Out of curiosity, which asteroid are you interested in exactly?

Hope this helps a bit,

Marie

**Comment by ptorrente** [comment]
Thanks for the answer and the link, I indeed thought that the data would not be available.

I would like to work with a binary asteroid, it is not fixed yet but maybe (66391)1999 KW4. From what I understand, the only binary with available orientation data is (243) Ida, so I will look into the computation of the quaternion myself then.

Thanks for the help.

Paul

**Comment by ptorrente** [comment]
Hello,

I am still having some trouble with the implementation of the environment model.

Basically, for the creation of a body Alpha, I would like to use the following lines in my code:
![image](https://user-images.githubusercontent.com/44982827/91580221-0c84ba00-e94d-11ea-9022-9e3f5bed9de7.png)
![image](https://user-images.githubusercontent.com/44982827/91580316-32aa5a00-e94d-11ea-949d-1ca4bf019b94.png)

where I provide the inputs needed.

My problem is that the simulation crashes at any of those lines, so I think by problem is that Alpha is not properly created at the bodySettings level, and I do not wish to create it at the bodyMap level (as I would do for a vehicle) as I would like to use the above lines.
The inputs are not the problem source, if I change "Alpha" to "Earth" for instance (just to check even though it has no meaning), it works. So I think the problem is that Alpha is not recognized as a body.

The celestial bodies that I use are created using the getDefaultBodySettings function, but I do not know how to append the bodySettings with Alpha right after that. 
I tried with a simple bodySettings[ "Alpha" ] for which a call to bodySettings.count("Alpha") returns 1, but the program still crashes afterwards when trying to provide the rotationModelSettings and gravityFieldSettings.

Could you help me with that? Thank you a lot and sorry if it is a silly question.

Paul

**Comment by MarieFayolle** [comment]
Hi Paul,

I think that you have indeed not created the element "Alpha" in your bodySettings map at first. Try adding this line to create a BodySettings pointer associated with your body name Alpha in your bodySettings map:
bodySettings[ "Alpha" ] = std::make_shared< BodySettings >( );
and then you should be able to specify the different settings properly.

A small remark about your previous post: the above will work perfectly but you could also very well create the body Alpha from the bodyMap directly. There is actually no difference between celestial bodies and vehicles in Tudat. The only difference with that option is that you would have to provide the rotational and gravity fields models directly, and not to provide the associated settings.

And just a small request for next time, please push your code to GitHub and add me and/or @DominicDirkx as collaborators. It is much easier for us to understand what's going on and to help you efficiently if we have access to your code :) 

Marie

**Comment by ptorrente** [comment]
Hi Dominic,

- From what I understood, the ephemeris from JPL provides the position of the mutual center of mass of Alpha and Beta together. I was planning on using it in my setup as the ephemeris of Alpha itself, and then propagate Beta around.

- I do not fully understand the part about the Euler angles, I am sorry. The paper I have provides Euler angles that define a 313 Euler axis rotation from the frame that I mentioned in my previous post. So I could define the rotation matrix from these Euler angles myself using a Z-X-Z Euler axis rotation order, but that would still be w.r.t. the frame in the paper.
What I want is to use the Simple Rotation Model in the following way:
![image](https://user-images.githubusercontent.com/44982827/93782225-96613380-fc2a-11ea-919e-ccd14113309a.png)
but the problem is that I can only define the _initialOrientationAlpha_ quaternion with regarding to the frame in the paper. So from I understand I would need either to create that particular frame somehow and be able to make it as an input for _originalFrameAlpha_, or somehow find the rotation matrix from the J2000 frame to the frame in the paper.

Let me know if I understand all this correctly or not, and thank you a lot for your time.

Kind regards,

Paul

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
