### ISSUE TITLE
disabling BUILD_WITH_ESTIMATION_TOOLS breaks build

### ISSUE THREAD

**Issue by rodyo** [Tudat/tudat#647]
As can be seen [here](https://github.com/Tudat/tudat/blob/318d168e01580c15ac17ed72172c8b214c146475/Tudat/SimulationSetup/PropagationSetup/propagationOutputSettings.h#L509), `stateDerivativePartials_`  is only defined when `BUILD_WITH_ESTIMATION_TOOLS ` has been defined. However, it is used [here](https://github.com/Tudat/tudat/blob/318d168e01580c15ac17ed72172c8b214c146475/Tudat/SimulationSetup/EstimationSetup/variationalEquationsSolver.h#L646) unconditionally. This breaks the compilation when switching `BUILD_WITH_ESTIMATION_TOOLS` off. 

A simple `#ifdef` around the call site should fix it—see PR.

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
