### ISSUE TITLE
Failed unit tests_System - OS windows 10 _2 cores 4 logical processors

### ISSUE THREAD

**Issue by AmitMalse** [Tudat/tudat#650]
Respected sir,

I am getting error as during the unit test compilation it is showing 62 tests failed out of 255. I have mentioned my operating system in the subject line itself. I am attaching the LastTest.log file as mentioned on the website. Please help me with this concern.
Thank you!

Note: In the 'Build the libraries' step, 2 warnings were there but there was no error. And 'LastTestsFailed.log' lists unit tests failed.

Regards,
Amit Malse
[LastTest.log](https://github.com/Tudat/tudat/files/5230940/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/5230941/LastTestsFailed.log)

**Comment by DominicDirkx** [comment]
Hi Amit,

Could you please provide the output of the compilation without the 'test' command? From the looks of it, something went wrong there. Also, please specify the type of system (OS, IDE) you are using to compile,

Best,

Dominic

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
