### ISSUE TITLE
Integration progress bar

### ISSUE THREAD

**Issue by MarkRonst** [Tudat/tudat#654]
Hi,

since the processing of my examples takes very long (my laptop is not the youngest anymore) I would like to implement some kind of progress bar / output if the programm is still running and if yes at what time of the propagation interval it is. As far as it seems to me the whole propagation is enclosed in the dynamics simulator, so it has to be implemented in that part. I searched for the "main" for-loop but am not able to find it. Could somebody guide me to it? Thank you!

Mark

**Comment by DominicDirkx** [comment]
Hi Mark,

There is a (sort of) functionality for that, which allows you to print the current time and state of the propagation at a given time interval (of propagation time). The class `TranslationalStatePropagatorSettings` has a constructor input ` const double printInterval = TUDAT_NAN`. BY default it's NaN (meaning no output), but if you set if to for instance 86400, it will print the time and state of the propagation once every day.

Hope that helps. Also, be aware that we're working on a significant refactoring of the structure and interface of Tudat, including a Python Interface. We will have this ready for first use in ~1-2 months!

Best,

Dominic
