### ISSUE TITLE
CMake issue when compiling tudat for the first time that prevents further actions

### ISSUE THREAD

**Issue by AntoineClout** [Tudat/tudat#656]
Hello all, 
I was installing tudat today following the online documentation, and everything went great until step 3.3. I am on macOS Catalina 10.15.7. It is written in the installation guide that CMake issues are not a problem, but when I go to the step 3.5 (3.4 is optionnal) I cannot click on the hammer as it is greyed. The joined txt file is containing the "6.General output ".
Thank you in advance for your help,

Antoine
[General Output.txt](https://github.com/Tudat/tudat/files/5340877/General.Output.txt)

**Comment by DominicDirkx** [comment]
Hi Antoine,

Is there a 'boost'  directory under your tudatBundle? If so, please delete it and try again. If this doesn't work, could you show a sreenshot of your 'kit' (depending on version, under tools/options/preferences->Build&Run->Kit)

It may also interest you to know that we are working on a completely revised tudat installation and interface. The interface will be only a few lines using a tool called 'conda', with all the code precompiled for you. The code interfaces will be modified and most importantly will now come with a Python interface for Tudat! The first release of this new Tudat will happen by mid-November

Best,

Dominic

**Comment by AntoineClout** [comment]
Hello Dominic, 
Indeed, a folder "boost" was in my tudatBundle directory, so I deleted it and started again. However, it still didn't work but the General message output is a bit different (I included it in .txt). As you asked, I took screenshots of all the subdirectories ok 'Kit'. 
<<Thank you for the help you've already provided.
Best, 
Antoine

![Capture d’écran 2020-10-08 à 11 49 40](https://user-images.githubusercontent.com/57559520/95443514-f5c67f80-095c-11eb-963b-18c4ab716c68.png)
![Capture d’écran 2020-10-08 à 11 49 55](https://user-images.githubusercontent.com/57559520/95443521-f7904300-095c-11eb-9700-7cedb9d8a9db.png)
![Capture d’écran 2020-10-08 à 11 50 03](https://user-images.githubusercontent.com/57559520/95443526-f828d980-095c-11eb-84a6-01ccbb81ec45.png)
![Capture d’écran 2020-10-08 à 11 50 10](https://user-images.githubusercontent.com/57559520/95443531-f95a0680-095c-11eb-9d26-f8e80d0f6ea6.png)
![Capture d’écran 2020-10-08 à 11 50 22](https://user-images.githubusercontent.com/57559520/95443533-f95a0680-095c-11eb-89f3-59e6b8437bc6.png)
[General message.txt](https://github.com/Tudat/tudat/files/5346887/General.message.txt)

**Comment by AntoineClout** [comment]
Hello Dominic,
Last week I rebooted my Macbook pro to initial configuration thus tried again the installation of Tudat. Unfortunatelly, even with a brand "new" computer, the same problem occurs and I cannot proceed with the installation. Do you know what can be the source of the problem and how to fix it ?
Best,
Antoine
![Capture d’écran 2020-10-17 à 09 35 57](https://user-images.githubusercontent.com/57559520/96331321-b551ba80-105c-11eb-9d2d-f714035ea32b.png)
![Capture d’écran 2020-10-17 à 09 36 03](https://user-images.githubusercontent.com/57559520/96331322-b71b7e00-105c-11eb-812a-e541ecab092e.png)
![Capture d’écran 2020-10-17 à 09 36 11](https://user-images.githubusercontent.com/57559520/96331323-b7b41480-105c-11eb-8982-02d56d79f5c0.png)
![Capture d’écran 2020-10-17 à 09 36 17](https://user-images.githubusercontent.com/57559520/96331324-b84cab00-105c-11eb-9d17-07e06ca1ca8f.png)
![Capture d’écran 2020-10-17 à 09 36 31](https://user-images.githubusercontent.com/57559520/96331325-b8e54180-105c-11eb-8f94-21212b32569c.png)
[main.txt](https://github.com/Tudat/tudat/files/5395151/main.txt)

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
