### ISSUE TITLE
"Invalid sizes when resizing a matrix or array."' failed.

### ISSUE THREAD

**Issue by bushraky8** [Tudat/tudat#659]
Dear Dominic,

I have run two different applications from the GalileanMoonDynamics. For the 'application_JuiceCoupledEstimation' however, I get the above mentioned error. Whereas 'application_JuiceDynamicSimulation' runs without error. It seems to be a conversion error from matrix to array or vice versa. To solve this I have tried the following:
1) I have run the example applications to test if applications are running on the server, which might have such a matrix resizing in my opinion, as I believe matrix inversion is already installed on tudat. 'application_singlesatellitepropagator' runs just fine!
2) I did all unit tests again and 'make' in the applicable folders where the applications are run from.
3) I have checked if the files in question are the same on my desktop and the server. They are.
4) I have checked if the same version of 'eigenboost' is used on the desktop as well as the server. Both 'eigenboost' versions are the same (version 3.3.2)
Is there a specific update that I can do to solve this matrix issue? 
(see file attachment for output)

kind regards,
[Resizing_matrix_array.txt](https://github.com/Tudat/tudat/files/5574688/Resizing_matrix_array.txt)
Bushra

**Comment by DominicDirkx** [comment]
Hi Bushra,

Which settings are you using for the propagation? Where in the process does this error occur, is it during the state propagation, the calculation of the partials, or the inversion of the covariance?

Best,

Dominic

**Comment by bushraky8** [comment]
Dear Dominic, 

I think it already fails at the 'PROPAGATE DYNAMICS AND VARIATIONAL EQUATIONS'. For this I commented the parts of the code after this section, built in the build folder and then ran the application (the settings for this and the results are attached in the files 'dynamics&VE_only.txt' and 'dynamics&VE_only_output.txt'. The output is the same as in the previous comment.

For the setting used in the previous comment see file 'currentSettings.txt'.
[currentSettings.txt](https://github.com/Tudat/tudat/files/5602684/currentSettings.txt)
[dynamics&VE_only.txt](https://github.com/Tudat/tudat/files/5602687/dynamics.VE_only.txt)
[dynamics&VE_only_output.txt](https://github.com/Tudat/tudat/files/5602688/dynamics.VE_only_output.txt)




Is this what you meant?

kind regards,
Bushra

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
