### ISSUE TITLE
CMAKE_OBJECT_PATH_MAX

### ISSUE THREAD

**Issue by abuIlyas** [Tudat/tudat#663]
CMake Warning in tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeLists.txt:
  The object file directory
    C:/Users/davide.menzio/AppData/Local/Temp/QtCreator-raWqwW/qtc-cmake-fdjBklvN/tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeFiles/application_EarthOrbiterBasicStateEstimation.dir/
  has 219 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file
    earthOrbiterBasicStateEstimation.cpp.obj
  cannot be safely placed under this directory.  The build may not work
  correctly.

This is only one, i got it multiple times

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
