### ISSUE TITLE
Default setting in Qt Creator

### ISSUE THREAD

**Issue by tobiastanis** [Tudat/tudat#665]
Hi,

Currently, I am installing TUDAT on my windows, but I am not able to switch the TUDATbundle in Qt Creator to Default. I can only choose between:
Debug
Minimum Size Release
Release
Release with Debug Information
Anyone know why I cannot switch to default?

Thanks in advance!
![tudatbundle](https://user-images.githubusercontent.com/94394184/142222577-8e9b60c9-81d7-4dae-8860-3e9fce0d0113.JPG)

**Comment by DominicDirkx** [comment]
Dear Tobias,

You seem to be using our old version of tudat, which is no longer maintained. See: https://tudat-space.readthedocs.io/en/latest/ for the latest version. 

If you would like to build the Tudat code yourself, please use the new bundle:

https://github.com/tudat-team/tudat-bundle

The development workflow for the new version is not well documented yet, please contact us (through e-mail or an issue in our new repo), if you want to know more,

Best,

Dominic
