### ISSUE TITLE
Failed running bootstrap during configuration (OSX)

### ISSUE THREAD

**Issue by roosmartens** [Tudat/tudat#670]
Hi Dominic,

I am trying to install Tudat again on my macbook (using OSX 12.1 Monterey), however I get the following errors during configuration:
```
Failed running bootstrap:

  Building Boost.Build engine with toolset clang...

  Failed to build Boost.Build build engine
```

I included the log files for boost and cmake below:

[CMakeOutput.log](https://github.com/Tudat/tudat/files/7913965/CMakeOutput.log)
[bootstrap.log](https://github.com/Tudat/tudat/files/7913970/bootstrap.log)

Before posting here, I already tried some stuff that were stated in the Tudat troubleshooting guide (for example changing the boost version in the CMakelists.txt file) and in the github issues that were posted before. I also checked the cmake and clang versions; they were not outdated (only maybe too new?). 
I made some screenshots so you can see the "kit" settings I changed:

<img width="1147" alt="Schermafbeelding 2022-01-21 om 14 44 22" src="https://user-images.githubusercontent.com/31625623/150537550-50327d20-e974-465b-94f4-1185bd671931.png">
<img width="1149" alt="Schermafbeelding 2022-01-21 om 14 44 32" src="https://user-images.githubusercontent.com/31625623/150537557-97741b1f-ec88-45cf-b211-e45fb5ed9ca8.png">
<img width="1150" alt="Schermafbeelding 2022-01-21 om 14 44 43" src="https://user-images.githubusercontent.com/31625623/150537560-b5e4572d-d5ac-4146-b5f8-814c62f87ed8.png">

Also, I have a screenshot of the CMake path:
![Schermafbeelding 2022-01-21 om 14 52 21](https://user-images.githubusercontent.com/31625623/150538606-62e52d08-2bbd-46df-8675-79958b1eb17b.png)

Not sure what exactly is going wrong. Hopefully you have some time to help me with this issue.

Kind regards,
Roos

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
