### ISSUE TITLE
CMake Build Error: Eigen library errors disrupting build(?)

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#676]
While attempting to build tudat, it gives the following error

In file included from /usr/include/eigen3/Eigen/Core:164:0,
                 from /home/rajath/tudatBundle/tudat/Tudat/../Tudat/Astrodynamics/OrbitDetermination/stateDerivativePartial.h:16,
                 from /home/rajath/tudatBundle/tudat/Tudat/../Tudat/SimulationSetup/EstimationSetup/createStateDerivativePartials.h:14,
                 from /home/rajath/tudatBundle/tudat/Tudat/SimulationSetup/EstimationSetup/createStateDerivativePartials.cpp:1:
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h: In instantiation of ‘void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Matrix<double, 3, 1>; Src = Eigen::Matrix<double, 3, 3>; Func = Eigen::internal::assign_op<double, double>]’:
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:858:27:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type) [with Dst = Eigen::Matrix<double, 3, 1>; Src = Eigen::Matrix<double, 3, 3>; Func = Eigen::internal::assign_op<double, double>; typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type = void*]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:836:18:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&) [with Dst = Eigen::Matrix<double, 3, 1>; Src = Eigen::Matrix<double, 3, 3>]’
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:779:32:   required from ‘Derived& Eigen::PlainObjectBase<Derived>::_set(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, 3, 3>; Derived = Eigen::Matrix<double, 3, 1>]’
/usr/include/eigen3/Eigen/src/Core/Matrix.h:225:24:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, 3, 3>; _Scalar = double; int _Rows = 3; int _Cols = 1; int _Options = 0; int _MaxRows = 3; int _MaxCols = 1]’
/home/rajath/tudatBundle/tudat/Tudat/../Tudat/SimulationSetup/EnvironmentSetup/body.h:601:111:   required from here
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:887:3: error: static assertion failed: YOU_MIXED_MATRICES_OF_DIFFERENT_SIZES

This is one of many such errors and trying to build tudatBundle as well as any custom or example applications leads to Eigen Errors. The unit test(s) also fail with similar Eigen errors. The one difference to my local copy I notice is that the Eigen libraries used (v 3.4.0) aren't that from the tudatBundle but rather a native install on the server (read from /usr).

**Comment by DominicDirkx** [comment]
Part of this issue was communicated by e-mail, and is likely due to an incompatible installation (server update; no tudat update). I'm closing this issue, and it can be reopened (provided full information is provided) at a later time if needed

**Comment by ebenezerrajadurai** [comment]
Same issue is happening @DominicDirkx

**Comment by DominicDirkx** [comment]
Please note that this Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ for the current setup. Or https://github.com/tudat-team/tudat-bundle for a from-code setup
