### ISSUE TITLE
Compile Warnings in SetNumericallyIntegratedStates.h

### ISSUE THREAD

**Issue by mhaneveer** [Tudat/tudat#80]
Warnings only, received it a couple of times when compiling TUDAT. 
Related to lines 230 and 397 in SetNumericallyIntegratedStates.h

line 230:
~TUDAT\tudatBundle\tudat\Tudat\SimulationSetup\PropagationSetup\setNumericallyIntegratedStates.h:230: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if( equationsOfMotionNumericalSolution.begin( )->second.rows( ) < startIndexAndSize.first + startIndexAndSize.second )

line 397:
~TUDAT\tudatBundle\tudat\Tudat\SimulationSetup\PropagationSetup\setNumericallyIntegratedStates.h:397: required from 'void tudat::propagators::TranslationalStateIntegratedStateProcessor<TimeType, StateScalarType>::processIntegratedStates(const std::map<S, Eigen::Matrix<RhsScalar, -1, 1> >&) [with TimeType = double; StateScalarType = long double]'
                                                                     ^

**Comment by DominicDirkx** [comment]
Thanks for letting us know. Some changes have been uploaded that should fix this, let me know if the warnings persevere. If not, this issue can be closed.
