### ISSUE TITLE
Altitude-dependent aerodynamic coefficients

### ISSUE THREAD

**Issue by DominicDirkx** [Tudat/tudat#83]
I've added some code for altitude-dependent aerodynamic coefficients, but have not yet added a unit test 

(https://github.com/DominicDirkx/tudat/tree/AltitudeIndependentVariableForAerodynamics)

Aleix, since you're going to be using this code anyway, and applying an altitude-dependent aerodynamics model, could you add a unit test when you have your code running? Y

ou could simply use a propagation that you will be doing anyway as code, save the aerodynamic coefficients and altitude as dependent variables (http://tudat.tudelft.nl/projects/tudat/wiki/Propagation_setup#Saving-output-of-the-simulation), and then compare these two values to see if the altitude is being properly used to compute the aerodynamic coefficients. Let me know.

**Comment by aleixpinardell** [comment]
I can't find where it is... I only see these variables:
```
enum AerodynamicCoefficientsIndependentVariables
{
    mach_number_dependent = 0,
    angle_of_attack_dependent = 1,
    angle_of_sideslip_dependent = 2,
    undefined_independent_variable = 3
};
```

**Comment by DominicDirkx** [comment]
Hi Aleix,

I guess you are taking this from the master branch? For the particular branch, the file is modified:

https://github.com/DominicDirkx/tudat/blob/AltitudeIndependentVariableForAerodynamics/Tudat/Astrodynamics/Aerodynamics/aerodynamicCoefficientInterface.h

You have to checkout this branch on your machine, then you will see the changes. From the terminal, the commands are:

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b DominicDirkx-AltitudeIndependentVariableForAerodynamics master
git pull https://github.com/DominicDirkx/tudat.git AltitudeIndependentVariableForAerodynamics

**Comment by DominicDirkx** [comment]
Hi Aleix,

I've changed a few things in the TabulatedAerodynamicCoefficientSettings constructor (createFlightConditions.h). For aerodynamic data with only 1 independent variable, you can now use the template specialization TabulatedAerodynamicCoefficientSettings< 1 > (so call make_shared< TabulatedAerodynamicCoefficientSettings< 1 > >( ... constructor arguments here .... ). There is a constructor with and without the option to set moment coefficients.

Note that you need to provide interpolation settings (object of class InterpolatorSettings in createInterpolator.h) to define how the discrete data is to be interpolated to a continuous database.

Let me know if you run into any issues when setting up the unit test for the altitude-dependence (which will also automatically test the TabulatedAerodynamicCoefficientSettings< 1 > ).

**Comment by aleixpinardell** [comment]
I am getting this runtime error:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Error, do not recognize aerodynamic coefficient settings for Rocket
```

**Comment by DominicDirkx** [comment]
Hi Aleix, thats odd... Could you attach your main file containing the code?

**Comment by aleixpinardell** [comment]
[GTO.cpp.zip](https://github.com/Tudat/tudat/files/591795/GTO.cpp.zip)

**Comment by DominicDirkx** [comment]
I patched the code in the branch, if you update it, it should run. Thanks for finding this bug.
